### ISSUE TITLE
Microbiome Study Curation - Outreachy Applicant Instructions

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#1]
Welcome Outreachy Applicants! 

_Note: This task can be completed by multiple Outreachy applicants._

### BugSigDB Project 

BugSigDB is a wiki built to capture standardized microbial signatures of health outcomes and enables the systematic comparison and synthesis of published human microbiome studies, https://bugsigdb.org/Main_Page. As context, the human microbiome is the collection of microorganisms colonizing the human body. It performs essential functions such as producing vitamins and important nutrients, metabolizing food and drugs and toxins, regulating epithelial development, and influencing innate immunity. It is modified by diet, medical treatment, and host-to-host transmission, and can be a mediator between environment and health. The main result of most published human microbiome studies are lists or “signatures” of differentially abundant microbial taxa in different groups, which are often classified by health condition, behavior or risk factor. A microbial signature is a list of bacteria, viruses, and/or archaea reported to be differentially abundant with respect to health outcomes (e.g., cancer, diabetes, obesity) or with respect to sociodemographic characteristics (e.g., age, smoking, income, or place of residence). These signatures are often reported in heterogeneous ways with different taxonomic nomenclature databases and do not allow direct comparison of methods or results in different studies. BugSigDB contributors aim to create a comprehensive coverage of the human microbiome literature that allows for (1) comparisons between new research findings and previously published results in any area of the health literature and (2) identify common patterns of differentially abundant microbes across otherwise disparate health outcomes.

### Prep Work

To make a contribution to the BugSigDB project, applicants should first review the onboarding materials: 
BugSigDB project information, estimated time: 15 minutes ([link](https://bugsigdb.org/Project:About))
Reading materials on the human microbiome, estimated time: 2 hours ([link](https://docs.google.com/document/d/1cpY8RoOHjJ_oxkDRGwlpqL-I29IN9B5BifhZIlqTjhE/edit)) 
Step-by-step guidance on how to document a signature in BugSigDB ([link](https://www.youtube.com/watch?v=yfpnwxefLFc&list=PLIUETfW6tVu2OGgZcIxqI7DbUBReHVdIq&index=5&ab_channel=WaldronLab)) 
View examples of completed BugSigDB curations, estimated time: 15 minutes ([link](https://bugsigdb.org/Study_600)) 
Video trainings on BugSigDB curation ([link](https://www.youtube.com/playlist?list=PLIUETfW6tVu2OGgZcIxqI7DbUBReHVdIq))  

### Contribution Task

~Review article on the human microbiome that is heavily annotated by BugSigDB project leaders (e.g., explaining the section(s) of the article that convey study design and the specific characteristics that determine study design) and complete a mini-curation, akin to BugSigDB curations, on Qualtrics XM. Link to curation form:~
~https://cunysph.az1.qualtrics.com/jfe/form/SV_0cYerh299Ftl49M.~

### The contribution task is now closed to new applicants at this time. Thank you for your interest in the project and the overwhelming enthusiasm we've had from Outreachy applicants!

~**Please submit a fully completed mini-curation via the form above before continuing.**~

**(Optional) Stretch Task:** As an optional, higher-difficulty-level task, you may claim an article on the human microbiome from the BugSigDBcuration Github issues tagged ["paper to curate"](https://github.com/waldronlab/BugSigDBcuration/issues?q=is%3Aissue+is%3Aopen+label%3A%22paper+to+curate%22) and work on a full curation.

To claim an article for curation, post a response to the issue with your name and we will mark it as claimed.

To curate the article you select, first create a BugSigDB account ([https://bugsigdb.org/Special:RequestAccount](https://bugsigdb.org/Special:RequestAccount)) and follow the website prompts to complete the curation.

### Questions

Communications regarding specific tasks should be done on the Slack BioC channel, to join, view https://slack.bioconductor.org/ then search for the channel [#bugsigdb](https://waldronlab.slack.com/archives/C016AL6G2R0)

### Contributions

Remember to record your contributions in Outreachy at https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/bioconductor/#microbiome-study-curation.

**Comment by RotimiDesire** [comment]
The link to join the Slack BioC channel isn't working.

**Comment by cmirzayi** [comment]
Hi @RotimiDesire it appears that something is going on with the Slack signup link which is provided by Bioconductor. A member of our team is following up with the core team. I'll hopefully have an update shortly.

**Comment by cmirzayi** [comment]
@RotimiDesire You can also provide me your email address and I should be able to invite you. Feel free to email me at cmirzayi@gmail.com if you don't want to post it publicly.

**Comment by RotimiDesire** [comment]
My email address is rotimidesire@gmail.com

I appreciate your response @cmirzayi

**Comment by cmirzayi** [comment]
@shallockh02 Awesome! See the optional task listed above:

> (Optional) Stretch Task: As an optional, higher-difficulty-level task, you may claim an article on the human microbiome from the BugSigDBcuration Github issues tagged ["paper to curate"](https://github.com/waldronlab/BugSigDBcuration/issues?q=is%3Aissue+is%3Aopen+label%3A%22paper+to+curate%22) and work on a full curation.

> To claim an article for curation, post a response to the issue with your name and we will mark it as claimed.

> To curate the article you select, first create a BugSigDB account (https://bugsigdb.org/Special:RequestAccount) and follow the website prompts to complete the curation.

**Comment by shallockh02** [comment]
Hello hope you are well this fine morning got assigned my first paper to
curate #15 <https://github.com/waldronlab/BugSigDBcuration/issues/15> and
would like your guidance on the way forward kindly

**Comment by Dherahrose** [comment]
I tried contributing by creating a study, matching nomenclature or editing but I keep getting;  I do not have permission for edit this page because the action I requested is limited to users in the group. Please what does this mean and what can I do to solve it. I have been unable to make any contributing and this is making me worried

**Comment by ftzohra22** [comment]
Hi @Dherahrose as part of your contribution task please finish these two tasks first:

**First contribution task:** Complete a mini-curation, akin to BugSigDB curations, on Qualtrics XM. Link to curation form: https://cunysph.az1.qualtrics.com/jfe/form/SV_0cYerh299Ftl49M.

**Second contribution task:** Please claim an article on the human microbiome from the BugSigDBcuration Github issues tagged ["paper to curate"](https://github.com/waldronlab/BugSigDBcuration/issues?q=is%3Aissue+is%3Aopen+label%3A%22paper+to+curate%22) and work on a full curation.

To claim an article for curation, post a response to the issue with your name and we will mark it as claimed.

To curate this article you selected, first create a BugSigDB account (https://bugsigdb.org/Special:RequestAccount) and follow the website prompts to complete the curation.

**Comment by ftzohra22** [comment]
@shallockh02 please follow the video trainings on BugSigDB curation ([link](https://www.youtube.com/playlist?list=PLIUETfW6tVu2OGgZcIxqI7DbUBReHVdIq)) and example of completed BugSigDB curations ([link](https://bugsigdb.org/Study_600)) for guidance on how to curate a paper.

**Comment by Dherahrose** [comment]
Thank you so much for sharing the link.

**Comment by Dherahrose** [comment]
Please what am I supposed to do on it?

**Comment by chondatondaponda** [comment]
Hi I submitted the qualtrics contribution task, but I'm confused, were we supposed to keep the submission link to record that contribution on Outreachy?

**Comment by Abosed** [comment]
@cmirzayi @ftzohra22 

Kindly help review my curation.
https://bugsigdb.org/Study_729

**Comment by shallockh02** [comment]
@cmirzayi @ftzohra22
Hope you are doing well. Finished this and would appreciate your reviews on the following and whether I can get assigned another curation paper.
[#15](https://bugsigdb.org/Study_731)
Also an experiment was duplicated and tried deleting but it said the administrators are the ones with the permission to do so how can I go ahead about it?

**Comment by Dherahrose** [comment]
Having this same challenge as well while trying to match unknown names to NCBI taxonomy

**Comment by lwaldron** [comment]
> @cmirzayi @ftzohra22
> 
> Kindly help review my curation.
> 
> https://bugsigdb.org/Study_729

@Abosed would you please post this link and update on the issue assigned to you? That's how we'll keep track of and review completed curation tasks.

**Comment by Abosed** [comment]
> > @cmirzayi @ftzohra22
> > Kindly help review my curation.
> > https://bugsigdb.org/Study_729
> 
> @Abosed would you please post this link and update on the issue assigned to you? That's how we'll keep track of and review completed curation tasks.

Ok I will.

Thanks

**Comment by RotimiDesire** [comment]
Hello @lwaldron @cmirzayi, I tried creating a BugSigDB account but I'm yet to get an email confirmation. I can't go ahead with my curation because of this.

**Comment by lwaldron** [comment]
@RotimiDesire there is an account under the username "Desire" active since 11 March (https://bugsigdb.org/Special:ListUsers) - is that you? If so, could you try logging in with Google?

**Comment by chondatondaponda** [comment]
@cmirzayi @ftzohra22 @lwaldron, I posted a comment asking to curate #12 (that was assigned and then removed) but haven't gotten a response yet, should I keep waiting or can I post a comment on another unclaimed study for my next contribution?

**Comment by ftzohra22** [comment]
@chondatondaponda please check #12

**Comment by RotimiDesire** [comment]
@lwaldron Yes, I registered with the username "Desire" on 11 March but I can't login at all with Google or my password.

**Comment by chondatondaponda** [comment]
@ftzohra22 thank you

**Comment by Annabelcute** [comment]
@lwaldron @cmirzayi @ftzohra22 
Please kindly review my curation thanks

https://bugsigdb.org/Study_636

**Comment by srishtig2412** [comment]
Hello, do we have to complete the above listed tasks first before contributing ?

**Comment by cmirzayi** [comment]
@srishtig2412 Yes please follow the instructions above which will involve making two contributions. Thanks!

**Comment by Mehak-4545** [comment]
> @RotimiDesire You can also provide me your email address and I should be able to invite you. Feel free to email me at [cmirzayi@gmail.com](mailto:cmirzayi@gmail.com) if you don't want to post it publicly.

Hello, I am Mehak Sharma, an Outreachy applicant from India. I am facing the same issue and am unable to join the slack channel. Can I get an invite as well? My mail address is : mehaksharma2303@gmail.com
Thanks!

**Comment by Mehak-4545** [comment]
If this issue is still open I would like to take up the curation as I have gone through the reference materials. Thanks!

**Comment by ftzohra22** [comment]
@Mehak-4545 Please complete the first contribution before you claim a paper and curate on your own. I've also sent you an invite to join bugsigdb channel. Thank you!

**Comment by EuniceMiriti** [comment]
Hello, Kindly help review my curation. Thank you
https://bugsigdb.org/Study_615

**Comment by cmirzayi** [comment]
The first contribution task using the Qualtrics survey is now closed to new applicants. If you have an in-progress mini-curation form, please complete it as soon as possible.

**Please note that this does _not_ affect curation on bugsigdb.org, edits to bugsigdb.org, and other stretch contribution tasks which will continue to be accepted until the application deadline on April 3rd.**
