### ISSUE TITLE
Gut microbiota analyses of inflammatory bowel diseases from a representative Saudi population

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#100]
Alsulaiman, R.M., Al-Quorain, A.A., Al-Muhanna, F.A. et al. Gut microbiota analyses of inflammatory bowel diseases from a representative Saudi population. BMC Gastroenterol 23, 258 (2023). https://doi.org/10.1186/s12876-023-02904-2

https://link.springer.com/article/10.1186/s12876-023-02904-2

**Comment by Omabekee** [comment]
Hi @cmirzayi , I notice a duplication here, this is the article I was assigned to at issue #78
