### ISSUE TITLE
The impact of cancer cachexia on gut microbiota composition and short-chain fatty acid metabolism in a murine model

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#102]
Mouse study!

Jeong SM, Jin EJ, Wei S, Bae JH, Ji Y, Jo Y, Jeong JH, Im SJ, Ryu D. The impact of cancer cachexia on gut microbiota composition and short-chain fatty acid metabolism in a murine model. BMB Rep. 2023 Jul;56(7):404-409. doi: 10.5483/BMBRep.2023-0068. PMID: 37220908; PMCID: PMC10390285.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10390285/

**Comment by deegrayce** [comment]
Grace Ogundaini

**Comment by cmirzayi** [comment]
Assigned.

**Comment by deegrayce** [comment]
Hello. In need of review please.

**Comment by cmirzayi** [comment]
Marked for review.

**Comment by cmirzayi** [comment]
@deegrayce Can you link me to the curation?

**Comment by deegrayce** [comment]
@cmirzayi sure, here's the link  https://bugsigdb.org/Study_802

**Comment by cmirzayi** [comment]
Hi @deegracye. Great curation.

I noticed a few small errors

- The direction of all the alpha diversity measures are reversed from what they should be.
- Clostridium sensu stricto 1 is curated as Clostridia. These are not equivalent. You may have to enter this one as clostridium sensu stricto 1 without finding the accompanying taxonomy in the browser. We've had issues identifying clostridium genera before.
- Candidatus Arthromitus is curated as Candidatus Arthromitus sp. SFB-mouse. Though this is a study of mice, these are not equivalent.	

Please make these changes. Thank you!

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 |1  |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 21 |

**Comment by deegrayce** [comment]
Hello @cmirzayi thank you for the corrections. I have made the changes accordingly. 
https://bugsigdb.org/Study_802

**Comment by Peacesandy** [comment]
Reviewed
