### ISSUE TITLE
Microbiome diversity in African American, European American, and Egyptian colorectal cancer patients

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#103]
Amr Elkholy, Nagavardhini Avuthu, Mohammed Abdalla, Michael Behring, Prachi Bajpai, Hyung-Gyoon Kim, Doaa Header, Reham AH. Abo Elwafa, Hesham Saed, Amira Embaby, Nefertiti El-Nikhely, Sarah Obuya, Mostafa Mohamed, Ahmed Ashour Badawy, Ahmed Nawar, Farrukh Afaq, Laura Q. Rogers, Sejong Bae, James M. Shikany, Lori Brand Bateman, Mona Fouad, Mansoor Saleh, Temesgen Samuel, Sooryanarayana Varambally, Chittibabu Guda, Waleed Arafat, Upender Manne,
Microbiome diversity in African American, European American, and Egyptian colorectal cancer patients,
Heliyon,
Volume 9, Issue 7,
2023,
e18035,

https://www.sciencedirect.com/science/article/pii/S240584402305243X

**Comment by Chloebea** [comment]
Hello, I would like to work on this for curation as my 2rd contribution. please assign me this study

**Comment by Imsara123** [comment]
Sara Mohammed

**Comment by Chloebea** [comment]
please asign this study to me. i would love to make curation on it
@cmirzayi  @lwaldron  please

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Chloebea** [comment]
hello @cmirzayi  @lwaldron @SvetlanaUP i have finished my curation on study  https://bugsigdb.org/Study_803 .
waiting for your review.

**Comment by SvetlanaUP** [comment]
Marked as ready for review.

**Comment by cmirzayi** [comment]
This is a good quality curation; however it's missing Figure 3 which is the one against all analysis and should be curated as well. Curate those 4 experiments correctly and this is done.

Also one small point is that it's a cross-sectional observational study, not a lab experiment.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 19 |

**Comment by Chloebea** [comment]
@cmirzayi @lwaldron @SvetlanaUP ...     i really appreciate the efforts you have put in to review my curated study and i have also put into practice the feedback you gave me.
here is the link with fig 3 also curated  https://bugsigdb.org/Study_803       
i will highly appreciate your further suggestions.

**Comment by Peacesandy** [comment]
Reviewed 
https://bugsigdb.org/Study_803
