### ISSUE TITLE
Rare phylotypes in stone, stool, and urine microbiomes are associated with urinary stone disease

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#104]
### NOTE TO CURATOR: Potentially difficult and time-consuming curation

Suryavanshi M, Agudelo J and Miller A (2023) Rare phylotypes in stone, stool, and urine microbiomes are associated with urinary stone disease. Front. Mol. Biosci. 10:1210225. doi: 10.3389/fmolb.2023.1210225

https://www.frontiersin.org/articles/10.3389/fmolb.2023.1210225/full

**Comment by stormztee** [comment]
Taiwo Adeyombo

**Comment by cmirzayi** [comment]
Assigned.

**Comment by stormztee** [comment]
Hello @cmirzayi  @lwaldron 
This study needs to be reviewed:
https://bugsigdb.org/Study_825

**Comment by cmirzayi** [comment]
This is a good first curation of a challenging article. We don't often do meta-analysis so it's a bit tougher than other studies. I think all of Figure 6 needs to be curated, not just 6B which appears to be what was primarily curated. Also some of these are decreased which is why they have a negative log2foldchange value so additional signatures for decreases are needed.

The p-values were FDR-adjusted therefore there was an MHT correction.

Firmicutes is NCBI taxon ID 1239.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 17 |

**Comment by stormztee** [comment]
Thank you very much @cmirzayi . I will work on the outstanding issues.

**Comment by lwaldron** [comment]
@Peacesandy would you mark these pages as reviewed, since @cmirzayi reviewed them in November and then you did too? I want to make sure that all the reviews that were posted here are also counted as reviewed in bugsigdb.org, but currently every subpage of https://bugsigdb.org/Study_825 is still listed as "Needs review".

**Comment by Peacesandy** [comment]
Marked as Reviewed
https://bugsigdb.org/Study_825
