### ISSUE TITLE
The gut microbiome in social anxiety disorder: evidence of altered composition and function

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#105]
Butler, M.I., Bastiaanssen, T.F.S., Long-Smith, C. et al. The gut microbiome in social anxiety disorder: evidence of altered composition and function. Transl Psychiatry 13, 95 (2023). https://doi.org/10.1038/s41398-023-02325-5

https://www.nature.com/articles/s41398-023-02325-5#Sec9

**Comment by SophieZSorenson** [comment]
Sophie Sorenson

**Comment by Imsara123** [comment]
Sara Mohammed

**Comment by cmirzayi** [comment]
Assigned.

**Comment by ChineseChikki** [comment]
@cmirzayi @lwaldron 
This was abandoned so i curated it
Needs review: https://bugsigdb.org/Study_858

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_858

Reviewed
