### ISSUE TITLE
A comparison of the infant gut microbiome before versus after the start of the covid-19 pandemic

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#106]
Querdasi, F.R., Vogel, S.C., Thomason, M.E. et al. A comparison of the infant gut microbiome before versus after the start of the covid-19 pandemic. Sci Rep 13, 13289 (2023). https://doi.org/10.1038/s41598-023-40102-y

https://www.nature.com/articles/s41598-023-40102-y

**Comment by Folakunmi21** [comment]
Afuape Esther

**Comment by cmirzayi** [comment]
Assigned!

**Comment by cmirzayi** [comment]
Hi @Folakunmi21. I think this is a great first curation!

While you curated the three experiments correctly, the labels for the group 1 and group 0 for each experiment make it extremely difficult to determine which experiment is which. Please remember that our goal here is not just to extract the information as written but to create something the someone looking at the curation can understand without having to look at the original paper.

Please revise the group 1 and group 0 names accordingly, thinking specifically about what each group 1 and group 0 was _specifically for each experiment._ Thank you!

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 21 |

**Comment by Folakunmi21** [comment]
Thank you for your feedback! I’ve edited the groups. Please, review them once more.

**Comment by Peacesandy** [comment]
Reviewed
