### ISSUE TITLE
The influence of liver transplantation on the interplay between gut microbiome and bile acid homeostasis in children with biliary atresia

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#107]
Waldner B, Aldrian D, Zöggeler T, Oberacher H, Oberhuber R, Schneeberger S, Messner F, Schneider AM, Kohlmaier B, Lanzersdorfer R, Huber WD, Entenmann A, Müller T, Vogel GF. The influence of liver transplantation on the interplay between gut microbiome and bile acid homeostasis in children with biliary atresia. Hepatol Commun. 2023 May 15;7(6):e0151. doi: 10.1097/HC9.0000000000000151. PMID: 37184522; PMCID: PMC10187839.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10187839/

**Comment by jumokeadeoyo** [comment]
Hi @cmirzayi. I would love to curate this paper. Can you please assign this to me.

**Comment by jumokeadeoyo** [comment]
Name: Olajumoke Adeoyo

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Peacesandy** [comment]
Reviewed
