### ISSUE TITLE
Delayed gut microbiota maturation in the first year of life is a hallmark of pediatric allergic disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#108]
Delayed gut microbiota maturation in the first year of life is a hallmark of pediatric allergic disease – Courtney Hoskinson et al. – Nature Communications 2023

https://www.nature.com/articles/s41467-023-40336-4

**Comment by Otakuwind** [comment]
HI, i wish to curate this paper.

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_818

Reviewed
