### ISSUE TITLE
Changes in the stool and oropharyngeal microbiome in obsessive-compulsive disorder

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#11]
Condition: Obsessive Compulsive Disorder (OCD)
URL: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8795436/

**Comment by kahvecirem** [comment]
Hi! I'm interested in this article. I'd love to be assigned to it.

**Comment by kahvecirem** [comment]
https://bugsigdb.org/Study_317 
Can you check my task?

**Comment by Kiiki015** [comment]
Hello @ftzohra22  can I please work on this?

**Comment by ftzohra22** [comment]
@kahvecirem I didn't find any experiment/signature entries by you in this study on bugsigdb. You might have gotten confused by the experiments curated by another person under the study. It was bug and I just cleared them for you. Please complete the curation and I'll review. Thank you

**Comment by kahvecirem** [comment]
> @kahvecirem I didn't find any experiment/signature entries by you in this study on bugsigdb. You might have gotten confused by the experiments curated by another person under the study. It was bug and I just cleared them for you. Please complete the curation and I'll review. Thank you

Everything is clearer now. Really thank you so much. I didn't want to change experiment, signature them, as it was stated on Slack that it's not okay to edit wiki comments.

**Comment by kahvecirem** [comment]
I have completed my work(https://bugsigdb.org/Study_317). I would be very happy if you could review it. Thank you for your interest. @ftzohra22 

Best regards

**Comment by kahvecirem** [comment]
Thank you for your feedback, I will revise

**Comment by ftzohra22** [comment]
@kahvecirem Thank you for taking the time to make the corrections.
