### ISSUE TITLE
Antibiotic treatment using amoxicillin-clavulanic acid impairs gut mycobiota development through modification of the bacterial ecosystem

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#110]
Antibiotic treatment using amoxicillin-clavulanic acid impairs gut mycobiota development through modification of the bacterial ecosystem – Madeleine Spatz et al. – Microbiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01516-y

**Comment by cmirzayi** [comment]
@hodanbili Assigned. I have no idea why I can't see your comments but I can't.

**Comment by cmirzayi** [comment]
This is a challenging curation and you've made a good start. There are in fact several experiments that should be curated:

1. Mouse sample fungal results post-antibiotic treatment using ITS (Fig. 2D)
2. Mouse sample bacterial results post-antibiotic treatment using 16S (Fig. 3C)
3. Child sample bacterial results post-antibiotic treatment using 16S (Fig. 3E)

Structuring the experiments like this should make the paper a bit less confusing to curate and would probably clarify most of the remaining issues around the curation. Make sure that what is curated for each experiment corresponds to that experiment.

Additionally, I did not find any evidence of matching.

Signatures should not be identical for increase and decrease.


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 11 |

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_820

Reviewed!
