### ISSUE TITLE
Gut microbiota-derived metabolites mediate the neuroprotective effect of melatonin in cognitive impairment induced by sleep deprivation

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#111]
Gut microbiota-derived metabolites mediate the neuroprotective effect of melatonin in cognitive impairment induced by sleep deprivation – Xintong Wang et al. – Microbiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01452-3

**Comment by Davidlred** [comment]
can i have this assigned to me please

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Davidlred** [comment]
Thank you very much.

**Comment by Davidlred** [comment]
i am done with the curation

**Comment by cmirzayi** [comment]
This is a good start to a curation. Unfortunately, I think there was a fundamental misunderstanding of what was occurring in the paper and what needs to be curated. The authors used LEfSe to perform what is called a one vs. all approach for three groups (CON-FMT, SD-FMT, SD+Mel-FMT). Each of these contrasts is a separate experiment and each had a single signature (increased in that group). You then curate the bacterial taxa for that group presented in Figure 4C.

Please revise with the corrected experiments. Thank you!

Some other small issues of note:

Any studies of non-humans (in this case mice) are almost certainly laboratory experiments.

This is a study of response to fecal microbial transplant, not sleep.


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 13 |

https://bugsigdb.org/Study_804

**Comment by Davidlred** [comment]
Thank you very much , although waldron said that the condition of a study
is what is being contrasted against, which is why I chose sleep. I'd duly
review , thanks for the feedback

**Comment by Davidlred** [comment]
Also could you please throw some light on " to perform what is called a one vs. all approach for three groups (CON-FMT, SD-FMT, SD+Mel-FMT). Each of these contrasts is a separate experiment and each had a single signature (increased in that group)." 

take for instance the CON-FMT group , what would i contrast against in the experiment?


thank you very much

**Comment by Davidlred** [comment]
hello @cmirzayi , after much deliberations and collaborations on the slack channel assisted by @lwaldron , i have implemented some changes , and i am ( subject to the request i made on the slack channel asking for signature 2 of experiment 1 to be deleted), ready for the second review. thank you very much

**Comment by Peacesandy** [comment]
Reviewed
https://bugsigdb.org/Study_804
