### ISSUE TITLE
Sputum bacterial load and bacterial composition correlate with lung function and are altered by long-term azithromycin treatment in children with HIV-associated chronic lung disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#112]
Sputum bacterial load and bacterial composition correlate with lung function and are altered by long-term azithromycin treatment in children with HIV-associated chronic lung disease – Regina E. Abotsi et al. – Mictobiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01460-x

**Comment by ChineseChikki** [comment]
Name: Chinenye Ozoagudike

I will like to claim this article please

**Comment by ChineseChikki** [comment]
ok thanks

**Comment by ChineseChikki** [comment]
@SvetlanaUP @lwaldron @cmirzayi 
Needs Review
https://bugsigdb.org/Study_822

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi @SvetlanaUP 
while waiting for my review, I re-worked on this paper which was incomplete and did some corrections and completed it. from TODO for Reviewers help clean up.
BELOW IS THE LINK (Needs Review)
https://bugsigdb.org/Study_503

**Comment by ChineseChikki** [comment]
@SvetlanaUP @lwaldron @cmirzayi  just a gentle reminder. I submitted my curated work a long time ago and it has since not yet been reviewed.

**Comment by cmirzayi** [comment]
Hi Chinenye. This is a good first attempt at a curation; however some changes are needed. Being an RCT and a very thorough one at that, this paper presents a fairly challenging curation. I look forward to seeing the revised curation.

- Case (group 1) and Control (group 0) are not properly defined. For experiment 1, the contrast is at a specific time point between cases and controls. For experiments 2 and 3, it is looking only at AZM-treated participants compared baseline to 48 weeks and 72 weeks respectively.

- The V4 region was sequenced, not V3.

- They report several differential abundance results in the supplement; however the main text used ANCOM which was not selected as a statistical test. This should be the only statistical test selected.

- Shannon was increased in cases at 48 weeks

- Several taxa present in Figure 5 appear to be missing from the curation for experiments 2 and 3

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 |  1|
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 14 |

**Comment by ChineseChikki** [comment]
I received the feedback with thanks. I have really learned a lot from the correction, and I will do as you pointed out and push back.

**Comment by ChineseChikki** [comment]
@cmirzayi I have taken note of the correction pointed out and i have implemented the missing futures. I have really grown in the past few weeks of been part of this project and I am confident i will perform better in my third curation.

**Comment by ChineseChikki** [comment]
@cmirzayi Just a gentle reminder: please take a second look at this. I have implemented the correction.
https://bugsigdb.org/Study_822

**Comment by Peacesandy** [comment]
Reviewed 
https://bugsigdb.org/Study_822
