### ISSUE TITLE
Longitudinal disease-associated gut microbiome differences in infants with food protein-induced allergic proctocolitis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#117]
Longitudinal disease-associated gut microbiome differences in infants with food protein-induced allergic proctocolitis – Victoria M. Martin et al. – Microbiome 2022

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01322-y

**Comment by Tolulope028** [comment]
Tolulope Ogunleye

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_815
Needs review

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_815

Reviewed
