### ISSUE TITLE
COVID-19 mRNA vaccine-mediated antibodies in human breast milk and their association with breast milk microbiota composition

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#119]
COVID-19 mRNA vaccine-mediated antibodies in human breast milk and their association with breast milk microbiota composition – Shilin Zhao et al. – npj Vaccines

https://www.nature.com/articles/s41541-023-00745-4

**Comment by frecklesnspecs** [comment]
May I have this paper assigned to me once my First Contribution is approved?
Thank you!
Clarissa Abidog

**Comment by cmirzayi** [comment]
Assigned.

**Comment by frecklesnspecs** [comment]
Hi @cmirzayi and @SvetlanaUP! 

Can you provide some guidance on how I should proceed on this article? In the spirit of accuracy over quantity, I did not consider that someone would hop on to finish what I'd started before I was able to return. I am happy that they are able to contribute so much and I am wondering if I should get a new article? Or if we are focused on cleaning up the database, locating another incomplete curation? I don't want to create ambiguity in her contribution and I'd love the chance to really contribute, myself.

Thank you for your feedback!

**Comment by Peacesandy** [comment]
Reviewed!
https://bugsigdb.org/Study_835
