### ISSUE TITLE
Temporal changes in fecal microbiota of patients infected with COVID-19: a longitudinal cohort 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#120]
Temporal changes in fecal microbiota of patients infected with COVID-19: a longitudinal cohort – Tatiana Galperine et al. – BMC Infectious Diseases 2023

https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-023-08511-6

**Comment by Tolulope028** [comment]
Tolulope Ogunleye

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Khadija411** [comment]
hey there @cmirzayi or @SvetlanaUP .kindly assign this to me.

**Comment by JigzG** [comment]
Jigyasa Gupta 
Can I curate this if no other response has been recorded?

**Comment by Fortunehechi** [comment]
I have the same question too. @SvetlanaUP , @cmirzayi 

If it hasn’t been curated, can I try to curate it while my first submission is being reviewed?

**Comment by lwaldron** [comment]
@Fortunehechi @JigzG whoever starts on this first can have it! Note though that it's no longer part of the Oct2023 contribution period.

**Comment by JigzG** [comment]
Sure!
Thanks @lwaldron

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_831

Needs review

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_831
Reviewed
