### ISSUE TITLE
Exploring gut microbiota in adult Atlantic salmon (Salmo salar L.): Associations with gut health and dietary prebiotics

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#121]
Exploring gut microbiota in adult Atlantic salmon (Salmo salar L.): Associations with gut health and dietary prebiotics – Jie Wang et al. – Animal Microbiome 2023

https://animalmicrobiome.biomedcentral.com/articles/10.1186/s42523-023-00269-1

**Comment by Gboladee** [comment]
May I have this paper assigned to me once my First Contribution is approved?
Thank you!
Adeniji Agbolade

**Comment by cmirzayi** [comment]
Assigned.

**Comment by lwaldron** [comment]
@SvetlanaUP also this one will need the host species added at https://bugsigdb.org/Help:Admin

**Comment by bolanlew** [comment]
Name: Bolanle Wahab
Hi @SvetlanaUP @cmirzayi  I’d like to claim this article

**Comment by bolanlew** [comment]
@SvetlanaUP @cmirzayi @Omabekee 
I’d like this article to be assigned to me please.

**Comment by snehuman** [comment]
can I be assigned this?

**Comment by SvetlanaUP** [comment]
@snehuman this study is already curated and it's under review.

**Comment by cmirzayi** [comment]
@bolanlew Good job. There seemed to be some confusion about what to curate between Figure S3 and Figure 7. From a close reading of the results, everything presented in 7 is present in S3 along with more taxa so I would have focused on that. I think as a result there are several mistakes in the curation.


| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 |  |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0|
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 16 |

- Study design is laboratory experiment
- Many significant taxa in supp. figure 3 were not curated
- Paper states no sig. differences in alpha diversity
- I think everything present in Figure 7 should be present in supp. figure 3 and supp. figure 3 is easier to read so I would have focused on that
- Statistcal test was MaAsLin2 only
- They did adjust for multiple comparisons

**Comment by bolanlew** [comment]
Thank you for the corrections @cmirzayi i have  taken note of them.

**Comment by omojokunoluwatomisin10** [comment]
@bolanlew, can we work on the correction together

**Comment by SvetlanaUP** [comment]
@bolanlew @omojokunoluwatomisin10 please do corrections in collaboration.

**Comment by omojokunoluwatomisin10** [comment]
@cmirzayi, the figure 7 is relative abundance, I know bugsigdb only curates differential abundance

**Comment by bolanlew** [comment]
@omojokunoluwatomisin10 yes we can, thanks
And noted @SvetlanaUP

**Comment by omojokunoluwatomisin10** [comment]
@bolanlew, my slack handle is Omojokun oluwatomisin

**Comment by SvetlanaUP** [comment]
Hello @bolanlew @omojokunoluwatomisin10, how are going your corrections?

**Comment by bolanlew** [comment]
Hi @SvetlanaUP thank you
We have made the corrections and sent it to the slack channel for second review. Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_912 reviewed.
