### ISSUE TITLE
Analysis of strain, sex, and diet-dependent modulation of gut microbiota reveals candidate keystone organisms driving microbial diversity in response to American and ketogenic diets

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#122]
Analysis of strain, sex, and diet-dependent modulation of gut microbiota reveals candidate keystone organisms driving microbial diversity in response to American and ketogenic diets – Anna C. Salvador et al. – Microbiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01588-w

**Comment by Win13nie** [comment]
@SvetlanaUP I would like to curate this article
Winnie Wahome

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by Win13nie** [comment]
@SvetlanaUP and @cmirzayi I need review on this paper curation
https://bugsigdb.org/Study_808

**Comment by SvetlanaUP** [comment]
Marked as ready for review.

**Comment by Win13nie** [comment]
Thanks @SvetlanaUP

**Comment by cmirzayi** [comment]
Hi @Win13nie I am not sure that this paper was actually curatable. You did a commendable job trying to curate it regardless and I had to spend more than half an hour puzzling it out.

It looks like Table 1 is the differential abundance results but I'm not sure how they'd be curated as there's so much in there that is unclear about what the actual contrasts were. I can't rightly grade you for this curation so I am going to mark you down as full credit. Apologies for what was surely a challenging article.

**Comment by Win13nie** [comment]
Thank you.
It was challenging.
