### ISSUE TITLE
PandaGUT provides new insights into bacterial diversity, function, and resistome landscapes with implications for conservation

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#123]
PandaGUT provides new insights into bacterial diversity, function, and resistome landscapes with implications for conservation – Guangping Huang et al. – Microbiome 2023

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01657-0

**Comment by Davidlred** [comment]
can i have this paper assigned to me please, although i have done a second contribution already..

**Comment by SvetlanaUP** [comment]
@Davidlred please see the other types of contribution that you can do while waiting the review report: https://community-bioc.slack.com/archives/C04RATV9VCY/p1697144958544289

**Comment by Omabekee** [comment]
@SvetlanaUP  May I curate this?
Chioma Onyido.

**Comment by Omabekee** [comment]
Hi @cmirzayi @SvetlanaUP currently looking for papers to curate, this doesn't look assigned yet. 🙏🏾

**Comment by Shruti700** [comment]
Hey @SvetlanaUP can you assign this to me?
-Shruti Pal

**Comment by JigzG** [comment]
Can I curate this?

**Comment by lwaldron** [comment]
@JigzG @Shruti700 @Omabekee @Davidlred please let us know if you still want to curate this even though it's no longer during the Outreachy contribution period.

**Comment by Davidlred** [comment]
that wont be a problem sir

**Comment by JigzG** [comment]
I am in for contributing!

**Comment by SvetlanaUP** [comment]
@Davidlred assigned.

**Comment by Davidlred** [comment]
thanks

**Comment by Dindihub** [comment]
Hi @SvetlanaUP. Can I be assigned this study to curate? Thanks

**Comment by abziatwrite** [comment]
I would like to claim this article @SvetlanaUP @lwaldron @Peacesandy @Omabekee. My name is Abiola Fausat. Thank you.

**Comment by Dindihub** [comment]
Hi @SvetlanaUP. Please review my curation of this study. https://bugsigdb.org/Study_892

Thanks

**Comment by SvetlanaUP** [comment]
Hi @Dindihub, unfortunately, this curation is poorly done:

- First, this study is a whole genome metagenomic study, not with a 16S rRNA gene sequencing approach. 

- Also, other study design elements are not correctly identified, such as condition, contrast groups, statistical analysis etc.

- Figure 4A is not curatable since we are not interested in relative abundances. Thus, we curated Figure 3A for significant differential abundances.

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 0
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 0
Contrast groups correctly identified (1 point): 0
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 1
Identified correct statistical test (1 point): 0
Identified MHT correction (1 point): 0
Correctly recorded matched on factors (1 point): 0
Entered correct number of statistical tests per experiment (1 point): 0
All diversity measures identified (1 point): 0
Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
All signature sources correctly identified (-1 for each error) (2 points): 0
Abundance direction correctly selected (1 point): 0
Members of Signatures identified correctly (2 points): 0
Correct use of NCBI taxonomy (2 points): 0
**Total (maximum 23 points): 5**

https://bugsigdb.org/Study_892 reviewed ✅

**Comment by Dindihub** [comment]
Thanks for the review @SvetlanaUP . I admit the study was overwhelming because I don't have a scientific background. I've seen your correction and will apply the specifics to future studies. Thank you.

**Comment by omojokunoluwatomisin10** [comment]
@SvetlanaUP can i work on this

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 yes please

**Comment by fiddyhamma** [comment]
Hello @SvetlanaUP 
@omojokunoluwatomisin10 reached out to me to collaborate in correcting this study and I noticed fig 2A and supplemental S7A showing statistically significant alpha diversity (Shannon and Simpson’s index) wasn’t curated in these groups MIN, QXL and QIN. The increase is shown in the image and supported in the texts too. 

Also, this excerpt
“Here, we present a comprehensive panda gut microbiome catalog (termed pandaGUT), established with Nanopore, Pacbio, and Illumina sequencing data across highly diverse samples to address host-microbe coevolution and improve conservation efforts.”
Only Illumina was recorded in this study and I want to confirm if it’s okay to add both Nanopore and Pacbio 

Lastly, do you think It's okay to contact the researchers to shed more light on fig 3A?

**Comment by SvetlanaUP** [comment]
@fiddyhamma @omojokunoluwatomisin10 In the end of my feedback is stated "https://bugsigdb.org/Study_892 reviewed and **corrected** ✅" that means that this curation did not need any changes. Corrections were made. Please put back this curation as it was before your changes.

**Comment by SvetlanaUP** [comment]
@fiddyhamma 
Thank you for adding alpha diversity.
Illumina is main sequencing method in this study. The other two are used for selected and/or pooled samples.
We are not contacting the authors of the paper to interpret their study. The paper should be interpreted by the curator as it is written.

**Comment by SvetlanaUP** [comment]
@fiddyhamma @omojokunoluwatomisin10 I made the curation back to corrected version. Please do not make any changes.
**https://bugsigdb.org/Study_892 is reviewed and corrected ✅**

**Comment by fiddyhamma** [comment]
Okay, noted @SvetlanaUP

**Comment by omojokunoluwatomisin10** [comment]
Noted @SvetlanaUP
