### ISSUE TITLE
The gut-microbiota-brain axis in a Spanish population in the aftermath of the COVID-19 pandemic: microbiota composition linked to anxiety, trauma, and depression profiles 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#125]
The gut-microbiota-brain axis in a Spanish population in the aftermath of the COVID-19 pandemic: microbiota composition linked to anxiety, trauma, and depression profiles – Stefanie Malan-Müller et al. – Gut Microbes 2022
https://www.tandfonline.com/doi/full/10.1080/19490976.2022.2162306

NOTE: This paper is without open access, here is downloaded pdf:
[The gut microbiota brain axis in a Spanish population in the aftermath of the COVID 19 pandemic microbiota composition linked to anxiety trauma and.pdf](https://github.com/waldronlab/BugSigDBcuration/files/12871061/The.gut.microbiota.brain.axis.in.a.Spanish.population.in.the.aftermath.of.the.COVID.19.pandemic.microbiota.composition.linked.to.anxiety.trauma.and.pdf)

**Comment by Wangui-T** [comment]
Wangui Thuo
Would love to curate the paper.

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by JigzG** [comment]
Can I curate this?

**Comment by Wangui-T** [comment]
Hey Jigz, I've already curated it. I'm currently waiting for its review.

**Comment by ChineseChikki** [comment]
@SvetlanaUP @cmirzayi @lwaldron 
Needs review: https://bugsigdb.org/Study_805
it was abandoned.
