### ISSUE TITLE
Metagenomic sequencing reveals altered gut microbial compositions and gene functions in patients with non-segmental vitiligo

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#127]
Metagenomic sequencing reveals altered gut microbial compositions and gene functions in patients with non-segmental vitiligo – Mei Luan – BMC Microbiology

https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03020-7

**Comment by RotimiDesire** [comment]
Desire Oluwarotimi.

I want to claim this article for curation. @SvetlanaUP @cmirzayi

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by RotimiDesire** [comment]
Thank you.

**Comment by RotimiDesire** [comment]
@SvetlanaUP @cmirzayi 

I'm ready for review. https://bugsigdb.org/Study_834

**Comment by cmirzayi** [comment]
Marked for review.

**Comment by cmirzayi** [comment]
Excellent curation. They only matched on age, sex, and BMI is the only mistake I found.

One small thing is that in combining LEfSe and Mann-Whitney results is that these results had slightly different criteria. For instance, LEfSe does not use MHT correction while the Mann-Whitney results in the paper did. However, it is good enough as-is and does not need to be changed.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 22 |

**Comment by cmirzayi** [comment]
Closed.

**Comment by RotimiDesire** [comment]
Thank you @cmirzayi
