### ISSUE TITLE
Association Between Breastmilk Microbiota and Food Allergy in Infants.

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#129]
Association Between Breastmilk Microbiota and Food Allergy in Infants -- Shuo Wang et al. --- Front Cell Infect Microbiol. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8790183/

**Comment by PATIENCE-ONAH** [comment]
Hello @cmirzayi, can I work on this for second contribution.

**Comment by cmirzayi** [comment]
@PATIENCE-ONAH Assigned.

**Comment by PATIENCE-ONAH** [comment]
Thank you.

**Comment by JigzG** [comment]
Can I curate this pl?

**Comment by Peacesandy** [comment]
This study has been reviewed 

https://bugsigdb.org/Study_836
