### ISSUE TITLE
Age and the aging process significantly alter the small bowel microbiome

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#13]
Condition: Aging
URL: https://www.sciencedirect.com/science/article/pii/S2211124721012195

**Comment by anshikabhatt** [comment]
Hello, I would like to work on this article.

**Comment by cmirzayi** [comment]
Hi @anshikabhatt I don't seem to have a completed curation survey for you. Please submit before working on this article. Thank you.

**Comment by anshikabhatt** [comment]
Hello, @cmirzayi 
Thank you for reaching out to me. I apologize for any inconvenience, but I have been having trouble submitting the curation survey. I tried to create an account on the platform you suggested, but I encountered some issues and I'm currently unable to complete the survey.
Given these circumstances, I kindly request that you unassign me from the task as I won't be able to complete it at this time. I'm sorry for any inconvenience this may cause.
Thank you for your understanding

**Comment by Anthonyqueencode** [comment]
@ftzohra22 please can I work on this one please

**Comment by Kiiki015** [comment]
Hello @ftzohra22 please can I work on this?

**Comment by Anthonyqueencode** [comment]
@lwaldron please can I work on this please. I requested on this earlier but no reply yet. Please @ftzohra22 @cmirzayi

**Comment by Anthonyqueencode** [comment]
Wow @cmirzayi  thank you

**Comment by Kiiki015** [comment]
Hello, @ftzohra22 @cmirzayi I'm yet to be assigned an issue. Please assign this to me.

**Comment by cmirzayi** [comment]
I'm sorry @Kiiki015 but we've already assigned it to someone. There are other ways to contribute as specified here: https://bugsigdb.org/Help:Contents#How_can_I_get_involved.3F

**Comment by Kiiki015** [comment]
> I'm sorry @Kiiki015 but we've already assigned it to someone. There are other ways to contribute as specified here: https://bugsigdb.org/Help:Contents#How_can_I_get_involved.3F

Thank you.

**Comment by cmirzayi** [comment]
Hi @Anthonyqueencode Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by Anthonyqueencode** [comment]
Hi Waldron
Thanks for writing, I would have loved to finish it up but I'm having some
challenges with it. So please you can assign it to someone else. Thank you

Enjoy the rest of your day

**Comment by cmirzayi** [comment]
@Anthonyqueencode No worries. Thank you for your efforts.

**Comment by atrayees** [comment]
I have curated this study at https://bugsigdb.org/Study_726 , also could you please delete Experiment 3 Signature 3? I do not know how it got duplicated from Signature 2. Thanks!

**Comment by lwaldron** [comment]
@atrayees I just made you a bugsigdb.org administrator so that you can delete pages. When deleting a Study or Experiment, make sure to delete any Experiments or Signatures within that page, so that they don't become "orphaned" (see "Orphaned Experiments" and "Orphaned Signatures" at https://bugsigdb.org/Help:Cleanup). The problem with orphaned signatures is that they can become connected to a new Study or Experiment created later.

**Comment by atrayees** [comment]
Thank you so much, and point noted!

**Comment by Chloebea** [comment]
> Condition: Aging URL: https://www.sciencedirect.com/science/article/pii/S2211124721012195
Hello, i would love to work in this please

**Comment by PATIENCE-ONAH** [comment]
Hello @cmirzayi, could you please assign this work to me.

**Comment by cmirzayi** [comment]
@PATIENCE-ONAH This one is not for curation. It needs to be reviewed (by me).

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_726

Reviewed
