### ISSUE TITLE
Gut Microbial Signatures Can Discriminate Unipolar from Bipolar Depression

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#130]
Gut Microbial Signatures Can Discriminate Unipolar from Bipolar Depression -- Peng Zheng et al. -- Adv. Sci.

https://onlinelibrary.wiley.com/doi/10.1002/advs.201902862

**Comment by ChineseChikki** [comment]
name: Chinelsy
I want to claim this paper

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi 
Needs review
https://bugsigdb.org/Study_806

**Comment by SvetlanaUP** [comment]
Assigned.
