### ISSUE TITLE
Changes in gut microbiota composition and diversity associated with post-cholecystectomy diarrhea

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#131]
Changes in gut microbiota composition and diversity associated with post-cholecystectomy diarrhea -- Yan-Dong Li et al.-- World Journal of Gastroenterology

https://www.wjgnet.com/1007-9327/full/v27/i5/391.htm

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi 
Name: Chinelsy
I want to curate this paper

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi 
Needs review
https://bugsigdb.org/Study_816
