### ISSUE TITLE
Dysbiosis and Implication of the Gut Microbiota in Diabetic Retinopathy

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#132]
Dysbiosis and Implication of the Gut Microbiota in Diabetic Retinopathy --Yinhua Huang et al. -- Front Cell Infect Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2021.646348/full

**Comment by ChineseChikki** [comment]
@cmirzayi @lwaldron 
Name: Chinelsy
I want to claim this paper

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi 
Needs review
https://bugsigdb.org/Study_809
