### ISSUE TITLE
Alterations in the vaginal microbiota of patients with preterm premature rupture of membranes

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#133]
Alterations in the vaginal microbiota of patients with preterm premature rupture of membranes -- Chunmei Yan -- Front Cell Infect Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2022.858732/full

**Comment by ChineseChikki** [comment]
Name: chinelsy
I would  like to be assign this paper

**Comment by ChineseChikki** [comment]
@cmirzayi seen..Thanks.

**Comment by ChineseChikki** [comment]
@cmirzayi @lwaldron 
please this curation needs review
https://bugsigdb.org/Study_810

**Comment by Peacesandy** [comment]
Reviewed!

https://bugsigdb.org/Study_810
