### ISSUE TITLE
Gut microbiome signatures reflect different subtypes of irritable bowel syndrome

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#134]
Gut microbiome signatures reflect different subtypes of irritable bowel syndrome -- Qi Su et al. -- Gut Microbes.

https://www.tandfonline.com/doi/full/10.1080/19490976.2022.2157697

**Comment by Omabekee** [comment]
Hi @cmirzayi , can I curate this?
Chioma Onyido

**Comment by cmirzayi** [comment]
Yes.

**Comment by Omabekee** [comment]
Yess!! Thank you.😁

**Comment by Omabekee** [comment]
Good morning @cmirzayi @SvetlanaUP @lwaldron 
 
This curation is complete and ready for review: 
https://bugsigdb.org/Study_774

**Comment by SvetlanaUP** [comment]
Marked as ready for review.
