### ISSUE TITLE
Hair Microbiome Diversity within and across Primate Species

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#136]
Hair Microbiome Diversity within and across Primate Species -- Catherine Kitrinos et al. -- ASM Journals

https://journals.asm.org/doi/10.1128/msystems.00478-22

**Comment by temmyoctavia08** [comment]
Hi@svetlanaUP please can I have this article assigned to me for curation

**Comment by MeddyCharles** [comment]
Hi@SvetalanaP, please,  can I have this article assigned to me ?

**Comment by temmyoctavia08** [comment]
Thank you. I have started working on it

**Comment by Omabekee** [comment]
It's already been assigned, kindly choose another.

**Comment by temmyoctavia08** [comment]
Hi @SvetlanaUP I’m done curating this article

**Comment by temmyoctavia08** [comment]
@cmirzayi Thank you so much for the review, okay I will report to the team and ask that a new paper be assigned to me. Thank you so much

**Comment by temmyoctavia08** [comment]
@SvetlanaUP My curation has been reviewed and the mentor advised that the I should not curate my article due to no differential abundance result in the article please I want to ask that a new paper be assigned to  me to curate thank you ma.

**Comment by SvetlanaUP** [comment]
@cmirzayi should we completely delete it https://bugsigdb.org/Study_894 ?

**Comment by temmyoctavia08** [comment]
@SvetlanaUP @cmirzayi please ma’am how can I get a new paper assigned to me, I have checked through and it seems all the available articles have been assigned

**Comment by SvetlanaUP** [comment]
@temmyoctavia08 you are assigned to https://github.com/waldronlab/BugSigDBcuration/issues/193

**Comment by temmyoctavia08** [comment]
Okay thank you ma’am @SvetlanaUP
