### ISSUE TITLE
Changes and significance of gut microbiota in children with focal epilepsy before and after treatment

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#137]
Changes and significance of gut microbiota in children with focal epilepsy before and after treatment -- Changci Zhou et al. -- Front. Cell. Infect. Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2022.965471/full

**Comment by Shruti700** [comment]
@cmirzayi @Omabekee Can I curate this?
-Shruti Pal

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by ChineseChikki** [comment]
@lwaldron @SvetlanaUP 
Needs review was abandoned
https://bugsigdb.org/Study_839
