### ISSUE TITLE
Biliary Microbiota in Choledocholithiasis and Correlation With Duodenal Microbiota

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#138]
Biliary Microbiota in Choledocholithiasis and Correlation With Duodenal Microbiota -- Jinyan Han et al. -- Front. Cell. Infect. Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2021.625589/full

**Comment by Tolulope028** [comment]
@cmirzayi can I curate this?

**Comment by lwaldron** [comment]
@Tolulope028 please let us know if you still want to curate this even though it's no longer during the Outreachy contribution period.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_733
Reviewed
