### ISSUE TITLE
Taxonomic Characterization and Short-Chain Fatty Acids Production of the Obese Microbiota

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#139]
Taxonomic Characterization and Short-Chain Fatty Acids Production of the Obese Microbiota -- Carmen Martínez-Cuesta et al. -- Front. Cell. Infect. Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2021.598093/full

**Comment by AleruDivine** [comment]
Aleru Divine

I want to claim this article for curation as my third contribution. @cmirzayi @lwaldron @SvetlanaUP

**Comment by AleruDivine** [comment]
Aleru Divine

I want to claim this article for curation. @cmirzayi @lwaldron @SvetlanaUP

**Comment by AleruDivine** [comment]
Hi @cmirzayi can i curate this?

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP @cmirzayi  my curation is ready for review.

Here's he link: https://bugsigdb.org/Study_847
