### ISSUE TITLE
Widespread protein lysine acetylation in gut microbiome and its alterations in patients with Crohn's disease

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#14]
Condition: Crohn's disease
URL: https://pubmed.ncbi.nlm.nih.gov/32807798/

**Comment by sopeadeniji** [comment]
@ftzohra22  Hi, I will like to claim this article.

**Comment by atrayees** [comment]
Hi, I would love to curate this article
Atrayee Samanta

**Comment by lwaldron** [comment]
@atrayees I'll post some more articles shortly that you can choose from.

**Comment by atrayees** [comment]
@lwaldron okay sure! thabk you

**Comment by sopeadeniji** [comment]
@ftzohra22 @cmirzayi 
Please review this completed curation https://bugsigdb.org/Study_738

**Comment by cmirzayi** [comment]
Hi @sopeadeniji. This is an excellent curation of a challenging paper. You were so close to being perfect on it but unfortunately it looks like you didn't complete the signatures. Each signature should have all the taxa listed as increased or decreased for that signature but you didn't quite finish them. For instance, signature 1 has 3 of 6 taxa. Signature 3 is incorrect. The metaproteome increased signature is also missing. Please consider revising.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Correctly recorded matched on factors (1 point): 1
12. Entered correct number of statistical tests per experiment (1 point): 1
13. All diversity measures identified (1 point):
14. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
15. All signature sources correctly identified  (-1 for each error)  (2 points): 1
16. Abundance direction correctly selected (1 point): 1
17. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0
18. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): Not scored

Total (maximum 23 points): Not scored

**Comment by sopeadeniji** [comment]
@cmirzayi I have included the missing signatures for https://bugsigdb.org/Study_738 as mentioned. Please, let me know if there are further changes to make. Thanks for the review.
