### ISSUE TITLE
Gallbladder microbiota composition is associated with pancreaticobiliary and gallbladder cancer prognosis

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#140]
Gallbladder microbiota composition is associated with pancreaticobiliary and gallbladder cancer prognosis -- Mari Kirishima et al. -- BMC Microbiol.

https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-022-02557-3

**Comment by Folakunmi21** [comment]
@cmirzayi I'll be curating this

**Comment by Folakunmi21** [comment]
@lwaldron @cmirzayi this is ready for review: https://bugsigdb.org/Study_827

**Comment by Folakunmi21** [comment]
The curation is ready for review: https://bugsigdb.org/Study_827 @lwaldron @cmirzayi
