### ISSUE TITLE
Geography, niches, and transportation influence bovine respiratory microbiome and health

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#141]
Geography, niches, and transportation influence bovine respiratory microbiome and health -- Jianmin Chai -- Front. Cell. Infect. Microbiol.

https://www.frontiersin.org/articles/10.3389/fcimb.2022.961644/full

**Comment by Folakunmi21** [comment]
I'll like to curate this @cmirzayi

**Comment by Folakunmi21** [comment]
This study is a meta analysis and it was my first time curating one. It can be reviewed here; https://bugsigdb.org/Study_850 so that I can make the necessary corrections. @lwaldron @cmirzayi
