### ISSUE TITLE
Microbial communities associated with honey bees in Brazil and in the United States

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#144]
Microbial communities associated with honey bees in Brazil and in the United States -- de Oliveira Scoaris et al. -- Braz J Microbiol.

https://link.springer.com/article/10.1007/s42770-021-00539-7

NOTE: This paper is not open access, here's the link to download the pdf:
[Microbial communities associated with honey bees in Brazil and in the United States](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8578358/pdf/42770_2021_Article_539.pdf)

**Comment by Nikilight** [comment]
@SvetlanaUP, please can I have this Paper assigned to me?

**Comment by Nikilight** [comment]
Thank you @Omabekee

**Comment by Omabekee** [comment]
No curatable signatures. Issue closed.

**Comment by SvetlanaUP** [comment]
@Nikilight yes, you are right, this paper does not report statistical analysis and does not provide curatable results. **Your effort will be recored.** Please select another paper.

**Comment by Nikilight** [comment]
Thank you @SvetlanaUP I have requested for a new one to be assigned to me.
