### ISSUE TITLE
Characterization of microbial communities and predicted metabolic pathways in the uterus of healthy mares

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#145]
Characterization of microbial communities and predicted metabolic pathways in the uterus of healthy mares -- Thomson P. et al. -- Open Vet J

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9805769/

**Comment by veekamunya** [comment]
Hello, can I be assigned to curate this paper, thank you.

**Comment by samreen-19** [comment]
Hello @veekamunya are you still working on curating this paper?

**Comment by samreen-19** [comment]
@SvetlanaUP it seems like the original assignee is not working on curating this paper anymore. I would like to curate it if that's the case. May I?

**Comment by SvetlanaUP** [comment]
Please @samreen-19 give some time to @veekamunya respond to your question that you made 5 hours ago. Thank you for your patience.

**Comment by SvetlanaUP** [comment]
@samreen-19 go ahead with this curation. I've checked, it's not even open on bugsigdb.

**Comment by samreen-19** [comment]
Hi @SvetlanaUP um, is this paper curatable? There are no signatures which can be curated, and overall there isn't much information to record. Can you please check?

**Comment by SvetlanaUP** [comment]
This study is not curatable.
