### ISSUE TITLE
Composition and Functional Potential of the Human Mammary Microbiota Prior to and Following Breast Tumor Diagnosis

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#147]
Composition and Functional Potential of the Human Mammary Microbiota Prior to and Following Breast Tumor Diagnosis -- Hoskinson C et al. -- mSystems

https://journals.asm.org/doi/10.1128/msystems.01489-21

**Comment by OdigiriGreat** [comment]
Please I'd love to curate this paper

**Comment by OdigiriGreat** [comment]
@Chloe Mirzayi @lwaldron this study is ready for review. 
bugsigdb.org/Study_789
