### ISSUE TITLE
Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#148]
Integrating microbial and host transcriptomics to characterize asthma-associated microbial communities -- Castro-Nallar E et al. -- BMC Med Genomics

https://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-015-0121-1

**Comment by MyleeeA** [comment]
Hi @cmirzayi @lwaldron  can I curate this?

**Comment by MyleeeA** [comment]
Hi @lwaldron @cmirzayi @svetlana_up 

I've finished curating this, waiting for your feedback

**Comment by MyleeeA** [comment]
Thank you

**Comment by lwaldron** [comment]
This is https://bugsigdb.org/Study_838
