### ISSUE TITLE
Alterations in Oral Microbiota in HIV Are Related to Decreased Pulmonary Function

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#15]
Condition: HIV
URL: https://pubmed.ncbi.nlm.nih.gov/31682463/

**Comment by shallockh02** [comment]
I Kelvin Joseph will curate this

**Comment by ftzohra22** [comment]
Assigned.

**Comment by shallockh02** [comment]
How is this coming a long [#15](https://bugsigdb.org/Study_731)

**Comment by shallockh02** [comment]
How is this coming a long [#15](https://bugsigdb.org/Study_731)

**Comment by shallockh02** [comment]
finished my curation would you check it out and give me feedback so that I can start on another curation?
[#15](https://bugsigdb.org/Study_731)

**Comment by lwaldron** [comment]
@shallockh02 would you include a link to the study in bugsigdb.org?

**Comment by lwaldron** [comment]
It looks like it is https://bugsigdb.org/Study_731, but this publication was already in bugsigdb.org as https://bugsigdb.org/Study_580. @ftzohra22 we should not be assigning papers that are already in bugsigdb.org - would you please check all the others you've assigned to make sure they are not already curated in the database?

@shallockh02 we will review your contribution, thank you!

**Comment by shallockh02** [comment]
Hello @lwaldron so I  have not contributed anything thus far??

**Comment by shallockh02** [comment]
Hello @lwaldron so I  have not contributed anything thus far??

**Comment by ftzohra22** [comment]
I'll double check @lwaldron. Thank you for catching this
