### ISSUE TITLE
Trans-ethnic gut microbiota signatures of type 2 diabetes in Denmark and India

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#150]
Trans-ethnic gut microbiota signatures of type 2 diabetes in Denmark and India -- Alvarez-Silva C et al. -- Genome Med.

https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-021-00856-4

**Comment by Omabekee** [comment]
Hi @cmirzayi @SvetlanaUP can I curate this?
Chioma Onyido

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by Omabekee** [comment]
Thank you.

**Comment by Omabekee** [comment]
Hi @SvetlanaUP  @cmirzayi @lwaldron 
This curation is complete and ready for review.
https://bugsigdb.org/Study_844
