### ISSUE TITLE
Divergence of Phyllosphere Microbial Communities Between Females and Males of the Dioecious Populus cathayana

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#152]
Divergence of Phyllosphere Microbial Communities Between Females and Males of the Dioecious Populus cathayana -- Liu L et al. -- Mol Plant Microbe Interact

https://apsjournals.apsnet.org/doi/10.1094/MPMI-07-20-0178-R

**Comment by SvetlanaUP** [comment]
Plant microbiome.
