### ISSUE TITLE
Metagenomic assessment of gut microbial communities and risk of severe COVID-19

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#153]
Metagenomic assessment of gut microbial communities and risk of severe COVID-19 -- Nguyen LH et al. -- Genome Medicine

https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-023-01202-6

**Comment by Tolulope028** [comment]
Tolulope Ogunleye

I'll like to work on this

**Comment by Tolulope028** [comment]
I'll like to work on this paper

**Comment by OdigiriGreat** [comment]
Hi @cmirzayi @lwaldron seems this paper hasn't been assigned to anyone. Can I go ahead to work on it please
