### ISSUE TITLE
Increased Abundance of Achromobacter xylosoxidans and Bacillus cereus in Upper Airway Transcriptionally Active Microbiome of COVID-19 Mortality Patients Indicates Role of Co-Infections in Disease Severity and Outcome

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#154]
Increased Abundance of Achromobacter xylosoxidans and Bacillus cereus in Upper Airway Transcriptionally Active Microbiome of COVID-19 Mortality Patients Indicates Role of Co-Infections in Disease Severity and Outcome-- Devi P et al. -- Microbiol Spectr.

https://journals.asm.org/doi/10.1128/spectrum.02311-21

**Comment by Boadiwaa** [comment]
@cmirzayi @SvetlanaUP I'd like to curate this article please

**Comment by leenaaize** [comment]
hello @SvetlanaUP, I would like to curate this article please

**Comment by leenaaize** [comment]
hello @SvetlanaUP @cmirzayi , I would like to curate this please

**Comment by leenaaize** [comment]
Hello @SvetlanaUP @Omabekee . I am done with my curation.
Here is the link for review: https://bugsigdb.org/Study_891
Thank you!

**Comment by leenaaize** [comment]
Thank you for the review!
@AleruDivine
@MyleeeA
@RotimiDesire
@MyleeeA

**Comment by Folakunmi21** [comment]
This was a great curation! @leenaaize  well-done! I appreciate how you properly included the definition for each group (the group 1). It made your curation easy to understand without having to read the paper. However, your condition was wrong. Remember, the condition is what is being contrasted, that is, what is different between both groups. In this case, both groups had COVID-19, but they had different disease severity. The condition I chose is defined as “Quantification of some aspect of COVID-19 symptoms, **such as severity** or time to remission”. I hope this helps in your subsequent curations. Good luck

CURATION RESULT 
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 22

@SvetlanaUP study 891 reviewed

**Comment by leenaaize** [comment]
Thank you for the review! @Folakunmi21. I have taken note of your feedback about how to properly identify the condition and will apply it in subseqent curations.

**Comment by omojokunoluwatomisin10** [comment]
@SvetlanaUP, can i change the condition 1 definition

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 this curation is already corrected by @Folakunmi21

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 I've noticed that you already changed it without permission. Please do not do any edits in already corrected curations with the green label "Reviewed". 

@Folakunmi21 I put back the corrected condition.

**Comment by omojokunoluwatomisin10** [comment]
Okay @SvetlanaUP and @Folakunmi21  but i saw in the review that '' Quantification of some aspect of COVID-19 symptoms, such as severity or time to remission”. The condition still remain COVID-19 measurement.

So sorry for the the inconvenience

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 it's exactly what it should be: https://www.ebi.ac.uk/ols4/ontologies/efo/classes?short_form=EFO_0600019
"COVID-19 symptoms measurement" defined as “Quantification of some aspect of COVID-19 symptoms, such as severity or time to remission”. 

cc @Folakunmi21

**Comment by Folakunmi21** [comment]
@omojokunoluwatomisin10 the condition in the study was different severity of COVID-19 symptoms. The condition I picked covers it, which is why I included the definition in my review.

**Comment by omojokunoluwatomisin10** [comment]
Okay, thank you
