### ISSUE TITLE
Composition of gut microbiota in infants in China and global comparison

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#156]
Composition of gut microbiota in infants in China and global comparison -- Kuang YS et al. -- Sci Rep.

https://www.nature.com/articles/srep36666

**Comment by OdigiriGreat** [comment]
I will love to work on this study

**Comment by OdigiriGreat** [comment]
I finished curating this study, please help review @cmirzayi 

bugsigdb.org/Study_213
