### ISSUE TITLE
Feeding Rapidly Alters Microbiome Composition and Gene Transcription in the Clownfish Gut

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#157]
Feeding Rapidly Alters Microbiome Composition and Gene Transcription in the Clownfish Gut -- Parris DJ et al. -- Appl Environ Microbiol.

https://journals.asm.org/doi/10.1128/aem.02479-18

**Comment by Omabekee** [comment]
Hi @cmirzayi @SvetlanaUP
I would love to curate this.
Chioma Onyido

**Comment by Muqtadirat** [comment]
Hi @SvetlanaUP I would love to claim this paper for curation. Thank you

**Comment by Muqtadirat** [comment]
Hi @Omabekee @SvetlanaUP, I would like to have this curated paper reviewed. Thank you

**Comment by Muqtadirat** [comment]
@AleruDivine Here's my paper, thank you

**Comment by cmirzayi** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 14.5 |

- Table S2 should have been curated
- Contrast should be condition of study, not where the sample was taken from
- Incorrect sample sizes
- Used ANCOM for differential abundance of taxa

**Comment by Buraah** [comment]
Hello @cmirzayi  , @SvetlanaUP 
I noticed the review/feedback for this study has not been implemented and I'd love to do it.
Please can I go ahead?

**Comment by Buraah** [comment]
Hello @SvetlanaUP. 
I'm so sorry this took a while, I had a minor health challenge.
Thank you for your patience.

I am done implementing the review on this study now and here are the things I changed:
1. I changed the condition of the study.
2. I changed the groups definition and added 3 more experiments to the study. Because it has more than 1 contrast group.
3. I changed the sample sizes for the groups.
4. I deleted the irrelevant statistical tests.
5. I changed the signature source and curated all signatures from Table S2.

**Comment by cmirzayi** [comment]
@SvetlanaUP Marked as reviewed.

**Comment by Fificode** [comment]
Hi @SvetlanaUP,
I am currently resolving missing NCBI Taxonomy IDs and noticed that Experiment 1, Signature 1 and Experiment 4, Signature 2 contains the taxon "Marinicellaceae".
https://bugsigdb.org/30446559/Experiment_1/Signature_1
https://bugsigdb.org/30446559/Experiment_4/Signature_2
I would like to update it with the Taxonomy ID: 3120710. 
Please kindly let me know if you have any concerns with making this change.

Thank you!
