### ISSUE TITLE
Vaginal Microbiome Metagenome Inference Accuracy: Differential Measurement Error according to Community Composition

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#158]
Vaginal Microbiome Metagenome Inference Accuracy: Differential Measurement Error according to Community Composition -- Carter KA et al. -- mSystems

https://journals.asm.org/doi/10.1128/msystems.01003-22

**Comment by ChineseChikki** [comment]
@cmirzayi @lwaldron 
please I will love to curate this paper

**Comment by ChineseChikki** [comment]
@cmirzayi @lwaldron 
I would love to curate this paper

**Comment by ChineseChikki** [comment]
@lwaldron @cmirzayi 
needs review
https://bugsigdb.org/Study_843
