### ISSUE TITLE
Learning machine approach reveals microbial signatures of diet and sex in dog

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#159]
Learning machine approach reveals microbial signatures of diet and sex in dog -- Scarsella E et al. -- PLoS One

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237874

**Comment by Davidlred** [comment]
can i have this assigned to me @cmirzayi

**Comment by Davidlred** [comment]
Seen ,thanks @lwaldron

**Comment by Peacesandy** [comment]
curated and reviewed at
https://bugsigdb.org/Study_846
