### ISSUE TITLE
Respiratory Tract Dysbiosis Is Associated with Worse Outcomes in Mechanically Ventilated Patient

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#16]
Condition: Critically ill Patients
URL: https://pubmed.ncbi.nlm.nih.gov/32717152/

**Comment by Dherahrose** [comment]
https://pubmed.ncbi.nlm.nih.gov/32717152/

Please assign me this article 
-dherahrose

**Comment by Dherahrose** [comment]
I would like to be assigned to this project

Dherahrose

**Comment by Dherahrose** [comment]
Thanks

**Comment by lwaldron** [comment]
I think this is https://bugsigdb.org/Study_715 . Why are both of the signatures empty? The descriptions "The α-diversity comparisons between clusters showed that cluster 2 had the lowest Shannon index, followed by cluster" refer to alpha diversity, but Signatures are only for reporting taxa. Alpha diversity is reported as part of the Experiment. This study does report differentially abundant taxa that belong in a Signature.

**Comment by Dherahrose** [comment]
I appreciate pointing this out, working on it and making the necessary
changes.

**Comment by Dherahrose** [comment]
@lwaldron I have worked on the signature as well as the description of #16, are there other adjustments I need to make?  
https://bugsigdb.org/Study_715

**Comment by Dherahrose** [comment]
@lwaldron @cmirzayi please I need a review on #16, also can start curating #25 while i wait for a review on #16?

**Comment by cmirzayi** [comment]
Hi @Dherahrose Unfortunately this paper is a bit more complex than it seems. There are more than a dozen experiments in it and you will need to curate Figure 4 as well as Figures E8 through E12. Please review carefully the statistical test methodologies used for _differential abundance_ and not for alpha diversity.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (prospective cohort)
3. Entered all relevant experiments and no irrelevant experiments (1 point): Not scored. This is a highly complex study with more than a dozen experiments. Only one experiment was entered and it was curated from a figure that does not contain differential abundance information.
4. Body site correctly identified (i.e. does not include multiple sites) (1 point):
5. Condition entered according to contrast (correct EFO ontology) (1 point):
6. Contrast groups correctly identified (1 point):
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point):
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Correctly recorded matched on factors (1 point):
12. Entered correct number of statistical tests per experiment (1 point):
13. All diversity measures identified (1 point):
14. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
15. All signature sources correctly identified  (-1 for each error)  (2 points):
16. Abundance direction correctly selected (1 point):
17. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
18. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 23 points): Not scored

**Comment by cmirzayi** [comment]
Hi @Dherahrose Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by Peacesandy** [comment]
Reviewed
