### ISSUE TITLE
Host-specificity among abundant and rare taxa in the sponge microbiome

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#160]
Host-specificity among abundant and rare taxa in the sponge microbiome -- Reveillaud J et al. -- ISME J

https://www.nature.com/articles/ismej2013227

**Comment by imalovee** [comment]
Hello, I'd love to work on this paper. Can You please assign it to me? Thank you @Omabekee , @lwaldron , @SvetlanaUP , @Peacesandy

**Comment by SvetlanaUP** [comment]
@imalovee this paper is not for curation. Please select another one.

**Comment by SvetlanaUP** [comment]
Sponge microbiome.

**Comment by SvetlanaUP** [comment]
Sponge microbiome not included in the "Hosts"
