### ISSUE TITLE
Host-Associated Quantitative Abundance Profiling Reveals the Microbial Load Variation of Root Microbiome

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#161]
Host-Associated Quantitative Abundance Profiling Reveals the Microbial Load Variation of Root Microbiome -- Guo X et al-- Plant Commun.

https://www.sciencedirect.com/science/article/pii/S2590346219300033

**Comment by Davidlred** [comment]
please could you explain the issues who are opening ?

**Comment by Omabekee** [comment]
Hi @Davidlred , these are curatable papers that have not been curated on BugSigDB.
You can comment on any paper you're interested in curating, with your name and tagging the mentors, @cmirzayi @SvetlanaUP

**Comment by Davidlred** [comment]
oh, thank you very much, i thought we weren't supposed to curate more than
one from the git repo

**Comment by lwaldron** [comment]
@Davidlred let us know if you still want to curate this even though it's no longer during the Outreachy contribution period.

**Comment by Ebere330** [comment]
> Host-Associated Quantitative Abundance Profiling Reveals the Microbial Load Variation of Root Microbiome -- Guo X et al-- Plant Commun.
> 
> https://www.sciencedirect.com/science/article/pii/S2590346219300033

Hello can you please assign this paper to me? I will love to curate this. @SvetlanaUP @Omabekee

**Comment by Omabekee** [comment]
Hi @Ebere330 I don't think this paper is available for curation for Outreachy applicants as the labels have been removed.

Please choose another one, specifically look out for those that have the "OutreachyMay2024" label and I'll assign to you. 🙏🏾

**Comment by Ebere330** [comment]
Great. will do that thank you
