### ISSUE TITLE
A Combined Analysis of Gut and Skin Microbiota in Infants with Food Allergy and Atopic Dermatitis: A Pilot Study

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#163]
A Combined Analysis of Gut and Skin Microbiota in Infants with Food Allergy and Atopic Dermatitis: A Pilot Study -- Ewas Los-Rycharska et al. -- Nutrients

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8156695/

**Comment by cmirzayi** [comment]
Sure. Assigned.

**Comment by Peacesandy** [comment]
Thank You so much

**Comment by Peacesandy** [comment]
Hi @cmirzayi @SvetlanaUp and @lwaldron 
This curation is complete and ready for review
https://bugsigdb.org/Study_842
