### ISSUE TITLE
Smoking and salivary microbiota: a cross-sectional analysis of an Italian alpine population

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#166]
Smoking and salivary microbiota: a cross-sectional analysis of an Italian alpine population -- Giacomo Antonello et al. -- Scientific reports

https://www.nature.com/articles/s41598-023-42474-7

**Comment by OdigiriGreat** [comment]
@lwaldron @cmirzayi  please I will love to curate this paper

**Comment by OdigiriGreat** [comment]
@lwaldron @cmirzayi  this study is ready for review bugsigdb.org/Study_845
