### ISSUE TITLE
Inferences in microbial structural signatures of acne microbiome and mycobiome

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#169]
Inferences in microbial structural signatures of acne microbiome and mycobiome –Jubin Kim et al – Journal of Microbiology

Note: The open access version of this paper is unavailable. The pdf version can be found here: https://sci-hub.se/https://doi.org/10.1007/s12275-021-0647-1

supplemental: https://static-content.springer.com/esm/art%3A10.1007%2Fs12275-021-0647-1/MediaObjects/12275_2021_647_MOESM1_ESM.pdf

**Comment by RotimiDesire** [comment]
I want to curate this. @cmirzayi @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by lwaldron** [comment]
Curated at https://bugsigdb.org/Study_852
