### ISSUE TITLE
Differences in gut microbiota between allergic rhinitis, atopic dermatitis, and skin urticaria

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#170]
Differences in gut microbiota between allergic rhinitis, atopic dermatitis, and skin urticaria - - Yu-Jih Su et al -- Medicine (Baltimore)

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7939153/

**Comment by Peacesandy** [comment]
Hi @cmirzayi @SvetlanaUp Please, can I curate this?
Peace Sandy

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by Peacesandy** [comment]
Thank You

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_863 
This study has been reviewed
