### ISSUE TITLE
Identifying microbial signatures for patients with postmenopausal osteoporosis using gut microbiota analyses and feature selection approaches

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#171]
Identifying microbial signatures for patients with postmenopausal osteoporosis using gut microbiota analyses and feature selection approaches -- Dageng Huang et al -- frontiers 2023

https://www.frontiersin.org/articles/10.3389/fmicb.2023.1113174/full#h4

**Comment by AleruDivine** [comment]
Hi @cmirzayi @SvetlanaUP I want to claim this article for curation.

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP I have completed the curation.
Here's the link: https://bugsigdb.org/Study_870
I am looking forward to your review.
Thank you!
