### ISSUE TITLE
Substantial overlap between symptomatic and asymptomatic genitourinary microbiota states

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#172]
Substantial overlap between symptomatic and asymptomatic genitourinary microbiota states – Boahemaa Adu-Oppong et al. – Microbiome 2022
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-021-01204-9

**Comment by SvetlanaUP** [comment]
Assigned.

**Comment by MyleeeA** [comment]
https://bugsigdb.org/Study_880

**Comment by MyleeeA** [comment]
@RotimiDesire @AleruDivine @Scholarpat @BarakatAA @imalovee

**Comment by Folakunmi21** [comment]
This was an excellent curation! @MyleeeA 
I slightly adjusted the signature sources by including the exact part the signature was gotten from within result text. This makes the signature source more descriptive. Well done!

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 23
@SvetlanaUP Study 880 reviewed

**Comment by MyleeeA** [comment]
Thank you so much @Folakunmi21 @SvetlanaUP 

This makes me confident to continue curating papers 🤗🤗❤️
