### ISSUE TITLE
Effects of proton pump inhibitor on the human gut microbiome profile in multi-ethnic groups in Singapore

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#175]
Effects of proton pump inhibitor on the human gut microbiome profile in multi-ethnic groups in Singapore – Seok Hwee Koo – Singapore Medical Journal

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6875812/

**Comment by RotimiDesire** [comment]
Hi @SvetlanaUP 

I'd love to curate this article.

**Comment by RotimiDesire** [comment]
Thank You.

**Comment by RotimiDesire** [comment]
Hi @SvetlanaUP 

My curation is ready for review. 

[](https://bugsigdb.org/Study_896)

**Comment by RotimiDesire** [comment]
@AleruDivine @MyleeeA @Scholarpat

**Comment by RotimiDesire** [comment]
Thank You.
