### ISSUE TITLE
Differential peripheral immune signatures elicited by vegan versus ketogenic diets in humans

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#176]
Differential peripheral immune signatures elicited by vegan versus ketogenic diets in humans – Verena M. Link et al – Nature Medicine (2024)
https://www.nature.com/articles/s41591-023-02761-2

**Comment by Enzujp** [comment]
Hi @SvetlanaUP , I'd love to work on this !

**Comment by Folakunmi21** [comment]
Assigned

**Comment by Enzujp** [comment]
> Assigned

Thank you very much!

**Comment by Enzujp** [comment]
> Hi @Enzujp is your curation https://bugsigdb.org/Study_920 ready for review?

It would be in a few hours @SvetlanaUP . Going through it, and finalising.

**Comment by TitilayoMG** [comment]
Hi @Enzujp 
I noticed you have been assigned this paper 3 weeks ago so I wanted to check in to know if everything is going well. I then noticed you commented that it will be ready in few hours but just incase you're facing any blockers, or you have any questions, please do let me know. I will be happy to help.

Thank you so much!

**Comment by Enzujp** [comment]
> Hi @Enzujp I noticed you have been assigned this paper 3 weeks ago so I wanted to check in to know if everything is going well. I then noticed you commented that it will be ready in few hours but just incase you're facing any blockers, or you have any questions, please do let me know. I will be happy to help.
> 
> Thank you so much!

Hi there @TitilayoMG, @SvetlanaUP  , thank you so much for reaching out. I spent about a week studying this paper and the papers of the other participants on the slack group, and I reckoned that I was to create 3 experiments for my paper. 
However, the information is not well organized, and in comparison to some of the other papers that I went through, I could only create one experiment for mine. Sigh. So I've been a little nervous in turning it in. I did ask for help but got vague answers.
Regardless, if I cannot figure it out at day's end, I'd turn it in as I'd rather have done something I'm sure of, than just populate my work with experiments that might be wrong. I hope this makes sense.

**Comment by TitilayoMG** [comment]
Well done @Enzujp 
I understand that curating some papers might not follow the same flow of papers we've curated but please do reach out to me whenever you decide to, my DM is open. I'd love to help 

Thank you

**Comment by AleruDivine** [comment]
Hi @Enzujp, How is this going? I can help review and give feedback if that is okay with you.

**Comment by Enzujp** [comment]
Hi @SvetlanaUP , and @Folakunmi21, I'd like to defer this particular assignment. While I love bugsigdb, I'm not available to complete this task at this time.
@AleruDivine has been extremely helpful in getting me to make what little progress I've made on it and it'd be great if she could get assigned to finish it up, she seems to be a natural at this.
Thank you for the experience!

**Comment by AleruDivine** [comment]
Thank you so much for the kind words @Enzujp🙏

@SvetlanaUP may I proceed to continue working on this, please?

**Comment by SvetlanaUP** [comment]
Assigned to @AleruDivine

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP
I will proceed with the curation right away.

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP, I have finished curating this study and would like to put it up for review.
Thank you so much!

Link to study: https://bugsigdb.org/Study_920

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

In this study Catonella morbi and Blautia sp. both decreased where initially curated as increased. I've corrected this and the curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_920 reviewed.
