### ISSUE TITLE
Airway Microbiome and Serum Metabolomics Analysis Identify Differential Candidate Biomarkers in Allergic Rhinitis

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#180]
Airway Microbiome and Serum Metabolomics Analysis Identify Differential Candidate Biomarkers in Allergic Rhinitis - Yuan et al. - Frontiers 

https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2021.771136/full

**Comment by AdejokeOgunyinka** [comment]
@SvetlanaUP I'd love to be assigned this. My full name is Adejoke Ogunyinka. I'm an Outreachy applicant.

**Comment by Abiola-Salako** [comment]
Hello, @SvetlanaUP May I get assigned to this project, please?

**Comment by SvetlanaUP** [comment]
@Abiola-Salako this paper is already assigned. Please choose another one.

**Comment by Isioma20** [comment]
Good morning @AdejokeOgunyinka , I hope you are doing well.
I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews . I'm willing to help out.

Thank you so much!

**Comment by Isioma20** [comment]
I'm quite certain you can still contribute to the project. Do you want to go ahead with the curation?I can collaborate or help you out if you do. You can @idiaruangela on the slack channel #BugSigDB. Thanks

**Comment by omojokunoluwatomisin10** [comment]
@AdejokeOgunyinka, Hope you are good. Are you still working on your study or did you forget to ask mentors for a review

**Comment by Nana-Habiba** [comment]
@SvetlanaUP May I work on this study, the own has abandon it.

**Comment by omojokunoluwatomisin10** [comment]
@Nana-Habiba, we can collaborate on the study if @SvetlanaUP assigned you to it

**Comment by SvetlanaUP** [comment]
@Nana-Habiba @omojokunoluwatomisin10 sure!

**Comment by omojokunoluwatomisin10** [comment]
@Nana-Habiba, you can chat me up on slack omojokunoluwatomisin

**Comment by Nana-Habiba** [comment]
@SvetlanaUP this is ready for review: https://bugsigdb.org/Study_1076

**Comment by Nana-Habiba** [comment]
@omojokunoluwatomisin10 Good morning just came online now to see your messages, I started working on the paper immediately I requested for it yesterday, I have finished the curation, however you can check it on the above link. And know if there's any input you can point out. Thank you. Maybe we can collaborate on future papers

**Comment by SvetlanaUP** [comment]
@Nana-Habiba this is not ok, you should wait for official approval and then for @omojokunoluwatomisin10

**Comment by omojokunoluwatomisin10** [comment]
In experiment 1 signature 1
proteobacteria should be changed to Pseudomonata
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1224&lvl=3&lin=f&keep=1&srchmode=1&unlock



Bacteroidetes changed to [Bacteroidia]
(https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=200643&lvl=3&srchmode=1&keep=1&unlock)

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 please do make corrections. Thanks!

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 22 |

- correct NCBI taxonomy for Pelomonas is **Roseateles** (corrected)

Well done @Nana-Habiba @omojokunoluwatomisin10

**Comment by Nana-Habiba** [comment]
@Svetlana Ugarcina Perovic ***@***.***> Thank you for the
review, I have taken note of this:  Pelomonas is *Roseateles*

**Comment by Nana-Habiba** [comment]
@Svetlana Ugarcina Perovic ***@***.***>  Good morning
My bad was just going through my inbox, then I came across this. So Sorry
about this, I moved too fast. This won't repeat itself ever again. Thank
you very much for this correction.
