### ISSUE TITLE
Pivotal interplays between fecal metabolome and gut microbiome reveal functional signatures in cerebral ischemic stroke

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#182]
Pivotal interplays between fecal metabolome and gut microbiome reveal functional signatures in cerebral ischemic stroke - Zhao _et al_ - PMC

https://pubmed.ncbi.nlm.nih.gov/36209079/

**Comment by jumokeadeoyo** [comment]
Hello @SvetlanaUP 
I have completed this paper curation, and it is now ready for review. Please find the link below to access it:
https://bugsigdb.org/Study_942

**Comment by jumokeadeoyo** [comment]
Hello @SvetlanaUP 
I have completed this paper curation, and it is now ready for review. Please find the link below to access it:
https://bugsigdb.org/Study_942

**Comment by Peacesandy** [comment]
Hi, @jumokeadeoyo this is a good curation attempt. Here are some errors you made and important points to take note of which will help your future curations ✍️

- The group 1 sample size is 60 not 30, if you read the introductory part of the study subjects, it stated that, A total of 60 subjects were recruited for this study. 30 patients with CIS were enrolled from Qilu Hospital of Shandong University between May 2017 and January 2018. They had been diagnosed by skull computed tomography examination. And 30 CIS patients did not suffer from any pre-existing metabolic or gut disease. In addition to this, they also recruited 30 healthy volunteers who were examined to ensure that they had no metabolic, cardiovascular, or cerebrovascular diseases or cancer and were included as the standard control group. So what this means is that there is a 60 sample size for group 1 and 30 for group 0.
- The sequencing type used is metagenomic sequencing which can be entered as WMS on BugSigDB.
- The Statistical test used is LEfSe, yes the other tests were mentioned, but it was not used to get the differential abundance.
- Ace was mentioned in the alpha diversity, and it accounts for Richness. 
- The Alpha diversity measures were all increased. - {It is found that all microbial richness (Observe, Chao1, and Ace) and diversity (Shannon) were higher in the CIS group than the control group} - reference from the study
- The study design is case-control
- Condition entered according to contrast (correct EFO ontology) - stroke
- There is an MHT correction in the study

*N/B:* The study have been reviewed and corrected

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 0
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 0
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 1
Identified correct statistical test (1 point): 0
Identified MHT correction (1 point): 0
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 0
All diversity measures identified (1 point): 0
Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 15**

@SvetlanaUP    https://bugsigdb.org/Study_942 reviewed and corrected ✅
