### ISSUE TITLE
Alterations in gut microbiota and metabolite profiles in patients with infantile cholestasis

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#185]
Alterations in gut microbiota and metabolite profiles in patients with infantile cholestasis - Jin _et al_ - BMC
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03115-1

**Comment by AmaraLewa** [comment]
I will like to have this paper assigned to me please

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_933

**Comment by AmaraLewa** [comment]
Hi. I am done curating and would love my paper to be reviewed. 

> Ready for review https://bugsigdb.org/Study_933

**Comment by Peacesandy** [comment]
Hi @AmaraLewa this is a good first curation attempt, however here are some few points to note. ✍️

- The body site you entered is incorrect.
- The condition you entered is incorrect
- you did not enter a significance threshold
- you did not correctly record the matched on factor
- Members of Signatures were not identified correctly
- The curatable signature can be gotten from Figure 1c, you just entered Figure 1, which also has relative abundance and Heatmap of KEGG pathway enrichment analysis

*N/B;* The study has been corrected and reviewed 

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
Condition entered according to contrast (correct EFO ontology) (1 point): 0
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 0
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 1
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 1
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 18**

@SvetlanaUP  https://bugsigdb.org/Study_933 reviewed and corrected ✅
