### ISSUE TITLE
A metagenomic study of the gut microbiome in Behcet’s disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#187]
A metagenomic study of the gut microbiome in Behcet’s disease – Zi Ye et al. – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0520-6

**Comment by fiddyhamma** [comment]
I'd love to be assigned this task please

**Comment by Iphenn** [comment]
Hello @SvetlanaUP,

I would love to curate this article if my second choice related to Littermate Methods for Microbiodata Standardization is already assigned to someone else.
Thank you

**Comment by SvetlanaUP** [comment]
Assigned to @fiddyhamma

**Comment by fiddyhamma** [comment]
Hello @SvetlanaUP 
I've completed this curation and would love a review

https://bugsigdb.org/Study_927

**Comment by Omabekee** [comment]
Overall this was a really good second curation! ⭐ @fiddyhamma. I especially appreciate how you curated your group descriptions and your attention to details. However, here are some errors you made and important points to take note which will help your future curations:
1. Study condition: Expt. 3, In this context, B10RIII mice are mice undergoing autoimmune uveitis). The study condition shouldn't be uveitis, but "response to transplant".
2. Sequencing type: Fecal samples were subjected to metagenomic analysis, whereas DNA extracted from saliva samples was subjected to 16S rRNA gene sequencing analysis.
3. Alpha diversity: The only alpha diversity I could identify in this study was that done for the mice group (which was well curated). However, I'm not sure where you got the alpha diversity results for the human aspect.
4. Additional expt: Sometimes, researchers do different stat tests for diff abundance analysis and then compare the results produced by these tests. In this case, Wilcoxon and LEfSe were both used and the results were different. When this happens, they should be curated as separate experiments in bugsigdb (see curation policy). Table S3 is an additional experiment that should've been curated, with the statistical test Wilcoxon (Expt. 4).

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0.5
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 1
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified (-1 for each error) (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2
**Total = 20.5**

@SvetlanaUP, review of Study 927 complete. ✅

**Comment by fiddyhamma** [comment]
Thank you so much for your review @Omabekee 
I've taken note and gone through the corrections on BugSigdb, I'll be more careful in my future curations. 💜
