### ISSUE TITLE
Characterization of microbial communities from gut microbiota of hypercholesterolemic and control subjects 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#188]
Characterization of microbial communities from gut microbiota of hypercholesterolemic and control subjects – Cristian Morales et al. – Front. Cell. Infect. Microbiol.
https://www.frontiersin.org/articles/10.3389/fcimb.2022.943609/full

**Comment by Abiola-Salako** [comment]
kindly assign me to this task @SvetlanaUP .thank you

**Comment by Abiola-Salako** [comment]
I AM THROUGH WITH MY WORK. HERE IS THE LINK FOR REVIEW https://bugsigdb.org/Study_903
THANK YOU @SvetlanaUP @Peacesandy

**Comment by Abiola-Salako** [comment]
Co-contributors review
@AleruDivine

**Comment by Folakunmi21** [comment]
This was a great second curation attempt @Abiola-Salako. Here are some of the errors you made:
1.	You are to curate the body site used for each of the experiment in the study. In this study, stool samples were used for the experiment on differential abundance between the condition and controls, while blood serum was used for the experiment on pathways (which you were right to not curate).
2.	You curated the signatures in reverse i.e you switched increases for decreases and vice versa. The taxa listed in front of the red bars in figure 3 were the ones abundant in hypercholesterolemic patients, while the ones listed in front of the green bars were abundant in the controls.

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 21

@SvetlanaUP Study 903 reviewed:white_check_mark:

**Comment by Abiola-Salako** [comment]
Thank you @SvetlanaUP @Folakunmi21 review seen and the errors will be amended. I appreciate the feedback.

**Comment by Abiola-Salako** [comment]
@SvetlanaUP oh...Thats good to know. Thank you so much for your guidance.

**Comment by Omabekee** [comment]
@SvetlanaUP 2nd review complete. ✅ This issue can now be closed. Thank you.

**Comment by SvetlanaUP** [comment]
[https://bugsigdb.org/Study_903](https://bugsigdb.org/Study_903) reviewed.
