### ISSUE TITLE
Structural and Functional Dysbiosis of Fecal Microbiota in Chinese Patients With Alzheimer's Disease

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#19]
Condition: Alzheimer's Disease
URL: https://pubmed.ncbi.nlm.nih.gov/33614635/

**Comment by sopeadeniji** [comment]
Hi,
Please, assign me to this article.

**Comment by ftzohra22** [comment]
Assigned to you @sopeadeniji

**Comment by sopeadeniji** [comment]
@ftzohra22 @cmirzayi 
Please review this recent curation https://bugsigdb.org/Study_736

**Comment by sopeadeniji** [comment]
@ mcarlsn https://bugsigdb.org/Study_736 has been updated with suggested corrections. Please, review.

**Comment by mcarlsn** [comment]
Thank you for updating the curation, @sopeadeniji!

**Comment by atrayees** [comment]
Study 736
Corrected the MHT correction, the rest of the curation seems fine.

**Comment by lwaldron** [comment]
Thanks @atrayees ! Please go ahead and mark everything as "reviewed" then close this issue.
