### ISSUE TITLE
Different Characteristics in Gut Microbiome between Advanced Adenoma Patients and Colorectal Cancer Patients by Metagenomic Analysis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#190]
Different Characteristics in Gut Microbiome between Advanced Adenoma Patients and Colorectal Cancer Patients by Metagenomic Analysis – Shuwen Han – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01593-22

**Comment by imalovee** [comment]
Hello please @SvetlanaUP 
the previous paper I was assigned which was already halfway worked on by an older intern has a completely different experimental procedures carried out in it which is highly distinct from the questions that we need to respond to...it uses different tests and methods..I can assume the other other intern left it half way because of the same issue.
Please can I be assigned to this paper thank you.

**Comment by allieniola1** [comment]
Hello @SvetlanaUP . I would love to curate this article. Thank you.

**Comment by AdegboyeRukayat** [comment]
Adegboye Rukayat

**Comment by allieniola1** [comment]
Hello, does this mail means the article has been assigned to me?

**Comment by Iphenn** [comment]
Hello @SvetlanaUP, 
I would love to curate this article.
Thank you

**Comment by SvetlanaUP** [comment]
Assigned to @imalovee

**Comment by imalovee** [comment]
Thank you @SvetlanaUP

**Comment by imalovee** [comment]
Hello Mentors @SvetlanaUP @Omabekee I am through with my second task of curating this paper, here is the link: https://bugsigdb.org/Study_907
Thank you.

**Comment by imalovee** [comment]
@scholarpat, @myleen, @BarakatAA here is my paper..thank you

**Comment by imalovee** [comment]
@MyleeA

**Comment by BarakatAA** [comment]
Alright Ima

**Comment by imalovee** [comment]
hello @Kweenb thank you for going through my paper, I have noted your observations.

**Comment by MyleeeA** [comment]
@imalovee 👍

**Comment by Peacesandy** [comment]
This is a great second curation attempt @imalovee. Here are some of the errors you made. 

1. The sequencing detail was not correctly identified, you left it blank. In the paper, the sequencing type used is WMS - metagenomic sequencing, the study used metagenomic analysis.
2. No matched on factor was mentioned in the study. 
3. The differential abundance was gotten from fig 2G and 2H. All signatures were not entered you omitted a lot of signatures. 
4. Abundance direction is incorrect.
5. The signatures you entered as increased and decreased abundance in colorectal cancer are incorrect.

CURATION RESULTS

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
6. Correct study design (1 point): 1
7. Entered all relevant experiments and no irrelevant experiments (1 point): 1
8. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
9. Condition entered according to contrast (correct EFO ontology) (1 point): 1
10. Contrast groups correctly identified (1 point): 1
11. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
12. Antibiotic exclusion correctly identified (1 point): 1
13. Correctly identified sequencing details (2 points): 0
14. Identified correct statistical test (1 point): 1
15. Identified MHT correction (1 point):  1
16. Correctly recorded matched on factors (1 point): 0
17. Entered correct number of statistical tests per experiment (1 point): 1
18. All diversity measures identified (1 point): 1
19. Diversity results correctly entered as increased/decreased/unchanged (1 point):  1
20. All signature sources correctly identified (-1 for each error) (2 points): 1
21. Abundance direction correctly selected (1 point): 0
22. Members of Signatures identified correctly (2 points): 0
23. Correct use of NCBI taxonomy (2 points): 1

Total (maximum 23 points):  15

@SvetlanaUP  https://bugsigdb.org/Study_907 Reviewed ✅

**Comment by imalovee** [comment]
Oops!!. This is an awesome review, to be honest. I am better informed now, though I lowkey wish it came before my second paper but it's all fine still. Pumped and ready to nail the next curation.
Thank you for the opportunity @Peacesandy and @SvetlanaUP

**Comment by Peacesandy** [comment]
Glad you found it helpful
