### ISSUE TITLE
Differences in gut microbiota structure in patients with stages 4-5 chronic kidney disease

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#192]
Differences in gut microbiota structure in patients with stages 4-5 chronic kidney disease - Wu et al- Am J Transl
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8507064/

**Comment by Sneha6003** [comment]
Hello @Folakunmi21 , can you assign this issue to me?

**Comment by Dehbeie** [comment]
Can this be assigned to me? please

**Comment by blessingpeters** [comment]
I see this hasn't been assigned to anyone, can I be assigned this paper, please @SvetlanaUP @Folakunmi21
it'll be my first contribution.

**Comment by Dehbeie** [comment]
Can this be assigned to me @Folakunmi21

**Comment by Scholarpat** [comment]
Hello @Sneha6003, I noticed that you have not completed your curation yet. I am willing to work together with you to help complete it. Kindly reach out, and let's collaborate to finish it. 🤗

**Comment by Sneha6003** [comment]
hi @Scholarpat thanks for reaching out! I am almost done with my curation, just having a lil bit difficulty understanding the signature. Would be grateful for your help 😊

**Comment by Scholarpat** [comment]
Happy to help, I'll go through it and get back to you @Sneha6003

**Comment by Scholarpat** [comment]
Hello @Sneha6003,

Firstly, I want to commend you on your curation efforts. Thank you for allowing me the opportunity to review your work. I found the process insightful, and I appreciate the chance to contribute to it. Upon thorough examination of the article, I've noted a few observations you may want to look into:

1. There appears to be more than one antibiotic exclusion criteria between the case and control groups. While you correctly recorded the exclusion period for the case group as 4 weeks, it seems the control group had a different exclusion period of 3 months. I suggest including both sets of exclusion criteria under the 'Antibiotic exclusion' section. Additionally, it might be beneficial to leave a note on the talk page regarding this. This is a first for me as I haven't encountered this in my curation before so the mentors will have a better suggestion for this.

2. I couldn't find information on "matched-on" or "confounders" within the article, I noticed you included them. You may want to revisit this aspect. Additionally, referring to the recording of the previous office hour where Chloe extensively discussed confounders could provide valuable insights.

3. According to this excerpt **"The Chao1, Observe, PD whole tree, Shannon, and Simpson indices of the fecal colonies in the stage 4-5 CKD group were lower than those of the control group (all P<0.05), indicating that the control group had higher species diversity"** all alpha diversity measures are decreased.  I noticed you curated increased for richness which is understandable. However, while the article discusses increased richness for certain species in the CKD group, it seems the overall richness (observed species - if I'm right) is decreased in the CKD group. PD whole tree is curated as 'Faith' index. I noticed you did not include that. 

4. Although the article references some differentially abundant signatures in-text, **Figure 4** presents a comprehensive list of the signatures and could be a good source for your signature

You may also want to share the curation on the slack platform for opinions from mentors and fellow contributors. I'm also looking forward to other opinions. Please let me know if my points are unclear and if there's anyway I could help further.

**Comment by Sneha6003** [comment]
Hey @Scholarpat , with your help I have made the changes and completed my curation. Your insights were really helpful and I'm grateful for it! If you see anymore errors or changes that are to be made in my curation please feel free to let me know 😊

**Comment by Scholarpat** [comment]
Always happy to help. Well done @Sneha6003 🤗

**Comment by Sneha6003** [comment]
@SvetlanaUP I need a review for this study.

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_908.

**Comment by Peacesandy** [comment]
Hi @Sneha6003 this is a good curation attempt. Here are some errors you made and important points to take note of which will help your future curations ✍️

- The antibiotic exclusion is wrong, the paper stated that exclusion criteria related to antibiotic exclusion specify that patients must not have received agents containing cathartic ingredients, such as antibiotics, urinalysis, and laxative drugs, within 4 weeks before sampling. 
- The sequencing platform is not Illumina
- The signatures were not correctly curated, you are supposed to curate for increase and decrease abundance, you curated for only increased abundance and the signatures are not complete. 


**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 0
Correctly identified sequencing details (2 points): 1
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 0
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 0
Members of Signatures identified correctly (2 points): 0
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 17**

@SvetlanaUP   https://bugsigdb.org/Study_908 reviewed and corrected ✅
