### ISSUE TITLE
Comparison of Small Gut and Whole Gut Microbiota of First-Degree Relatives With Adult Celiac Disease Patients and Controls

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#193]
Comparison of Small Gut and Whole Gut Microbiota of First-Degree Relatives With Adult Celiac Disease Patients and Controls - Bodkhe et al-Front. Microbiol.
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2019.00164/full?utm_source=Email_to_authors_&utm_medium=Email&utm_content=T1_11.5e1_author&utm_campaign=Email_publication&field&journalName=Frontiers_in_Microbiology&id=419818

**Comment by KiitanTheAnalyst** [comment]
I will like to be assigned this paper
My name is Olaitan Suru

**Comment by KiitanTheAnalyst** [comment]
Many Thanks!

**Comment by AleruDivine** [comment]
Good morning @KiitanTheAnalyst, I hope you are doing well.
I have noticed that this issue has been assigned to you for almost three weeks, and as we're in the final week of contribution, I wanted to reach out and see if you're facing any difficulties. If you need assistance or have any blockers or questions, I'm available to help🙏 

Thank you so much!😊

**Comment by SvetlanaUP** [comment]
Reassigned to @temmyoctavia08

**Comment by temmyoctavia08** [comment]
Hi @SvetlanaUP i have started working on this article that has been reassigned to me but it seems it has already been entered into BugSigdb when I tried creating a study, so should I just search for the study and edit or what can I do about this ma’am

**Comment by SvetlanaUP** [comment]
@temmyoctavia08 OK, I see you have already started working on it https://bugsigdb.org/Study_914

**Comment by temmyoctavia08** [comment]
@SvetlanaUP Yes ma’am I have edit and complete the curation, I discovered I could do that without any permission required so I decided to work on it since you have reassigned it to me

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_914

**Comment by temmyoctavia08** [comment]
@SvetlanaUP please ma’am help me delete signature 3 and 5

**Comment by SvetlanaUP** [comment]
@temmyoctavia08 after getting the tag "needs review" there is no editing.

**Comment by temmyoctavia08** [comment]
@SvetlanaUP Okay I’m really sorry about this. Alright ma’am. Thank you for always helping out.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, 

Please I need signatures 4 - 6 of experiment 1 deleted. Thank you!

**Comment by SvetlanaUP** [comment]
@Scholarpat signatures 4 - 6 of experiment 1 deleted.

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Please I need signature 3 of experiment 1 also deleted. Mistakenly left this out in the first post. 
Thank you so much

**Comment by SvetlanaUP** [comment]
"Study 914/Experiment 1/Signature 3" has been deleted. @Scholarpat

**Comment by Scholarpat** [comment]
Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've completed curation of this study.
https://bugsigdb.org/Study_914.

Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_914 is reviewed.

**Comment by cynthianwauzor-sudo** [comment]
Hi, @SvetlanaUP. "old entry" change to "new entry". I would like to resolve the DOI of this curation as well as include its URL

**Comment by SvetlanaUP** [comment]
@cynthianwauzor-sudo please be more specific when recording the changes:
from [copy paste here the old entry of this curation] to [copy paste here the new entry of this curation]

**Comment by cynthianwauzor-sudo** [comment]
Ok, @SvetlanaUP. I would change the DOI from https://doi.org/10.3389/fmicb.2019.00164 to 10.3389/fmicb.2019.00164 and include https://doi.org/10.3389/fmicb.2019.00164 as URL. Thanks. The PMID is valid.

**Comment by SvetlanaUP** [comment]
@cynthianwauzor-sudo 
Why not the journal page: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2019.00164/full as URL?

**Comment by cynthianwauzor-sudo** [comment]
> [@cynthianwauzor-sudo](https://github.com/cynthianwauzor-sudo) Why not the journal page: https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2019.00164/full as URL?

@SvetlanaUP, Okay, thanks. so the journal url should be used always? I was thinking it should be the doi url.
