### ISSUE TITLE
Gut Microbiota Alterations and Their Functional Differences in Depression According to Enterotypes in Asian Individuals

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#194]
Gut Microbiota Alterations and Their Functional Differences in Depression According to Enterotypes in Asian Individuals - Park et al - International Journal of Molecular Sciences
https://www.mdpi.com/1422-0067/24/17/13329

**Comment by allieniola1** [comment]
Hello @SvetlanaUP . I would love to curate this article. Thank you.

**Comment by allieniola1** [comment]
Thank you @SvetlanaUP .

**Comment by allieniola1** [comment]
Hi @SvetlanaUP

I have finished the curation. This article is ready for review. Thank you so much!

**Comment by allieniola1** [comment]
Good morning mentors, my first curation link https://bugsigdb.org/Study_921.
@lwaldron @cmirzayi @SvetlanaUP @Omabekee . Thank you for your review in anticipation

**Comment by Folakunmi21** [comment]
Unfortunately, this curation was not of great quality @allieniola1 .  While there are 3 experiments in the study, only 1 was created. The wrong statistical test was used, there were no confounders nor matched on criteria in the paper but you curated both, and you curated the signatures from figure 2B, instead of 2C. A good read of the methods section also shows that this was a meta analysis, not a cross-sectional observational study. Please, go through the new curation to see more corrections.

**CURATION RESULT**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 0
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 1
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 0
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 0

Total (maximum 23 points): 8
@SvetlanaUP study 921 reviewed

**Comment by allieniola1** [comment]
wow. This is coming in as a shock, but in all thank you so much for the feedback it will help me improve in future contributions @Folakunmi21

**Comment by SvetlanaUP** [comment]
@allieniola1 please do not edit your next work; instead you could make corrections of this one based on @Folakunmi21's feedback.

[Tech-neophyte](https://github.com/Tech-neophyte) could you support this correction?

**Comment by Tech-neophyte** [comment]
> @allieniola1 please do not edit your next work; instead you could make corrections of this one based on @Folakunmi21's feedback.
> 
> [Tech-neophyte](https://github.com/Tech-neophyte) could you support this correction?

Yes absolutely I would love to help!

**Comment by Tech-neophyte** [comment]
Hi! @SvetlanaUP  I went through the article and the curation... The corrections suggested were already in place, only some bacteria names were missing which I have added :)

**Comment by SvetlanaUP** [comment]
BugSigDB reviewed.
