### ISSUE TITLE
Differential Analysis of Gut Microbiota Correlated With Oxidative Stress in Sows With High or Low Litter Performance During Lactation

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#195]
Differential Analysis of Gut Microbiota Correlated With Oxidative Stress in Sows With High or Low Litter Performance During Lactation - Wang et al - Front. Microbiol.
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2018.01665/full

**Comment by blessingpeters** [comment]
Please can i be assigned this? @Folakunmi21 @SvetlanaUP

**Comment by blessingpeters** [comment]
Thank you.

**Comment by Isioma20** [comment]
Hi @blessingpeters  I hope you are doing well.
I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews . I'm willing to help out.

Thank you so much!

**Comment by blessingpeters** [comment]
> Hi @blessingpeters I hope you are doing well. I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews . I'm willing to help out.
> 
> Thank you so much!

Hi @Isioma20 Thanks for offering. Yes, I'd appreciate your help.

**Comment by Isioma20** [comment]
You can find me in the #BugSigDB channel @idiaru Angela on slack. Or tag me here letting me know whatever you need help with.

**Comment by blessingpeters** [comment]
Hi, @Isioma20 I plan on completing it myself with the tips you gave me. I'll let you know if I get stuck. give me some time.

**Comment by Scholarpat** [comment]
Hello @blessingpeters, I hope you are doing well. I noticed this study listed under the 'Incomplete studies' section. It seems it has yet to be completed. I'm available to collaborate on completing the curation. Please let me know if you need any assistance. Sending my best regards.

Best,
Scholastica Urua

**Comment by SvetlanaUP** [comment]
@Scholarpat @blessingpeters please finalize this curation.

**Comment by Isioma20** [comment]
It's the same thing on slack @Scholarpat you can reach her there

**Comment by Scholarpat** [comment]
Thank you @Isioma20

**Comment by blessingpeters** [comment]
> Hi @blessingpeters I hope you are doing well. I noticed this issue has been assigned for over 3 weeks for your second contribution and since this is the final week of contributions, I just want to know if you'd need help or want to collaborate or if you're done and need peer reviews. I'm willing to help out.
> 
> Thank you so much!
Yeah! sure thing

> @Scholarpat @blessingpeters please finalize this curation.
Sure thing. I apologize for taking this much time.

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP, please this curation is ready for review.
https://bugsigdb.org/Study_930

Thank you

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,

I made some changes to the alpha diversity measures previously curated.
The curation is now complete.

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_930 reviewed.
