### ISSUE TITLE
Association of fecal short-chain fatty acids with clinical severity and gut microbiota in essential tremor and its difference from Parkinson’s disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#198]
Association of fecal short-chain fatty acids with clinical severity and gut microbiota in essential tremor and its difference from Parkinson’s disease – Pei Huang et al. – npj Parkinson's Disease
https://www.nature.com/articles/s41531-023-00554-5

**Comment by nityasinghal-14** [comment]
kindly assign this to me

**Comment by SvetlanaUP** [comment]
Assigned to @nityasinghal-14

**Comment by nityasinghal-14** [comment]
I have completed the curation and would like to submit it for review @SvetlanaUP ?

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 19 |

Figure 4 (the discriminant genera identified by LEfSE analysis were used for the Spearman correlation analysis of SCFAs) is quite challenging to curate (well done!), but there is Table 5 in the Supplementary material that could facilitate this curation.

- there is no matching in this study and no MHT (corrected)
- signature source is Figure 4, Table 5 (corrected)
- In the Experiment 2 stats analysis details should be the same and there is only one signature (corrected)

**Comment by nityasinghal-14** [comment]
@SvetlanaUP can I make the corrections and submit again?

**Comment by SvetlanaUP** [comment]
@nityasinghal-14 it's already corrected. Thank you.
