### ISSUE TITLE
Outreachy Applicants- Weekly Meetings/Office hour

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#2]
Welcome, Outreachy applicants! 

My name is Fatima, pronouns she/her. We’re excited for the contribution period to begin and to meet you all. I have been working with Chloe (pronouns: she/her) on the BugSigDB project for some time and am available to answer questions you have about BugSigDB contribution tasks.

In case it’s useful - here is the link to guidance for the first contribution task and the second (optional) contribution task on out Github repo: https://github.com/waldronlab/BugSigDBcuration/issues/1

Also, between now and Monday, April 3, we will be offering weekly office hours for you to log in and ask questions during our normal team meetings. If you are interested in learning more about the BugSigDB project, we strongly recommend attending one of these BugSigDB team meetings. You are welcome to come participant or observe these meetings as well as ask questions. 

These meetings are scheduled for:
Thursday March 9, 10-11 AM ET (https://us02web.zoom.us/j/2737200499)
Thursday March 16, 10-11 AM ET (https://us02web.zoom.us/j/2737200499)
Thursday March 23, 10-11 AM ET (https://us02web.zoom.us/j/2737200499)
Thursday March 30, 10-11 AM ET (https://us02web.zoom.us/j/2737200499)

We are happy to meet with you on a different day or time upon request. Thank you!

**Comment by Dherahrose** [comment]
Thank you so much Fatimah, I have been navigating the platform and still trying to understand it, I wont hesitate to get across as soon as I can. its so reliving to come across your post.

-Rose
