### ISSUE TITLE
Altered microbiomes distinguish Alzheimer's disease from amnestic mild cognitive impairment and health in a Chinese cohort

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#20]
Condition: Alzheimer's Disease
URL: https://pubmed.ncbi.nlm.nih.gov/31063846/

**Comment by sopeadeniji** [comment]
@ftzohra22 
I will like to claim this article

**Comment by ftzohra22** [comment]
Assigned

**Comment by sopeadeniji** [comment]
@ftzohra22 please review my recent curation https://bugsigdb.org/Study_740

**Comment by claregri** [comment]
Hi, thanks for making those updates!! I updated your score based on your changes and made a few to close out this curation.
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1 
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 (this was correct for the first experiment but it seemed like you copied forward for the others - there were no significant changes in alpha diversity for the Experiments 2-3)
16. All signature sources correctly identified (-1 for each error) (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 (you missed a number of taxa - make sure to examine all figures carefully and curate all of them, even if they are from the same family)
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2 Total (maximum 23 points): 19
