### ISSUE TITLE
Parkinson's disease and Parkinson's disease medications have distinct signatures of the gut microbiome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#201]
Parkinson's disease and Parkinson's disease medications have distinct signatures of the gut microbiome. Mov Disord. 2017 May;32(5):739-749. doi: 10.1002/mds.26942. Epub 2017 Feb 14.

https://pubmed.ncbi.nlm.nih.gov/28195358/

**Comment by Msjulieozi** [comment]
Kindly assign this paper to me for curation @SvetlanaUP . Thank you 🙏🏽

**Comment by AleruDivine** [comment]
Hello @Msjulieozi, i hope you are doing well. I noticed this issue has been assigned to you for a while now, and since we're in the final week of contributions, I just wanted to check in and see if everything is okay with you and If you needed a hand with this curation.
If you have any questions or blockers, just shoot at me. I'll be more than happy to help out however I can! 😊

**Comment by samreen-19** [comment]
@AleruDivine Are either you or @Msjulieozi working on this paper?

**Comment by samreen-19** [comment]
HI @SvetlanaUP I noticed this study on bugsigdb has not been worked on in almost a month. Can you please confirm it, and if so, can I be assigned to work on it? Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_905 reassigned to @samreen-19

**Comment by Rahila-me** [comment]
@SvetlanaUP I don't know if @samreen-19 is still working on this paper, thou i opened it and is not been worked on since. Can be assigned this too?

**Comment by samreen-19** [comment]
Hi @Rahila-me I've been really busy with my college work the past few days, I'll be working on this in a few days. Thank you.

**Comment by Rahila-me** [comment]
@samreen-19 you are welcome, if you are open for collaboration when you start let me know

**Comment by samreen-19** [comment]
Sure @Rahila-me I'll let you know 😊

**Comment by SvetlanaUP** [comment]
@samreen-19 @Rahila-me please do collaborate to finalize this curation.

**Comment by samreen-19** [comment]
@SvetlanaUP @AleruDivine is already helping me to curate this paper.

**Comment by SvetlanaUP** [comment]
@samreen-19, ok, please do let me know about the status of this curation?

**Comment by samreen-19** [comment]
@SvetlanaUP Aleru has done quite a bit. She'll finish the rest of the curation soon

**Comment by SvetlanaUP** [comment]
@Rahila-me, my apologies. @AleruDivine is on this curation together with @samreen-19. This is a good example how online communication should be clear and actions well documented (e.g. I was not informed about already set collaboration).

**Comment by Rahila-me** [comment]
@SvetlanaUP its fine. I found other issues on github i am already working on.

**Comment by AleruDivine** [comment]
Thank you @SvetlanaUP  and @samreen-19  for the clarification.  @SvetlanaUP, after @samreen-19 reached out on the Slack channel, I replied to the message thread and we started collaborating on this. My sincere apologies for the initial confusion.

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I'd like to submit this study for review.
Thank you so much!
Link: https://bugsigdb.org/Study_905

**Comment by Peacesandy** [comment]
Hello @AleruDivine, Thank you for this excellent review, no corrections were detected. ⭐

@SvetlanaUP  https://bugsigdb.org/Study_905  Reviewed ✔️

**Comment by AleruDivine** [comment]
Thank you so much @Peacesandy @SvetlanaUP
