### ISSUE TITLE
Altered gut microbiota in Parkinson's disease patients with motor complications

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#202]
Altered gut microbiota in Parkinson's disease patients with motor complications https://pubmed.ncbi.nlm.nih.gov/34954497/

**Comment by Msjulieozi** [comment]
Kindly assign this paper to me for curation. Thank you 🙏🏽

**Comment by Praiseagbetuyi** [comment]
Hi. 

Kindly assign this issue to me for the fulfillment of my second contribution. Thank you.

**Comment by Peacesandy** [comment]
@Msjulieozi was the first to claim the paper 
Assigned to @Msjulieozi

**Comment by Peacesandy** [comment]
@Msjulieozi I noticed another paper has already been assigned to you

**Comment by Praiseagbetuyi** [comment]
The paper is not open access, and I have not been able to download it directly or through scihub.
https://pubmed.ncbi.nlm.nih.gov/34954497/

Please can you share the PDF of the paper.


> Altered gut microbiota in Parkinson's disease patients with motor complications https://pubmed.ncbi.nlm.nih.gov/34954497/

**Comment by lwaldron** [comment]
I was able to get it through the "Access through your institution" and UNITN. 
[1-s2.0-S1353802021004673-main.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14539991/1-s2.0-S1353802021004673-main.pdf)

**Comment by SvetlanaUP** [comment]
Thank you @lwaldron

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_1006

**Comment by Praiseagbetuyi** [comment]
> @Praiseagbetuyi Is this curation ready for review?

Yes, it is.

**Comment by Peacesandy** [comment]
Hi @Praiseagbetuyi this is a good first curation attempt, how ever here are some few points to note ✍️

-  The group name is incorrect
- The contrast groups were not correctly identified
- The group sample size was mentioned in the study, you omitted it
- The significant threshold was omitted

N/B; This study has been reviewed and corrected

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 0
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 21**

@SvetlanaUP https://bugsigdb.org/Study_1006  reviewed and corrected ✔️
