### ISSUE TITLE
Parkinson's Disease Medication Alters Small Intestinal Motility and Microbiota Composition in Healthy Rats

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#205]
[Parkinson's Disease Medication Alters Small Intestinal Motility and Microbiota Composition in Healthy Rats](https://pubmed.ncbi.nlm.nih.gov/35076270/)

**Comment by AdegboyeRukayat** [comment]
@SvetlanaUP kindly assign me this paper

**Comment by nwakaegovincent26** [comment]
Kindly assign this paper to me for curation @SvetlanaUP Thank you.

**Comment by Iam-Iman** [comment]
Hi, @SvetlanaUP may I be assigned this article

**Comment by Praiseagbetuyi** [comment]
Hello @SvetlanaUP Kindly assign this issue to me towards fulfillment of my second contribution. Thank you.

**Comment by Peacesandy** [comment]
@AdegboyeRukayat  claimed this paper first

Assigned to @AdegboyeRukayat

**Comment by AdegboyeRukayat** [comment]
Thank you @Peacesandy

**Comment by SvetlanaUP** [comment]
@AdegboyeRukayat is your curation ready for review?

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_925

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0.5 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0.5 |
|  | TOTAL | 23 | 9 |

This curation is incomplete in many sections.

**Comment by SvetlanaUP** [comment]
[Scholarpat](https://github.com/Scholarpat) you could help out in correcting this curation.

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP 🙏
I'll get on it.

**Comment by AdegboyeRukayat** [comment]
> @AdegboyeRukayat is your curation ready for review?

@SvetlanaUP Yes Please. I thought I already tagged you since last month. So sorry

**Comment by AdegboyeRukayat** [comment]
> Ready for review https://bugsigdb.org/Study_925

@SvetlanaUP Yes Please

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP, this curation is ready for review.
https://bugsigdb.org/Study_925

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I previously made some changes to this curation:
- Curated the appropriate data for experiment 1 and its signatures.
- Curated missing experiments (2 to 6) and their signatures.

I have now reviewed the curation and changed the conditions earlier curated from 'Parkinson' to 'Treatment,' and also altered the signature descriptions for clarity.

The curation is now complete. Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_925 reviewed.
