### ISSUE TITLE
Influence of aerobic exercise training on mice gut microbiota in Parkinson’s disease

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#207]
Influence of aerobic exercise training on mice gut microbiota in Parkinson’s disease - Fan et al - Turk J Biol
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10388120/

**Comment by nwakaegovincent26** [comment]
kindly review my paper @SvetlanaUP @Folakunmi21 Thank you

**Comment by nwakaegovincent26** [comment]
https://bugsigdb.org/Study_923
here is the link to the study

**Comment by Folakunmi21** [comment]
Hello @nwakaegovincent26 unfortunately, this curation was poorly done. Here are a few corrections to note:
-Figure 4A and table S1 are not curatable
-You entered the wrong condition
-Entered MHT correction as yes when there was none
-Wrong sequencing details
-There were no confounders controlled for in the paper but you entered some
please check the corrected curation to see the other changes I made.

CUARTION RESULT 
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 0 
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
8. Antibiotic exclusion correctly identified (1 point): 0
9. Correctly identified sequencing details (2 points): 1
10. Identified correct statistical test (1 point): 0.5 
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 9.5

@SvetlanaUP study 923 reviewed

**Comment by nwakaegovincent26** [comment]
thank you for the review feedback . all the correction is well noted and hopefully i will do better in my other curation @SvetlanaUP @Folakunmi21
