### ISSUE TITLE
Analysis of Gut Microbiota in Patients with Parkinson’s Disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#208]
Analysis of Gut Microbiota in Patients with Parkinson’s Disease - Petrov et al. - Bulletin of Experimental Biology and Medicine
https://link.springer.com/article/10.1007/s10517-017-3700-7

**Comment by SvetlanaUP** [comment]
@Omabekee curated. https://bugsigdb.org/Study_22
