### ISSUE TITLE
Structural changes of gut microbiota in Parkinson's disease and its correlation with clinical features

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#209]
Structural changes of gut microbiota in Parkinson's disease and its correlation with clinical features - Li et al. - Science China life Sciences
https://pubmed.ncbi.nlm.nih.gov/28536926/

**Comment by Omabekee** [comment]
[Download article.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527304/Download.article.pdf)

Supplementary files:
[Family level comparison.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527335/Family.level.comparison.pdf)

[Table S1 Significantly different genera between PD and HC groups.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527349/Table.S1.Significantly.different.genera.between.PD.and.HC.groups.pdf)

[Demographic characteristics of three groups.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527359/Demographic.characteristics.of.three.groups.pdf)

[Table S3 Summary of clinical information between PD and HC groups.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527363/Table.S3.Summary.of.clinical.information.between.PD.and.HC.groups.pdf)

**Comment by Druscillaa** [comment]
Hello, can I please have this assigned to me

**Comment by Codegirlemem** [comment]
Helllo @SvetlanaUP Can this issue be assigned to me?
Name: Emem Eduoku

**Comment by Shulamite54** [comment]
Good day @Codegirlemem trust you are doing great. I noticed this issue has been open for a while so I'm reaching out to offer an extra hand if you need one. 
Please reach out to me so we can work on completing the curation together.

**Comment by MyleeeA** [comment]
Would love to be of help as well @Codegirlemem and @Shulamite54

**Comment by SvetlanaUP** [comment]
@MyleeeA @Shulamite54 please finalize this curation.

**Comment by Shulamite54** [comment]
Thanks @SvetlanaUP, will contact @MyleeeA so that we can get to work.

**Comment by Shulamite54** [comment]
Good day @SvetlanaUP I and @MyleeeA  has finalized the paper, please review it.
Here is the link: https://bugsigdb.org/Study_857

Thank you

**Comment by Shulamite54** [comment]
Hi @SvetlanaUP, is there any other paper I can work on, am free and willing to work. Thank you.

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,

I've reviewed this curation. I made some minor changes in the signature source and description to make it more descriptive and uniform.

Well done @Shulamite54 @MyleeeA !

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_857 reviewed.
