### ISSUE TITLE
Gut microbiota regulate Alzheimer’s disease pathologies and cognitive disorders via PUFA-associated neuroinflammation

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#210]
Gut microbiota regulate Alzheimer’s disease pathologies and cognitive disorders via PUFA-associated neuroinflammation - Chen et al-  Epub
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10720732/

**Comment by graycepaul** [comment]
Hello @SvetlanaUP, can I please have this paper assigned to me? 
Name: Grace Salawe

**Comment by graycepaul** [comment]
Hello @SvetlanaUP 
Here is the link to my completed paper for review 
LINK:  https://bugsigdb.org/Study_929

**Comment by Folakunmi21** [comment]
Hello @graycepaul This was not a bad second curation attempt. Here are a few things you should note:

- The healthy and Alzheimer's groups were not directly compared. The comparison between both groups was carried out in mice **through** a procedure called faecal microbiota transfer (FMT), Therefore, the compared groups should have been the different groups of mice present.
- Bacteroides ovatus should not have been entered because it was not significant in figure 5. That is what "ns" stands for.
- Only one significant test showed the differential abundance between the groups. Check figure 5 caption, as well as the methods section.
- The mice did not have an antibiotic exclusion. However, the donors of the faecal samples they were inoculated with did, This should have been entered.

**CURATION RESULT**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
8. Antibiotic exclusion correctly identified (1 point): 0
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 15
@SvetlanaUP study 929 reviewed
