### ISSUE TITLE
Functional implications of microbial and viral gut metagenome changes in early stage L-DOPA-naïve Parkinson’s disease patients

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#211]
Functional implications of microbial and viral gut metagenome changes in early stage L-DOPA-naïve Parkinson’s disease patients - Bedarf et al. - Genome Medicine
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5408370/

**Comment by SvetlanaUP** [comment]
@Omabekee curated! https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=28449715&go=Go
