### ISSUE TITLE
The nasal and gut microbiome in parkinson’s disease and idiopathic rapid eye movement sleep behavior disorder

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#212]
The nasal and gut microbiome in parkinson’s disease and idiopathic rapid eye movement sleep behavior disorder - Heintz-Buschart et al. - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5811909/

**Comment by SvetlanaUP** [comment]
@Omabekee curated https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=28843021&go=Go
