### ISSUE TITLE
Gut microbiota are related to parkinson’s disease and clinical phenotype

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#213]
Gut microbiota are related to parkinson’s disease and clinical phenotype - Scheperjans et al. - Movement disorders
https://pubmed.ncbi.nlm.nih.gov/25476529/

**Comment by Omabekee** [comment]
[Supplementary information.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527155/Supplementary.information.pdf)
[Download article.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527156/Download.article.pdf)

**Comment by Junie06** [comment]
Isoken June Ibizugbe

**Comment by Junie06** [comment]
can this issue please be assigned to me @Omabekee

**Comment by AteeqahYussuf** [comment]
Hi, my name is Ateeqah Yussuf. I would like to make my contribution on this issue but I still don’t understand how. Is there anyone that can help?

**Comment by Abiola-Salako** [comment]
@AteeqahYussuf KINDLY JOIN THE BIOCONDUCTOR COMMUNITY ON SLACK

**Comment by Junie06** [comment]
You have to make a first contribution, then ask for an issue to be assigned to you. Use this link to understand better https://github.com/waldronlab/BugSigDBcuration/issues/94 @AteeqahYussuf

**Comment by natureoflagos** [comment]
Hi @SvetlanaUP @cmirzayi Kindly assign this paper for curation. Thank you.
Michael Adekanye in #bugsigdb on Slack. Thank you.

**Comment by Junie06** [comment]
Hello @SvetlanaUP I am done curating this paper
Link -https://bugsigdb.org/Study_934
 Please help me review it. Thanks

**Comment by Junie06** [comment]
@Abiola-Salako Link -https://bugsigdb.org/Study_934

**Comment by mariam665** [comment]
Hello @SvetlanaUP , can I be assigned this issue?

**Comment by SvetlanaUP** [comment]
@mariam665 this paper is already curated.

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1|
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 21 |

Corrected:
- ACE index missed; we are recording it as richness
- Eubacteriales incertae sedis -> Eubacteriales incertae sedis **IV** We have to record all the details.

**Comment by Fificode** [comment]
Hi @SvetlanaUP,
I am currently resolving missing NCBI Taxonomy IDs and noticed that Experiment 1, Signature 1 contains the taxon "
Eubacteriales incertae sedis IV " - https://bugsigdb.org/25476529/Experiment_1/Signature_1
I would like to update it to "Eubacteriales Family IV. Incertae Sedis"- Taxonomy ID: 1689151

Please let me know if you have any concerns with making this change.

Thank you.

**Comment by SvetlanaUP** [comment]
Agree.
