### ISSUE TITLE
Effect of Parkinson's disease and related medications on the composition of the fecal bacterial microbiota

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#217]
Effect of Parkinson's disease and related medications on the composition of the fecal bacterial microbiota - Weis et al - NPJ Parkinsons Disease
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6884491/

**Comment by imalovee** [comment]
Hello @FaithAlexander I saw on the Slack channel that you had already started working on this paper, I just thought to check if you were through with it as there's no "needs review" tag on it.
If you are done with the curation, you can comment here that you are done and attach a link to the study asking for a review by tagging the mentors.
If you're still working on it and you're facing any difficulty with the curation, feel free to call my attention here or on Slack (for a wider audience) as I'm currently available to go through the paper with you.  Best Wishes Faith

**Comment by FaithAlexander** [comment]
Hello @SvetlanaUP, I have curated this study. 

Here is the link to my curation:
https://bugsigdb.org/Study_971

Kindly review it. 
Thank you.

**Comment by Peacesandy** [comment]
Hi @FaithAlexander this is an exceptionally good and excellent first curation ⭐


**CURATION RESULT**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 23**

@SvetlanaUP   https://bugsigdb.org/Study_971 reviewed and corrected ✅

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_971  reviewed.
