### ISSUE TITLE
Progression of Parkinson's disease is associated with gut dysbiosis: Two-year follow-up study.

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#219]
Progression of Parkinson's disease is associated with gut dysbiosis: Two-year follow-up study -Minato et al. - PLoS One
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5665539/

**Comment by omojokunoluwatomisin10** [comment]
Hello,please kindly assigned to me

**Comment by Tiwalade0002** [comment]
Hello, please assign this to me

**Comment by natureoflagos** [comment]
Hi @SvetlanaUP @cmirzayi Kindly assign this paper for curation. Thank you. 
Michael Adekanye in #bugsigdb on Slack.

**Comment by SvetlanaUP** [comment]
Assigned to @natureoflagos

**Comment by natureoflagos** [comment]
> Assigned to @natureoflagos

Thank you.

**Comment by natureoflagos** [comment]
The annotated pdf of the research study. 
[Progression of Parkinson's disease is associated with gut dysbiosis_ Two-year follow-up study - PMC.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14549866/Progression.of.Parkinson.s.disease.is.associated.with.gut.dysbiosis_.Two-year.follow-up.study.-.PMC.pdf)

**Comment by SvetlanaUP** [comment]
@natureoflagos please proceed to curation of your paper to https://bugsigdb.org/Main_Page

**Comment by samreen-19** [comment]
Hello @natureoflagos it's been a while since you've been assigned this paper. Are you still working on curating it? I would be happy to help in case you're facing any difficulty!

**Comment by Isioma20** [comment]
Hello @natureoflagos. I noticed that you started the curation of this study 3 weeks ago but have yet to make any progress, I'd like to know If you need any help or would love to collaborate so as to complete this study. Thank you!

**Comment by SvetlanaUP** [comment]
@Isioma20 Please see this incomplete curation https://github.com/waldronlab/BugSigDBcuration/issues/324

**Comment by SvetlanaUP** [comment]
@Isioma20 please finalize this curation.

**Comment by Isioma20** [comment]
Would do! Thank you

**Comment by Isioma20** [comment]
This curation is now ready for review. Thank you!
https://bugsigdb.org/Study_948

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

All data was completely curated for this curation and it's complete.
Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_948 reviewed.
