### ISSUE TITLE
Correlation Analysis between Gut Microbiota and Metabolites in Children with Systemic Lupus Erythematosus

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#22]
Condition: Systemic Lupus 
URL : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325587/

**Comment by Aiysha689** [comment]
Hello, can you please assigne this paper to me.

**Comment by Annabelcute** [comment]
Hello please I'll love to work on this topic.
Name: Aguobi Amara

**Comment by Aiysha689** [comment]
> Condition: Systemic Lupus URL : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8325587/

could you plzz assigne this topic to me.

**Comment by atrayees** [comment]
Hello, I'd love to work on this! Could you please assign this paper to me?

**Comment by Aiysha689** [comment]
HELLO, hope you are doing well. Kindly please review my curation https://bugsigdb.org/Study_711 . Hoping to get your valuable feedback.

**Comment by claregri** [comment]
Hi Aiysha, great job with this! Please see a few comments I had below but this was generally a very good curation.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (observational, not case-control would be more appropriate here)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0 (I don't believe there was matching of subjects in this study, though the factors you listed were mentioned in Table 1 there is no mention of matching)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 21

**Comment by Aiysha689** [comment]
THANK YOU, for your feedback I will surely work on the issues. I some doubt as you mentioned I should use observational instead of case control, so there are two option for observational case study cross sectional observational and time series longitudinal observational.  And 2nd, as in the points you mentioned maximum is 24 and you have deducted 1-1 marks, so it will be 22 na or else i have made another mistake you can tell me so, i can rectify it.

**Comment by Aiysha689** [comment]
Hello, @claregri . Thanks for  your feedback I have worked on the issue's you mentioned. Kindly please review my curation https://bugsigdb.org/Study_711 . Hoping to get your valuable feedback.

**Comment by claregri** [comment]
Hi Aiysha, nice work! With those updates you have achieved full points for this curation.

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 23 points): 23

**Comment by Aiysha689** [comment]
THANK YOU @claregri
