### ISSUE TITLE
Gut Microbiota is Altered in Patients with Alzheimer’s Disease

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#220]
Gut Microbiota is Altered in Patients with Alzheimer’s Disease - Zhuang et l- IOS press
https://sci-hub.se/10.3233/JAD-180176

**Comment by Praiseagbetuyi** [comment]
Kindly assign this to me, @SvetlanaUP 

Thank you.

**Comment by TemitayoG** [comment]
kindly assign me

**Comment by Scholarpat** [comment]
Hello @TemitayoG , I hope you had a wonderful weekend. I noticed this issue has been open for a while so I'm reaching out to offer and extra hand if you need one. Please reach out to me so we can work together to complete the curation. Sending my best regards.

Looking forward to your reply. 😊
Scholastica Urua

**Comment by TemitayoG** [comment]
Thank you for reaching out. @Scholarpat 

here is the link to my curation, it's completed and ready for review  https://bugsigdb.org/Study_1024 
@SvetlanaUP

**Comment by Scholarpat** [comment]
Okay, well done @TemitayoG on your curation

**Comment by Peacesandy** [comment]
Hi @TemitayoG this is a good first curation attempt, however here are some few points to note. ✍️

- The study design is case control 
- The study recorded an Antibiotic exclusion - "a history of taking antibiotics within six months"
- The statistical test used is LEfSe the study stated that they used LEfSe to identify the taxa that were significantly different between groups.
- Shannon Index, Simpson and Chao1 were also mentioned as diversity measures -"Alpha diversity, including the Shannon Index, were investigated in QIIME, and the significance 174 was determined using a t test."
173 observed species, Simpson and Chao1 indices,
- The members of Signatures were not identified correctly 
- You missed out a lot of signatures

*N/B:* The study have been corrected and reviewed ✔️

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 0
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 0
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 0
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 0
All diversity measures identified (1 point): 0
Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
All signature sources correctly identified (-1 for each error) (2 points): 0
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 1
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 14**

@SvetlanaUP    https://bugsigdb.org/Study_1024  reviewed and corrected ✅

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1024 reviewed.
