### ISSUE TITLE
Gut Microbiota Regulate Motor Deficits and Neuroinflammation in a Model of Parkinson's Disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#221]
Gut Microbiota Regulate Motor Deficits and Neuroinflammation in a Model of Parkinson's Disease - Sampson et al. - Cell
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5718049/

**Comment by Toyosiolann** [comment]
kindly assign me

**Comment by Toyosiolann** [comment]
Hello @SvetlanaUP 
I am done curating this paper and it's ready for review.

Link: https://bugsigdb.org/Study_910

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0.5 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0.5 |
|  | TOTAL | 23 | 12 |

Unfortunately, this curation has 3 main errors:

- This is a laboratory study done in mice models, thus the host species is not Homo sapiens (although human feces was used for fecal transfer).

- There are two experiments:
1. germ-free, wild-type (WT) mice colonized with fecal microbes from healthy controls (HC) versus germ-free, wild-type (WT) mice colonized with fecal microbes from Parkinson’s disease patients (PD); and

2. germ-free, Thy1-α-synuclein genotype (ASO) mice colonized with fecal microbes from healthy controls (HC) versus germ-free mice, Thy1-α-synuclein genotype (ASO) colonized with fecal microbes from Parkinson’s disease patients (PD).

- The signature source is correctly identified – Figure 6E – a figure fairly difficult to curate. However, it's wrongly interpreted by the curator.

**Comment by Toyosiolann** [comment]
Thank you for the review, all corrections duly noted. @SvetlanaUP
