### ISSUE TITLE
Altered microbiomes distinguish Alzheimer’s disease from amnestic mild cognitive impairment and health in a Chinese cohort

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#222]
Altered microbiomes distinguish Alzheimer’s disease from amnestic mild cognitive impairment and health in a Chinese cohort - Liu et al - Brain Behav Immun.
https://sci-hub.se/https://doi.org/10.1016/j.bbi.2019.05.008

**Comment by TemitayoG** [comment]
Kindly assign this to me. I would love to curate it and contribute significantly to this. Thank you

**Comment by TemitayoG** [comment]
@SvetlanaUP

**Comment by Msjulieozi** [comment]
Please kindly assign this to me @SvetlanaUP 
Thank you 🙏🏽

**Comment by SvetlanaUP** [comment]
Assigned to @TemitayoG

**Comment by SvetlanaUP** [comment]
@Folakunmi21 https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=31063846&go=Go this one is already curated. 

My apologies @TemitayoG, please select another paper.
