### ISSUE TITLE
Association between Parkinson's disease and the faecal eukaryotic microbiota

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#223]
Association between Parkinson's disease and the faecal eukaryotic microbiota - Weis et al. - NPJ Parkinsons Disease
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8602383/

**Comment by Nuellaada** [comment]
Please can this be assigned to me @Omabekee @SvetlanaUP

**Comment by Nuellaada** [comment]
My full name is Simon Emmanuella

**Comment by Oyizaadewuyi** [comment]
Hello, please I would also like to curate this paper can it be assigned to me too please @SvetlanaUP .. 
Thanks
My name is Raihanat Adewuyi
GitHub:Oyizaadewuyi

**Comment by Oyizaadewuyi** [comment]
> Hello, please I would also like to curate this paper can it be assigned to me too please @SvetlanaUP .. Thanks My name is Raihanat Adewuyi GitHub:Oyizaadewuyi

**Comment by SvetlanaUP** [comment]
Assigned to @Nuellaada

**Comment by AleruDivine** [comment]
Hi @Nuellaada Good morning, I hope you are doing well.
I have noticed that this issue has been assigned to you for sometime now, and as we're in the final week of contribution, I wanted to reach out and see if you're facing any difficulties. If you need assistance or have any blockers or questions, I'm available to help🙏

**Comment by samreen-19** [comment]
Hello @Nuellaada 
Are you still working on curating the paper? In case you aren't, I'd like to work on it. If you're facing any difficulties, please let me know, I'd love to assist you! Thank you.

**Comment by SvetlanaUP** [comment]
Assigned to @samreen-19

**Comment by samreen-19** [comment]
Thank you @SvetlanaUP ❤️

**Comment by SvetlanaUP** [comment]
Hi @samreen-19 @omojokunoluwatomisin10 

could you please tell me which curation is active one?
https://bugsigdb.org/Study_992
https://bugsigdb.org/Study_991

Thank you.

**Comment by samreen-19** [comment]
@SvetlanaUP I created study 992. I'm confused why there's another study created after that.

**Comment by SvetlanaUP** [comment]
OK @samreen-19 please do inform me when https://bugsigdb.org/Study_992 is ready for review.

**Comment by samreen-19** [comment]
@SvetlanaUP it already is. But I'm not able to mark it for review since it says I don't have permission to do so.

**Comment by SvetlanaUP** [comment]
@samreen-19 you should claim it here for review. Also pay attention that you leave "incomplete" fields.

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_992

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_992 reviewed.
