### ISSUE TITLE
Altered gut microbiota in Parkinson’s disease patients/healthy spouses and its association with clinical features

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#224]
Altered gut microbiota in Parkinson’s disease patients/healthy spouses and its association with clinical features - Zhang et al. - Parkinsonism & Related Disorders
https://www.prd-journal.com/article/S1353-8020(20)30827-0/fulltext

**Comment by SvetlanaUP** [comment]
@Omabekee https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=33099131&go=Go this one is already curated.
