### ISSUE TITLE
Gut microbiota differs between Parkinson’s disease patients and healthy controls in northeast china

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#225]
Gut microbiota differs between Parkinson’s disease patients and healthy controls in northeast china - Li et al. - Front Mol Neurosci.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6637281/

**Comment by SvetlanaUP** [comment]
@Omabekee https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=31354427&go=Go this one is already curated.

**Comment by Omabekee** [comment]
Ooops closing this now, thank you.
