### ISSUE TITLE
Systematic analysis of gut microbiome reveals the role of bacterial folate and homocysteine metabolism in Parkinson’s disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#226]
Systematic analysis of gut microbiome reveals the role of bacterial folate and homocysteine metabolism in Parkinson’s disease - Rosario et al - Cell Reports
https://linkinghub.elsevier.com/retrieve/pii/S2211-1247(21)00121-2

**Comment by Oyizaadewuyi** [comment]
Please can this paper be assigned to me 
@SvetlanaUP 
Thanks 
Name Raihanat Adewuyi (Oyizaadewuyi)

**Comment by SvetlanaUP** [comment]
@Oyizaadewuyi Is this study ready for curation?

**Comment by Oyizaadewuyi** [comment]
@SvetlanaUP  yes it is already curated.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_935 ready for review.

**Comment by Peacesandy** [comment]
Hi @Oyizaadewuyi this is a good first curation attempt, however you missed out some tiny details

- The sample size you entered were incorrect, yes the study initially stated that The cohort comprised 31 early-stage
L-DOPA-naive PD male individuals and 28 matched controls. But with further reading they also stated that  "we removed a few samples and reanalyzed the metagenomics data of 26 PD and 25 controls, of which 11 were healthy controls (COs) while 14 were diseased controls (DCs) with cardiovascular risk factors" which carries the correct sample size

- Secondly you omitted some signatures. 

**N/B:** Overall this is a good first curation attempt, please note that the study has been reviewed and corrected


**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 1
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 22**

@SvetlanaUP    https://bugsigdb.org/Study_935  reviewed and corrected ✅
