### ISSUE TITLE
Alteration of the fecal microbiota in Chinese patients with Parkinson’s disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#227]
Alteration of the fecal microbiota in Chinese patients with Parkinson’s disease - Qian et al - Brain, Behavior and I
[Alteration of the fecal microbiota in Chinese patients with Parkinson’s disease.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14524688/Alteration.of.the.fecal.microbiota.in.Chinese.patients.with.Parkinson.s.disease.pdf)
mmunity

**Comment by SvetlanaUP** [comment]
@Omabekee https://bugsigdb.org/w/index.php?title=+Special%3ASearch&search=29501802&go=Go already curated
