### ISSUE TITLE
Differences in the Composition of Gut Microbiota between Patients with Parkinson's Disease and Healthy Controls: A Cohort Study

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#229]
Differences in the Composition of Gut Microbiota between Patients with Parkinson's Disease and Healthy Controls: A Cohort Study. J Clin Med. 2021 Dec 3;10(23):5698.  https://pubmed.ncbi.nlm.nih.gov/34884399/

**Comment by Nikilight** [comment]
@SvetlanaUP @Omabekee Please, can I have this paper assigned to me? Thank you.

**Comment by Nikilight** [comment]
Thank you @SvetlanaUP

**Comment by Nikilight** [comment]
@SvetlanaUP  @Omabekee @Abiola-Salako @Ima-obong (Aimah) . Good day everyone, Could you please help to review my curation? Here is the Link: https://bugsigdb.org/Study_909

**Comment by Codegirlemem** [comment]
Hi @Nikilight. I am not yet done reviewing but I noticed some data which I think may be incorrect. For example, the study design is more Case control as it compares between the healthy control group and the PD group.

Also for the group 1 definition the study was limited to hospitalized PD patients with well-controlled symptoms and not just any PD patient.

You can go through this resource to guide you in each of the steps https://bugsigdb.org/Curation_Policy

**Comment by Nikilight** [comment]
Thank you so much @Codegirlemem for this. I appreciate it. All corrections are noted and will be taken.

**Comment by RotimiDesire** [comment]
I also dropped a few things I observed in your DM on slack. @Nikilight

**Comment by Codegirlemem** [comment]
You are welcome. You can look for example of a completed curation in addition to the curation guide and  also read the materials on human microbiome posted to get a good grasp of concepts being discussed

**Comment by Nikilight** [comment]
I appreciate you both @RotimiDesire and @Codegirlemem

**Comment by Peacesandy** [comment]
Hi @Nikilight, this is a good curation attempt. However, here are a few points to note. ✍️

- The statistical test used to get the differential abundance result is the LefSE analysis, you mentioned two statistical tests.
- All signature sources were not correctly identified. Fig 7 has a cladogram that shows the taxa differences between PD patients and Healthy Controls
- Some members of the signatures were not identified correctly

*N/B*: All corrections have been made, for ease, you can go through the reviewed curation to see the changes I made


**CURATION RESULT**

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point):  1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points):  1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 2 

**Total (maximum 23 points): 20**

@SvetlanaUP corrected and reviewed https://bugsigdb.org/Study_909

**Comment by Nikilight** [comment]
I really appreciate you @SvetlanaUP and @Peacesandy 
Your reviews are eye-opening for me.
It will help me to do better on my present curation.
Thank you.
