### ISSUE TITLE
Characteristics of gut microbiota in patients with asthenozoospermia: a Chinese pilot study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#232]
Characteristics of gut microbiota in patients with asthenozoospermia: a Chinese pilot study - Yang Pan – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03173-5

**Comment by eve10111** [comment]
Hello @SvetlanaUP , I can see that this paper has not been assigned yet. Can you kindly assign it to me? Thank you

**Comment by farheengul001** [comment]
Hi @SvetlanaUP! Please assign me this paper to curate. Thank you

**Comment by eve10111** [comment]
@SvetlanaUP .. thank you very much Sir.

**Comment by WelileDlamini** [comment]
@SvetlanaUP Hi is it possible to assign me the same paper, looks like the are no available papers

**Comment by SvetlanaUP** [comment]
@WelileDlamini this paper is already assigned. Today we will be adding more, thank you for your patience.

**Comment by SvetlanaUP** [comment]
@eve10111 claimed it for review https://bugsigdb.org/Study_941

**Comment by eve10111** [comment]
Hello @SvetlanaUP, can you kindly review my curation, here is the link 👇  https://bugsigdb.org/Study_941
Asthenozoospermia wasn't on the list of conditions mentioned so I opted for Abnormal Sperm Morphology. Thank you very much

**Comment by Folakunmi21** [comment]
Hello @eve10111 Unfortunately, this curation was poorly done. Here are the corrections to your curation:

- There was no MHT correction in the paper and you recorded yes for it

- No matched on criteria in the paper but it was entered

- Signatures were wrongly curated from figure 4

- your choice of study design was wrong and you did not enter a body site

**CURATION RESULT** 
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 0
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 13
@SvetlanaUP study 941 reviewed

**Comment by eve10111** [comment]
@Folakunmi21 Thanks for the review, corrections taken and noted for future curations.

**Comment by eve10111** [comment]
Hello @SvetlanaUP @Folakunmi21 , I checked my curation to update the corrections stated here and I noticed that it had been updated already by @Folakunmi21 and also added as a co-curator.. what does that really mean please?

**Comment by SvetlanaUP** [comment]
Hi @eve10111, you are recorded as a "Curator".

@Folakunmi21 has been added as a **Revision editor** since she did a revision of your work (in her feedback text you can see that she pointed out her corrections). In an open source project, several people working on the very same task is quite usual to experience.

**Comment by eve10111** [comment]
Hello @SvetlanaUP Yes it is, thanks for the clarification.
