### ISSUE TITLE
The Gut Microbiome Is Associated with Clinical Response to Anti–PD-1/PD-L1 Immunotherapy in Gastrointestinal Cancer

### ISSUE THREAD

**Issue by Folakunmi21** [waldronlab/BugSigDBcuration#233]
The Gut Microbiome Is Associated with Clinical Response to Anti–PD-1/PD-L1 Immunotherapy in Gastrointestinal Cancer - Peng et al -  Cancer Immunol Res.
https://aacrjournals.org/cancerimmunolres/article/8/10/1251/466881/The-Gut-Microbiome-Is-Associated-with-Clinical

**Comment by hamzambo** [comment]
Hello. I would love to curate this article. Name : Hamza Mohamed Haji

**Comment by WelileDlamini** [comment]
Hello I would like to be assigned this paper

**Comment by hamzambo** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hello @hamzambo , I hope you are doing well. I noticed this issue has been open for a while and is not also available on BugSigDB so I'm reaching out to help with the curation. Please reach back to me so we can collaborate to complete the curation. Sending my best regards.

Looking forward to your reply. 😊
Scholastica Urua

**Comment by hamzambo** [comment]
Hello @Scholarpat, thank you for reaching out. I would like us to cooperate on this project.

Hamza Haji

**Comment by hamzambo** [comment]
Hello @SvetlanaUP, the study curation is ready for review.

**Comment by hamzambo** [comment]
Hello @Folakunmi21 , the study curation is ready for review.

**Comment by Folakunmi21** [comment]
@Scholarpat @hamzambo  well-done on your joint efforts on this curation. Here are the corrections to be made to it:

- ruminococcaceae UCG was wrongly curated in experiment 1. There's a guideline on the discussion page for curating Ruminococcaceae_UCG. The same guideline can be used for lachnospiraceae UCG (uncultured lachnospiraceae bacterium)
- The groups should have been curated the other way round (NR- group 0, R- group 1). The taxa in yellow are actually abundant in NR, not decreasing (check result text). I switched the groups already
- They did not control for confounders. please edit that out
- correct the wrong alpha diversity analysis. no significant difference was found in the alpha diversity between responders and nonresponders regardless of cancer type.
- MHT is yes for last experiment (p-adjusted present in table)

CURATION RESULT
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 1
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0.5
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 0.5
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 19.5

@SvetlanaUP study 978 graded

**Comment by Scholarpat** [comment]
Thank you @Folakunmi21 for the review and feedback. I have effected the corrections you suggested.

**Comment by Folakunmi21** [comment]
Thank you @Scholarpat please curate the ruminococcacea_UCG as uncultured oscillospiraceae bacterium as it has been resolved on the discussion page. Don't worry about the rank. Do the same for lachnospiraceae_UCG using uncultured lachnospiraceae bacterium. please don't forget to leave a note of what was originally reported using the green bubble.

**Comment by Scholarpat** [comment]
Hello @Folakunmi21 the rank got me confused a bit. I have now made the changes. I have also noted what was originally reported in the study. Thank you for your time and patience.
