### ISSUE TITLE
The Airway Microbiota Signatures of Infection and Rejection in Lung Transplant Recipients

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#236]
The Airway Microbiota Signatures of Infection and Rejection in Lung Transplant Recipients - Jin Su - Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00344-21

**Comment by sidrakhandev** [comment]
@SvetlanaUP could you kindly assign me this article to curate?

**Comment by sidrakhandev** [comment]
WIP: [Curation Link](https://bugsigdb.org/Study_1044)

**Comment by sidrakhandev** [comment]
@SvetlanaUP, this study is ready for review

**Comment by Peacesandy** [comment]
Hi @sidrakhandev this is an excellent first curation attempt ⭐

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 23**

@SvetlanaUP   https://bugsigdb.org/Study_1044 reviewed and corrected ✅

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP
