### ISSUE TITLE
Alterations in the Gut Microbiota and Metabolomics of Seafarers after a Six-Month Sea Voyage

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#237]
Alterations in the Gut Microbiota and Metabolomics of Seafarers after a Six-Month Sea Voyage – Chun-Hui Jiang et al. – Microbiology Spectrum

https://journals.asm.org/doi/10.1128/spectrum.01899-22

**Comment by WelileDlamini** [comment]
Hi can this paper be assigned to me

**Comment by WelileDlamini** [comment]
Thank you

**Comment by thegirlcoderr** [comment]
Hello @WelileDlamini , I trust you're doing well. I noticed that this this issue have been open for some time and is not yet available on BugSigDB. I'm contacting you to offer my assistance with the curation.  If you'd like any assistance, please respond so we can collaborate and complete the curation process together. Best regards.

**Comment by WelileDlamini** [comment]
@thegirlcoderr hi how are thank you for reaching, please do help me, I have been working on it, just that I had a few personal challenges that I have just sorted. I would appreciate your assistance so I curate it

**Comment by thegirlcoderr** [comment]
Hi @WelileDlamini, I'm glad to hear that you've sorted out your challenges, happy to be able to help with your curation as well. Can we collaborate on Slack?

**Comment by WelileDlamini** [comment]
@Scholarpat please this is the project I was talking about

**Comment by Scholarpat** [comment]
Okay @WelileDlamini , I check it out.

**Comment by SvetlanaUP** [comment]
Well done @WelileDlamini and @Scholarpat 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 23 |

**Comment by Scholarpat** [comment]
Happy weekend @SvetlanaUP 
Thank you for the review. 🤗

**Comment by WelileDlamini** [comment]
Blessed weekend @SvetlanaUP . Thank you for the feedback
