### ISSUE TITLE
Limited Impact of SARS-CoV-2 on the Human Naso-Oropharyngeal Microbiota in Hospitalized Patients

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#240]
Limited Impact of SARS-CoV-2 on the Human Naso-Oropharyngeal Microbiota in Hospitalized Patients – Christopher K. C. Lai - Microbiology Spectrum

https://journals.asm.org/doi/10.1128/spectrum.02196-22

**Comment by Abiola-Salako** [comment]
@SvetlanaUP @Peacesandy @Folakunmi21 @Omabekee, Well done.
I just want to notify you that my study is ready for review.
Here's the link ; https://bugsigdb.org/Study_977
Thanks to you all.

**Comment by Abiola-Salako** [comment]
@SvetlanaUP @Folakunmi21 @Omabekee @Peacesandy, Well done, you all.
My study is ready for review and here's the link; https://bugsigdb.org/Study_977
Huge thanks to you all.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this study:

1. In Experiment 3, Signature 1, 'Candidatus Nanosynbacter' was curated, but TM7x was reported. I changed this to '[Candidatus Nanosynbacter lyticus](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1476577)' which is another name for TM7x ([web source](https://en.wikipedia.org/wiki/TM7x)).

2. Condition: Changed from 'COVID-19' to 'Pneumonia' in Experiment 4 and 'Viral load' in Experiment 5.

> I'm conflicted about this: 
> 
> Prevotella sp. 1-8 was curated in place of 'Prevotella_7' in Signature 1 of Experiments 1, 2, 4, and 6. Although this looks like it may be correct, I've not found any resources to back this up. Should I change it back to Prevotella_7, which was originally reported in the study?

**Comment by SvetlanaUP** [comment]
@Scholarpat put it back to Prevotella_7, which was originally reported in the study, thanks!

**Comment by Scholarpat** [comment]
The curation has been updated and is now complete.

Thank you @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_977 reviewed.
