### ISSUE TITLE
Analysis on the change of gut microbiota and metabolome in lung transplant patients

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#241]
Analysis on the change of gut microbiota and metabolome in lung transplant patients – Hou et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03142-23

**Comment by Gloshe** [comment]
hello @SvetlanaUP I would like to curate this paper

**Comment by Gloshe** [comment]
Hi @SvetlanaUP
I am done curating this study, your review on it will be appreciated

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_958 ready for review

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0.5 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 14 |

- Study design is not cross-sectional observational (corrected)
- Diversity results incorrectly entered (corrected)
- LDA score missed (corrected)
- MHT correction with LEfSe is rare and I see no evidence to suggest that was done (corrected)
- Fig3C can be curated and 1 experiment (with unchanged alpha diversity) is missing (should be corrected)
- not all the members recorded in the signatures (should be corrected)

**Comment by Gloshe** [comment]
Thank you @SvetlanaUP for the review, let me go through to see where I went wrong. However i request for another chance to curate more papers as I learn more and gaining knowledge. Thank you.

**Comment by SvetlanaUP** [comment]
@Gloshe first 4 points in my feedback notes are corrected, but the last two points can be corrected by you.

**Comment by fiddyhamma** [comment]
Hi @Gloshe do you mind making the last two corrections together?

**Comment by SvetlanaUP** [comment]
@Gloshe @fiddyhamma go ahead with correction. Please make notes about your corrections. Thank you.

**Comment by fiddyhamma** [comment]
Okay, will do that. Thank you @SvetlanaUP

**Comment by fiddyhamma** [comment]
Hello @SvetlanaUP I've made corrections to this study

**Comment by Gloshe** [comment]
Good morning @SvetlanaUP, I had an issue  with internet service provider, which was supposed to be worked on yesterday but since it was a public holiday and its been worked on today. I realized  the points to be corrected by me were corrected by others. I am sorry for delay to correct the points raised in my paper.

**Comment by SvetlanaUP** [comment]
@Gloshe no worries!

**Comment by Folakunmi21** [comment]
@SvetlanaUP Study 958 reviewed
