### ISSUE TITLE
Upper respiratory tract microbiome profiles in SARS-CoV-2 Delta and Omicron infected patients exhibit variant specific patterns and robust prediction of disease groups

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#242]
Upper respiratory tract microbiome profiles in SARS-CoV-2 Delta and Omicron infected patients exhibit variant specific patterns and robust prediction of disease groups – Shankha Nath – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.02368-23

**Comment by TitilayoMG** [comment]
@SvetlanaUP Please I'll like to curate this paper

**Comment by TitilayoMG** [comment]
Hi @SvetlanaUP 
I have finished curating this paper. This article is ready for review.
Link to curation: 
https://bugsigdb.org/Study_883 
Thank you!

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_883

**Comment by TitilayoMG** [comment]
Noted all the corrections with thanks @Folakunmi21 
It will definitely guide my subsequent curation. Thank you.
