### ISSUE TITLE
Alterations of the Gut Microbiota in Patients with Diabetic Nephropathy

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#243]
Alterations of the Gut Microbiota in Patients with Diabetic Nephropathy – Lili Zhang – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00324-22

**Comment by Rahila-me** [comment]
Thank you

**Comment by Rahila-me** [comment]
@cmirzayi @lwaldron @SvetlanaUP
 Please this needs a review: https://bugsigdb.org/Study_884

**Comment by Rahila-me** [comment]
@SvetlanaUP @cmirzayi 
My Second contribution, please it also needs review:
https://bugsigdb.org/Study_1009

**Comment by Rahila-me** [comment]
@Omabekee please may i know why you assigned my issue to yourself that's marked for review to yourself. I have worked on this issue recorded it and waiting for its review

**Comment by SvetlanaUP** [comment]
Hi @Rahila-me, **@Omabekee, as one of the mentors**, has been assigned to review your curation. Soon you will get from her feedback and scoring. Thank you for your patient!

**Comment by Rahila-me** [comment]
oh! I see, thank you, what a relief.

**Comment by Omabekee** [comment]
An excellent curation! Fantastic! ⭐ @Rahila-me 
I updated the source descriptions and the condition for experiment 3. Well done!

**CURATION RESULTS**
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0.5
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2
Total = 22.5

@SvetlanaUP, review of Study 884 complete. ✅

**Comment by Rahila-me** [comment]
Thank you @Omabekee for the review and your kind word. I will take a look at the paper again, to understand condition better.
