### ISSUE TITLE
Identification of Gut Microbiome and Metabolites Associated with Acute Diarrhea in Cats

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#244]
Identification of Gut Microbiome and Metabolites Associated with Acute Diarrhea in Cats – Huasong Bai – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00590-23

**Comment by SvetlanaUP** [comment]
@WelileDlamini you are assigned to https://github.com/waldronlab/BugSigDBcuration/issues/237

**Comment by imalovee** [comment]
Hello, @SvetlanaUP  since he's been assigned to one already, I'd love to work on this thanks

**Comment by imalovee** [comment]
Thank you @SvetlanaUP

**Comment by imalovee** [comment]
Hello @SvetlanaUP I have completed this curation, here is the link; https://bugsigdb.org/Study_950
P.s. I have also attached a few observations on the discussion page about the condition of the study, and more importantly about the names of the microbiomes found on the NCBI site.
Thank You ~Ima-obong

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This study is now complete and ready for your review. It had a couple of experiments and signatures missing, which I have now curated. The study consists of 7 experiments, each with 2 signatures. However, they don't seem to be displaying all at once. I've reported the issue.

Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_950 reviewed.
