### ISSUE TITLE
Insights into the Unique Lung Microbiota Profile of Pulmonary Tuberculosis Patients Using Metagenomic Next-Generation Sequencing

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#246]
Insights into the Unique Lung Microbiota Profile of Pulmonary Tuberculosis Patients Using Metagenomic Next-Generation Sequencing – Xiao et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01901-21

**Comment by B612Spac** [comment]
Hello @SvetlanaUP Please I'd like to be assigned to this article, thanks

**Comment by eve10111** [comment]
Hi @SvetlanaUP , can you kindly assign this to me to curate? Thank you very much

**Comment by B612Spac** [comment]
Thank you @SvetlanaUP 🫶🏾

**Comment by B612Spac** [comment]
Hello @SvetlanaUP thank you for assigning me to this paper. I'd appreciate if you can help me review it and let me know if it needs to be editted. I enjoyed working on this project and it made me realise my little contribution to bugsigdb is for a greater cause. I'd continue to contribute after now and get more conversant with working with Open Source. Thanks for the opportunity

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0.5|
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0.5 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0.5 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 13.5 |

The main errors here are due to the missing fact that we are not curating relative abundance results. We are interested only in differential abundance results. 

- The ACE index (Richness) is missed
- There is no matching in this study
- Figure 3C and 4D are only curatable; thus this curation has irrelevant experiments recorded
- Sequencing details and statistical test details missed or incorrect in experiments, except in the Experiment 1

**Comment by B612Spac** [comment]
Thanks for the feedback @SvetlanaUP can I use your corrections to make changes on the study?

**Comment by B612Spac** [comment]
Thank you @SvetlanaUP I'll get started with it

**Comment by Buraah** [comment]
Hello @B612Spac 
Good day and hope you're doing well.
I noticed you haven't started correcting this study yet. If you don't mind collaborating on it, you can reach out to me, I'd be glad to help.

**Comment by SvetlanaUP** [comment]
@Buraah go ahead with this correction! Thanks.

**Comment by Buraah** [comment]
Okay @SvetlanaUP 
I'll get to it

**Comment by Buraah** [comment]
Okay @B612Spac 
No problem...Thank you for your response.

**Comment by Buraah** [comment]
Hello @SvetlanaUP 
I am done implementing the feedback for this study and it's ready for a second review.

Here are the things I changed:
1. I removed the previously inputted matched-on factors.
2. I deleted experiment 4 because it was irrelevant.
3. I added the sequencing details and statistical test details that were missing in the first curation.
4. I changed the signature sources and curated all signatures from Fig 3c and Fig 4d.
5. I changed the contrast group definitions.

**Comment by Scholarpat** [comment]
Hi @Buraah,

I noticed that in this study, the signatures were presented using LEfSe analysis in a "one against all" format. Therefore, the signatures should be represented as follows:

**Figure 3C**
1. **HCG (group 0) vs. UTG and LCG (group 1)**
   - Red bars: Decreased
2. **LCG and HCG (group 0) vs. UTG (group 1)**
   - Blue bars: Increased
3. **HCG and UTG (group 0) vs. LCG (group 1)**
   - Green bars: Increased

**Figure 4D**
4. **TTG and CTG (group 0) vs. UTG (group 1)**
   - Blue bars: Increased

What do you think about this representation?

**Comment by Buraah** [comment]
Hi @Scholarpat,
I think we should follow your suggestion; it makes more sense to curate as 'one against all'.

**Comment by Scholarpat** [comment]
@Buraah Should I proceed with making the corrections, or would you prefer to handle it yourself?

**Comment by Buraah** [comment]
Yes, please proceed with making the corrections. I'm a little bit occupied. Thank you so much!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Please kindly delete Signature 2 of exp. 1 and 2 of this study;
https://bugsigdb.org/Study_988

Thank you!

**Comment by Scholarpat** [comment]
> Hi @Buraah,
> 
> I noticed that in this study, the signatures were presented using LEfSe analysis in a "one against all" format. Therefore, the signatures should be represented as follows:
> 
> **Figure 3C**
> 
> 1. **HCG (group 0) vs. UTG and LCG (group 1)**
>    
>    * Red bars: Decreased
> 2. **LCG and HCG (group 0) vs. UTG (group 1)**
>    
>    * Blue bars: Increased
> 3. **HCG and UTG (group 0) vs. LCG (group 1)**
>    
>    * Green bars: Increased
> 
> **Figure 4D** 4. **TTG and CTG (group 0) vs. UTG (group 1)**
> 
> * Blue bars: Increased
> 
> What do you think about this representation?

Hi @SvetlanaUP,

I've curated this study as specified above.
Please kindly delete Signature 2 of exp. 1 and 2.
https://bugsigdb.org/Study_988

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_988 reviewed.
