### ISSUE TITLE
Dysbiosis of Oral Microbiota and Metabolite Profiles Associated with Type 2 Diabetes Mellitus

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#247]
Dysbiosis of Oral Microbiota and Metabolite Profiles Associated with Type 2 Diabetes Mellitus – Li et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03796-22

**Comment by Aeeshah1** [comment]
I will like to review this please

**Comment by Aeeshah1** [comment]
Hello, please here is my curation on this- https://bugsigdb.org/Study_951
It is ready for review

**Comment by Folakunmi21** [comment]
@Aeeshah1 Unfortunately, this curation was poorly done. This study is a case control, not a cross-sectional observational. It has 2 experiments and you curated only one. The signatures for that experiment were not completely entered. The groups (group 1 and 0) were also poorly defined. This study has only one statistical test which is Lefse, you entered multiple tests. Please, check the corrected curation to see more of the changes made.

CURATION RESULT
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0.5
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 13

@SvetlanaUP study 951 reviewed

**Comment by SvetlanaUP** [comment]
@Rahila-me https://bugsigdb.org/Study_951 has all fields corrected and reviewed; you can see that in the feedback text here and in the bugsidb page where all sections are with tage "Reviewed".

**Comment by Rahila-me** [comment]
Oh! Noted going forward, thanks a lot
