### ISSUE TITLE
Diagnostic Potential and Interactive Dynamics of the Colorectal Cancer Virome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#25]
https://pubmed.ncbi.nlm.nih.gov/30459201/

**Comment by Cindy-erella** [comment]
Kindly assign me to this. Cindy

**Comment by mockingjay13** [comment]
I want to get this assigned to me.
Name: Aditi SIngh

**Comment by lwaldron** [comment]
Assigning to @Cindy-erella based on first request.

**Comment by Cindy-erella** [comment]
Thank you.

**Comment by Cindy-erella** [comment]
I have finished curating #25 I had issues on increase and decrease in microbiomes since they only recorded a mean decrease of the virome. Kindly review and inform on how to handle this.

**Comment by Cindy-erella** [comment]
@lwaldron @cmirzayi I was done here quite long ago please review so that I can make corrections

**Comment by cmirzayi** [comment]
Hi @Cindy-erella It seems bugsigdb is not loading right now but once it's back up I will review.

**Comment by cmirzayi** [comment]
Hi @Cindy-erella. I think you did a fairly good job with what is an extremely challenging curation. Unfortunately there's a big mistake here--and it was extremely difficult to identify--but this paper is not actually curatable. It reports no differential abundant results and the authors attempted no differential abundance testing therefore the correct curation was to not curate anything at all. I tried my best to grade it as if this were a normal curation to be fair to you. If you curate another paper, we can count that as your score.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (it's a case-control)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (there are no experiments)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (the paper distinguishes between colon adenoma and colon carcinomas)
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1 (variable region is V4)
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):  2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 13
