### ISSUE TITLE
The Interaction between Intratumoral Microbiome and Immunity Is Related to the Prognosis of Ovarian Cancer

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#250]
The Interaction between Intratumoral Microbiome and Immunity Is Related to the Prognosis of Ovarian Cancer – Sheng et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03549-22

**Comment by Muqtadirat** [comment]
Hi @SvetlanaUP , I'd like to submit this for review and thank you to @scholarpat, she's a co curator for this paper. 


Curation link: https://bugsigdb.org/Study_974

**Comment by Scholarpat** [comment]
Yes @SvetlanaUP , this study is now ready for review. Thank you for the opportunity to collaborate with you @Muqtadirat 🤗.

**Comment by Peacesandy** [comment]
Hi @Muqtadirat this is an excellent curation attempt, however here are some few points to note. ✍️

- The sequencing type is PCR

**N/B:** This study has been corrected and reviewed ✔️

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 1
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 22**

@SvetlanaUP https://bugsigdb.org/Study_974 corrected and reviewed ✔️
