### ISSUE TITLE
Exploring the Relevance between Gut Microbiota-Metabolites Profile and Chronic Kidney Disease with Distinct Pathogenic Factor

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#253]
Exploring the Relevance between Gut Microbiota-Metabolites Profile and Chronic Kidney Disease with Distinct Pathogenic Factor – Chen et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.02805-22

**Comment by eve10111** [comment]
Hi @SvetlanaUP , can you assign this paper to me to curate? Thank you.

**Comment by PreciousMike** [comment]
Hello @SvetlanaUP  please kindly assign this paper to me.

**Comment by PreciousMike** [comment]
Hello @SvetlanaUP I'm done curating this study and I'll appreciate your review on it. 
Here's the link to the study:  https://bugsigdb.org/Study_985

Also, my study sampled four groups but the bugsigdb form only allows for comparison of two groups, is there a way to incorporate the other two groups or can they be ignored? Thank you

**Comment by SvetlanaUP** [comment]
Hi @PreciousMike, from your question and a quick look at your curation, we can conclude that https://bugsigdb.org/Study_985 is not ready for review.

Please ask support in the Slack #bugsigdb, especially if you have this kind of doubts.
@Scholarpat and/or @MyleeeA, could you help out here?

**Comment by MyleeeA** [comment]
Yes I can help @SvetlanaUP 

@PreciousMike I’m willing to help on this 😊

**Comment by Scholarpat** [comment]
Yes, I'll be happy to help @SvetlanaUP.
@PreciousMike and @MyleeeA let's work together

**Comment by PreciousMike** [comment]
Thank you for taking a look at it @SvetlanaUP .

@MyleeeA and @Scholarpat, I'll be super happy to work with you two on this. What's the way forward?

**Comment by Scholarpat** [comment]
@PreciousMike I already chatted @MyleeeA on slack. What's your username on slack so we can collaborate there.

**Comment by PreciousMike** [comment]
That's awesome.
My username is Mkpouto Shedrack (MK).

**Comment by PreciousMike** [comment]
Hello @SvetlanaUP , This study https://bugsigdb.org/Study_985  is now ready for review.

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0.5 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 2|
| 19 | Correct use of NCBI taxonomy | 2 | 2|
|  | TOTAL | 23 | 21.5 |

Well done @PreciousMike @Scholarpat @MyleeeA 

- a proper matching was not done in this study (corrected)
- Figure 1 does show alpha diversity between healthy and 3 disease subgroups (Experiment 2-4), but for the Experiment does not. (corrected)

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP for the review and corrections.
 I have taken note of the corrections for future curations.

**Comment by PreciousMike** [comment]
Thank you so much @SvetlanaUP for the review, I appreciate and have taken note of all the corrections.
