### ISSUE TITLE
Divergent maturational patterns of the infant bacterial and fungal gut microbiome in the first year of life are associated with inter-kingdom community dynamics and infant nutrition

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#254]
Divergent maturational patterns of the infant bacterial and fungal gut microbiome in the first year of life are associated with inter-kingdom community dynamics and infant nutrition – Emily M. Mercer et al. – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01735-3

**Comment by AleruDivine** [comment]
Aleru Divine

Hi @SvetlanaUP I am done with my second contribution and while waiting for the review, I'd like to be assigned this paper to curate.

Thak you so much!

**Comment by tayyabak26** [comment]
@SvetlanaUP Kindly assign me this paper to curate. Thank You

**Comment by tayyabak26** [comment]
Hi @SvetlanaUP
I am done curating this study and it is ready for review.

Thank you.
Link to study : https://bugsigdb.org/Study_993

**Comment by tayyabak26** [comment]
@SvetlanaUP
