### ISSUE TITLE
Dysbiosis of gut microbiota inhibits NMNAT2 to promote neurobehavioral deficits and oxidative stress response in the 6-OHDA-lesioned rat model of Parkinson’s disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#255]
Dysbiosis of gut microbiota inhibits NMNAT2 to promote neurobehavioral deficits and oxidative stress response in the 6-OHDA-lesioned rat model of Parkinson’s disease -- Yu et al. -- Journal of Neuroinflammation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10199500/

**Comment by BarakatAA** [comment]
Good morning @SvetlanaUP can this be assigned to me?

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Happy new month!

In this curation, a couple of taxa were missing or incorrectly curated in signature 2, including:
- Unclassified Veillonella atypica
- Unclassified Streptococcus thermophilus
- Unclassified Paraprevotella
- Catenibacterium
- Unclassified Escherichia
- Coprococcus sp. ART55_1

I've added these, and the curation is now complete as all other data were accurately curated.

Thank you!
