### ISSUE TITLE
Implications of gut microbiota dysbiosis and metabolic changes in prion disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#256]
Implications of gut microbiota dysbiosis and metabolic changes in prion disease -- Yang et al. -- Neurobiology of Disease

**Comment by Omabekee** [comment]
Implications of gut microbiota dysbiosis and metabolic changes in prion disease -- Yang et al. -- Neurobiology of Disease
[Download article.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14564953/Download.article.pdf)

[1-s2.0-S0969996119303791-mmc1.docx](https://github.com/waldronlab/BugSigDBcuration/files/14564954/1-s2.0-S0969996119303791-mmc1.docx)

[1-s2.0-S0969996119303791-mmc2.docx](https://github.com/waldronlab/BugSigDBcuration/files/14564956/1-s2.0-S0969996119303791-mmc2.docx)

[1-s2.0-S0969996119303791-mmc3.docx](https://github.com/waldronlab/BugSigDBcuration/files/14564957/1-s2.0-S0969996119303791-mmc3.docx)

**Comment by ikehdarlington** [comment]
Hi @SvetlanaUP @Omabekee I would like this paper to be assigned to me. 

However, this would be my third contribution, if you add the introductory contribution. 

I noticed there are some new applicants who have no paper assigned to them for their second contribution. If assigning this paper to me would affect them not getting to make a second contribution, please don't assign to me. But if not, please assign to me as this has been fun and enlightening and I want to continue.

**Comment by SvetlanaUP** [comment]
Is https://bugsigdb.org/Study_982 ready for review?

**Comment by ikehdarlington** [comment]
Yes My Mentor! Thank you for your prompt intervention.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Study design: changed from "case-control" to "laboratory experiment".
- Statistical test: changed from "LEfSe, Random Forest Analysis, Welch's T-Test" to just "LEfSe"
- Altered the signature description.
- Curated missing taxa (uncultured Oscillospiraceae bacterium) for signature 2.

This curation is complete. Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_982 reviewed.
