### ISSUE TITLE
The alteration of intestinal mucosal α-synuclein expression and mucosal microbiota in Parkinson's disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#257]
The alteration of intestinal mucosal α-synuclein expression and mucosal microbiota in Parkinson's disease -- Shi et al. - Applied Microbiology and Biotechnology
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10006030/

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to curate this. Can it be assigned to me?

Thank you!

**Comment by Scholarpat** [comment]
Thanks Svetlana

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to put this curation up for review.
https://bugsigdb.org/Study_955

Scholastica Urua
Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've made some changes in the group definition and signature description. The curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_955 reviewed.
