### ISSUE TITLE
Integrated Microbiome and Host Transcriptome Profiles Link Parkinson's Disease to Blautia Genus: Evidence From Feces, Blood, and Brain

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#259]
Integrated Microbiome and Host Transcriptome Profiles Link Parkinson's Disease to Blautia Genus: Evidence From Feces, Blood, and Brain -- Guo et al. -- Frontiers in Microbiology
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9204254/

**Comment by leenaaize** [comment]
Hello @SvetlanaUP @Omabekee.
I have finished my second contribution and while awaiting review I would like to be assigned this study for curation. Thank you

**Comment by thegirlcoderr** [comment]
Hello @leenaaize  I trust you're doing well. I noticed that this this issue have been open for some time and is not yet available on BugSigDB. I'm contacting you to offer my assistance with the curation.  If you'd like any assistance, please respond so we can collaborate and complete the curation process together. Best regards.

**Comment by leenaaize** [comment]
Hello @thegirlcoderr I would love to collaborate and complete the curation process thank you!

**Comment by thegirlcoderr** [comment]
@leenaaize I'm happy to help. Can we collaborate on slack?

**Comment by leenaaize** [comment]
@thegirlcoderr yes, I'll message you on slack

**Comment by leenaaize** [comment]
Hello @SvetlanaUP @Omabekee I am done curating this paper, here is the link for review: https://bugsigdb.org/Study_998. 
Thank you.

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP 
I'd love to review this curation

**Comment by SvetlanaUP** [comment]
Sure @fiddyhamma!

**Comment by SvetlanaUP** [comment]
@fiddyhamma any update on reviewing https://bugsigdb.org/Study_998?

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP 
I was waiting for the next meeting to confirm the sample sizes and sequencing platform.
Although these are the errors I've noticed so far
- Data transformation should be relative abundance 
- There should be two separate experiments for suppl tables 4 & 5 which used Greengenes and SILVA in the meta-analysis

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP 
I've made all corrections to this study but some taxas are still unresolved with NCBI ID's

**Comment by SvetlanaUP** [comment]
Hi @fiddyhamma could you please specify which ones? Thanks!

**Comment by fiddyhamma** [comment]
Cc_115
1-68
ph2
rc4-4
I recorded them like this for now, is that fine?

**Comment by SvetlanaUP** [comment]
Is this study https://bugsigdb.org/Study_998 now completely reviewed? Thanks!

**Comment by fiddyhamma** [comment]
Yes, it is @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_998 reviewed.
