### ISSUE TITLE
Tobacco exposure associated with oral microbiota oxygen utilization in the New York City Health and Nutrition Examination Study

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#26]
https://www.ncbi.nlm.nih.gov/pubmed/31076212

**Comment by atrayees** [comment]
Hello, I would love to curate this paper.
Atrayee Samanta

**Comment by atrayees** [comment]
I have finished curating this paper! It would be great if you could please review it
https://bugsigdb.org/Study_727
Atrayee Samanta

**Comment by lwaldron** [comment]
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (this is a case-control study nested within a cross-sectional observational study)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 0 (list only the test used to produce the signatures reported, in this case edgeR)
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1 (note that you could combine phyla and genera in the same signature, having 2 experiments instead of 4)
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0.5 (tricky but observed OTUs = Richness and this is missing)
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1 (should have used Figure 2 which was the primary report of differential abundance - this was an adjusted analysis whereas supplemental figures reported crude analysis). 
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 20.5

**Comment by lwaldron** [comment]
Great contribution @atrayees, only a few relatively small corrections to make, noted above. I'm very familiar with this publication as you may have noticed from the author list! :)

**Comment by cmirzayi** [comment]
Great work. Closing.

**Comment by atrayees** [comment]
Thank you so much for the review @lwaldron and yes, I noticed you as an author in the paper and research has always fascinated me so I too would love to be a part of research projects like this when I grow up! I'm really grateful to have learned at least something from you and the other mentors :D

I'll make the changes in the curation as soon as possible

**Comment by atrayees** [comment]
Thanks a lot @cmirzayi !
