### ISSUE TITLE
Clinical Phenotypes of Parkinson's Disease Associate with Distinct Gut Microbiota and Metabolome Enterotypes

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#260]
Clinical Phenotypes of Parkinson's Disease Associate with Distinct Gut Microbiota and Metabolome Enterotypes -- Vascellari et al. -- Biomolecules
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7911638/

**Comment by Junie06** [comment]
@SvetlanaUP can this be assigned to me.
My name is Isoken Ibizugbe

**Comment by Peacesandy** [comment]
Hi, @Junie06 this is a fair first curation attempt. However, there were some errors;
Here are some points to take note ✍️

- All relevant experiments were not entered.
-  Contrast groups were not correctly identified
- Groups were not correctly labeled
- All the signature sources were not correctly identified. The signature sources are in Figure 3, which shows a Linear discriminant analysis effect size (LEfSE) analysis: The bar plots represent the significantly different taxa among PD patients with distinct motor phenotypes, based on effect size (Linear discriminant analysis (LDA) score (log 10) > 2). This study has three experiments based on PD patients with distinct motor phenotypes. You entered just one experiment and it was which was not completely correct.
- Abundance direction was not correctly identified

**N/B**: I've made all the necessary corrections. For ease kindly go through the reviewed curation and the paper again, this will help you to gain a better understanding of how to curate papers with multiple experiments



**CURATION RESULTS**

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 0
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 1

Total (maximum 23 points): 15

@SvetlanaUP  https://bugsigdb.org/Study_1001 Corrected and reviewed ✅
