### ISSUE TITLE
Study of gut microbiota alterations in Alzheimer's dementia patients from Kazakhstan

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#262]
Study of gut microbiota alterations in Alzheimer's dementia patients from Kazakhstan -- Kaiyrlykyzy et al. --Scientific Reports
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9448737/

**Comment by Ademolawe** [comment]
Hello, can I curate this for my third curation?

Adebayo Eniola

**Comment by Ademolawe** [comment]
Hi, this study is ready for review, https://bugsigdb.org/Study_968
Thank you.

Eniola Adebayo

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made:

- Statistical test: changed from 'ANOSIM and PERMANOVA' to 'MaAsLin2' in Experiment 1.
- Curated missing signatures in Experiments 1 and 2.

This curation is complete.

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_968 reviewed.
