### ISSUE TITLE
Injection of amyloid-β to lateral ventricle induces gut microbiota dysbiosis in association with inhibition of cholinergic anti-inflammatory pathways in Alzheimer's disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#264]
Injection of amyloid-β to lateral ventricle induces gut microbiota dysbiosis in association with inhibition of cholinergic anti-inflammatory pathways in Alzheimer's disease -- Qian et al. -- Journal of Neuroinflammation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9520842/

**Comment by FlourishRalph** [comment]
Hi @SvetlanaUP, I'm done with my first curation and it's currently marked for review.
I will like to curate this study, kindly assign it to me.

Thank you!

**Comment by FlourishRalph** [comment]
Hi @SvetlanaUP
I’m done with curating this paper and it’s ready for review.

Here is the link:

https://bugsigdb.org/Study_972
 Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, Happy Friday!

After reviewing this study, I observed that only Experiments 3 and 6 are statistically significant.

I have adjusted the group and source descriptions and also curated appropriate signatures for both experiments. The curation is complete.

Please kindly delete Experiments 1, 2, 4, and 5.

Thank you very much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_972 reviewed.
