### ISSUE TITLE
Normal gut microbiome in NMDA receptor encephalitis

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#268]
Normal gut microbiome in NMDA receptor encephalitis --Herken et al. --  Neurology, Neuroimmunology and Neuroinflammation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6857909/

**Comment by Aeeshah1** [comment]
Kindly assign this to me please

**Comment by Aeeshah1** [comment]
Hello, I'm done with curating this and it is ready for review. Please check: https://bugsigdb.org/Study_956
Thank you

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

After reviewing this article, I realized that it is not curatable. None of the results, including alpha diversity and bacterial signatures, were significantly different (all q > 0.05) between groups after correction for multiple testing. These excerpts, among others, affirm this;

![Significance](https://github.com/waldronlab/BugSigDBcuration/assets/107363472/81b5de92-49d1-47a6-93f7-65e621e58de7)
![Significance1](https://github.com/waldronlab/BugSigDBcuration/assets/107363472/360bc2d7-710f-460f-b9c9-18bbf097d207)

**Comment by SvetlanaUP** [comment]
Not curatable.
