### ISSUE TITLE
Fibroblast growth factor 21 ameliorates behavior deficits in Parkinson's disease mouse model via modulating gut microbiota and metabolic homeostasis

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#269]
Fibroblast growth factor 21 ameliorates behavior deficits in Parkinson's disease mouse model via modulating gut microbiota and metabolic homeostasis -- Yang et al. -- CNS Neuroscience and Therapeutics
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10651963/

**Comment by fiddyhamma** [comment]
I'd love to be assigned this paper
Peace Daniel

**Comment by fiddyhamma** [comment]
Hello, I'm done with this curation and would love a review 

https://bugsigdb.org/Study_961

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, 

Here are the changes I made to this curation,
- Changed Richness from 'unchanged' to 'increased' for exp. 1 (fig. 4A/B)
- Changed both Shannon and Richness indices from 'increased' to 'unchanged' for exp. 2 (fig. 4A/B)
- I've also adjusted the group definition for both experiments

This curation is now complete. Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_961 reviewed.

**Comment by fiddyhamma** [comment]
Hey @Scholarpat 
I don't quite understand why you feel experiment 2 should be unchanged, take a look at this
"The Shannon Diversity Index and observed species showed that mice from the FGF21 + MPTP group were characterized by a higher richness than PD mice"

**Comment by Scholarpat** [comment]
Hi @fiddyhamma,

I understand why you used "increased." While the alpha diversity measures were indeed higher, the increase was not statistically **_significant_**. If you refer to Figure 4A/B, you'll notice that the significant difference (indicated by an asterisk) was observed only in the experiment comparing CON and MPTP (experiment 1).

> Hi @SvetlanaUP,
> 
> Here are the changes I made to this curation,
> 
> Changed Richness from 'unchanged' to 'increased' for exp. 1 (fig. 4A/B)
> Changed both Shannon and Richness indices from 'increased' to 'unchanged' for exp. 2 (fig. 4A/B)
> I've also adjusted the group definition for both experiments
> This curation is now complete. Thank you!

For my first point here, Richness is changed from 'unchanged' to 'decreased' and not 'increased. Apologies for the mistake.

**Comment by fiddyhamma** [comment]
Yh i also do understand why you feel it should be unchanged although other curations I've seen didn't follow the asterisk rule, take a look here
https://bugsigdb.org/Study_926

**Comment by Scholarpat** [comment]
I just checked the curation you mentioned and I noticed the study reported that "_The Chao1 diversity index was **significantly lower** in patients with UC and CD than in HC and was significantly lower in patients with CD than in UC patients (Fig. 1A)_". Also the fig. listed the different p-value for each comparison done which was below 0.05.

Please can you elaborate further, I might be missing something in [this study](https://bugsigdb.org/Study_926). Thank you!

**Comment by Scholarpat** [comment]
Hi @fiddyhamma,

I brought this curation up during office hours, and it was confirmed that the lack of an asterisk or any other mention of significance does mean the alpha diversity is unchanged.

Thank you for bringing this up. I had to double-check some of my previous curation.

**Comment by fiddyhamma** [comment]
I see, thanks for the update and clarification @Scholarpat 
This means some curations might need this adjustment, I'll let you know if/when I come across any.

**Comment by Scholarpat** [comment]
Okay, thank you @fiddyhamma
