### ISSUE TITLE
Deep nasal sinus cavity microbiota dysbiosis in Parkinson's disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#270]
Deep nasal sinus cavity microbiota dysbiosis in Parkinson's disease --Pal et al. -- NPJ Parkinson's disease
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8655044/

**Comment by allieniola1** [comment]
Hello mentors, i will like to curate this article. thank you @SvetlanaUP @Omabekee @lwaldron

**Comment by allieniola1** [comment]
Hello mentors @SvetlanaUP @Omabekee @lwaldron @cmirzayi . i have just completed my second contribution. Below is the link to the curated study. Thank you.
https://bugsigdb.org/Study_969

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
I'd like to review this study. Can I go ahead?

**Comment by SvetlanaUP** [comment]
Sure! @Buraah

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I'm done with my review.

Here are my observations and additions:

The study has 3 experiments. The first 2 experiments used 2 statistical tests, and the results are shown separately; therefore, I have curated them separately. Bringing this study to a total of 5 experiments.
The initial curator only curated 1, so I have the remaining 4.

1. 16S variable region
* I added the variable region 'V4' as seen on page 20 of the supplemental material.

2. Statistical Analysis
* According to the 'Results' section ", Microbial taxa differing in abundance between rHC & SpHC were identified using DESeq2 and ANCOM"
* I removed the previously curated values and replaced them with DESeq2 and ANCOM. For clarity, I created Separate experiments for both statistical tests.

3. Experiments
* I added 4 new experiments to match what was carried out in the study

4. Signatures
* Only signatures at the species taxonomic level were curated for experiment 1. I added signatures at the genus taxonomic level from supplementary table 10 of the study.
* All signatures were curated from Supplementary Tables 6, 7, 10, 11 & 13, Supplementary Figures 1 & 2, and Figure 2b of the study.

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_969 reviewed.

**Comment by lwaldron** [comment]
Excellent review.

**Comment by Buraah** [comment]
Thank you! @lwaldron
