### ISSUE TITLE
Gut microbiota-associated taurine metabolism dysregulation in a mouse model of Parkinson's disease

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#272]
Gut microbiota-associated taurine metabolism dysregulation in a mouse model of Parkinson's disease --Cui et al.-- mSphere
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10732050/

**Comment by Buraah** [comment]
Hello @SvetlanaUP, I am done with my first curation and it has been marked for review.
I would like to take this as a second. PLease assign it to me.

Thank you
Victoria

**Comment by PreciousMike** [comment]
Hello @SvetlanaUP Please assign this project to me. 

Thanks

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
I am done curating this study and i'll appreciate your review on it.
I have also added notes on the discussion page.
This is the link to the study: https://bugsigdb.org/Study_954

Thank you.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, 

Just finished reviewing this curation and all details have been accurately captured.
Well done @Buraah :clap:

**Comment by Buraah** [comment]
Thank you! @Scholarpat

**Comment by SvetlanaUP** [comment]
@Buraah and @Scholarpat THANKS! https://bugsigdb.org/Study_954 reviewed.
