### ISSUE TITLE
Dysbiosis of the Beneficial Gut Bacteria in Patients with Parkinson's Disease from India 

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#273]
Dysbiosis of the Beneficial Gut Bacteria in Patients with Parkinson's Disease from India -- Sujith Pavan et al. - Ann Indian Acad Neurol 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10789430/

**Comment by Peacesandy** [comment]
Dysbiosis of the Beneficial Gut Bacteria in Patients with Parkinson's Disease from India -- Sujith Pavan et al. - Ann Indian Acad Neurol    https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10789430/

**Comment by assu140607** [comment]
Hello @Peacesandy , I am done with my first curation and it has been marked for review. I would like to take this as a second. Please assign one of them  to me.
Thank you Assel

**Comment by kayceecross** [comment]
Hello @Peacesandy Kindly assign this issue  as I am yet to curate one for my second contribution. Thanks

**Comment by kayceecross** [comment]
Thank you @Peacesandy @SvetlanaUP Let's get down to business

**Comment by kayceecross** [comment]
@SvetlanaUP I thought this was assigned to me already? I can't see the assigned label there. Please check

**Comment by SvetlanaUP** [comment]
@kayceecross yes, it is assigned to you.

**Comment by kayceecross** [comment]
https://bugsigdb.org/Study_975 is ready for review. Thanks

**Comment by kayceecross** [comment]
Thank you @SvetlanaUP @Peacesandy I appreciate your guidance and will make better curations going forward.

**Comment by SvetlanaUP** [comment]
Reviewed.
