### ISSUE TITLE
Gut Microbiota and Its Repercussion in Parkinson's Disease: A Systematic Review in Occidental Patients

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#274]
Gut Microbiota and Its Repercussion in Parkinson's Disease: A Systematic Review in Occidental Patients - Ana Cristina Proano et al. -Neurol Int 
https://pubmed.ncbi.nlm.nih.gov/37368331/

**Comment by SvetlanaUP** [comment]
It's a review paper, and challenging for outreachy.

**Comment by Peacesandy** [comment]
Okay
