### ISSUE TITLE
Nutritional Intake and Gut Microbiome Composition Predict Parkinson's Disease

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#275]
Nutritional Intake and Gut Microbiome Composition Predict Parkinson's Disease - Michal Lubomski et.al. - Front Aging Neurosci

https://pubmed.ncbi.nlm.nih.gov/35645785/

**Comment by assu140607** [comment]
Hello , I am done with my first curation and it has been marked for review. I would like to take this as a second. PLease assign it to me.
Thank you Assel

**Comment by assu140607** [comment]
Hello @Peacesandy , I am done with my first curation and it has been marked for review. I would like to take this as a second. PLease assign it to me.
Thank you Assel

**Comment by assu140607** [comment]
@SvetlanaUP Thank you

**Comment by nityasinghal-14** [comment]
Hey @assu140607 I would love to help you and collaborate with you in case you need any assistance.

**Comment by assu140607** [comment]
https://bugsigdb.org/Study_981

**Comment by assu140607** [comment]
Hello @SvetlanaUP my study is ready for review
Thank you for the opportunity !
https://bugsigdb.org/Study_981
