### ISSUE TITLE
Amelioration of Colitis by a Gut Bacterial Consortium Producing Anti-Inflammatory Secondary Bile Acids

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#279]
Amelioration of Colitis by a Gut Bacterial Consortium Producing Anti-Inflammatory Secondary Bile Acids – Chunhua Zhou – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03330-22

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I am done with my previous curation and I would like to work on this. Please assign this to me.

Thank you
Victoria

**Comment by Buraah** [comment]
Hello @SvetlanaUP, this study didn't carry out any analysis for Alpha diversity. Only Beta diversity analysis was done. Please, should I go ahead with this curation and leave the Alpha diversity results empty?

**Comment by SvetlanaUP** [comment]
Hi @Buraah, please note that this question is for our Slack channel (not here) and it's been answered several times there. 

If differential abundance results were reported but no alpha diversity was stated, we are recording the experiments with the alpha diversity section leaving blank. (Some authors could be not interested in alpha diversity.)

**Comment by Buraah** [comment]
@SvetlanaUP 
My apologies and thank you for your response.

**Comment by Buraah** [comment]
I am done with this curation and I will appreciate your review.
Thank you @SvetlanaUP 

Link to curation: https://bugsigdb.org/Study_989

**Comment by Scholarpat** [comment]
Hi @Buraah,

Great job on your curation! You've done an excellent job capturing all the necessary details. Here are a few observations I've made:

1. The differentially abundant taxa were obtained from samples collected on day 7. To enhance clarity, it would be beneficial to add 'day 7' to the group names.

2. It appears that MHT correction was not applied in this study, despite 'Yes' being ticked for this field.

Would you mind implementing these changes yourself?

Thank you very much!

**Comment by Buraah** [comment]
Thank you for your review @Scholarpat 

I agree, adding 'Day 7' to the group names will definitely improve clarity.

For the MHT correction, I ticked yes because the use of the Bonferroni post hoc test was mentioned under the description of Figure 5. The figure I curated signatures from.

**Comment by Scholarpat** [comment]
I agree with you on the MHT. I see now they mentioned Bonferroni post hoc test under the curated figure. I missed this earlier.

Once the group names are altered, the study will be complete as other details have been accurately curated.

Thank you so much for taking the time 😊

**Comment by Buraah** [comment]
I have made the addition to the group names now.

Thank you too! @Scholarpat
 Always a pleasure🤗

**Comment by SvetlanaUP** [comment]
Good job @Buraah @Scholarpat! https://bugsigdb.org/Study_989 reviewed.
