### ISSUE TITLE
Understanding of the Site-Specific Microbial Patterns towards Accurate Identification for Patients with Diarrhea-Predominant Irritable Bowel Syndrome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#280]
Understanding of the Site-Specific Microbial Patterns towards Accurate Identification for Patients with Diarrhea-Predominant Irritable Bowel Syndrome – Zhu et al. – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01255-21

**Comment by AleruDivine** [comment]
Aleru Divine

I would like to be assigned this paper for curation.

Thank you so much!

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP this study is ready for review.
Link: https://bugsigdb.org/Study_996
Thank you so much!🙏🙏

I am waiting on feedback from fellow contributors before I submit the other study for review. Thanks!

**Comment by Scholarpat** [comment]
@SvetlanaUP, this curation is reviewed and it's complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_996 reviewed.

**Comment by AleruDivine** [comment]
Thanks @Scholarpat
