### ISSUE TITLE
The efficacy of prevention for colon cancer based on the microbiota therapy and the antitumor mechanisms with intervention of dietary Lactobacillus

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#282]
The efficacy of prevention for colon cancer based on the microbiota therapy and the antitumor mechanisms with intervention of dietary Lactobacillus – Fuqiang Xu – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00189-23

**Comment by manisha-nair28** [comment]
hello @SvetlanaUP Can you please assign this issue to me for my second contribution.

**Comment by manisha-nair28** [comment]
https://bugsigdb.org/Study_990 is ready for review @SvetlanaUP

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0.5 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 14 |

- In experiments 1 and 2, Chao1 is missed (corrected)
- Some members in the signatures incorrect or missed (corrected)
- Experiment 3 is missing: Inactivated bacteria group vs Living bacteria group (**to correct**)

**Comment by AleruDivine** [comment]
@SvetlanaUP I would like to help out here in the correction of this curation from the feedback given.
@manisha-nair28 I would like to collaborate with you on this 🙏

**Comment by SvetlanaUP** [comment]
@AleruDivine if you open https://bugsigdb.org/Study_990 you will see all green highlighted "Reviewed". That means that this curation is corrected/reviewed. Also in the feedback notes it says "corrected".

**Comment by AleruDivine** [comment]
My apologies! I missed this. Thank you so much!
