### ISSUE TITLE
Impacts of Dietary Protein and Niacin Deficiency on Reproduction Performance, Body Growth, and Gut Microbiota of Female Hamsters (Tscherskia triton) and Their Offspring

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#283]
Impacts of Dietary Protein and Niacin Deficiency on Reproduction Performance, Body Growth, and Gut Microbiota of Female Hamsters (Tscherskia triton) and Their Offspring – Jidong Zha – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00157-22

**Comment by TitilayoMG** [comment]
@SvetlanaUP My name is Modinat Ganiyu. Please I'd like to curate this paper

**Comment by SvetlanaUP** [comment]
@TitilayoMG please do finish your curation https://bugsigdb.org/Study_345 before claiming for a new one.

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, please is this available for curation? I noticed it has not been assigned to anyone yet.

**Comment by TitilayoMG** [comment]
Hi @SvetlanaUP 
I've been working on this paper and was about to put it up for review before you commented that I should finish up my curation. You said I should finish this before claiming another and was rounding up already and now I saw you've already assigned it to another person. Please kindly rectify this issue. Thank you

**Comment by TitilayoMG** [comment]
I saw that it has been reviewed but I didn't put it up for review and besides my second contribution that has the 'needs review' tag hasn't been reviewed till now. I don't understand what's happening here. I don't know if @AleruDivine can help explain why its like that please.
First, I didn't put it up for review. I'm still working on it
Secondly, my second contribution hasn't been reviewed. It has the tag 'needs review' but has not been reviewed till now.

Why is it like that please?

**Comment by AleruDivine** [comment]
Hello @SvetlanaUP it appears that @TitilayoMG is already curating this paper 🙏

<img width="1440" alt="Screenshot 2024-03-22 at 20 55 37" src="https://github.com/waldronlab/BugSigDBcuration/assets/111589884/57907942-0a24-46bf-9ce6-068fa7f91fde">

**Comment by AleruDivine** [comment]
This is a mistake on my part @TitilayoMG 

I truly apologize for this. I saw that it was unassigned and I requested for it.

**Comment by SvetlanaUP** [comment]
@AleruDivine it is not your mistake.

@TitilayoMG the applicant starts to work only when it is officially assigned. You have never been assign to this paper. Especially, because you did not finish your previous curation.

**Comment by AleruDivine** [comment]
Okay, do I go ahead to complete the curation? @SvetlanaUP 

No experiments have been added yet.

**Comment by SvetlanaUP** [comment]
Let me check once again, there is a misunderstanding due to claiming papers in parallel.

**Comment by SvetlanaUP** [comment]
> I saw that it has been reviewed but I didn't put it up for review and besides my second contribution that has the 'needs review' tag hasn't been reviewed till now. I don't understand what's happening here. I don't know if @AleruDivine can help explain why its like that please. First, I didn't put it up for review. I'm still working on it Secondly, my second contribution hasn't been reviewed. It has the tag 'needs review' but has not been reviewed till now.
> 
> Why is it like that please?

That's ALL ok. Please do continue curating this paper.

**Comment by SvetlanaUP** [comment]
@AleruDivine please continue curation of this paper https://bugsigdb.org/Study_345 
Thank you for your understanding.

**Comment by AleruDivine** [comment]
Alright, @SvetlanaUP I will start working on this now. 
Thank you so much!

I apologize for the misunderstanding and I am glad this has been sorted out now @TitilayoMG 😊

**Comment by TitilayoMG** [comment]
Thank you so much @SvetlanaUP for being kind, I truly appreciate! 

I sincerely apologize for the confusion @AleruDivine

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, I have finished curating this paper and would like to put it up for review.
Link to paper: https://bugsigdb.org/Study_345
Thank you so much!

**Comment by Scholarpat** [comment]
Hi @AleruDivine,

You've done a wonderful job here.

I made a slight adjustment to the group names of experiments 1 and 3 by adding the full meanings of NPD and LPD. Additionally, the study did not report differential abundance or alpha diversity for the female hamsters in the niacin+/- group (experiment 2). Therefore, this experiment can be exempted. Every other detail has been well curated.

Well done! 👏

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Please kindly delete experiment 2 of this study; https://bugsigdb.org/Study_345.
The curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_345 reviewed.
