### ISSUE TITLE
Role of intestinal flora in the development of nonalcoholic fatty liver disease in children

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#284]
Role of intestinal flora in the development of nonalcoholic fatty liver disease in children – Jing Zhang – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.01006-23

**Comment by Scholarpat** [comment]
Hello Svetlana, please I'll love to curate this.🙏
Scholastica Urua

**Comment by Isioma20** [comment]
Hi. I'd like to be assigned this paper for curation. Thank you

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP 🙏

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to put this curation up for review and feedback. 🙏
https://bugsigdb.org/Study_980

Thank you!
Scholastica Urua

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made here;

- Edited Antibiotic exclusion in exp. 1 to include only the time frame.
- Included antibiotic exclusion for experiment 2 which was not initially curated.
- Altered the signature description for both experiments.

The curation is now complete. Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_980 reviewed.
