### ISSUE TITLE
Virulence genes are a signature of the microbiome in the colorectal tumor microenvironment

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#286]
Virulence genes are a signature of the microbiome in the colorectal tumor microenvironment - Michael B. Burns et al. - Genome Med

https://pubmed.ncbi.nlm.nih.gov/26170900/

**Comment by manisha-nair28** [comment]
Hi @SvetlanaUP please assign this issue to me

**Comment by Tech-neophyte** [comment]
hey there! I have completed my previous task. Can you please assign this to me?

**Comment by omojokunoluwatomisin10** [comment]
can i be assigned to this @SvetlanaUP

**Comment by Tech-neophyte** [comment]
@SvetlanaUP Hi! I would like to kindly request a review for the curation : https://bugsigdb.org/Study_1002
Your valuable feedback would be greatly appreciated. 
Thank you for your time and consideration!

**Comment by Peacesandy** [comment]
Hi @Tech-neophyte this is a good first curation attempt, however here are some few points to note ✍️

- The sequencing platform used is Illumina, "We assessed the microbiome associated with each sample by Illumina sequencing across the V5-V6 hypervariable regions of the 16S rRNA gene" - This is an excerpt from the study also DNA concentration in the final pool was assayed with PicoGreen and normalized to 2 nM for input into Illumina MiSeq (v3 Kit) to produce 2 × 250 bp sequencing products. Clustering was performed at 10 pM with a 5 % spike of PhiX. A single lane on an Illumina MiSeq instrument was used to generate the 16S rRNA gene sequences. Raw sequencing data have been submitted to the NCBI Sequence Read Archive under project accession PRJNA284355.
- The statistical test used is Mann-Whitney, - "Wilcoxon signed rank test to determine differential abundance between the normal and tumor microbiomes. "
- The Alpha Diversity were all decreased. From the supplemental - Additional File 7 - Paired line plots show the phylogenetic diversity, Shannon’s Index, and Inverse Simpson’s Index (alpha diversity metrics) for the microbiomes associated with normal and patient-matched tumor samples. The colors of the lines represent the direction of the change for each matched pair (blue lines indicate a decrease in diversity from normal to tumor, while red lines indicate an increase in diversity from the normal to tumor).  Looking closely at the diagram on figure 7, the alpha diversity measures were all decreased.

**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 1
Identified correct statistical test (1 point): 0
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 20**

@SvetlanaUP   https://bugsigdb.org/Study_1002 reviewed and corrected ✅

**Comment by Tech-neophyte** [comment]
Hi! @Peacesandy Thank you for the review and corrections. I've carefully noted all the adjustments and will ensure to remember them. Now that the article has been corrected, please let me know if there are any further actions required on my part.
Regards

**Comment by SvetlanaUP** [comment]
@Tech-neophyte please see my message here https://github.com/waldronlab/BugSigDBcuration/issues/194 :)
