### ISSUE TITLE
Gut mucosal microbiome across stages of colorectal carcinogenesis

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#287]
Gut mucosal microbiome across stages of colorectal carcinogenesis - Geicho Nakatsu et al. - Nat Commun

https://pubmed.ncbi.nlm.nih.gov/26515465/

**Comment by Druscillaa** [comment]
@SvetlanaUP please assign me this article

**Comment by Druscillaa** [comment]
Hello @SvetlanaUP  this study already exists in BugSigDB
![Screenshot 2024-03-19 152935](https://github.com/waldronlab/BugSigDBcuration/assets/137729908/b51785dd-9773-41ce-9dcc-ee7212f8e7ed)

**Comment by Peacesandy** [comment]
Okay, noted @SvetlanaUP . I'll take proper note next time
