### ISSUE TITLE
Genomic analysis identifies association of Fusobacterium with colorectal carcinoma

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#289]
Genomic analysis identifies association of Fusobacterium with colorectal carcinoma - Aleksandar D Kostic et al. - Genome Res 

https://pubmed.ncbi.nlm.nih.gov/22009990/

**Comment by kingyy200** [comment]
Hi @SvetlanaUP. Please assign me this paper for curation.

**Comment by MyleeeA** [comment]
Hi @kingyy200 can we collaborate on this if you are not done with it?

**Comment by SvetlanaUP** [comment]
Assigned to @MyleeeA 
Please continue curating https://bugsigdb.org/Study_878

**Comment by MyleeeA** [comment]
Thank you 🙏🏾 @SvetlanaUP

**Comment by FaithAlexander** [comment]
Hello @MyleeeA how is your curation going? I would love to know if you are open to collaboration because I would love to collaborate with you on this curation if that is Okay. I would be expecting your response. 

Thanks.

**Comment by MyleeeA** [comment]
Sure @FaithAlexander i still have a few things I haven’t figured out yet you could help 


Link to curation  
https://bugsigdb.org/Study_878

**Comment by MyleeeA** [comment]
@FaithAlexander I believe you haven’t gotten my response agreeing to the collaboration, I’ve been able to complete the curation 
Thank you for offering to help

@SvetlanaUP this curation is ready for review 
https://bugsigdb.org/Study_878

**Comment by FaithAlexander** [comment]
@MyleeeA yes I didn't get your response until now. So sorry that I wasn't able to help but I am glad that you have been able to figure it out. 

Thank you for agreeing to let me collaborate with you.

**Comment by Scholarpat** [comment]
Hi @MyleeeA,

This is a great curation! 👏

I've reviewed and confirmed all the details curated.

I made a slight adjustment group 0 name, changing it from 'Normal colonic tissue' to '**Adjacent** normal colonic tissue' to quickly indicate that both samples were obtained from the same participant.

This curation is complete. @SvetlanaUP, thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_878 reviewed.

**Comment by MyleeeA** [comment]
Thank you @Scholarpat and well done on the work you are doing 👏🏾
