### ISSUE TITLE
Effects of smoking on the lower respiratory tract microbiome in mice

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#29]
https://pubmed.ncbi.nlm.nih.gov/30547792/

**Comment by sopeadeniji** [comment]
@ftzohra22 @lwaldron please assign this article to me.

**Comment by chioma-grace** [comment]
Hello, 
I am Enwolo-Chibueze Chioma Grace (chigrace95@gmail.com), I am interested in work on this publication. I hope to actualize wonderful contributions. 
Kind Regards.

**Comment by Ellajessica** [comment]
@lwaldron @ftzohra22  . Please assign this to me. Thanks

**Comment by claregri** [comment]
Hi Sophy, good start with this curation! Please see my scoring and comments below. Figure 10 from this study should be curated as a separate LefSe experiment; looking at Table 2 there are many more significantly different taxa that should be curated in your Experiment 1.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (if the study is looking at rats/mice it would be considered a laboratory experiment)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (I would just say lung here)
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0 (you should choose only one statistical test per experiment based on results of the figure/table that you are actually curating - what statistical test did they use for that specifically?)
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1 (but please note that the confounders field is about the analysis controlling for confounders. Even though they selected only male Kunning mice, this was not part of the analysis and therefore does not need to be documented in this field - if you wanted to document this, I would add it to the Group 1 definition (ie Male Kunming mice exposed to smoking...))
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 0 (they mention Chao1 in the methods section but don't proviude any info re: statistical significance of alpha diversity by that measure, so I would not include this in the Alpha Diversity section)
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

**Comment by sopeadeniji** [comment]
@claregri https://bugsigdb.org/Study_509 has been updated with suggested corrections. Please, review.

**Comment by claregri** [comment]
Hi Sophy, thanks for working more on this! To clarify, I meant that there should be one experiment curating Table 2 and another experiment using Figure 10 (the statistical tests would differ). Also, it seems that you only curated the up-regulated taxa from Figure 10, but the down-regulated taxa (green bars) should also be curated in a "decreased abundance" signature.

**Comment by cmirzayi** [comment]
Hi @sopeadeniji Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by sopeadeniji** [comment]
Hi Chloe,

Please, open up the curation for other curators to finish. I have other priorities at this time and can no longer work on BugSigDB project.

Best,

Sophy


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by atrayees** [comment]
Study 509
Added and curated the differential testing results for Experiment 2 (using Wilcoxon test) and its signatures. The rest of the study was already reviewed.
