### ISSUE TITLE
Fusobacterium Is Associated with Colorectal Adenomas

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#291]
Fusobacterium Is Associated with Colorectal Adenomas - Amber N McCoy et al. -  PLoS One
https://pubmed.ncbi.nlm.nih.gov/23335968/

**Comment by uhabiba14** [comment]
hey there, kindly assign this paper for my third contribution. @SvetlanaUP @Peacesandy

**Comment by uhabiba14** [comment]
https://bugsigdb.org/Study_983 is ready for review.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Sequencing platform: Changed from RT-qPCR to Roche454.
- Edited out the confounders initially curated. Although the study identified some variables (characteristics of study participants), they were not controlled for.
- Altered the signature description.

This curation is complete. Thank you!

**Comment by lightamadi-stack** [comment]
Good day @SvetlanaUP, kindly add the CRC label.

Thank you.
