### ISSUE TITLE
Salivary microbiome profiles for different clinical phenotypes of pituitary adenomas by single-molecular long-read sequencing

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#296]
Salivary microbiome profiles for different clinical phenotypes of pituitary adenomas by single-molecular long-read sequencing – Xuefei Ji  – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00234-23

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to curate this please.

Scholastica Urua
Thank you!

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I've completed my curation and it's ready for review. 
https://bugsigdb.org/Study_1015

Scholastica Urua
Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've adjusted the signature description of this study to be better descriptive. The curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1015 reviewed.
