### ISSUE TITLE
Changes in the Gut Microbiome Associated with Intussusception in Patients with Peutz-Jeghers Syndrome 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#299]
Changes in the Gut Microbiome Associated with Intussusception in Patients with Peutz-Jeghers Syndrome – Zhiqing Wang – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.02819-22

**Comment by Aeeshah1** [comment]
I'd like to curate this please

**Comment by SvetlanaUP** [comment]
Please do not claim more than 1 paper at the time @Aeeshah1

**Comment by Rahila-me** [comment]
@SvetlanaUP i would love to curate this paper,
my first curation is marked with review already: here is the link :https://bugsigdb.org/Study_884

**Comment by Rahila-me** [comment]
Seen, Thank you

**Comment by Aeeshah1** [comment]
> Please do not claim more than 1 paper at the same time @Aeeshah1

Well noted, I'm sorry about that

**Comment by Rahila-me** [comment]
@SvetlanaUP @cmirzayi Second contribution, please it needs review:
https://bugsigdb.org/Study_1009

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Study design: Changed from 'cross-sectional' to 'case-control'.
- Missing signatures: Curated signature 2 for experiments 1 and 3. These newly curated signatures are not displaying. I've reported the issue.

This curation is now complete.

Thank you!

---

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1009 reviewed.
