### ISSUE TITLE
The gut microbiota and metabolite profiles are altered in patients with spinal cord injury

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#3]
Condition: Spinal Cord Injury
URL: https://molecularbrain.biomedcentral.com/articles/10.1186/s13041-023-01014-0

**Comment by kahvecirem** [comment]
Hello, I'd like to contribute to this article.

**Comment by anshikabhatt** [comment]
Hello, I am interested to work on this article.

**Comment by cmirzayi** [comment]
@kahvecirem assigned!

**Comment by BlessingKaz** [comment]
@cmirzayi please can I get assigned to this task or another one?
I'm interested in this article as well.

**Comment by kahvecirem** [comment]
> @cmirzayi a please can I get assigned to this task or another one? I'm interested in this article as well. Noticed all issues have been assigned.

Hello @BlessingKaz , I entered  first data of this article into system. It's almost done.

**Comment by ftzohra22** [comment]
@BlessingKaz please claim an article without the label "assigned". Thank you

**Comment by BlessingKaz** [comment]
@ftzohra22  alright thank you

**Comment by kahvecirem** [comment]
Curated Article for review: https://bugsigdb.org/Study_730

Best Regards

**Comment by claregri** [comment]
Hi there, good start with this curation! I noticed that you picked the incorrect abundance direction (in Figure 2e, the red is increased in controls and the blue is increased in SCI patients). Also, you labeled both of the signatures in Experiment 1 as Figure 3e, but I think you meant 2e based on the curation. Thirdly, it looks like you started a second experiment - you should curate figures 2b-c as they also document differential abundance between the groups (using a different statistical test). Though this paper goes into analyses of the blood, none of them are curatable by our standards so make sure to update the details of Experiment 2 to reflect figures 2b-c. Please see my grading below.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0 (be sure to go through and check that you got all the possibly curatable taxa, I think a few were missed)
19. Correct use of NCBI taxonomy (2 points): 0 (you'll notice that in Signature 1, Lachnospirales is highlighted in orange. I couldn't find it in the NCBI database, so you should remove it)

Total (maximum 23 points): 13

**Comment by atrayees** [comment]
Corrected the abundance direction, entered the new experiment and signatures, corrected MHT.
