### ISSUE TITLE
Dysbiosis in the Gut Microbiota in Patients with Inflammatory Bowel Disease during Remission

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#300]
Dysbiosis in the Gut Microbiota in Patients with Inflammatory Bowel Disease during Remission – Anthea Pisani – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.00616-22

**Comment by samreen-19** [comment]
Hello, I would like to curate this paper. Thank you.

**Comment by SvetlanaUP** [comment]
@samreen-19 is this paper ready for review? https://bugsigdb.org/Study_1007

**Comment by samreen-19** [comment]
Yes @SvetlanaUP I'm just awaiting reviews from my fellow contributors, and will be putting it up for review in some time

**Comment by samreen-19** [comment]
@SvetlanaUP this curation is ready for review 
https://bugsigdb.org/Study_1007

**Comment by Buraah** [comment]
Hi @SvetlanaUP,
I want to review this curation.

**Comment by Buraah** [comment]
Hi @SvetlanaUP
Here are the few things I changed;

1. **Condition:** Ulcerative colitis and Crohn's disease are both types of IBD, so the study's condition is Inflammatory Bowel Disease (IBD).
2. **Data transformation:** The data transformation for DESeq2 is **Raw count**
3. **Group Names:** I changed the group names to make them more descriptive.

Thank you, I am done with my review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1007 reviewed.
