### ISSUE TITLE
Longitudinal gut microbiota composition of South African and Nigerian infants in relation to tetanus vaccine responses

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#303]
Longitudinal gut microbiota composition of South African and Nigerian infants in relation to tetanus vaccine responses – Saori C Iwase – Microbiology Spectrum
https://journals.asm.org/doi/10.1128/spectrum.03190-23

**Comment by Aeeshah1** [comment]
Hello, kindly assign this to me please

**Comment by Aeeshah1** [comment]
Hello, I am done curating this article and it's ready for review. Here is the link- https://bugsigdb.org/Study_1004

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this study:

- Most fields in this curation were incorrectly or not entered, except for the lab and statistical analysis sections in the experiment 1.
- The signature source initially curated (Fig 1A) for experiment 1 is not curatable. I’ve rectified this.
- Curated missing experiments that were not previously curated, including experiments 2 and 3 with their signatures.

This curation is now complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1004 reviewed.
