### ISSUE TITLE
Salivary microbiome changes distinguish response to chemoradiotherapy in patients with oral cancer

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#307]
Salivary microbiome changes distinguish response to chemoradiotherapy in patients with oral cancer – Marcell Costa de Medeiros – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01677-w

**Comment by nityasinghal-14** [comment]
Can this paper be assigned to me for my third curation?

**Comment by nityasinghal-14** [comment]
Hey @SvetlanaUP , my curation is ready for review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1016 ready for review.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Updated condition, group names/descriptions, significance threshold, and LDA score for all experiments.
- Corrected the alpha diversity for experiments 2 and 3.
- Adjusted the signature sources for experiments 1 and 3, and curated the reported taxa.
- Altered the group arrangement for experiments 4 and 5, and curated the signatures accordingly.

Please kindly delete signature 2 of experiment 5 as it was not statistically significant.

I’m uncertain if there are better alternatives to the conditions I curated. I’ve posted this on the Slack channel and am awaiting feedback.

I will inform you when the curation is complete.

Thank you very much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1016 reviewed.

@Scholarpat we can update it once you have better solution, no problem.

**Comment by SvetlanaUP** [comment]
Ok I see on Slack you got an approval :) @Scholarpat

**Comment by Scholarpat** [comment]
Yes @SvetlanaUP, issue resolved. Thank you
