### ISSUE TITLE
Maternal microbiota communicates with the fetus through microbiota-derived extracellular vesicles

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#308]
Maternal microbiota communicates with the fetus through microbiota-derived extracellular vesicles – Anna Kaisanlaht – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01694-9

**Comment by Iam-Iman** [comment]
Hey @SvetlanaUP I see this issue has not been assigned, may I please curate it while waiting for my second contribution feedback. Thank you

**Comment by Iam-Iman** [comment]
@SvetlanaUP paper ready to review, https://bugsigdb.org/Study_1055

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP can i review this study?

**Comment by SvetlanaUP** [comment]
Sure @fiddyhamma, enjoy!

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP 

These are my observations:
- The Condition should not be Pregnancy but Extracellular vesicles
- Data transformation and statistical test were not entered correctly 
- Alpha diversity is not entered correctly 
- Signature description could be better
- Antibiotics was used but duration wasn't recorded specifically, it says during pregnancy and delivery. See Additional file 1, Table 1

Can I make changes to this curation?

**Comment by SvetlanaUP** [comment]
@fiddyhamma please do, thanks!

**Comment by fiddyhamma** [comment]
Hi @SvetlanaUP 
I've made necessary changes to this study, I await your feedback 😊

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1055 reviewed.
