### ISSUE TITLE
Household environment and animal fecal contamination are critical modifiers of the gut microbiome and resistome in young children from rural Nicaragua

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#310]
Household environment and animal fecal contamination are critical modifiers of the gut microbiome and resistome in young children from rural Nicaragua – Molly Mills – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01636-5

**Comment by Aeeshah1** [comment]
I am interested in curating this study. Can it be assigned to me please?

**Comment by Aeeshah1** [comment]
Hello, please I am done curating this article and it is ready for review. Here is the link: https://bugsigdb.org/Study_1062

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made:

- **Study design:** Changed from 'time series / longitudinal observational' to 'Cross-sectional'.
- **Added:** Sequencing type and data transformation.
- **Statistical test:** Changed from 'Kruskall-Wallis, PERMANOVA, Spearman Correlation' to 'LEfSe'.
- **Confounders:** Edited out initially curated confounders (LEfSe does not control for confounders).
- **Signature description:** Altered.
- **Taxonomy update:** Changed 'Ruminococcaceae' to its heterotypic synonym 'Oscillospiraceae' in signature 1 of experiment 1.
- **Additional experiment:** Curated additional experiment 2 (and signature 1) which is not displaying. I've reported the issue.

This curation is completed.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1062 reviewed.
