### ISSUE TITLE
Characteristics of the oral and gastric microbiome in patients with early-stage intramucosal esophageal squamous cell carcinoma 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#313]
Characteristics of the oral and gastric microbiome in patients with early-stage intramucosal esophageal squamous cell carcinoma – Han Chen – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-024-03233-4

**Comment by Buraah** [comment]
Hi @SvetlanaUP , I would love to curate this paper.

Thank you
Victoria.

**Comment by Buraah** [comment]
Hello @SvetlanaUP ,
I am done curating this paper and I would appreciate your review.

Link to study: https://bugsigdb.org/Study_1020

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP can I review this?

**Comment by SvetlanaUP** [comment]
Under review by @MyleeeA

**Comment by MyleeeA** [comment]
Hi @Buraah 
You this is an excellent curation and it made the review quite easy. 
Well done 

I have very few observations
1. **Group name and Group Definition**: I'm of the opinion that the group name should be written in full for the second experiment.
The group definition for both experiments can be rephrased, using the second experiment as an example it can appear this way _"Patients diagnosed with early-stage intramucosal esophageal squamous carcinoma (EIESC) who provided gastric biopsy samples."_ 
2. **MHT correction**: LEfSe doesn't support MHT although there are some exceptions and this paper doesn't say MHT was done for LEfSe but for some sort of Co-Occurence network using Spermans rank correlation _"A correlation matrix was developed by calculating the pairwise Spearman’s rank correlations in all EIESC saliva or gastric biopsy samples. A correlation between two microbes was considered statistically robust if Spearman’s correlation coefficient was > 0.6 and the p-value was < 0.01. To reduce the chances of obtaining falsepositive results, the p-values were adjusted using the Benjamini–Hochberg method"._ So I think the MHT should be NO.
3. **Antibiotic Exclusion**: I think 4 weeks works just fine for this.

Do let me know what you think about this observations.
Well done again for doing a great job

**Comment by Buraah** [comment]
Hi @MyleeeA 
Thank you so much for your review!
I'm starting to enjoy getting feedback 😊
Because now I have to go back to this paper and re-evaluate my prior decisions.

I agree with every point, I'm starting to understand the importance of a very descriptive group name.
Point 2 is new to me, thank you for pointing it out. I might have to go back to my previous curations to ensure they're in order.
And 4 weeks work fine for antibiotic exclusion.

Can I please ask you to make these changes for me? So it can be closed? I'm currently very occupied and won't be on my PC until Monday.
Thank you so much again!

**Comment by MyleeeA** [comment]
All corrections effected @Buraah.
If this is okay by you @SvetlanaUP then this article can be marked as reviewed. 

Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1020 reviewed.
