### ISSUE TITLE
Specific gastrointestinal microbiota profiles in Chinese Tan sheep are associated with lauric acid content in muscle

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#318]
Specific gastrointestinal microbiota profiles in Chinese Tan sheep are associated with lauric acid content in muscle – Zhen LI – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03079-2

**Comment by Preethigrace-7** [comment]
Hi @SvetlanaUP mam, Will u please assign me this paper to curate, I'm happy to contribute :)

**Comment by Preethigrace-7** [comment]
Thank u mam for assigning.

**Comment by nityasinghal-14** [comment]
Hello @Preethigrace-7, I see you have been assigned this curation. Would you be open to collaborating?
I'm looking forward to it, thank you.

**Comment by Preethigrace-7** [comment]
Hii @nityasinghal-14 , yes we can do it together, but we need to confirm it with @SvetlanaUP mam. I'm happy to work with you @nityasinghal-14

**Comment by SvetlanaUP** [comment]
@Preethigrace-7 @nityasinghal-14 enjoy your collaboration!

**Comment by nityasinghal-14** [comment]
Hey @Preethigrace-7, please provide your username on Slack so we can discuss this further. Thank you.

**Comment by Preethigrace-7** [comment]
It is Preethi grace Manthena, will catch u there @nityasinghal-14 :) 🤝

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP I noticed this study is not yet available on BugSigDB. Can I curate it?

**Comment by SvetlanaUP** [comment]
@Scholarpat sure!

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , this study is ready for review.
https://bugsigdb.org/Study_938

Thank you!
Scholastica Urua

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've reviewed this study and confirmed all the data curated. I've adjusted the signature description for clarity.
This curation is complete. Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_938 reviewed.
