### ISSUE TITLE
Alterations in gut microbiota and host transcriptome of patients with coronary artery disease

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#319]
Alterations in gut microbiota and host transcriptome of patients with coronary artery disease – Liuying Chen – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-03071-w

**Comment by Isioma20** [comment]
Hi. I'd love to be assigned to this study. Thank you!

**Comment by Rahila-me** [comment]
@SvetlanaUP I would love to curate this. Here is my second curation that has be marked for review:
https://bugsigdb.org/Study_1009

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
Hi 
This study is ready for review 
https://bugsigdb.org/Study_1058
 I really enjoyed curating this particular study.
I'd like to ask if it's okay to open new issues, found some articles that I'm quite certain fall within the scope of BugSigDB. Thank you

**Comment by SvetlanaUP** [comment]
Hi @Isioma20, please do not add new issues. You could go to unfinished curations of your colleagues and support them, thanks. Team work is appreciated.

**Comment by Isioma20** [comment]
Alright @SvetlanaUP . Thank you

**Comment by Scholarpat** [comment]
Hi @Isioma20,

You've a nice job capturing all the curatable details. Well done!
I updated some of the taxa highlighted orange to resolve them;

"lachnospiraceae_NK4A136_group" to "Lachnospiraceae bacterium NK4A136"		  
"Eubacterium_hallii_group" to "Anaerobutyricum hallii"

This curation is complete @SvetlanaUP.
Thank you!

**Comment by Isioma20** [comment]
Thank you and well-done @Scholarpat

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1058 reviewed.
