### ISSUE TITLE
Fecal Metabolomic Signatures in Colorectal Adenoma Patients Are Associated with Gut Microbiota and Early Events of Colorectal Cancer Pathogenesis

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#32]
https://pubmed.ncbi.nlm.nih.gov/32071266/

**Comment by Susu-spec** [comment]
I'd like to curate this article
Name: Suwaiba

**Comment by ftzohra22** [comment]
@Susu-spec assigned

**Comment by ftzohra22** [comment]
@Susu-spec thank you. We have more papers on the list. Please feel free to claim another article. @lwaldron closing issue since paper does not contain signatures.

**Comment by Susu-spec** [comment]
Alright!
