### ISSUE TITLE
Effects of OsomeFood Clean Label plant-based meals on the gut microbiome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#321]
Effects of OsomeFood Clean Label plant-based meals on the gut microbiome – Dwiyanto Jacky – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-02822-z

**Comment by TitilayoMG** [comment]
@SvetlanaUP I'd like to curate this paper

Ganiyu Modinat

**Comment by SvetlanaUP** [comment]
@TitilayoMG please do finish your previously assigned curation. https://github.com/waldronlab/BugSigDBcuration/issues/283

**Comment by TitilayoMG** [comment]
Thank you @SvetlanaUP 
I'll start working on this then

**Comment by SvetlanaUP** [comment]
@AleruDivine you could work on this paper, interested?

**Comment by AleruDivine** [comment]
Yes @SvetlanaUP, I would love to work on this.

**Comment by AleruDivine** [comment]
Thank you so much for this. 
And I apologize for the previous misunderstanding. It was not at all intentional.

**Comment by AleruDivine** [comment]
Hi @SvetlanaUP, @TitilayoMG has already almost finished curating this study. Now I am very confused.

**Comment by SvetlanaUP** [comment]
This paper is now assigned to @TitilayoMG 

BIG apologies to @AleruDivine

**Comment by SvetlanaUP** [comment]
@TitilayoMG @AleruDivine 
Online communication and working remotely in a team can be challenging. Thus, we have to have **concise and precise communication**, extra patience and understanding. Thank you.

**Comment by AleruDivine** [comment]
I totally understand @SvetlanaUP 
Thank you so much for the clarification 🙏

**Comment by TitilayoMG** [comment]
PLEASE I do apologize for the confusion  

Thank you so much for being patient @AleruDivine 
Thank you so much for being kind @SvetlanaUP

**Comment by TitilayoMG** [comment]
Thank you @Scholarpat and @isioma20 for reviewing my curation

**Comment by TitilayoMG** [comment]
Hello @SvetlanaUP I've finished curating this paper, I'll like to put it up for review. 
Link to the study - https://bugsigdb.org/Study_1059

Thank you so much

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

In this study, I changed condition from 'Health study participation' to 'Diet'. This curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1059 reviewed.
