### ISSUE TITLE
Irinotecan-gut microbiota interactions and the capability of probiotics to mitigate Irinotecan-associated toxicity

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#322]
Irinotecan-gut microbiota interactions and the capability of probiotics to mitigate Irinotecan-associated toxicity – Marwa S. Mahdy – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-023-02791-3

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,

Can this be assigned to me please, I'll love to curate it. 🙏

Scholastica Urua
Thank you!

**Comment by SvetlanaUP** [comment]
@Scholarpat please take a look this paper https://github.com/waldronlab/BugSigDBcuration/issues/98

**Comment by fetle1** [comment]
Can I be assigned to this @SvetlanaUP

**Comment by samreen-19** [comment]
@SvetlanaUP I would like to curate this paper

**Comment by nityasinghal-14** [comment]
Hello @fetle1 , I see you have been assigned this curation. Would you be open to collaborating?
I'm looking forward to it, thank you.

**Comment by fetle1** [comment]
Yes that would be lovely @nityasinghal-14

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_1064

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1064 reviewed.
