### ISSUE TITLE
Dysbiosis of skin microbiome and gut microbiome in melanoma progression 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#324]
Dysbiosis of skin microbiome and gut microbiome in melanoma progression – Chahrazed Mekadim – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-022-02458-5

**Comment by jumokeadeoyo** [comment]
Hi, I would love to curate this paper

**Comment by nityasinghal-14** [comment]
Hello @jumokeadeoyo , I see you have been assigned this curation. Would you be open to collaborating?
I'm looking forward to it, thank you.

**Comment by snehuman** [comment]
can I be assigned this?

**Comment by snehuman** [comment]
I have tried to curate the complete study as per my knowledge, I would like you to review it. Thank you.
https://bugsigdb.org/Study_991

**Comment by SvetlanaUP** [comment]
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0.5 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0.5 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0.5 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0.5 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 9.5 |

- not defined study design
- incorrect use of NCBI taxonomy
- not identified correct sources of signatures nor experiments
- and more errors to correct

**Comment by SvetlanaUP** [comment]
[Isioma20](https://github.com/Isioma20) you could help out here in correction of this incomplete curation.

**Comment by Isioma20** [comment]
Would work it and make all the necessary corrections per the feedback. Thank you!

**Comment by Isioma20** [comment]
the changes I made to this curation include
-changed the study design
-added all the relevant experiments including those with significant alpha diversity results
-identifies signature sources and curated them
