### ISSUE TITLE
Comparison of fecal and oral collection methods for studies of the human microbiota in two Iranian cohorts

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#325]
Comparison of fecal and oral collection methods for studies of the human microbiota in two Iranian cohorts – Zeni Wu – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02387-9

**Comment by nwakaegovincent26** [comment]
hello @SvetlanaUP can you assign me this paper for curation while i wait for the review of my second contribution, thanks

**Comment by nwakaegovincent26** [comment]
thank you @SvetlanaUP

**Comment by nwakaegovincent26** [comment]
hi @SvetlanaUP kindly review my paper , thanks.  https://bugsigdb.org/Study_1056

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I've made to this curation:

- **Study design**: Changed from case-control to prospective cohort.
- **Curated condition**: Added condition for all the experiments which was not initially curated.
- **Sequencing type**: Changed from PCR to 16S (V4).
- **Statistical test**: Changed from Spearman Correlation to Wilcoxon.
- **Significance threshold**: Changed from 0.05 to 0.01.
- **Alpha diversity**: Added observed species (richness).
- **Matched-on**: Removed "matched-on" which was initially curated.
- **Signatures**: Completed the curation of signatures that were not fully curated.
- **Additional experiments**: Curated experiments 3 and 4 and signatures, which were not initially curated.

This curation is now complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1056 reviewed.
