### ISSUE TITLE
Disturbed microbial ecology in Alzheimer’s disease: evidence from the gut microbiota and fecal metabolome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#326]
Disturbed microbial ecology in Alzheimer’s disease: evidence from the gut microbiota and fecal metabolome – Jianxiong Xi – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02286-z

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,

I have completed my previous curation, but I have not yet submitted it for review. I am awaiting feedback from fellow contributors to collaborate on my curation. Could I please claim this issue for curation? I would love the opportunity to work on it.


Scholastica Urua
Thank you!

**Comment by SvetlanaUP** [comment]
@Scholarpat take your time for your current curation. Let's be fair and give other applicants the same opportunity.

**Comment by Scholarpat** [comment]
Thank you for your response @SvetlanaUP 🙏

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP, Happy Friday!

Please I'll love to submit this curation for a review and feedback.
https://bugsigdb.org/Study_1052

Scholastica Urua
Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

After reviewing this curation, I've altered the signature description for clarity. The curation is complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1052 reviewed.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1052 reviewed.
