### ISSUE TITLE
Gut microbiota: effect of pubertal status 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#327]
Gut microbiota: effect of pubertal status – Xin Yuan – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-02021-0

**Comment by Junie06** [comment]
@SvetlanaUP Please assign this to me. Isoken Ibizugbe

**Comment by nityasinghal-14** [comment]
Hello @Junie06 , I see you have been assigned this curation. Would you be open to collaborating?
I'm looking forward to it, thank you.

**Comment by Junie06** [comment]
@nityasinghal-14 yes i am interested

**Comment by nityasinghal-14** [comment]
That's great. Please let me know your Slack username so we can connect and work together. Mine is Nitya Singhal.
Thank you.

**Comment by nityasinghal-14** [comment]
Just texted you on Slack. Please share your study on chat over there. Thank you

**Comment by Junie06** [comment]
Please tag for review @SvetlanaUP thanks.

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_1075

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,
One of the alpha diversity measure, richness was not curated. I've included this and the curation is now complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1075 reviewed.
