### ISSUE TITLE
Quantitative metagenomics reveals unique gut microbiome biomarkers in ankylosing spondylitis

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#33]
https://pubmed.ncbi.nlm.nih.gov/28750650/

**Comment by joy-commits** [comment]
Hello @lwaldron,
Please can this study be assigned to me?
Thank you

**Comment by joy-commits** [comment]
Hello @lwaldron @ftzohra22 
Please, kindly review
https://bugsigdb.org/Study_638
Thank you

**Comment by cmirzayi** [comment]
@joy-commits Good job. However, I think you missed that there is a supplemental table 4 from which you can curate the differential abundance results. I have scored your curation below but please consider inputting the results presented in table S4 to complete the curation.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 0 (1 month)
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1 (curated as figure 1A but are coming from text and table S4)
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 (many missing that are present in table S4)
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 19

**Comment by joy-commits** [comment]
Thank you for the review @cmirzayi 
I'd effect the changes as soon as possible.

**Comment by joy-commits** [comment]
Hello @cmirzayi,
I have effected the changes.
Please, kindly review. Thank you.

**Comment by cmirzayi** [comment]
Hi @joy-commits this was a good update. There were a few taxa still missing so I handled them myself. This curation is complete.
