### ISSUE TITLE
Changes in the vaginal microbiota associated with primary ovarian failure

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#330]
Changes in the vaginal microbiota associated with primary ovarian failure – Juan Wang – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-01918-0

**Comment by Druscillaa** [comment]
@SvetlanaUP please assign me this paper while I wait for review

**Comment by Druscillaa** [comment]
Hey @SvetlanaUP my study is ready for review

https://bugsigdb.org/Study_1067

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

The curation has been reviewed and is now complete.

Thank you!
