### ISSUE TITLE
Dysbiosis of saliva microbiome in patients with oral lichen planus

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#331]
Dysbiosis of saliva microbiome in patients with oral lichen planus – Fei Yan Yu – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-01733-7

**Comment by fiddyhamma** [comment]
Hello @SvetlanaUP
My second contribution is up for review and while I wait, I'd love to be assigned this paper.
Peace Daniel

**Comment by omojokunoluwatomisin10** [comment]
@fiddyhamma, are you still working on your study or did you forget to ask mentor for a review

**Comment by fiddyhamma** [comment]
Hi @omojokunoluwatomisin10 
I'm still working on this, thanks

**Comment by fiddyhamma** [comment]
Hello @SvetlanaUP 
I'm done with this curation and it's ready for review 
https://bugsigdb.org/Study_1063

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

In this curation, I changed group 1 sample size for experiment 1 from 10 to 20. I've also alter the signature descriptions for all the experiments with signature for clarity.

This is a good curation, @fiddyhamma  well done 👏 .

This curation is complete. Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1063 reviewed.
