### ISSUE TITLE
Profiling the urinary microbiome in men with calcium-based kidney stones

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#332]
Profiling the urinary microbiome in men with calcium-based kidney stones – Jing Xie – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-01734-6

**Comment by Buraah** [comment]
Hi @SvetlanaUP ,
Can I please be assigned to this paper, I would love to curate it.

Thank you
Victoria.

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
I am done curating this study and it is ready for review.

Thank you.
Link to study: https://bugsigdb.org/Study_1053

**Comment by Peacesandy** [comment]
Awesome Curation @Buraah . Thank you for all your hard work 🎉
@SvetlanaUP  https://bugsigdb.org/Study_1053  Reviewed ✔

**Comment by Buraah** [comment]
Thank you! @Peacesandy

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1053 reviewed.
