### ISSUE TITLE
Dysbiosis of gut microbiota and its correlation with dysregulation of cytokines in psoriasis patients 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#333]
Dysbiosis of gut microbiota and its correlation with dysregulation of cytokines in psoriasis patients – Xinyue Zhang – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02125-1

**Comment by Praiseagbetuyi** [comment]
Hi, @SvetlanaUP 

Can you assign this paper to me? I would love to curate it.

**Comment by kwennB** [comment]
Hello @Praiseagbetuyi I see you have been assigned this curation, would you be open to collaborating? 

Looking forward to it, thank you.

**Comment by Praiseagbetuyi** [comment]
@kwennB We can collaborate in curating the study.

Looking forward to working together.

**Comment by Praiseagbetuyi** [comment]
https://bugsigdb.org/Study_1071

**Comment by kwennB** [comment]
@Praiseagbetuyi Awesome. I have reached out on slack and started on the study.

**Comment by Praiseagbetuyi** [comment]
Hello, @SvetlanaUP 

This study is ready to be reviewed

Thank you.

**Comment by SvetlanaUP** [comment]
Ready for review https://bugsigdb.org/Study_1071

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This curation has been reviewed and I've updated a few data.
It is now completed.

Thank you!
