### ISSUE TITLE
Alterations in the intestinal microbiome and mental health status of workers in an underground tunnel environment

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#334]
Alterations in the intestinal microbiome and mental health status of workers in an underground tunnel environment – Zhen-Hua Lu – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-02056-3

**Comment by FlourishRalph** [comment]
Hi! @SvetlanaUP 
Can this be assigned to me? I'll like to work on it.
Also, my second curation has already been submitted and tagged by you as 'ready for review'.

**Comment by FlourishRalph** [comment]
Hi @SvetlanaUP
I’m done curating this paper and it’s ready for review.

Here is the link:

https://bugsigdb.org/Study_1045
 Thank you!

**Comment by Scholarpat** [comment]
Nicely curated @FlourishRalph, well done 👏 

@SvetlanaUP this curation has been reviewed and its complete.
Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1045 reviewed.
