### ISSUE TITLE
Profiles of subgingival microbiomes and gingival crevicular metabolic signatures in patients with amnestic mild cognitive impairment and Alzheimer's disease 

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#335]
Profiles of subgingival microbiomes and gingival crevicular metabolic signatures in patients with amnestic mild cognitive impairment and Alzheimer's disease – Che Qiu – Alzheimers Res Ther
https://alzres.biomedcentral.com/articles/10.1186/s13195-024-01402-1

**Comment by omojokunoluwatomisin10** [comment]
can i curate this study

**Comment by Tech-neophyte** [comment]
Hi! Can you please assign this to me, I am waiting for review in my last curated paper and have also asked for peer review ..

**Comment by Tech-neophyte** [comment]
Hi! Thanks for assigning this to me. I would like to request review for the curation : https://bugsigdb.org/Study_1061
Thank you!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This study presents abundant signatures using LEfSe, one against all. I've curated the signatures in each group.

Please kindly delete:
- Signature 2 of experiment 1
- Signature 2 of experiment 2

This curation is now ready. Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1061 reviewed.

**Comment by SvetlanaUP** [comment]
@Scholarpat Signature 2 of experiment 2 did not exist.

**Comment by Scholarpat** [comment]
My bad, I meant signature 2 of experiment 3.
Thank you
