### ISSUE TITLE
Breast cancer but not the menopausal status is associated with small changes of the gut microbiota

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#336]
Breast cancer but not the menopausal status is associated with small changes of the gut microbiota – Natalia Zeber-Lubecka – Frontiers in Oncology
https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2024.1279132/full

**Comment by keamybams** [comment]
@SvetlanaUP  I would love to curate this. Thanks.

**Comment by omojokunoluwatomisin10** [comment]
@keamybams, Are you still working on your curation or did you forget to ask for review from mentors

**Comment by keamybams** [comment]
Hello @SvetlanaUP this curation is ready for review https://bugsigdb.org/Study_1065 Thanks.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

For this experiment, I've made a few changes:

- Altered the antibiotics exclusion criteria to include only the time frame.
- Curated only taxa that were significantly abundant in the study.

Signature 2 of experiment 1 is not significant (p > 0.05) and should not be included.
Additionally, the signatures for experiment 5 are not significant. Therefore, the study should have only two experiments:
- Experiment 1 with signature 1
- Experiment 2 with signatures 1 and 2

Please kindly delete the others.

For the statistical test, a linear model for differential abundance (LINDA) was used. Linear regression has been curated. Is this correct please?

**Comment by SvetlanaUP** [comment]
Correct @Scholarpat

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1065 reviewed.
