### ISSUE TITLE
Vaginal Microbiome in Pregnant Women with and without Short Cervix

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#338]
Vaginal Microbiome in Pregnant Women with and without Short Cervix - Angela Silvano - MDPI
 https://www.mdpi.com/2072-6643/15/9/2173

**Comment by Nana-Habiba** [comment]
@SvetlanaUP @cmirzayi Please i created this issue and i have also curated it. Please assign it to me and also make it as needs review. 
Here is Link: https://bugsigdb.org/Study_889

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

Please note that several applicants already asked publicly in the bugsigdb Slack channel if they can open the issues with their suggested papers but we said to instead adding more new issues to help **closing already open issues** where other applicants are stuck. Right now adding new issues is on hold.

**Comment by Scholarpat** [comment]
Well done on your curation @Nana-Habiba. I've made a few changes here;

- Only LEfSe was used for differential abundance so I excluded Wald test that was also curated.
- Only one signature was initially curated, I've added the second (decreased) signature.

This curation is now completed @SvetlanaUP.

Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_889 reviewed.
