### ISSUE TITLE
Oral microbiome and preterm birth

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#339]
Oral microbiome and preterm birth - Vidmar Šimic M - frontiers
https://www.frontiersin.org/articles/10.3389/fmed.2023.1177990/full

**Comment by Nana-Habiba** [comment]
@SvetlanaUP @cmirzayi Please i created this issue and i have also curated it. Please assign it to me and also make it as needs review. 
Link: https://bugsigdb.org/Study_890

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

**Comment by Scholarpat** [comment]
This also have a signature (2) that is not displaying. I've just reported this.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_890 reviewed.
