### ISSUE TITLE
Whole metagenome profiling reveals skin microbiome-dependent susceptibility to atopic dermatitis flare

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#34]
https://pubmed.ncbi.nlm.nih.gov/27562258/ This is behind a paywall so here is the [PDF](https://github.com/waldronlab/BugSigDBcuration/files/10951197/chng2016.pdf).

**Comment by joy-commits** [comment]
Hello @lwaldron,
Please, can I be assigned this study?
Thank you

**Comment by lwaldron** [comment]
Yes!

**Comment by lwaldron** [comment]
Oh but I just saw you've already completed a second assignment at #33 - please wait on this until we've reviewed that first.

**Comment by joy-commits** [comment]
Noted!
Thank you for assigning to the study to me though

**Comment by joy-commits** [comment]
Hello @lwaldron @cmirzayi
I'm done with this study: https://bugsigdb.org/Study_725
Please kindly review
Thank you

**Comment by lwaldron** [comment]
Nice job on a challenging study, see comments below. 

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1 - great job of this, numerous experiments presented in supplemental information.
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1 (Skin epidermis http://purl.obolibrary.org/obo/UBERON_0001003 may be a better choice but I don't think skin epithelium is wrong. Any reason for your choice?)
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1 (although the following sentence in Methods implies exclusion of current antibiotics usage, although it's not clear if that includes other types of antibiotics not related to skin care: 
> Participants were allowed to maintain a healthy skin care regimen, and only restricted for antibiotics, based on prior observations that discontinuing medications and emollients for AD patients frequently leads to dysbiosis similar to what is seen in AD flares")
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2 - the paper is vague about which results are from WMS and which from 16S, since they did both. In some places they report results being from WMS, although it's unclear why they are at genus and not species level as WMS can provide.
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 0 - not filled out, but FDR was applied
12. Correctly recorded matched on factors (1 point): 0 - matched on age and sex, I would skip ethnic group since all are listed as the same ethnic group. 
> The three groups were approximately matched according to mean age (Control: 24.1; Case: 23.1; SPT+: 23.0), gender (Control: 8 males, 7 females; Case: 8 males, 12 females; SPT+: 3 males, 2 females) and ethnicity (Chinese) (Supplementary Table 2). 

13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 - missing comparisons of diversity that were done, Shannon's diversity was reported in Figure 5B
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 2
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0 - Experiment 1 Signature 2 missing Deinococcus. In Signature 1, Veillonella genus entered as species Veillonella parvula. 
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 18

**Comment by lwaldron** [comment]
Also, in Supplemental Figure 6, only the genera with asterisks in the bar plots should be recorded as differentially abundant.

**Comment by joy-commits** [comment]
Thank you for the review, Levi
I'll make the appropriate changes

**Comment by lwaldron** [comment]
I think I made most of them already, but please double-check!

**Comment by joy-commits** [comment]
@lwaldron, for 14, I indicated Shannon's diversity for Experiment 1, as that was the only information provided

**Comment by lwaldron** [comment]
The diversity measures were blank when I reviewed; I added Shannon's Diversity as seen in [this change](https://bugsigdb.org/w/index.php?title=Study_725%2FExperiment_1&type=revision&diff=108597&oldid=108596) in the history.

**Comment by lwaldron** [comment]
I think the minor issues are corrected now and this issue can be closed. Excellent work @joy-commits!
