### ISSUE TITLE
Profiling the Urinary Microbiota in Male Patients With Bladder Cancer in China

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#341]
Profiling the Urinary Microbiota in Male Patients With Bladder Cancer in China - Peng Wu - frontiers
https://www.frontiersin.org/articles/10.3389/fcimb.2018.00167/full

**Comment by Nana-Habiba** [comment]
@SvetlanaUP @cmirzayi Please i created this issue and i have also curated it. Please assign it to me and also make it as needs review. 
Here is Link: https://bugsigdb.org/Study_898

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

**Comment by AleruDivine** [comment]
Hello @SvetlanaUP, I also have a study that I am currently curating. @cmirzayi said we could go ahead last weeks office hours. Should I open an issue for it just as @Nana-Habiba did? 
Thank you!

**Comment by SvetlanaUP** [comment]
@AleruDivine please see my messages here https://github.com/waldronlab/BugSigDBcuration/issues/338

**Comment by AleruDivine** [comment]
Seen and noted. Thank you so much!

I have helped complete some curations but I also reached out to a couple of other applicants regarding their unfinished studies and I did not hear back from them and I cannot work on their studies without their permission. I have no idea what to do in this case. I can't tell if they are still interested or not. I am very available to help if there is any.

Thank you so much!

**Comment by SvetlanaUP** [comment]
@AleruDivine all noted. You could check if reviewed issues are corrected in bugsigdb, if not claim it for correction and/or collaborate with the main curator.

**Comment by AleruDivine** [comment]
Thank you so much for the suggestion. I will check out the reviewed issues again.😊

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Please kindly delete experiments 4 and 5 of this curation; https://bugsigdb.org/Study_898.
There are no signatures for these experiments and the alpha diversity indices are not significant as well.

I've reviewed the curation and altered some fields like group 1 definition, source description. I've also changed the conditions for experiment 2 and 3 from 'bladder carcinoma' to '[Disease recurrence](https://bugsigdb.org/Disease_recurrence)' and [Disease progression measurement](https://bugsigdb.org/Disease_progression_measurement) respectively, based on the contrasting groups in the experiments.

This curation is ready for your review. Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_898 reviewed.
