### ISSUE TITLE
Comprehensive profiles and diagnostic value of menopausal-specific gut microbiota in premenopausal breast cancer

### ISSUE THREAD

**Issue by Rahila-me** [waldronlab/BugSigDBcuration#343]
Comprehensive profiles and diagnostic value of menopausal-specific gut microbiota in premenopausal breast cancer - Hou MF - EMM
https://www.nature.com/articles/s12276-021-00686-9

**Comment by Rahila-me** [comment]
@SvetlanaUP @Omabekee Please assign this paper to me. Mark as needs review
Link: https://bugsigdb.org/Study_915

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I've reviewed and made a couple of changes to this curation:

- Included the age-matching of female controls
- Curated missing experiments and signatures
- The study has 4 experiments with two signatures each. Experiments 3 and 4 are not displaying, and I've reported this issue.

This curation is ready for your review. Thank you.

Well done @Rahila-me!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_915 reviewed.
