### ISSUE TITLE
Clinical Significance of Composition and Functional Diversity of the Vaginal Microbiome in Recurrent Vaginitis

### ISSUE THREAD

**Issue by Rahila-me** [waldronlab/BugSigDBcuration#344]
Clinical Significance of Composition and Functional Diversity of the Vaginal Microbiome in Recurrent Vaginitis - Kim MJ, - frontiers
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2022.851670/full

**Comment by SvetlanaUP** [comment]
Noted as a self-assigned curation.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes and additions I've made to this curation:

- Curated the appropriate signature source for experiment 1.
- Curated additional experiments 2, 3, and 4, each with one signature.

These newly curated experiments are not displaying, and I've reported the issue.

This curation is now complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_916 reviewed.
