### ISSUE TITLE
Maternal smoking during pregnancy increases the risk of gut microbiome-associated childhood overweight and obesity

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#348]
Maternal smoking during pregnancy increases the risk of gut microbiome-associated childhood overweight and obesity – Ye Peng – Gut Microbes
https://www.tandfonline.com/doi/full/10.1080/19490976.2024.2323234

**Comment by omojokunoluwatomisin10** [comment]
GOODDAY @SvetlanaUP, can i be assigned to this study

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 we are first closing already started curations.

**Comment by omojokunoluwatomisin10** [comment]
kindly assign me to this study

**Comment by omojokunoluwatomisin10** [comment]
This is ready for review 
https://bugsigdb.org/Study_1021

**Comment by omojokunoluwatomisin10** [comment]
This is ready for review 
https://bugsigdb.org/Study_1021

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made in both experiments of this curation:

- Changed the location of subjects from China to Canada.
- Altered the definition of Group 1.
- Included the default LDA score of 2.
- Altered the signature description and resolved some taxa.

The curation is now complete. Thank you!

**Comment by SvetlanaUP** [comment]
@omojokunoluwatomisin10 about the study cohort: https://childstudy.ca/for-researchers/cohort-profile/
Although the first author's location was China :) the cohort is in Canada. Good job!

https://bugsigdb.org/Study_1021 reviewed.
