### ISSUE TITLE
Immunoregulatory role of the gut microbiota in inflammatory depression

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#349]
Immunoregulatory role of the gut microbiota in inflammatory depression – Penghong Liu – Nature Communications
https://www.nature.com/articles/s41467-024-47273-w

**Comment by Aeeshah1** [comment]
Please assign this issue to me

**Comment by SvetlanaUP** [comment]
Please see my message here https://community-bioc.slack.com/archives/C04RATV9VCY/p1712871755335179?thread_ts=1712820398.728959&cid=C04RATV9VCY

**Comment by Rahila-me** [comment]
@SvetlanaUP may i curate this paper. Thank you

**Comment by Rahila-me** [comment]
@SvetlanaUP Seen, thank you

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Unfortunately, this curation had a lot of data curated incorrectly. Figures 3(A1), 4(D3), and 6(C) were not grouped properly. Additionally, signature 2 was not curated for experiments 1 and 5. I've updated these.

I’ve also curated 3 additional experiments and 1 signature each, which are not displaying. I’ve reported this issue.

Please kindly delete the following signatures:
- Signature 2 of experiment 7
- Signature 2 of experiment 8
- Signature 2 of experiment 9
- Signature 2 of experiment 10

This curation is now complete. Thank you.
