### ISSUE TITLE
Cigarette smoking and oral microbiota in low-income and African-American populations

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#35]
https://pubmed.ncbi.nlm.nih.gov/31563898/

**Comment by chioma-grace** [comment]
Hello,
I am Chioma Grace, I want to work on this publication. I hope to provide detailed contribution.
Kind Regards.

**Comment by Nnadichioma** [comment]
Please can you assign this topic to me
Name: Nnadi Chioma

**Comment by Nnadichioma** [comment]
Thanks

**Comment by Nnadichioma** [comment]
Please review this. Thanks

**Comment by Nnadichioma** [comment]
This is the link to my study, by the way, waiting to be reviewed
https://bugsigdb.org/Study_530

**Comment by cmirzayi** [comment]
Hi @Nnadichioma. Unfortunately this curation is incomplete. There should be three experiments: current smokers vs. never smokers, current smokers vs. former smokers, and former smokers vs. never smokers. For each experiment there should be an increased and decreased signature. Then you will curate the findings of tables 2, 3, and 4 accordingly. They had lots of significant results so this will take a substantial amount of effort to complete. Please ask questions along the way as this is a complex paper.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1 
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point): Not scored
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Identified MHT correction (1 point):
12. Correctly recorded matched on factors (1 point):
13. Entered correct number of statistical tests per experiment (1 point):
14. All diversity measures identified (1 point):
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points):
17. Abundance direction correctly selected (1 point):
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 24 points):

**Comment by Nnadichioma** [comment]
Thank you @cmirzayi
I will work on it and make the necessary corrections
Thank you

**Comment by Nnadichioma** [comment]
Please review this. Thanks

**Comment by Nnadichioma** [comment]
@cmirzayi 
I have made the necessary corrections. Please review this. Thanks.
https://bugsigdb.org/Study_530

**Comment by atrayees** [comment]
Corrected and included the missing taxa curated into signatures of experiments 1, 2 and 3 from tables 2, 3 and 4.

**Comment by lwaldron** [comment]
Thanks @atrayees, as with all the studies you've reviewed you can go ahead and mark them as "Reviewed" in bugsigdb.org and close the issue.

**Comment by atrayees** [comment]
Yes, I'm currently marking all of the reviewed studies on bugsigdb.org, but I'm facing difficulties closing the issue. Perhaps only collaborators on the github repo can close issues, so could you please add me as a collaborator?
