### ISSUE TITLE
Social isolation induces intestinal barrier disorder and imbalances gut microbiota in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#351]
Social isolation induces intestinal barrier disorder and imbalances gut microbiota in mice – Yue Wang – Neuroscience Letters
https://www.sciencedirect.com/science/article/pii/S0304394024000910

**Comment by BarakatAA** [comment]
Thank you! @SvetlanaUP 

The paper is inaccessible. Can I get a link to the PDF as well as all supplementary materials? 

Thank you

**Comment by SvetlanaUP** [comment]
Here you go! @BarakatAA 
[Uploading 1-s2.0-S0304394024000910-main.pdf…]()

**Comment by BarakatAA** [comment]
Hi @SvetlanaUP this study is now ready for review, thank you!

https://bugsigdb.org/Study_947

**Comment by Peacesandy** [comment]
Hi @BarakatAA this is an excellent review and I've made all the necessary corrections.
Thank you so much 🎉

@SvetlanaUP reviewed and corrected.

**Comment by SvetlanaUP** [comment]
Thanks @Peacesandy and @BarakatAA!
