### ISSUE TITLE
Characterization of oral bacterial and fungal microbiome in recovered COVID-19 patients

### ISSUE THREAD

**Issue by fiddyhamma** [waldronlab/BugSigDBcuration#352]
Characterization of oral bacterial and fungal microbiome in recovered COVID-19 patients Nana Wei 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10166687/

**Comment by fiddyhamma** [comment]
I found this study while researching and curating on oral lichen planus, looking forward to the curation 😊

**Comment by Junie06** [comment]
Can I be assigned to curate this paper @SvetlanaUP 
My name is Isoken Ibizugbe

**Comment by Scholarpat** [comment]
Hello @Junie06 

Hope you're doing well. I noticed this [curation](https://bugsigdb.org/Study_1040) is available on BugSigDB under 'Studies without signatures'. Are you still working on it or do you need help completing it?

Kindly awaiting your response.

Best Regards
Scholastica Urua

**Comment by Buraah** [comment]
Hi @SvetlanaUP, @Scholarpat 
Can I complete and review this curation?

**Comment by SvetlanaUP** [comment]
@Buraah Sure! https://bugsigdb.org/Study_1040 is in your hands now :)

**Comment by Buraah** [comment]
Thank you! @SvetlanaUP

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I am done completing and reviewing this study.

Here are the things I changed and why;
1. Statistical test
  * I changed the statistical test from t-test and Mann-Whitney to Lefse. Under 'Statistical analysis' and Phylogenetic profiles of oral bacteria in recovered patients with COVID-19'. The study explains the use of Lefse to identify bacteria that differed between the groups

2. Condition
  * I changed the condition from 'COVID-19' to 'Microbiome measurement'. The study compared the oral bacterial and fungal microbiomes between recovered COVID-19 patients and healthy controls.

3. MHT Correction
  * I changed the MHT correction to 'yes'. The discussion under 'Statistical analysis' explained the correction through FDR.
 
4. Signatures
* I added signatures 1 and 2 from Figure 3a and Figure 6a of the study.

5. Group names
* I changed the Group 0 and Group 1 names from HCs and RPs to 'HCs (Healthy Controls)' and 'RPs (Recovered Patients)' to make them more descriptive.

The other curated data are in order. Thank you.

**Comment by SvetlanaUP** [comment]
Excellent review and corrections, @Buraah!  

https://bugsigdb.org/Study_1040 is reviewed.
