### ISSUE TITLE
Gut microbiome diversity is an independent predictor of survival in cervical cancer patients receiving chemoradiation

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#356]
Gut microbiome diversity is an independent predictor of survival in cervical cancer patients receiving chemoradiation - Travis T. Sims - nature
https://www.nature.com/articles/s42003-021-01741-x?fromPaywallRec=false

**Comment by Scholarpat** [comment]
Hello @Nana-Habiba , this study already exist on BugSigDB 
https://bugsigdb.org/Study_677

Just thought to add this here so someone doesn't request for it.

**Comment by Nana-Habiba** [comment]
@Scholarpat Thank you, @SvetlanaUP please can you close this open issue. or delete it. A mistake from my own end

**Comment by SvetlanaUP** [comment]
This study is already curated.
