### ISSUE TITLE
Dysbiosis of the Saliva Microbiome in Patients With Polycystic Ovary Syndrome

### ISSUE THREAD

**Issue by Buraah** [waldronlab/BugSigDBcuration#358]
Dysbiosis of the Saliva Microbiome in Patients With Polycystic Ovary Syndrome
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7921782/

**Comment by Buraah** [comment]
I chose this paper because it talks about PCOS. My mom, my sisters, and my best friend all have PCOS...So it is a very fascinating topic for me and I enjoy digging up information about it.
PCOS also seems to be a common hormonal issue that affects women these days and I believe anybody curating this will have a great time.

**Comment by Isioma20** [comment]
Hello. I'd like to be assigned this article. Looks very interesting.

**Comment by Isioma20** [comment]
Thank you!

**Comment by Isioma20** [comment]
This article was curated at https://bugsigdb.org/Study_964 and is ready for review. Thank you

**Comment by Buraah** [comment]
Hello @SvetlanaUP,
Can I ahead and review this curation?

**Comment by SvetlanaUP** [comment]
@Buraah assigned as a reviewer.

**Comment by Buraah** [comment]
Hi @Isioma20 
Thank you for curating this study!
It looks well put together and accurate to me.

My only suggestion is to change "metabolic factors" to "metabolic syndrome" under the Matched-on factors. They are similar, and "metabolic syndrome" is on the list of allowed values. Well done

**Comment by Buraah** [comment]
@SvetlanaUP 
I am done reviewing this curation.

**Comment by SvetlanaUP** [comment]
Thanks @Buraah! @Isioma20 please do let me know when you correct your curation. Thanks!

**Comment by Isioma20** [comment]
Sorry for the very late reply. Thank you!@Buraah. I would correct and revert here @SvetlanaUP

**Comment by Isioma20** [comment]
I have made the suggested changes to the curation. I believe it now readuy to be reviewed Thanks!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_964 is reviewed.
