### ISSUE TITLE
Intestinal microbiota influences clinical outcome and side effects of early breast cancer treatment

### ISSUE THREAD

**Issue by Rahila-me** [waldronlab/BugSigDBcuration#359]
Intestinal microbiota influences clinical outcome and side effects of early breast cancer treatment - Safae Terrisse - nature
https://www.nature.com/articles/s41418-021-00784-1

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to curate this. Please assign it to me.
Thank you

Scholastica Urua

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , thank you for assigning this issue to me. It is now ready for review.
https://bugsigdb.org/Study_963

Best regards,
Scholastica Urua

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP, can I provide a slow review to this curation?
Also, this might be better on the slack channel but i just want to know if there are any tips on how to be faster and more productive with the reviews.

**Comment by SvetlanaUP** [comment]
Sure, @MyleeeA! Feel free to share it on Slack.

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP 
Thank you

**Comment by MyleeeA** [comment]
Hi @Scholarpat This is an excellent curation 
Despite the lengthy signatures and experiments you were so accurate in this curation and it made the review very interesting, Well done 

The only thing I noticed was the Alpha diversity indices for Experiment 14 was Shannon and not Richness as recorded (Supplemental Figure S7(a) for Constipation).

@SvetlanaUP I was able to get this review done using our outlined steps and tips and there were really helpful and direct

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_963 reviewed.

**Comment by MyleeeA** [comment]
@SvetlanaUP sorry I didn’t mention, I had not effected the change 

Can I do that?

**Comment by SvetlanaUP** [comment]
@MyleeeA sure, once @Scholarpat agrees.

**Comment by Scholarpat** [comment]
I do agree with you @MyleeeA. Thank you for the review.

**Comment by SvetlanaUP** [comment]
Please @MyleeeA do the corrections and let me know once ready. Thanks!

**Comment by MyleeeA** [comment]
All done @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_963 reviewed.
