### ISSUE TITLE
Differences in the microbial profiles of early stage endometrial cancers between Black and White women.

### ISSUE THREAD

**Issue by Analyst-Joan** [waldronlab/BugSigDBcuration#362]
Link: [Differences in the microbial profiles of early stage endometrial cancers between Black and White women.](https://www.gynecologiconcology-online.net/article/S0090-8258(22)00142-1/fulltext)

Yet another non-gut microbiome study. 🥰 

CC: @SvetlanaUP @cmirzayi @lwaldron

**Comment by Oyizaadewuyi** [comment]
Please can I be assigned this paper to curate @SvetlanaUP  @Analyst-Joan

**Comment by SvetlanaUP** [comment]
Hi @Oyizaadewuyi, just to check what's the status of this curation? Thanks!

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . Please can I curate this paper?

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1217

Thank you so much.

**Comment by AleruDivine** [comment]
Well done on your curation @KateRasheed! 👏
Just a few suggestions.
1. Body sites should be changed from connective tissue to the **uterus** since uterine tissue samples were collected.
2. Benign Endometrium is a more appropriate name for group 0 in experiment 1.
3. In signature 2 of experiment 2, please correct the signature to [Candidatus Parcubacteria](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=221216&lvl=3&keep=1&srchmode=1&unlock). It is candidate phylum OD1 bacteria (also referred to as Parcubacteria). Also in signature 1 of experiment 3.

Thank you so much!

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP! Please I'd like to confirm the data transformation for metastats.
Thank you!

**Comment by SvetlanaUP** [comment]
@AleruDivine if you go through this list of already curated metastats results https://bugsigdb.org/Special:RunQuery/Quick_filter?Quick_filter%5Bcategory%5D=Experiments&Quick_filter%5Bproperty%5D=Statistical%20test&Quick_filter%5Bvalue%5D=Metastats&_run=1

you will see "Data transformation: **relative abundances"**

and when you take a look at the paper https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000352:
In the Metastats method, the raw abundance measures are converted to a fraction representing **the relative contribution** of each feature to each individual. This results in a normalized version of the data where the counts are expressed **as relative abundances.** The paper mentions that this simple normalization procedure provides a natural representation of the count data as relative abundance measures, but it also notes that other normalization approaches can be used to ensure comparability across samples

**Comment by KateRasheed** [comment]
Thanks for the review @AleruDivine. For OD1 phylum, I'm guessing you meant signature 1 of experiment 1 so I made corrections to it.

I also changed the data transformation to relative abundance.

Thank you so much.

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 

@KateRasheed, I also meant OD1 bacteria in signature 1 of experiment 3, which is currently Candidatus Saccharibacteria. Please check and make corrections too.
Thank you!

**Comment by KateRasheed** [comment]
It's done. Thank you @AleruDivine

**Comment by AleruDivine** [comment]
@SvetlanaUP this review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1217 reviewed.
