### ISSUE TITLE
Stachyose ameliorates obesity-related metabolic syndrome via improving intestinal barrier function and remodeling gut microbiota

### ISSUE THREAD

**Issue by BarakatAA** [waldronlab/BugSigDBcuration#365]
Stachyose ameliorates obesity-related metabolic syndrome via improving intestinal barrier function and remodeling gut microbiota
https://www.sciencedirect.com/science/article/pii/S1756464624001087

Modulating gut health with prebiotics like stachyose which are indigestible by humans but fermentable by gut bacteria is an excellent way of increasing beneficial bacteria populations. I found this study interesting because it shows how stachyose can be used to address obesity-related metabolic syndrome (MetS) thereby improving the integrity of the intestinal epithelial barrier and reversing gut microbiota dysbiosis, potentially reducing the risk factors associated with certain types of cancer.

**Comment by Analyst-Joan** [comment]
Thanks for adding this @BarakatAA 
@SvetlanaUP Please can this be assigned to me for curation?
Thank you

**Comment by Analyst-Joan** [comment]
Thanks @SvetlanaUP

**Comment by Analyst-Joan** [comment]
Good afternoon @SvetlanaUP
This Study has been curated and is ready for review at [Study_1078](https://bugsigdb.org/Study_1078)

**Comment by Scholarpat** [comment]
Excellent curation @Analyst-Joan, well done :clap:
I noticed the article did not report an LDA score. I have added the default LDA score of 2 to the curation.

Happy weekend @SvetlanaUP! This curation is ready for your review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1078 reviewed.
