### ISSUE TITLE
Effects of alcohol on the composition and metabolism of the intestinal microbiota among people with HIV: a cross-sectional study

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#369]
Effects of alcohol on the composition and metabolism of the intestinal microbiota among people with HIV: a cross-sectional study
https://www.sciencedirect.com/science/article/pii/S0741832924000193?via%3Dihub

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP can I be assigned this?

**Comment by MyleeeA** [comment]
Thank you so much @SvetlanaUP

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP this curation is ready for review
Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1025 ready for review.

**Comment by MyleeeA** [comment]
I apologize for not including the link to the study 🙏🏾 @SvetlanaUP

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll like to review this curation.

Thank you

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hi @MyleeeA, 

This is an excellent curation! I went through the study and it it only had one experiment which you have curated. I have also reviewed and confirmed that all the necessary details were accurately captured. 

Well done! 👏

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1025 reviewed.

**Comment by MyleeeA** [comment]
Thanks alot @Scholarpat 😊
