### ISSUE TITLE
The microbiome in urogenital schistosomiasis and induced bladder pathologies

### ISSUE THREAD

**Issue by Analyst-Joan** [waldronlab/BugSigDBcuration#370]
Link: https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0005826

**Comment by Nikilight** [comment]
Hello @SvetlanaUP , Please can I be assigned this paper?

**Comment by Nikilight** [comment]
Thank you @SvetlanaUP

**Comment by Nikilight** [comment]
Hello @SvetlanaUP This is to notify you that this curation is ready for review. https://bugsigdb.org/Study_1035

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP, I'll love to review this study.

Thank you

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,
I've reviewed and completed this curation. There were some taxa missing from some of the experiments which I've included.

Well done @Nikilight. This is a great curation. 👍

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1035 reviewed.
