### ISSUE TITLE
Changes in the Gut Microbiome Contribute to the Development of Behcet’s Disease via Adjuvant Effects

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#376]
Changes in the Gut Microbiome Contribute to the Development of Behcet’s Disease via Adjuvant Effects - Qingfeng Wang - frontiers
https://www.frontiersin.org/articles/10.3389/fcell.2021.716760/full

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll love to curate this. Please assign to me.

Thank you
Scholastica Urua

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , this curation is ready for review.
https://bugsigdb.org/Study_1036

Thank you
Scholastica Urua

**Comment by Peacesandy** [comment]
Hello @Scholarpat This is a good curation; however, there are some mistakes on the signatures. You entered Healthy Control signatures as increased and Behcet patients as decreased. I've made the necessary changes, thank you so much for your hard work.  

@SvetlanaUP  https://bugsigdb.org/Study_1036 corrected and reviewed ✔

**Comment by Scholarpat** [comment]
Thank you so much @Peacesandy

**Comment by SvetlanaUP** [comment]
Excellent @Peacesandy and @Scholarpat! https://bugsigdb.org/Study_1036 reviewed
