### ISSUE TITLE
Characterization of Supragingival Plaque and Oral Swab Microbiomes in Children With Severe Early Childhood Caries

### ISSUE THREAD

**Issue by Nana-Habiba** [waldronlab/BugSigDBcuration#378]
Characterization of Supragingival Plaque and Oral Swab Microbiomes in Children With Severe Early Childhood Caries - Vivianne Cruz - frontiers
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2021.683685/full

**Comment by Rahila-me** [comment]
@SvetlanaUP may i curate this paper, thank you

**Comment by Nana-Habiba** [comment]
I have to update this study because the first one already exist

**Comment by SvetlanaUP** [comment]
@Rahila-me please see message by @Nana-Habiba. My apologies to you on behalf of @Nana-Habiba.

**Comment by Rahila-me** [comment]
@SvetlanaUP yes i have to reach out to @Nana-Habiba that the former study already exist but she can just update a new study so i will still create the new one but it will still have same issue tag. so it's not a problem.  I have started working on the recent one

**Comment by Rahila-me** [comment]
@SvetlanaUP This study is ready for a review: https://bugsigdb.org/Study_1013

**Comment by Scholarpat** [comment]
Good morning @SvetlanaUP , I'll like to review this curation.
Thank you

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

I have made the corrections to this curation and added the experiments/signatures that were not previously curated.

During the curation process, some of the experiments and signatures intermittently failed to display. Reloading the page sometimes resolves this issue, but not consistently.

I have included this report [here](https://github.com/waldronlab/BugSigDB/issues/221#issuecomment-2150582819).

Additionally, please delete Signature 3 of Experiment 1, as it was curated in error.

Thank you very much!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1013 reviewed.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, this curation has one signature that is still not displaying with the others;
https://bugsigdb.org/Study_1013/Experiment_3/Signature_2

**Comment by SvetlanaUP** [comment]
Thanks for letting me know @Scholarpat!
