### ISSUE TITLE
PM2.5 exposure perturbs lung microbiome and its metabolic profile in mice

### ISSUE THREAD

**Issue by Isioma20** [waldronlab/BugSigDBcuration#379]
PM2.5 exposure perturbs lung microbiome and its metabolic profile in mice
https://www.sciencedirect.com/science/article/pii/S0048969720309426?via%3Dihub

**Comment by Analyst-Joan** [comment]
Good afternoon @SvetlanaUP 
Please may I be assigned this paper for curation?

**Comment by Analyst-Joan** [comment]
Thank you @SvetlanaUP

**Comment by Analyst-Joan** [comment]
I checked in with @cmirzayi and this [study](https://bugsigdb.org/Study_1037) is now to be deleted as there was no differential abundance testing done.

Thanks

**Comment by SvetlanaUP** [comment]
@Isioma20 please note that this study has no differential abundance results. Thus, this issue is closed.

**Comment by Isioma20** [comment]
Noted. Apologies @Analyst-Joan. Thanks! @SvetlanaUP
