### ISSUE TITLE
Intratumoral Microbiota Changes with Tumor Stage and Influences the Immune Signature of Oral Squamous Cell Carcinoma

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#382]
Intratumoral Microbiota Changes with Tumor Stage and Influences the Immune Signature of Oral Squamous Cell Carcinoma

https://pubmed.ncbi.nlm.nih.gov/37409975/

**Comment by cmirzayi** [comment]
Assigned.

**Comment by MyleeeA** [comment]
Thank you @cmirzayi 🙏🏾

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 
This curation is ready for review 

https://bugsigdb.org/Study_1041

**Comment by Scholarpat** [comment]
Hi @MyleeeA,

This is a really good curation. Well done. Here are my observations:

**Matched on:** Based on the curation policy, _"Matching typically only occurs in a case-control study. Matching occurs when they select controls similar to cases and match them on certain characteristics such as race, age, health status, gender, etc."_ This is a cross-sectional study, so I'm unsure if this should be curated. Also, in some experiments (e.g., experiments 1 and 2), the two different samples compared were taken from one individual, so matching is not likely since they are from one person. However, I came across this section in the study that says, _"In our cross-sectional sample sets, we tried to match the subjects based on their age, sex, risk factor status, and ethnicity"_, which seems like where you got the matching from, hence my confusion.

I also noticed that there are seven experiments with alpha diversity (some significant and some not significant) without signatures curated as experiments 7-13. While I commend the effort, I think that's a lot of experiments to curate without signatures and suggest those should be deleted.

I'd appreciate your thoughts on this. Thank you so much.

**Comment by MyleeeA** [comment]
Thank you @Scholarpat 

For the experiments, I curated them because the ones with significant alpha diversity were more than the ones that weren’t significant and the last time I asked about curating experiments without signatures Chloe said it should be solely based on discretion but it wasn’t an issue if you do not, hence my reason for curating.

For the matching, yes that’s where it was gotten from and I share in your confusion.
I’m unsure if it’s to remain that way or be removed.

Maybe further clarifications will help

**Comment by Scholarpat** [comment]
Hi @MyleeeA,

Thank you for your response. 
I agree with you, let's bring up the 'matched-on' in this study during the next office hour for further clarifications.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,
I've excluded the 'matched-on' in this curation and it's now complete.

Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1041 reviewed.
