### ISSUE TITLE
Gut Microbiota Composition Changes in Constipated Women of Reproductive Age

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#383]
Gut Microbiota Composition Changes in Constipated Women of Reproductive Age

https://pubmed.ncbi.nlm.nih.gov/33552996/

**Comment by AleruDivine** [comment]
Hello @cmirzayi, @Peacesandy, @Omabekee, @Folakunmi21,
I'd like to be assigned this paper for curation.
Thank you so much!

**Comment by Peacesandy** [comment]
please go ahead @AleruDivine

**Comment by AleruDivine** [comment]
Thank you so much! @Peacesandy

**Comment by cmirzayi** [comment]
Marked as assigned.

**Comment by AleruDivine** [comment]
Thank you so much! @cmirzayi

**Comment by AleruDivine** [comment]
Good morning @cmirzayi @SvetlanaUP, I have finished curating this study and would like to put it up for review.
Link to study:https://bugsigdb.org/Study_1037
Thank you so much!

**Comment by Scholarpat** [comment]
Hello @AleruDivine ,

This was an excellent curation. Only one experiment was done and you captured this and its signatures correctly. Additionally, I thoroughly reviewed all other elements, and they were curated with precision.

Well done!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1037 reviewed.

Good job, @AleruDivine @Scholarpat!
