### ISSUE TITLE
Diet changes due to urbanization in South Africa are linked to microbiome and metabolome signatures of Westernization and colorectal cancer

### ISSUE THREAD

**Issue by MyleeeA** [waldronlab/BugSigDBcuration#384]
https://www.nature.com/articles/s41467-024-46265-0

Adding this for curation because it doesn’t exist on BugSigdb and I believe it should be curated

**Comment by Scholarpat** [comment]
Thank you @MyleeeA for adding.

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Scholarpat** [comment]
Thank you @cmirzayi

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP ,
This curation is ready for review.
https://bugsigdb.org/Study_1039

Thank you!

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP can I attempt a review on this?

**Comment by SvetlanaUP** [comment]
Sure! @MyleeeA

**Comment by MyleeeA** [comment]
Hi @Scholarpat 

Well done on a great curation. 
I have a few observations/suggestions:
1. Antibiotic Exclusion: I think using just the timeframe should work. (6 Weeks).
2. Group Name and Group Description: You can add 'Frozen' to either the group name or Group description for Experiment 3 Making it 'Frozen Food Samples', I'm unsure what difference this would make but since the paper mentioned it  believe it shouldn't be omitted as it might provide better understanding of the results.
For Experiment 2, the groups were compared based on their virome using viral contigs to identify the presence of phages in the groups from my understanding and that is not reflected in the group name or description. If this is captured it will help further differentiate Experiment 1 and Experiment 2.
3. Signature Source/Signature : The signature source in Experiment 4 could include Fig 5D as the paper cited that along side Supplementary Table 2. 
In Experiment 1 Signature 2 Thomasclavelia is a homotypic synonym for Erysipelatoclostridium and you captured that already so I believe the review should be removed for that taxon. 
4. Statistical Test: The statistical test used for differential abundance for the Virome analysis which was captured in Experiment 2 appears to be DESeq2 as stated in the supplemental material somewhere under "Viral Metagenome Assembly and Analysis" and the Figure description says Two way Anova this left me a bit unsure of which is more appropriate although I'm leaning more towards DESeq2 since it says that was used for differential abundance.
 
Do let me know what you think about this and Well done again on this curation.

**Comment by Scholarpat** [comment]
Hi @MyleeeA ,

Thank you so much for your detailed feedback. Here is my response:

1. **Antibiotic Exclusion:** I have edited this part to include only the timeframe.

2. **Group Name and Group Description:** I have adjusted the group names and descriptions for more clarity.

3. **Signature Source/Signature:** Regarding Experiment 4, I believe you are referring to Supplementary Table 3 rather than Supplementary Table 2. The paper cites both Fig. 5D and Supplementary Table 3, but I chose the latter because it provides more detailed information compared to Fig. 5D, which only mentions two signatures.

> In the past, I documented all signature sources quoted in the paper, but recently I came across a [Slack message](https://community-bioc.slack.com/archives/C04RATV9VCY/p1704320770281189) from @cmirzayi, which informed my decision to document a single signature source. This section in particular:
> **Signature Sources:** "Ideally a signature should come from a single source (i.e., a single table, figure, or supplement). If there is a supplement that has all the results from a figure in a raw table, it would be preferable to source from the table in most cases as there is usually more information."

For the signature in Experiment 1 (and others as well), the review tag has now been adjusted to "No known issues."

4. **Statistical Test:** Under the signature source (Fig. 3C) in the paper, it states that _"Statistical analysis was performed by two-way ANOVA corrected for multiple comparisons with Sidak’s test"_ which is why I chose it. I also came across the part you mentioned in the supplementary materials that says the DESeq2 package was used for differential abundance analyses under Viral Metagenome Assembly and Analysis, which is indeed contrasting.

Your observations and suggestions have been very helpful, and I have made the necessary adjustments for points 1-3 to enhance clarity in the curation 😊.

Much appreciated!

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP,
Would love your help with point 4 please.🙏

Thank you so much.

**Comment by MyleeeA** [comment]
Okay @Scholarpat 

Well done, I guess the source should remain that way then, While we await response for the statistical test

**Comment by SvetlanaUP** [comment]
Under _Viral metagenome Assembly and Analysis_ they described methodology that used for virus analysis. We are interested in bacterial signatures, so we are recording details from Bacteriome analysis section.

Be careful, Experiment 2 and Fig. 3C is actually describing VIRAL/phages (bacterial viruses) signatures: **viral contigs or VC stands for viral OTUs**
For example: VC14-Faecalibacterium means **phages directed at Faecalibacterium**, that's a viral signature.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1039 is reviewed.

Well done @Scholarpat @MyleeeA!!

**Comment by MyleeeA** [comment]
Thank you so much @SvetlanaUP 
Just learnt Another thing, the learning is endless 😊

**Comment by Scholarpat** [comment]
Wow, thank you @SvetlanaUP 😊

**Comment by Scholarpat** [comment]
> Under _Viral metagenome Assembly and Analysis_ they described methodology that used for virus analysis. We are interested in bacterial signatures, so we are recording details from Bacteriome analysis section.
> 
> Be careful, Experiment 2 and Fig. 3C is actually describing VIRAL/phages (bacterial viruses) signatures: **viral contigs or VC stands for viral OTUs** For example: VC14-Faecalibacterium means **phages directed at Faecalibacterium**, that's a viral signature.
> 
> Experiment 2 is now deleted.

Hello @SvetlanaUP, please I need further clarification on this because of the study #378 I'm currently reviewing. Are fungal signatures also curatable? I noticed the curation has additional experiments with fungal signatures that were not curated by the initial curator. 

Thank you so much 🙏

**Comment by SvetlanaUP** [comment]
@Scholarpat bugsigdb initially recorded bacterial signatures but with the time we expanded with fungal signatures, for example see this curation https://bugsigdb.org/Study_820 and please note that for fungal analysis different sequencing methodology is used.

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP for the clarification.
