### ISSUE TITLE
The gut microbiome of COVID-19 recovered patients returns to uninfected status in a minority-dominated United States cohort

### ISSUE THREAD

**Issue by MyleeeA** [waldronlab/BugSigDBcuration#385]
The gut microbiome of COVID-19 recovered patients returns to uninfected status in a minority-dominated United States cohort

https://www.tandfonline.com/doi/full/10.1080/19490976.2021.1926840

**Comment by AleruDivine** [comment]
Good morning @cmirzayi, @SvetlanaUP, @Peacesandy, @Folakunmi21, @Omabekee, 
I'd like to be assigned this paper for curation.
Thank you so much!

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
@SvetlanaUP this study has already been curated in BugSigDB. 
Here is the link: https://bugsigdb.org/Study_453

**Comment by SvetlanaUP** [comment]
Thanks @AleruDivine!
@MyleeeA, this issue is closed since this study is already curated and reviewed.

**Comment by MyleeeA** [comment]
I missed that 

Thank you so much and I apologize for not checking properly 🙏🏾 @SvetlanaUP
