### ISSUE TITLE
Microbial Similarity and Preference for Specific Sites in Healthy Oral Cavity and Esophagus

### ISSUE THREAD

**Issue by AleruDivine** [waldronlab/BugSigDBcuration#387]
Microbial Similarity and Preference for Specific Sites in Healthy Oral Cavity and Esophagus
https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2018.01603/full#F2

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , I'll like to curate this.
Can it be assigned to me please?

Thanks you!

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , this [curation](https://bugsigdb.org/Study_1050) is ready for review.
Thank you.

Happy weekend!

**Comment by SvetlanaUP** [comment]
@AleruDivine could you please do review of this curation? Thanks!

**Comment by AleruDivine** [comment]
It’ll be my pleasure 😊 @SvetlanaUP

**Comment by AleruDivine** [comment]
Excellent curation, @Scholarpat! Your work showcases a remarkable attention to detail and dedication. I've noted a few suggestions that could further enhance your already outstanding efforts.

- The bacteria S24_7 in signature 1 of experiment 1 can be replaced with [Muribaculaceae](https://en.wikipedia.org/wiki/Muribaculaceae) as this is its new name.
- The bacteria TM7 in signature 2 of experiment 1 can be replaced with [Candidatus Saccharibacteria](https://microbewiki.kenyon.edu/index.php/Saccharibacteria). I added links for more insights.
- I noticed that in signature 1 of experiment 2, you omitted Fusobacteria and I believe your reason is because the 
homotypic synonym and NCBI BLAST name for [Fusobacteriia](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=203490&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&lin=f&keep=1&srchmode=1&unlock) is also Fusobacteria. While you are very correct, there is also [Fusobacteriota](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=32066&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&keep=1&srchmode=1&unlock), which is equivalent to Fusobacteria. Let me also point out that both these bacteria are of different ranks, which are class and phylum respectively. Please check it out once more.
- Lastly, is there a reason you referred to "Subgingival plaque samples"? The reason for my question is the paper refers to the **supragingival plaques** and they are both different regions of the gingiva. Supragingival plaque is bacteria adherent above the gingiva, whereas bacteria below the gingiva is called subgingival plaque.

I hope these suggestions are helpful. Keep up the fantastic work! 👏

**Comment by Scholarpat** [comment]
Hello @AleruDivine,

Thank you for your thoughtful review and feedback.

- Regarding the first and second points, I've taken your suggestions and replaced the signatures S24_7 and TM7, following the links you provided. 

- For the third point, you're correct about Fusobacteria. I initially omitted one because they share a homotypic synonym, but after revisiting the study, I see that they are of different ranks, with Fusobacteriota being a phylum and Fusobacteriia a class, just as you mentioned. I've now included Fusobacteriota accordingly.

- Lastly, documenting **subgingival** plaque instead of **supragingival** plaque was an oversight on my part. Thanks for catching that, and I have corrected it.

Thank you again for your valuable suggestions—I appreciate your keen eye for detail. I've made the necessary corrections.

**Comment by AleruDivine** [comment]
Well done @Scholarpat 😊

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1050 reviewed.

**Comment by Fificode** [comment]
Hi @SvetlanaUP,
I am currently resolving missing NCBI Taxonomy IDs and noticed that Experiment 4, Signature 1 contains the taxon "SR1".
https://bugsigdb.org/30065718/Experiment_4/Signature_1
I would like to update it to "Candidatus Absconditibacteriota, Taxonomy ID: 221235".  Another name for Candidatus Absconditibacteriota is Candidate division SR1
Please kindly let me know if you have any concerns with making this change.

Thank you!

**Comment by SvetlanaUP** [comment]
Please see this one https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1540874&mode=info

**Comment by Fificode** [comment]
> Please see this one https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1540874&mode=info

Okay then, I will leave it as it was curated.

**Comment by SvetlanaUP** [comment]
Corrected SR1 to SR1 bacterium human oral taxon HOT-345.
