### ISSUE TITLE
Alteration in Oral Microbiome Among Men Who Have Sex With Men With Acute and Chronic HIV Infection on Antiretroviral Therapy

### ISSUE THREAD

**Issue by Isioma20** [waldronlab/BugSigDBcuration#388]
Alteration in Oral Microbiome Among Men Who Have Sex With Men With Acute and Chronic HIV Infection on Antiretroviral Therapy - [Shuang Li] - [Front Cell Infect Microbiol.] 2021
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8317457/

**Comment by AleruDivine** [comment]
Thank you @SvetlanaUP 😊

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP @cmirzayi, I'd like to put this study up for review.
Link to study: https://bugsigdb.org/Study_1043
Thank you so much!

**Comment by Shulamite54** [comment]
Good Day @SvetlanaUP, can I review this

**Comment by Buraah** [comment]
Hi @SvetlanaUP,
I'm currently reviewing this.

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I have reviewed this. I changed 2 things and added 1

* Data transformation for t-test: I changed this from **Relative abundance** to **Raw counts**
* Antibiotic exclusion: Edited to just **4 weeks**
* Alpha diversity: I  added more alpha diversity results from Supplementary Table S1 (Simpson & Richness).

Well done @AleruDivine

**Comment by AleruDivine** [comment]
Thanks for the review and the changes @Buraah 🙏

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1043 reviewed.
