### ISSUE TITLE
Alteration in gut mycobiota of patients with polycystic ovary syndrome

### ISSUE THREAD

**Issue by Buraah** [waldronlab/BugSigDBcuration#394]
Alteration in gut mycobiota of patients with polycystic ovary syndrome
Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10580825/#s2title

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP , please can this be assigned to me for curation?
Thank you.

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP @Buraah, this issue has already been curated.
https://bugsigdb.org/Study_1066

**Comment by Buraah** [comment]
Oh, I see! My bad
Thank you @Scholarpat
