### ISSUE TITLE
Associations of the Gut Microbiome With Treatment Resistance in Schizophrenia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#396]
Associations of the Gut Microbiome With Treatment Resistance in Schizophrenia – Svetlina S Vasileva – JAMA Psychiatry
https://pubmed.ncbi.nlm.nih.gov/38294805/
[Associations of the Gut Microbiome With Treatment Resistance in Schizophrenia.pdf](https://github.com/waldronlab/BugSigDBcuration/files/15417888/Associations.of.the.Gut.Microbiome.With.Treatment.Resistance.in.Schizophrenia.pdf)
data available: https://espace.library.uq.edu.au/view/UQ:23fd2eb

**Comment by SvetlanaUP** [comment]
It seems that the Supplements are not available online; I already contacted Svetlina to see if she can send it.

**Comment by SvetlanaUP** [comment]
This paper is reserved for an NSURP intern.

**Comment by JacobDeJesus** [comment]
Hi Dr. Svetlana, I would like to curate this study.

**Comment by JacobDeJesus** [comment]
Hi Dr. Svetlana, I hope you are very well. This curation is ready for review.

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

Well done on your first curation. I've reviewed and highlighted areas that need changes. This is a detailed write-up, so please take your time. I have explained all my points below in detail for easy understanding. Please ask questions about any point you don't understand.

---

This study includes three primary experiments:

1. Control vs. schizophrenia - [Control vs. SCZ]
2. Treatment-responsive vs. treatment-resistant schizophrenia individuals taking atypical antipsychotics (not including clozapine) - [AAP vs. TRS]
3. Clozapine responsive vs. clozapine non-responsive - [CR vs. CNR]

> Note: There was no evidence for differentially abundant species in the analysis comparing individuals who were responsive to clozapine vs. those who were not (no. 3), so this particular experiment should not be curated. I listed it here for context.

Based on Fig. 3, there are 4 additional experiments comparing control individuals to each of the schizophrenia subgroups (alpha diversity in supp. fig. 6).

**Location of subjects:** :white_check_mark:

**Host species:** :white_check_mark:

**Body site:** :white_check_mark:

**Condition:** This does not necessarily have to be the same for all the experiments. Condition is usually what is contrasted between groups. For example, **_'Schizophrenia'_** is a perfect condition when comparing Control versus Schizophrenia groups (experiment 1). **_'Response to antipsychotic drug'_** is a good fit for experiment 2. You can always refer to the [ontology site](https://www.ebi.ac.uk/ols4/ontologies/efo) to find the closest term when you cannot find an exact term on BugsigDB. For experiment 2, 'Response to **_atypical_** antipsychotic drug' would have been a more specific term, but this is not available on BugsigDB; hence 'Response to antipsychotic drug' is used.

**Group 1 definition:** Define only group 1 of that particular experiment.

**Data transformation:** This is often dependent on the statistical test used for differential abundance. Different tests make use of different data transformation techniques. Please refer to this [chat](https://community-bioc.slack.com/archives/C04RATV9VCY/p1697145085673689?thread_ts=1697141457.022309&cid=C04RATV9VCY) by @cmirzayi for more details.

**Statistical test:** Only the test used for differential abundance should be curated, which is ANCOM in this case.

**Matched on:** This is very different from confounders and typically only occurs in a case-control study. This field is usually curated if the study specifically states that participants were "matched on xyz." In this study, Control individuals were **_"matched for age, sex, and body mass index (BMI) to the individuals with schizophrenia."_** This means that this will only be curated for experiments comparing control to other groups. You can leave this field out for experiment(s) that are only comparing different groups of Schizophrenia patients.

**Confounders controlled for:** Terms like adjusted for, covariates, controlled for, etc., also represent confounders. There's mention of confounders adjusted for in the description of Fig. 3 (signature source) and other part of the paper as well.  What you curated were characteristics of the study population.

**Alpha diversity:** This excerpt, "We observed significantly lower bacterial species richness in participants with schizophrenia compared to control individuals," shows that richness was decreased in patients with Schizophrenia when comparing them to controls. There were no differences (unchanged) for the other alpha diversity measures. You correctly curated this field for experiment 1. For the other experiments (listed as no. 2 and 3 above), all alpha diversity measures were unchanged. Please refer to the 'Microbiome Diversity Differences Between Groups' section for this.

**Signatures:** I noticed you curated 5 signatures for experiment 1. Each experiment usually has two signatures at most (it can sometimes have just one) as BugsigDB is interested in documenting taxa that are differentially abundant when comparing two groups (group 0 vs. group 1). You are right to curate Fig. 3 as the signature source, but here are things to note:
- Numerical values represent log fold changes for species that were significant for the group of interest.
- Negative log fold changes are decreased while positive log fold changes are increased in the group of interest.
- Using the first experiment as an example: Control vs. SCZ, those with red colors/positive values are increased in SCZ, while the blue/negative values are decreased.
"Differentially Abundant Bacterial Species and Metabolic Pathways in Schizophrenia and Treatment Resistance" and the description below figure 3 will give you more insight into how to interpret the figure.

---

> **Other things to note:**
> - It's very common to enter an experiment or signature mistakenly, so you can always request for it to be deleted rather than leave it there.
> - Always mark all fields 'complete' once you are done curating. Some of your experiments/signatures are marked 'incomplete.'
> - Please ask questions on the Slack channel or message me or @SvetlanaUP privately if you are in doubt or stuck on something for a long time.
> 

I hope this is helpful.

**Comment by SvetlanaUP** [comment]
Thank you @Scholarpat for this very helpful and detailed review.
@JacobDeJesus please do corrections and if anything is not clear, feel free to ask.

**Comment by JacobDeJesus** [comment]
Thanks @Scholarpat! :)

**Comment by JacobDeJesus** [comment]
Hi Dr. @SvetlanaUP , I hope you are well. I finally check which experiments of the curation we should delete: 
-  from Experiment1: Signatures 1/2/3
- Experiment 2
- Experiment 4
- Experiment 5

**Comment by SvetlanaUP** [comment]
@JacobDeJesus deleted!

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

You have done a great job implementing the corrections suggested earlier. Below are a few changes I have made to the curation:

- **Antibiotics exclusion**: I edited this field to include only the time frame.

- **Condition**: In Experiment 3, I excluded "Response to antipsychotic drug" and left only "Treatment refractory schizophrenia," as the condition is always dependent on the case group (Group 1). In Experiment 5, I changed "Treatment refractory schizophrenia" to "Response to Clozapine."

- **Alpha diversity**: In Experiment 6, I changed the Richness index from "decreased" to "unchanged" because the p-value reported here (0.055) is above the significant threshold of 0.05.

- **Confounders**: I added this field for all the experiments. The confounders adjusted for are mentioned under Figure 3. Although they are the same variables as the matched-on variables, they should still be curated since both were reported in the study.

- **MHT**: I also included this field for all the experiments. I realized I did not make a note on MHT in my previous review. Due to the large number of statistical tests conducted, researchers sometimes correct their p-values for the number of tests conducted. This is called a multiple hypothesis test (MHT) correction. You can often find this if they refer to "q," "q-value," "Benjamini-Hochberg procedure," "false discovery rate (FDR)," "adjusted p-value," "Bonferroni," or "MHT-corrected p-value."

Well done on your curation! 👏 Feel free to ask questions on any of these points if they are unclear.

Thank you.

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, 

All changes have been effected and this curation is complete.
https://bugsigdb.org/Study_1087

Thank you.

**Comment by JacobDeJesus** [comment]
Thanks @Scholarpat!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1087 reviewed.
