### ISSUE TITLE
Comparative characterization of the infant gut microbiome and their maternal lineage by a multi-omics approach

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#397]
Comparative characterization of the infant gut microbiome and their maternal lineage by a multi-omics approach – Tomás Clive Barker-Tejeda –Nature Communications
https://www.nature.com/articles/s41467-024-47182-y

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP, Please I'd like to be assigned this paper for curation. Thank you so much!

**Comment by SvetlanaUP** [comment]
Hi @AleruDivine, can you pick another one please. (this is reserved for another project) Thanks!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP! Sure thing!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I am still working on the previous one assigned to me. Can I curate this once I am done with that?

**Comment by SvetlanaUP** [comment]
Sure @AleruDivine take your time!

**Comment by AleruDivine** [comment]
@SvetlanaUP I'd like to go ahead with this curation.

**Comment by AleruDivine** [comment]
This study is now ready for review @SvetlanaUP 
Link: https://bugsigdb.org/Study_1096

**Comment by Scholarpat** [comment]
Hi @AleruDivine,

This is a great curation, and it must have been a lot of work to curate all the signatures. Well done! 👏 Here are my observations:

1. **Alpha Diversity**: The measures used here are Shannon and Richness, not Simpson and Richness.

2. **Signature Description**: This section could be more descriptive. For example:
   "Differential abundance results at the phylum and genus levels for 16S rRNA gene sequencing in infants compared to mothers" provides a clearer description and reflects the comparison made.

3. **Additional Experiments**: This excerpt and Fig. 7E/F show three additional experiments where each group is compared to the other two groups, with 16S as the sequencing platform;
   "We further analyzed the ASVs data using the linear discriminant analysis (LDA) effect size (LEfSe) tool on the Galaxy / Hutlab webpage, resulting in the LDA scores shown in Fig. 7E and the cladogram shown in Fig. 7F. These results confirm that the main genera enriched in the Infant microbiota – compared to the other two groups – are Bifidobacterium and Lactobacillus, while Mothers are enriched in the Clostridia class (Clostridium III group and Blautia genus), and Grandmothers have higher levels of the Deltaproteobacteria class and Verrucomicrobia phylum (synonym Verrucomicrobiota)."

Looking forward to hearing your thoughts on this.

Thank you!

**Comment by AleruDivine** [comment]
I apologize for the delay in replying. I had a lot on my plate. Thank you so much @Scholarpat for the thorough review. I will go through the study and your observations.

**Comment by Scholarpat** [comment]
I understand @AleruDivine, please take your time. If you want my help in anyway, do let me know.
Thank you.

**Comment by AleruDivine** [comment]
Thank you so much

**Comment by AleruDivine** [comment]
@SvetlanaUP I reviewed this study following @Scholarpat's observations, made changes and updated the data.

It can be reviewed to check for inaccuracies, but I believe this is complete.

Thank you so much for the review @Scholarpat.
