### ISSUE TITLE
The role of Bifidobacterium genus in modulating the neonate microbiota: implications for antibiotic resistance acquisition in early life

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#398]
The role of Bifidobacterium genus in modulating the neonate microbiota: implications for antibiotic resistance acquisition in early life – Anna Samarra – Gut Microbes
https://www.tandfonline.com/doi/full/10.1080/19490976.2024.2357176

**Comment by AleruDivine** [comment]
Can I curate this @SvetlanaUP?

**Comment by SvetlanaUP** [comment]
Sure!

**Comment by AleruDivine** [comment]
Thank you so much!😊

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, this study is ready for review.
[Study Link
](https://bugsigdb.org/Study_1085)
[Experiment 1](https://bugsigdb.org/Study_1085/Experiment_1)
[Experiment 2](https://bugsigdb.org/Study_1085/Experiment_2)

[Signature 2 in experiment 2](https://bugsigdb.org/Study_1085/Experiment_2/Signature_2)

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,
In this curation, I've changed the data transformation from 'centered log ratio' to 'relative abundance'.

The curation is complete. Well done @AleruDivine 👏

**Comment by AleruDivine** [comment]
Thank you @Scholarpat. Please before this is closed as reviewed, I'd like to point a part of the study under the "**Bioinformatic and statistical analyses**" section stated the abundances were log transformed. Could you have a quick look? Thank you so much!

"A Mann – Whitney U test in the “rstatix” R package[Citation35](https://www.tandfonline.com/doi/full/10.1080/19490976.2024.2357176#) was performed on the **log transformed** abundances of genera to identify significantly different genera between the two clusters. Phylogenetic trees based on zOTUs assigned to Bifidobacterium genus were constructed using “plot_tree” function of “phyloseq” package."

**Comment by Scholarpat** [comment]
Hi @AleruDivine,

@Buraah and I brought up this curation during last week's office hour. The data transformation seemed incorrect at first, but upon reading through the paper, I found that the abundances were 'log transformed.' @cmirzayi mentioned that 'log transformation' (which is not available on BugSigDB) could be recorded as the data transformation, but it is not the same as 'centered log ratio.' She mentioned adding it to BugSigDB in the future, but in its absence, 'relative abundance' should be used.

I apologize for not including this context in the review earlier.

I hope this is helpful.

**Comment by AleruDivine** [comment]
Thank you so much for the clarification. Sadly, I missed office hours last week. I appreciate your effort, both you and Victoria.

Thank you so much!

@SvetlanaUP this review is complete🙏

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1085 reviewed.

**Comment by Buraah** [comment]
Thank you, and well done @AleruDivine 
@Scholarpat, 'Log Transformation' has been added now😊

**Comment by Scholarpat** [comment]
Thank you @Buraah, I noticed you've changed it.

**Comment by AleruDivine** [comment]
Thank you so much @Buraah and @Scholarpat

**Comment by AleruDivine** [comment]
@SvetlanaUP I know this issue is closed but I was going through studies that have no experiment and I noticed I created another duplicate experiment on this.

Please delete it, it was a mistake that I didn't even know existed. 
https://bugsigdb.org/Study_1084

**Comment by SvetlanaUP** [comment]
@AleruDivine deleted, thanks for letting us know!
