### ISSUE TITLE
Altered Gut Microbiome in Patients With Dermatomyositis

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#4]
Condition: Dermatomyositis
URL: https://onlinelibrary.wiley.com/doi/pdf/10.1002/acr2.11436

**Comment by Busayo-ojo** [comment]
Hi @cmirzayi I think this link is broken.

**Comment by cmirzayi** [comment]
@Busayo-ojo Fixed! Thank you.

**Comment by Merit25** [comment]
Ibizugbe Merit

**Comment by ftzohra22** [comment]
Sorry @Dherahrose would you please choose another paper. I had to assign this to Ibizugbe since they claimed it first.

**Comment by Dherahrose** [comment]
Okay, will do

**Comment by Merit25** [comment]
Please @cmirzayi @ftzohra22 I need a review on https://bugsigdb.org/Study_747 
Please I would also like assistance and corrections on anywhere I might have missed a point.
Thanks

**Comment by Dherahrose** [comment]
please  i need a review and correction on https://bugsigdb.org/Study_715. @cmirzayi @ftzohra22

**Comment by Merit25** [comment]
Thank you so much @ftzohra22 I’ll be sure to make the necessary corrections.

**Comment by cmirzayi** [comment]
Hi @Merit25 Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
I went through the study, and it has already been corrected and reviewed!
