### ISSUE TITLE
16S rRNA gene sequencing reveals altered gut microbiota in young adults with schizophrenia and prominent negative symptoms

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#401]
16S rRNA gene sequencing reveals altered gut microbiota in young adults with schizophrenia and prominent negative symptoms – Yi-Huan Chen – Brain and Behavior
https://onlinelibrary.wiley.com/doi/10.1002/brb3.3579

**Comment by JacobDeJesus** [comment]
Hi Dr. Svetlana, I hope you are very well. I would like to curate this data, I recently curated a paper regarding to treatment-resistant schizophrenia, and it cultivated my interest to understand more about the microbiota of induvivuals with this pathology.

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

This is a good curation. I have made a couple of changes for clarity and completeness:

1. **Antibiotics exclusion**: I edited this field to only include the time frame.

2. **Data transformation**: This is often dependent on the statistical test used for differential abundance. Different tests make use of different data transformation techniques. Please refer to this [chat](https://community-bioc.slack.com/archives/C04RATV9VCY/p1697145085673689?thread_ts=1697141457.022309&cid=C04RATV9VCY) by @cmirzayi for more details. I changed the centered log-ratio previously curated to relative abundance.

3. **Statistical test**: I've removed the Spearman Correlation and left only the LEfSe. In BugSigDB, we curate only differential abundance. LEfSe was performed to identify the significantly abundant taxa of bacteria, while Spearman correlation analysis was used to investigate the association between the clinical variables and gut-microbiome composition at the genus level.

4. **Alpha diversity**: I added the Richness index that was not previously curated. Observed-species is another name for Richness.

5. **Signature**: Changed source from 'Figure 2' to 'Figure 2B' and from 'Figure 3' to 'Figure 3B' in exp. 1 and 2 respectively. I've also altered the description for both experiments.

6. **Taxa resolution**: I also resolved a couple of taxa (highlighted in orange) using the [NCBI taxonomy browser](https://www.ncbi.nlm.nih.gov/taxonomy):
   - Exp. 1 Sig. 1
     - Proteobacteria to Pseudomonadota
     - Corynebacteriales to Mycobacteriales
   - Exp. 1 Sig. 2
     - Firmicutes to Bacillota
     - Oscillospirales to Eubacteriales
     - Ruminococcaceae to Oscillospiraceae
     - Ruminococcus torques to [Ruminococcus] torques
   - Exp. 2 Sig. 2
     - Rhizobiales to Hyphomicrobiales

Well done 👏

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

This curation is now complete.
https://bugsigdb.org/Study_956

Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_956 freviewed.
