### ISSUE TITLE
Gut microbiota-derived LCA mediates the protective effect of PEDV infection in piglets

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#408]
Gut microbiota-derived LCA mediates the protective effect of PEDV infection in piglets – Jun-Hong Xing – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01734-4

**Comment by Nathcynthia** [comment]
@SvetlanaUP, can this paper be assign to me @Cynthia Iwuouha

**Comment by TheTosin** [comment]
Hello @Nathcynthia I believe 2G is a one against all analysis, with only increased abundance and 4D is curatable.
See the statement below “LEfSe (Fig.4D)were used to analyze the differences in species”.

Let me know if you need assistance in curating this issue.

From your study, i can see you curated 8 signatures for Experiment 2 which is incorrect.
You can reach me as “Adeshile Oluwatosin” on slack.
Let’s work on it together, so I guide you through this curation.

**Comment by Nathcynthia** [comment]
Hello @TheTosin, yes I would like to collaborate with you.

**Comment by TheTosin** [comment]
Hello Nathcynthia, I have untagged you

**Comment by Nathcynthia** [comment]
> @Nathcynthia could you at-mention yourself instead of me? Every time you mention me I get subscribed to every comment until I manually unsubscribe..

Sorry about that plz.

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review.

https://bugsigdb.org/Study_1209

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review.

https://bugsigdb.org/Study_1209

**Comment by KateRasheed** [comment]
I would like to review this as well @SvetlanaUP . Thank you so much.

**Comment by TheTosin** [comment]
@KateRasheed Thank you so much
All corrections have been made to the study

**Comment by KateRasheed** [comment]
Thank you so much for the corrections.

For the unidentified actinomycetota, actinomycetota fall under the rank 'Phylum' while 'actinobacteria' is under class and from the figure, it's stated that it's under class. This was why I suggested leaving it as curated. 

Please let me know if this is clear @TheTosin 😊

**Comment by KateRasheed** [comment]
@SvetlanaUP This study has been reviewed. Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1209 reviewed.
