### ISSUE TITLE
Dimethyl itaconate ameliorates cognitive impairment induced by a high-fat diet via the gut-brain axis in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#409]
Dimethyl itaconate ameliorates cognitive impairment induced by a high-fat diet via the gut-brain axis in mice – Wei Pan – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01471-8

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
Please assign this to me, I'd love to curate it.
Thank you

**Comment by Buraah** [comment]
Hi @SvetlanaUP 
I'm done curating this study.

I also brought up my questions about the study during the office hour today, and Chloe answered them.

**Comment by Scholarpat** [comment]
Hi @Buraah,

This is a good curation. I have just one observation:
In signature 1 of experiment 2, Desulfovibrionaceae was not curated. Please include this. Other than that, the curation is complete. Well done!

Thank you.

**Comment by Buraah** [comment]
Wheww, thank you. I missed that.
It's included now @Scholarpat

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP, this curation is complete. 
Thank you!

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1095 reviewed.
