### ISSUE TITLE
Microbiota from alginate oligosaccharide-dosed mice successfully mitigated small intestinal mucositis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#410]
Microbiota from alginate oligosaccharide-dosed mice successfully mitigated small intestinal mucositis – Pengfei Zhang – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-020-00886-x

**Comment by TheTosin** [comment]
@SvetlanaUP can this issue be assigned to me?

**Comment by TheTosin** [comment]
Hello @SvetlanaUP 
This study is ready for review.

https://bugsigdb.org/Study_1206

**Comment by AleruDivine** [comment]
@TheTosin  👏👏 You did an excellent job curating this study. Well done!

@SvetlanaUP this review is complete.

**Comment by TheTosin** [comment]
Gracias ☺️ @AleruDivine

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1206 reviewed.
