### ISSUE TITLE
Whole metagenome sequencing of cecum microbiomes in Ethiopian indigenous chickens from two different altitudes reveals antibiotic resistance genes

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#413]
Whole metagenome sequencing of cecum microbiomes in Ethiopian indigenous chickens from two different altitudes reveals antibiotic resistance genes – Himansu Kumar – Genomics

https://www.sciencedirect.com/science/article/pii/S0888754319305774

**Comment by TheTosin** [comment]
Hello @SvetlanaUP can this issue be assigned to me?

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review.

https://bugsigdb.org/Study_1207

**Comment by AleruDivine** [comment]
Well done on this impressive curation @TheTosin 👏👏
Just a few corrections to make.

1. The study design is Laboratory experiment.
2. In experiment 2, the statistical test used is metastats and MHT correction is YES. See "Metastats is also developed in the context of [metagenomic](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/metagenomics) data comprising multiple samples, and relies on a non-parametric t-test for detecting differentially abundant features in [metagenomic](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/metagenomics) studies [[32](https://www.sciencedirect.com/science/article/pii/S0888754319305774#bb0160)]. The p-value is further corrected as q-value to discover taxa with significant variation as shown in [supplementary Fig. S1](https://www.sciencedirect.com/science/article/pii/S0888754319305774#f0040)."

Thank you so much!

**Comment by TheTosin** [comment]
Thank you so much @AleruDivine All corrections have been made to the study

**Comment by AleruDivine** [comment]
Thank you @TheTosin

This review is now complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1207 reviewed.
