### ISSUE TITLE
Perturbations in gut microbiota composition in schizophrenia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#418]
Perturbations in gut microbiota composition in schizophrenia – YiMeng Wang et al. – PlosOne 2024
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0306582

**Comment by JacobDeJesus** [comment]
Hi Dr. @SvetlanaUP, I hope you are doing well. I would like to curate this study.

**Comment by JacobDeJesus** [comment]
Hi @SvetlanaUP and @Scholarpat, I hope you both are well. This curation is ready for review! :)

https://bugsigdb.org/Study_1094

**Comment by SvetlanaUP** [comment]
@Scholarpat can you review it, please?

**Comment by Scholarpat** [comment]
I'll get on it ASAP @SvetlanaUP. Thank you

**Comment by Scholarpat** [comment]
Hi @JacobDeJesus,

This is a very good curation. You've done a wonderful job curating important details. There are just a few minor details to be added for completeness:

- The 16S regions are V3-V4, not V3-V3.
- The controls were age-matched, which was not curated.

Please include these updates. Thank you!

**Comment by SvetlanaUP** [comment]
@JacobDeJesus 👏
Let me know once you do corrections. Good job!

**Comment by JacobDeJesus** [comment]
> Hi @JacobDeJesus,
> 
> This is a very good curation. You've done a wonderful job curating important details. There are just a few minor details to be added for completeness:
> 
> * The 16S regions are V3-V4, not V3-V3.
> * The controls were age-matched, which was not curated.
> 
> Please include these updates. Also define SZ and NC in the signatures for clarity.
> 
> Thank you!

Thanks @Scholarpat! :)

**Comment by JacobDeJesus** [comment]
> @JacobDeJesus 👏 Let me know once you do corrections. Good job!

Thanks @SvetlanaUP!

I have done all corrections.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1094 reviewed.
