### ISSUE TITLE
Gut microbiota: impacts on gastrointestinal cancer immunotherapy

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#42]
Initiated at https://bugsigdb.org/Study_659. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by Ellajessica** [comment]
@lwaldron @cmirzayi  Please can this be assign to me

**Comment by Ellajessica** [comment]
Good day .. I have worked on these. please can you review @lwaldron @cmirzayi @fbeghini 
https://bugsigdb.org/Study_659

**Comment by ftzohra22** [comment]
@Ellajessica this is a review article and does not contain any signatures. Sorry you already reviewed the paper. This issue will be closed, would you please choose another from the unassigned ones? #47 is open
