### ISSUE TITLE
Profiling the differences of gut microbial structure between schizophrenia patients with and without violent behaviors based on 16S rRNA gene sequencing

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#420]
Profiling the differences of gut microbial structure between schizophrenia patients with and without violent behaviors based on 16S rRNA gene sequencing – Xiacan Chen et al. – International Journal of Legal Medicine
https://link.springer.com/article/10.1007/s00414-020-02439-1

PDF to download: 
[s00414-020-02439-1.pdf](https://github.com/user-attachments/files/17643426/s00414-020-02439-1.pdf)

Electronic supplementary material to download: 
[414_2020_2439_MOESM1_ESM.docx](https://github.com/user-attachments/files/17643431/414_2020_2439_MOESM1_ESM.docx)

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP Can I curate this?

I noticed the paper is not open access

**Comment by SvetlanaUP** [comment]
@MyleeeA thank you for letting us know. I just added pdf and supplementary material for download.

**Comment by SvetlanaUP** [comment]
@MyleeeA, please help in closing already assigned papers. Thank you.

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP I'll check for already assigned papers

I'd also appreciate if I can be tagged to a few
Thank you

**Comment by Tino-code07** [comment]
Hello @SvetlanaUP can I be assigned this issue to curate or I should focus on helping to close assigned issues just as you advised @MyleeeA?

**Comment by Tino-code07** [comment]
Hi @SvetlanaUP this study is ready for review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1216 ready for review.

**Comment by KateRasheed** [comment]
Good morning @Tino-code07 . Great job on this curation. However, there are little corrections to be made on it.

Please simplify the antibiotics exclusion as "3 months".

For experiment 1 done with LEfSe, there was no MHT correction 

You didn't curate the experiment done with Metastat statistical test with MHT correction. The signature source for this is in Fig 2a-d.

Thank you so much.

**Comment by Tino-code07** [comment]
@KateRasheed thank you for the review. I will do the corrections right away!

**Comment by KateRasheed** [comment]
Good afternoon @Tino-code07 . Just checking up on this review. How is it going? Do you need more time to finalize this curation?

If you are currently unavailable, it's fine, I can finalize it for you. 

I look forward to your feedback. Thank you so much.

**Comment by Tino-code07** [comment]
Good morning @KateRasheed. I need more time to finalize this curation. I need clarification on how to curate experiments done with the Metastat statistical test. Let me reach out to you and others on Slack.

**Comment by KateRasheed** [comment]
Alright @Tino-code07 . I would be expecting.

**Comment by SvetlanaUP** [comment]
Experiment_2/Signatures_3, 4 and 5
Experiment_3
deleted.

**Comment by Tino-code07** [comment]
Hello @KateRasheed I'm done with the corrections.
https://bugsigdb.org/Study_1216 is ready for a second review.

**Comment by KateRasheed** [comment]
Hello @Tino-code07 . Thank you for correcting this curation. Just two things before we close this:
1. Experiment 2 Signature 2 is having over twenty missing taxa.
2. For the unidentified taxa, during the last meeting, Chloe mentioned that unidentified taxa can be curated as unclassified or uncultured.

Please let me know if you would like me to assist in correcting this. Thank you so much.

**Comment by Tino-code07** [comment]
Hi @KateRasheed I would appreciate your help on correcting this.

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . All corrections have been made on this study.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1216 reviewed.
