### ISSUE TITLE
Profiles and diagnostic value of intestinal microbiota in schizophrenia patients with metabolic syndrome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#423]
Profiles and diagnostic value of intestinal microbiota in schizophrenia patients with metabolic syndrome - Mengjuan Xing et al. – Frontiers in Endocrinology
https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2023.1190954/full

**Comment by eve10111** [comment]
Hi @SvetlanaUP , can you kindly assign this paper to me? Thank you

**Comment by eve10111** [comment]
@SvetlanaUP Accepted.. Thank you very much..

**Comment by eve10111** [comment]
Hello @SvetlanaUP, Can you kindly review my curation!
Link: https://bugsigdb.org/Study_1090
Thank you.

**Comment by Scholarpat** [comment]
Hi @eve10111,

This is a nice attempt. However, I noticed some inconsistencies that need to be addressed:

1. **Study Design:** The study follows a cross-sectional design, not a time-series design. Time-series studies involve repeated observations of the same participants over time, which is not the case here.

2. **Condition:** The condition contrasted in the study is Metabolic Syndrome (MetS), not Schizophrenia.

3. **Group Names:** The correct names should be '**_Schizophrenia patients without MetS_**' for Group 0 and '**_Schizophrenia patients with MetS_**' for Group 1. There are no healthy controls in the study. Additionally, please recheck the group sizes, as they seem to have been interchanged in your curation.

4. **Matched on:** The patients were not matched on any variables.

5. **Alpha Diversity:** Both the Shannon and Simpson indices show an increase.

6. **Signature:** Fig. 4A should be used as the source for the signature instead.

Please make these changes. Well done on your work so far!

**Comment by Scholarpat** [comment]
Hi @SvetlanaUP,

Here are the changes I made:
- Included the definition of MetS in the group description.
- Updated the signature description for clarity.
- Resolved some taxa that were highlighted in orange.

This curation is now complete. Please kindly delete experiment 2, as the study has only one experiment.

Thank you!

**Comment by eve10111** [comment]
Hi @Scholarpat .. thank you so much. Corrections noted for future curation.
