### ISSUE TITLE
Differential human gut microbiome assemblages during soil-transmitted helminth infections in Indonesia and Liberia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#425]
Differential human gut microbiome assemblages during soil-transmitted helminth infections in Indonesia and Liberia – Bruce A. Rosa – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0416-5

**Comment by KateRasheed** [comment]
Please can I be assigned this paper to curate @SvetlanaUP

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1195

Thank you so much.

**Comment by AleruDivine** [comment]
Hi @KateRasheed, well done on this impressive curation 👏👏

I have just a few suggestions and this review will be complete.

1. Experiment 1 is missing quite a handful of signatures, about 25 more, to be precise. Can you check this again, please?
2. For Experiments 3, 6, and 16, please correct Escherichia Shigella to Escherichia/Shigella with NCBI ID: 1940338.
3. Check and correct the abundance direction in experiments 11, 12 and 12.

Thank you so much and well done again!

**Comment by KateRasheed** [comment]
Thank you so much @AleruDivine. I'll work on the corrections. Please check point 3, experiment 12 is repeated twice.

**Comment by KateRasheed** [comment]
@SvetlanaUP Please delete signature 1 in experiment 11.

**Comment by SvetlanaUP** [comment]
Experiment 11/Signature 1 deleted.

**Comment by KateRasheed** [comment]
I'm so sorry please. Also signature 2 in experiment 12

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP .

 @AleruDivine All corrections have been made on this study. I also changed Chloroplast to Cyanobacteriota and Clostridium XI to Peptostreptococcaceae.

Experiment 11, 12 and 13 have one abundance direction, hence, I deleted the second signatures.

For the repeated experiment 12, I assumed you meant experiment 13, hence, I made correction to it.

**Comment by AleruDivine** [comment]
Yes I meant 13. My apologies. Thank you @KateRasheed 

@SvetlanaUP this review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1195 reviewed.

**Comment by Fificode** [comment]
Hi @SvetlanaUP,
I am currently resolving missing NCBI Taxonomy IDs and noticed that Experiment 14, Signature 2 contains the taxon "
Bacillales Incertae Sedis XI " - https://bugsigdb.org/29486796/Experiment_14/Signature_2
I would like to update it to "Gemellaceae"- Taxonomy ID: 539738
The heterotypic synonym is Bacillales Family XI. Incertae Sedis

Please let me know if you have any concerns with making this change.

Thank you.

**Comment by SvetlanaUP** [comment]
Agree.
