### ISSUE TITLE
Extending colonic mucosal microbiome analysis—assessment of colonic lavage as a proxy for endoscopic colonic biopsies

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#428]
Extending colonic mucosal microbiome analysis—assessment of colonic lavage as a proxy for endoscopic colonic biopsies – Euan Watt – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-016-0207-9

**Comment by IfeanyiSam** [comment]
@SvetlanaUP I'd like to curate this paper

**Comment by IfeanyiSam** [comment]
@SvetlanaUP this paper is ready for review
https://bugsigdb.org/Study_1215

**Comment by AleruDivine** [comment]
An excellent curation @IfeanyiSam, well done! 👏👏

Just a couple of small additions:

1. Could you add more detail in your Group 1 description please. For example, something like "**Colonic lavage samples from the sigmoid colon of 23 participants undergoing colorectal cancer screening colonoscopy**."
2. Could you also add Figure 6A as a source for both signatures. It shows the same results, and I think both table S2 and figure 6A should be acknowledged. Then update the description to "LefSe results showing differentially abundant OTUs between the two samples (Biopsy and Lavage)"

**Comment by IfeanyiSam** [comment]
Thank you @AleruDivine for pointing this out. I'll make these updates ASAP.

**Comment by AleruDivine** [comment]
Alright @IfeanyiSam, thanks!

**Comment by IfeanyiSam** [comment]
@AleruDivine The suggested changes have been made, kindly check now. Thank you

**Comment by AleruDivine** [comment]
@SvetlanaUP this review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1215 reviewed.
