### ISSUE TITLE
A history of repeated antibiotic usage leads to microbiota-dependent mucus defects

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#430]
A history of repeated antibiotic usage leads to microbiota-dependent mucus defects – Kertu Liis Krigul – Gut Microbes
https://www.tandfonline.com/doi/full/10.1080/19490976.2024.2377570

**Comment by eve10111** [comment]
Hello @SvetlanaUP , Can you kindly assign this paper to me?.. Thank you

**Comment by SvetlanaUP** [comment]
This paper is available for curation.

**Comment by SvetlanaUP** [comment]
Hello, @yokoDots what's the status of your curation https://bugsigdb.org/Study_1245? 
Do you need help to finalize it?

**Comment by AleruDivine** [comment]
Hi @yokoDots, well done on this curation. 
Here are a few suggestions to improve the curation:

1. Please add the full meanings of the group names in Experiment 1.
2. For experiment 1, the data transformation applied is Centered Log Ratio, not Log transformation. The metabolomics profile data were transformed using log-transformation.
3. Please I'd like to know why you have curated Kruskall-Wallis as the statistical test for experiment 2.
4. The relative abundances of Roseburia and Faecalibacterium are higher in controls for experiment 1.
5. You missed curating Unclassified Eubacteriales (increased in hABX).

I am looking forward to your feedback. Thank you so much!

**Comment by AleruDivine** [comment]
Thank you @yokoDots 
I have no idea which test was used specifically in this case, I also know that ALDEX uses a generalized linear model. I think Chloe talked about it in one of the Office Hours.

Hopefully, we get answers soon.🤞
