### ISSUE TITLE
The gut microbiome, mild cognitive impairment, and probiotics: A randomized clinical trial in middle-aged and older adults

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#431]
The gut microbiome, mild cognitive impairment, and probiotics: A randomized clinical trial in middle-aged and older adults – Aljumaah MR, Bhatia U, Roach J, Gunstad J, Azcarate Peril MA – Journal Clinical nutrition
https://www.clinicalnutritionjournal.com/article/S0261-5614(22)00344-2/abstract

**Comment by SvetlanaUP** [comment]
Under curation by @joyceqiu23 
https://bugsigdb.org/Study_1092

**Comment by SvetlanaUP** [comment]
[Aljumaah-etal-1-Clin-Nutri-2022.pdf](https://github.com/user-attachments/files/16493083/Aljumaah-etal-1-Clin-Nutri-2022.pdf)

@joyceqiu23 please add here the supplementary material of this paper, thanks!

cc @Scholarpat

**Comment by Scholarpat** [comment]
Thank you @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Supplementary material sent by the author Mashael Aljumaah
[Appendix A. Supplementary data.docx](https://github.com/user-attachments/files/16597351/Appendix.A.Supplementary.data.docx)

**Comment by joyceqiu23** [comment]
I would like to request a review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1092 ready for review.

**Comment by Buraah** [comment]
Hi @SvetlanaUP
Can I review this study?

**Comment by SvetlanaUP** [comment]
@Buraah enjoy reviewing!

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I am done with my review.

**Comment by SvetlanaUP** [comment]
Thanks @Buraah for a great and clear review!
@joyceqiu23 please make corrections and feel free to contact @Buraah in case of any doubt.

**Comment by Buraah** [comment]
Thank you! @SvetlanaUP

**Comment by SvetlanaUP** [comment]
This curation is assigned to @Buraah to finalize it.

**Comment by SvetlanaUP** [comment]
> Hello, @joyceqiu23 , just wondering if you need some help to finalize this curation? Let me know, thanks!

@joyceqiu23 this curation is out of outreachy (does not have label: outreachy)

**Comment by Buraah** [comment]
Hi @SvetlanaUP,
I have finalized this curation.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1092 reviewed.
