### ISSUE TITLE
Faecal Microbiota Characterisation of Potamochoerus porcus Living in a Controlled Environment

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#434]
Faecal Microbiota Characterisation of Potamochoerus porcus Living in a Controlled Environment - Donatella Scarafile – Microorganisms

https://www.mdpi.com/2076-2607/11/6/1542

**Comment by codeX-111** [comment]
Good day @SvetlanaUP Can you please assign me this paper, Thank You.

**Comment by codeX-111** [comment]
@SvetlanaUP kindly delete Experiment 2.... https://bugsigdb.org/Study_1165

**Comment by SvetlanaUP** [comment]
> @SvetlanaUP kindly delete Experiment 2.... https://bugsigdb.org/Study_1165

@codeX-111, deleted. By the way, this should be communicated in Slack.

**Comment by codeX-111** [comment]
@SvetlanaUPUnderstood, My apology Sir

**Comment by codeX-111** [comment]
@SvetlanaUP Sir, please I have been trying to reach you on slack. The experiment 2 is still there

**Comment by SvetlanaUP** [comment]
@codeX-111 And I answered it (4:48 PM):
<img width="377" alt="Screenshot 2024-10-17 at 18 59 27" src="https://github.com/user-attachments/assets/cc10fcdd-f7d0-4b62-be62-18c47c9ce5aa">

**Comment by codeX-111** [comment]
@Scholarpat Thank you

**Comment by codeX-111** [comment]
@SvetlanaUP @Scholarpat @cmirzayi Kindly review https://bugsigdb.org/Study_1165

**Comment by SvetlanaUP** [comment]
Hi @codeX-111, thank you for your contribution. Unfortunately this is a poor curation with critical curation points missed. Please see the details below and revise. 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 0 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 8 |

- Host species missed
- Condition incorrect:  "Gut microbiome measurement" is not a condition. The condition should be something that the experiment contrasted on.
- NCBI taxonomy not correctly used
- Chao1, Shannon, invSimpson should be reported
- "Confounders controlled for" information you found I could not find
- Source of signature not specified, thus I could not confirm your statistical tests recorded

**Comment by codeX-111** [comment]
I'm sad to see that i was scored poorly. I'll definietely try to learn from this experience and improve @SvetlanaUP . You're welcomed to help @AleruDivine . Thank You

**Comment by AleruDivine** [comment]
Glad we worked on this together @codeX-111 🤗

**Comment by SvetlanaUP** [comment]
@AleruDivine @codeX-111 please explain rationale behind curating Table 2? Thank you.

**Comment by AleruDivine** [comment]
I suggested curating the table because I thought it indicated a differential abundance of Bifidobacterium species between Rome and Verona. 

From this excerpt "In the present study, different bifidobacterial species distribution was found with respect to the site of sampling. Indeed, RRHs in Rome showed only the presence of B. porcinum, whereas Verona RRHs had B. boum and B. thermoacidophilum ([Table 2](https://www.mdpi.com/2076-2607/11/6/1542#table_body_display_microorganisms-11-01542-t002))."

I interpreted this as differential abundance since each site has different species present. Bifidobacterium porcinum in Rome while in Verona, Bifidobacterium boum and Bifidobacterium thermoacidophilum.

**Comment by SvetlanaUP** [comment]
@AleruDivine in the review comment it is stated: "Table 3 should be curated."

Table 2 include results from culturing not microbial community sequencing methodology.
Please see _2.2. Bifidobacterial Enumeration, Isolation, Genotyping, and Identification_.

**Comment by AleruDivine** [comment]
My apologies!🙏

**Comment by SvetlanaUP** [comment]
@AleruDivine no need for apologies. Hope you did understand why we do not curate Table 2.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1165 reviewed.

**Comment by AleruDivine** [comment]
Yes, I understand. Thank you so much for pointing that out.

**Comment by codeX-111** [comment]
@SvetlanaUP Thank you for teachings and mentoring
