### ISSUE TITLE
Tumor microbial diversity and compositional differences among women in Botswana with high-grade cervical dysplasia and cervical cancer

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#437]
Tumor microbial diversity and compositional differences among women in Botswana with high-grade cervical dysplasia and cervical cancer - Travis T Sims – Int J Gynecol Cancer.

https://ijgc.bmj.com/content/30/8/1151.long

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 
Can I be assigned this paper to curate?
Thank you

**Comment by AleruDivine** [comment]
An excellent curation @MyleeeA, well done!👏

Just one correction; the minimum LDA score for experiment 1 (Figure 2G) is 2.0

And one suggestion; I believe cervical swabs were taken from the **cervix** making (**uterine cervix** is available in BugSisDB) a more suitable body site in my opinion.

Let me know what you think. Thank you so much!

**Comment by AleruDivine** [comment]
Thank you so much @MyleeeA 

Good morning @SvetlanaUP, this review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1222 reviewed.
