### ISSUE TITLE
The penile microbiota of Black South African men: relationship with human papillomavirus and HIV infection

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#438]
The penile microbiota of Black South African men: relationship with human papillomavirus and HIV infection - Harris Onywera – BMC Microbiology 

https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-020-01759-x

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . Please I would like to be assigned this paper.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1201

**Comment by AleruDivine** [comment]
This is an excellent curation @KateRasheed well done 👏 👏

This review is complete @SvetlanaUP

**Comment by KateRasheed** [comment]
Thank you so much @AleruDivine

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1201 reviewed.
