### ISSUE TITLE
Structural changes in the oral microbiome of the adolescent patients with moderate or severe dental fluorosis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#439]
Structural changes in the oral microbiome of the adolescent patients with moderate or severe dental fluorosis – Qian Wang – Scientific Reports 
https://www.nature.com/articles/s41598-021-82709-z

**Comment by LiliGC** [comment]
Hello, I'd like to be assigned to this.

**Comment by Rahila-me** [comment]
Hello @LiliGC I want to know the state of your curation. Have you started, do you need help for I am open for collaboration. Waiting for your kind reply seeing that this was assigned to you since last week that's why i am asking.

**Comment by SvetlanaUP** [comment]
@Rahila-me @LiliGC when searching for PMID: 33536555 there is no created study on bugsigdb.
@LiliGC if you need help, do not hesitate to ask for help on our Slack channel.

**Comment by Rahila-me** [comment]
ok... I will just wait for @LiliGC approval, if he needs help as collaboration or if the paper will be re-assigned to me maybe after waiting for his reply in the next 3 days. if that's okay by you @SvetlanaUP

**Comment by LiliGC** [comment]
Hello @SvetlanaUP and @Rahila-me. I apologize for the late response. I’m currently working on the curation and have added the study on the  BuSigDB https://bugsigdb.org/Study_1205.  I hope to finish adding the experiments today. At the moment, I don’t need any assistance, but I appreciate your offer for collaboration. If anything comes up, I’ll be sure to reach out.

Thank you for your understanding!

**Comment by ChineseChikki** [comment]
@LiliGC ok...noted. weldone in your curation

**Comment by Rahila-me** [comment]
@LiliGC Thanks for the heads-up. Well-done in your curation. Should you encounter any blocker please feel free to reach me on slack @Liza. If you need peer-review before submitting your final curation i am also available. In the main time take care.

**Comment by KateRasheed** [comment]
Good afternoon @LiliGC. How is this curation going? I see that you've created a study but haven't added any experiment.

I would love to collaborate with you on the completion of this curation. Thank you so much.

**Comment by LiliGC** [comment]
Hello @KateRasheed .I created the experiment. Today, I'm going to add the signatures. I'll reach you out for a review once they're completed. 
Thanks again for your offer.

**Comment by SvetlanaUP** [comment]
@KateRasheed here you are: Liliana Garmendia (Slack)

**Comment by SvetlanaUP** [comment]
@KateRasheed @LiliGC what's the status of this curation? Thanks!

**Comment by KateRasheed** [comment]
I am waiting for @LiliGC to respond on slack before we put it up for submission.

I'll put it up for submission soon.

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1205

Thank you so much.

**Comment by TheTosin** [comment]
Alright, noted @SvetlanaUP

**Comment by TheTosin** [comment]
Hello @KateRasheed  @LiliGC You both did well on this curation. Well done 👏

However, I noticed some errors. Kindly take note:
- Figure 3c should not be curated as it depicts Significant differences of the taxa at phylum level between Healthy and M&S group, as Figure 4a already shows us results at species level and this is lower in the taxonomical rank.
* In that case, Kindly remove Taxa bacillota and bacteroidota in the curation “Experiment 1/signature 2 and 3. 
* Also reference only Figure 4A as the source.

- In Experiment 1/signature 3: These taxa were omitted. Kindly curate.
* Eubacterium sulci : Taxa ID “143393”
* Lachnoanaerobactulum umeanse: Taxa ID “617123”

- Experiment 3: sample size for Group 0: Healthy is 9 not 14. 
- Experiment 4: The sample sizes were interchanged as well. Kindly correct this. Mild(14), Moderate&Severe(19).

- Experiment 4: the increased abundances of the signature should be listed first. Kindly interchange the curation.

CURATION RESULTS

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 0
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2
Total (maximum 23 points): 16

@SvetlanaUP This study has been reviewed.

**Comment by KateRasheed** [comment]
Thanks for the review @TheTosin . I'll make the needed corrections. However, there are some things I would like you to look into:

For the figure that shouldn't be curated, it was stated in the curation policy that we "Curate all taxa no matter of their taxonomic rank". 

Also, "If two different figures/tables differ only in which taxonomic level they provide (e.g. one figure for species, one supplemental table for genera, but these resulted from the same contrast), these can be combined into a single signature."

For experiment 4, decreased signature got saved first that's why it's appearing as Signature 1.

Thank you @SvetlanaUP

**Comment by TheTosin** [comment]
Hello @KateRasheed According to the curation policy and discussions on the group, always curate taxa lower in the taxonomical rank as long as the contrast and statistical test is same.

Also, as seen in the curation policy “Signature 1 is for increased abundance in exposed group. Signature 2 is for decreased in exposed group”. 

Please make the necessary corrections. Well done once again.

**Comment by TheTosin** [comment]
@KateRasheed I can see you’ve made changes to the study asides the abundances stated for Experiment 4, although it is accurate.
It’s better for it to be curated in the manner initially stated.
Kindly notify me on when this change has been made.

Also, you have not curated the two taxa listed out for Experiment 1.

**Comment by KateRasheed** [comment]
Thank you @TheTosin. All corrections have been made.

Kindly review the points for number 7, 16 and 17(just as you observed,  the abundance direction was rightly selected)

**Comment by TheTosin** [comment]
@KateRasheed Kindly correct the source in both signatures in experiment 4.

7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point) was recorded as zero because the sample sizes were incorrect.

17. Abundance direction correctly selected (1 point) was recorded as zero because of the curation. Although, it was accurate.

**Comment by TheTosin** [comment]
Hello @SvetlanaUP All corrections have been made to the study.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . Please this paper has been reviewed too.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1205 reviewed.
