### ISSUE TITLE
Intestinal permeability before and after albendazole treatment in low and high socioeconomic status schoolchildren in Makassar, Indonesia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#441]
Intestinal permeability before and after albendazole treatment in low and high socioeconomic status schoolchildren in Makassar, Indonesia – Aldian I. Amaruddin – Scientific Reports
https://www.nature.com/articles/s41598-022-07086-7

**Comment by AleruDivine** [comment]
Good day @SvetlanaUP 
I'd like to be assigned this paper for curation

Thank you so much!

**Comment by AleruDivine** [comment]
Thank you 😊

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP 
I'd like to submit this study for review.
Link: https://bugsigdb.org/Study_1242
Thank you so much!

**Comment by AleruDivine** [comment]
Good evening @KateRasheed, please can you review this study?
Thank you so much!

**Comment by KateRasheed** [comment]
Yes please. Thank you @AleruDivine

**Comment by KateRasheed** [comment]
Good afternoon @AleruDivine . Great job on this curation. Just few things to note on this study before we close it:

- For experiment 1 signature 2, curate Prevotella 2 and Prevotella 9 separately.
- I have checked the NCBI discussion page and I can't find where Ruminococcaceae UCG-002 was resolved; please can you point me to it.
- For experiment 2 signature 2, please curate Prevotella 9 as it is.

Thank you so much.

**Comment by AleruDivine** [comment]
Thank you for the review @KateRasheed 
Ruminococcaceae UCG-002 has not been resolved, this is now clarified on the Slack channel. My apologies. All corrections have been made.

Under "Microbiota analysis" there is a reference to where the sample processing and microbiota analysis has been described previously in 2020. Here you will find all the laboratory analysis details.

"Microbiota analysis was performed in 140 children from whom sufficient stool samples were available before and after treatment. The procedure for sample processing and microbiota analysis is already described elsewhere[13](https://www.nature.com/articles/s41598-022-07086-7#ref-CR13)."

Thank you so much!

**Comment by KateRasheed** [comment]
Thank you so much @AleruDivine . This review is now complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1242 reviewed.
