### ISSUE TITLE
Risk factors for type 1 diabetes, including environmental, behavioural and gut microbial factors: a case–control study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#442]
Risk factors for type 1 diabetes, including environmental, behavioural and gut microbial factors: a case–control study – Deborah Traversi – Scientific Reports
https://www.nature.com/articles/s41598-020-74678-6

**Comment by IfeanyiSam** [comment]
Samuel Nnanna
I would like to claim this article @SvetlanaUP

**Comment by IfeanyiSam** [comment]
I'll get started

**Comment by SvetlanaUP** [comment]
This study is NOT to be curated due to NO significant differences reported. 
@IfeanyiSam your effort is noted, please select other paper to curate.

**Comment by IfeanyiSam** [comment]
https://bugsigdb.org/Study_1109
@SvetlanaUP ready for review

**Comment by SvetlanaUP** [comment]
Hi @IfeanyiSam, thank you for your contribution. This is a good curation.

There are some details to recheck and correct:
- Signature source: you reported Table 3, maybe I am missing it but I see only **in the text** significant taxa reported?
- Significance threshold of 0.05 is not correct: please see "DeSeq2 showed 48 significantly abundant OTUs **(p < 0.001)**"
- Data transformation: DESeq2 uses a negative binomial model which requires **raw counts**
- How did you identify **confounding factors** for this study?: If they didn't state any clearly (usually using words like "adjusted for" or "controlled for") they probably didn't control for any confounders. Maybe I missed it, please do let me know. 

**Looking forward to your answers and corrections.**

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0.5 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 20.5 |

**Comment by IfeanyiSam** [comment]
Thank you for the review, I'll make the corrections and report back ASAP.

**Comment by IfeanyiSam** [comment]
I've made the necessary corrections, thank you for pointing them out. 

For the Confounding Factors, please review the text below and then table 4;
"The multivariable analysis produced a ­ R2=0.6259 (p < 0.001). After adjusting for confounding factors, the
likelihood of having diabetes is significantly higher in those with higher amount of Firmicutes, lower amount of
Bifidobacterium spp and a higher amount of total carbohydrate intake (Table 4)."

@SvetlanaUP

**Comment by SvetlanaUP** [comment]
@IfeanyiSam Signature source: "From Text" is too vague. Corrected to "Results: T1D risk factors"

As for the "Confounding factors that have been accounted for by stratification or model adjustment", in the table 4 they are not reported for statistical analysis for differential abundances.

https://bugsigdb.org/Study_1109 reviewed and corrected.
