### ISSUE TITLE
Changes in the vaginal microbiota across a gradient of urbanization

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#443]
Changes in the vaginal microbiota across a gradient of urbanization – Daniela Vargas-Robles – Scientific Reports
https://www.nature.com/articles/s41598-020-69111-x

**Comment by TheTosin** [comment]
This paper seems interesting, can it be assigned to me? @SvetlanaUP

**Comment by Agatha-Chineke** [comment]
@TheTosin ,  I am also interested in the paper, can we collaborate?

Just saw it and was about to request and saw you have requested earlier

**Comment by TheTosin** [comment]
@Agatha-Chineke I need @SvetlanaUP permission to go ahead with the curation, she hasn’t assigned it to me yet.
Let’s await her response.

**Comment by SvetlanaUP** [comment]
@TheTosin you are assigned to this paper.
@Agatha-Chineke please select other one to curate, thanks!

**Comment by TheTosin** [comment]
Thank you @SvetlanaUP

**Comment by SvetlanaUP** [comment]
@Agatha-Chineke what do you think about this one https://github.com/waldronlab/BugSigDBcuration/issues/445?

**Comment by TheTosin** [comment]
@SvetlanaUP i need clarifications on Figure S2 curation, which I intend to ask in the office hour on Thursday.
So it’s pending
Every other experiments have been curated

**Comment by SvetlanaUP** [comment]
@TheTosin thanks for the update! (no worries, when there is a clear update :) )

**Comment by TheTosin** [comment]
Thank you, definitely @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Hello, @TheTosin what's the status of your curation https://bugsigdb.org/Study_1194?
Do you need help to finalize it?

**Comment by TheTosin** [comment]
Good morning @SvetlanaUP i would go over it again, please give me some minutes
I thought I submitted it already

**Comment by TheTosin** [comment]
I would like to collaborate with Kate to finalize this curation. I have to work on one more experiment to hasten the process @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Sure! Just do not forget to tag Kate ;) @KateRasheed https://github.com/KateRasheed

**Comment by KateRasheed** [comment]
Good morning @TheTosin . It would be great finalizing this curation with you.

**Comment by TheTosin** [comment]
Alright @KateRasheed let’s get to it.

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . Kindly delete experiment 12 and 16 from this [study](https://bugsigdb.org/Study_1194)

After which the study is ready for review.

Thank you so much @TheTosin

**Comment by SvetlanaUP** [comment]
Deleted. 
@KateRasheed is this study "Reviewed"?

**Comment by KateRasheed** [comment]
Experiment 1-11 is reviewed. I just added experiments 13-15 @SvetlanaUP .

**Comment by SvetlanaUP** [comment]
OK, I am waiting everything to be reviewed to close this curation.

**Comment by AleruDivine** [comment]
Of course @KateRasheed 😌

**Comment by AleruDivine** [comment]
An excellent curation @TheTosin @KateRasheed well done!👏👏 This must have been a lot of work.

Just one observation, In signature 1 of experiment 6, _**Prevotella timonensis**_ is [_**Hoylesella timonensis**_](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=386414&lvl=3&keep=1&srchmode=1&unlock) and not _**Prevotellamassilia timonensis**_. Please review and make this correction.

Once that's done, this review will be complete, @SvetlanaUP

**Comment by TheTosin** [comment]
Thank you so much @AleruDivine I would do that now

**Comment by TheTosin** [comment]
Done now

**Comment by AleruDivine** [comment]
Thank you so much @TheTosin 

This review is now complete @SvetlanaUP

**Comment by KateRasheed** [comment]
Thank you so much for the review @AleruDivine . Thank you for effecting the correction @TheTosin

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1194 reviewed.

**Comment by SvetlanaUP** [comment]
Please check if **an**aerococcus christensenii is a typo of Aerococcus christensenii!

**Comment by TheTosin** [comment]
I would check this now @SvetlanaUP

**Comment by SvetlanaUP** [comment]
Sorry I was not precise, I meant a typo by the study authors. Because if you google Anaerococcus Christensenii there is no Anaerococcus Christensenii BUT there is Aerococcus Christensenii...

**Comment by SvetlanaUP** [comment]
Even in the NCBI search you got this https://www.ncbi.nlm.nih.gov/taxonomy/?term=Anaerococcus+Christensenii

**Comment by SvetlanaUP** [comment]
Ok, I found it, I was right and corrected it.
See supplementary tables and you will spot: **_Aerococcus christensenii_**

**Comment by SvetlanaUP** [comment]
@TheTosin: "Anaerococcus Christensenii was mentioned instead **in both text and figure**."

This is another example to ALWAYS check **the supplementary material.**

cc @KateRasheed @AleruDivine

**Comment by KateRasheed** [comment]
Okay. Thank you so much for pointing this out.

**Comment by AleruDivine** [comment]
Oh my! Thank you so much @SvetlanaUP

**Comment by TheTosin** [comment]
This is noted. Thank you so much @SvetlanaUP
