### ISSUE TITLE
Diet at birth is critical for healthy growth, independent of effects on the gut microbiota

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#444]
Diet at birth is critical for healthy growth, independent of effects on the gut microbiota – Lieke J. W. van den Elsen – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01852-7

**Comment by Princess-Ben** [comment]
My name is Princess Asuelimen. Please, I'd like to be assigned to this article.

**Comment by Princess-Ben** [comment]
Hi. @SvetlanaUP I'm done with this, please I need it to be reviewed: https://bugsigdb.org/Study_1141

**Comment by SvetlanaUP** [comment]
@Folakunmi21 ha! I started to do this review :)

**Comment by SvetlanaUP** [comment]
Hi @Princess-Ben, thank you for your contribution! This is a good curation. 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 20 |

Please revise Members of Signatures.

**Comment by Princess-Ben** [comment]
Thank you @SvetlanaUP. For the second correction you highlighted, "record precisely: group, if it is candidatus or not (Candidatus Saccharimonadaceae?), name (Clostridia vadin BB60 group) etc".  I corrected Saccharimonadaceae (Family) to Saccharimonas (Genus) and Clostridia vadin (Class) to Unclassified Clostridia.

**Comment by SvetlanaUP** [comment]
@Princess-Ben please see my precise corrections.

https://bugsigdb.org/Study_1141 reviewed and corrected.
