### ISSUE TITLE
Lung microbiome of stable and exacerbated COPD patients in Tshwane, South Africa

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#445]
Lung microbiome of stable and exacerbated COPD patients in Tshwane, South Africa – T. Goolam Mahomed – Scientific Reports

https://www.nature.com/articles/s41598-021-99127-w

**Comment by TheTosin** [comment]
Hello @SvetlanaUP can you kindly assign this to me?

**Comment by SvetlanaUP** [comment]
@TheTosin you are already assigned to another one https://github.com/waldronlab/BugSigDBcuration/issues/443 Enjoy!

**Comment by Agatha-Chineke** [comment]
Ok @SvetlanaUP assign this this to me, thank you

**Comment by Agatha-Chineke** [comment]
@SvetlanaUP , the link to this paper is not available. At least that was the response I have  been getting since you assigned it to me.

Is it possible to change it?

**Comment by SvetlanaUP** [comment]
@Agatha-Chineke please be patient, all the journals platforms are temporary down. Check it later and continue with your curation.

**Comment by AleruDivine** [comment]
Hi @Agatha-Chineke, this paper is now visible.
I see one experiment so far in this paper. I'm open to collaborating if that's okay with you. 
If you have any questions/concerns/blockers, you can reach out on slack @AleruDivine
Thank you so much!

**Comment by SvetlanaUP** [comment]
@AleruDivine, @ToluwalaseAO (https://github.com/ToluwalaseAO) needs help.
Please see:
https://github.com/waldronlab/BugSigDBcuration/issues/447
https://github.com/waldronlab/BugSigDBcuration/issues/449

**Comment by AleruDivine** [comment]
Thank you @SvetlanaUP

**Comment by Agatha-Chineke** [comment]
@AleruDivine , yeah. Still working on it

Thank you

**Comment by AleruDivine** [comment]
Okay @Agatha-Chineke well done 👍

**Comment by AleruDivine** [comment]
Hi @Agatha-Chineke, I hope you're doing okay!
Checking in again on this study. Wanted to know if you are having any difficulties. I'm available to collaborate or answer any questions you may have.

Thank you so much!

**Comment by SvetlanaUP** [comment]
@Agatha-Chineke please team with @AleruDivine and finalize this curation.

**Comment by AleruDivine** [comment]
Thank you @SvetlanaUP 
I’ll reach out to @Agatha-Chineke on Slack.

**Comment by Agatha-Chineke** [comment]
@AleruDivine thank you for reaching out. Still the same challenge I told you earlier even after changing browser like you suggested

**Comment by AleruDivine** [comment]
This is a great idea @SvetlanaUP thank you so much!

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP 
@Agatha-Chineke and I will like to submit this study for review.
https://bugsigdb.org/Study_1198

Thank you so much!

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . Great job on this curation.

Just a little review on the group sample name. Please add the full name of COPD to the group name; just as we have in the group description.

**Comment by AleruDivine** [comment]
Done! Thank you for the review @KateRasheed

**Comment by KateRasheed** [comment]
Thank you Divine. This work has been reviewed @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1198 reviewed.
