### ISSUE TITLE
The lung microbiome in HIV-positive patients with active pulmonary tuberculosis

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#446]
The lung microbiome in HIV-positive patients with active pulmonary tuberculosis - Veronica Ueckermann –
Scientific Reports
https://www.nature.com/articles/s41598-022-12970-3

**Comment by AishatBolarinwa** [comment]
> Greetings
> 
> I will like to be assigned to this paper please.
> 
> Thank you.

Hello 
Can I be assigned to this study please? @SvetlanaUP @Scholarpat

**Comment by AishatBolarinwa** [comment]
Thank you.
I'm on it

**Comment by MyleeeA** [comment]
Hi @AishatBolarinwa 

How's your curation going?
Are you experiencing any blockers?.....I am available to collaborate with you on this

Do let me know if that is okay, Thank you

**Comment by SvetlanaUP** [comment]
@AishatBolarinwa and @MyleeeA enjoy your team work!

**Comment by AishatBolarinwa** [comment]
Thank you very much

**Comment by MyleeeA** [comment]
Thank you @SvetlanaUP

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 

This curation is ready for review, Thank you
https://bugsigdb.org/Study_1184

**Comment by KateRasheed** [comment]
Good morning @MyleeeA @AishatBolarinwa . Great job on this curation. Just a little correction before we close this:

Please state the full meaning of HIV in experiment 1 group names.

For experiment 3, it is stated in the caption that the result is from BALF not sputum and BALF. See this: "In the BALF of the TB specimens, the genus Stenotrophomonas was over-represented when compared with the BALF specimens of the Pneumonia cohort. In the pneumonia cohort Neisseria, Corynebacterium, Dialister and Prevotella were over-represented."

Please change the signatures description of experiment 3 and the body site.

Thank you so much.

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . All corrections have been made on this study.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1184 reviewed.
