### ISSUE TITLE
Association between clinical and environmental factors and the gut microbiota profiles in young South African children

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#449]
Association between clinical and environmental factors and the gut microbiota profiles in young South African children - Kristien Nel Van Zyl – Scientific Reports
https://www.nature.com/articles/s41598-021-95409-5

**Comment by ToluwalaseAO** [comment]
@SvetlanaUP , can I get this issue assigned to me?

**Comment by ToluwalaseAO** [comment]
Hi! @SvetlanaUP, I signed up to create an account, but I have not yet received the password to access the curation site.

**Comment by SvetlanaUP** [comment]
Hi @ToluwalaseAO,

this is a question to be posted in our dedicated Slack channel (all communication is there, not related to this specific GitHub issue). **Answer to your question is here:** https://community-bioc.slack.com/archives/C04RATV9VCY/p1727940469459309?thread_ts=1727940203.037609&cid=C04RATV9VCY

I just checked it and all requests have been approved.

**Comment by ToluwalaseAO** [comment]
Okay . Thank you!

**Comment by ToluwalaseAO** [comment]
Hi. @SvetlanaUP my second contribution is ready for review. Thank you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1156 ready for review.

**Comment by SvetlanaUP** [comment]
@ToluwalaseAO thank you for your contribution. Unfortunately this curation needs more work and careful revision of all curation points.

- Study information left "Incomplete"
- Copy-Pasting text/paragraphs from the paper should be changed with concise and accurate descriptions
- V4 region of 16S rRNA gene was sequenced
- Figure 5 with ANCOM results indicate 3 experiments
etc. etc.

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |        0 |
| 2    | Correct study design                                                 | 1   |        1 |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |        0 |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |        1 |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |        0 |
| 6    | Contrast groups correctly identified                                 | 1   |        0|
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |        1 |
| 8    | Antibiotic exclusion correctly identified                            | 1   |        1|
| 9    | Correctly identified sequencing details                              | 2   |        1 |
| 10   | Identified correct statistical test                                  | 1   |        0 |
| 11   | Identified MHT correction                                            | 1   |        0 |
| 12   | Correctly recorded matched on factors                                | 1   |        0 |
| 13   | Entered correct number of statistical tests per experiment           | 1   |        0 |
| 14   | All diversity measures identified                                    | 1   |        1 |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |        1|
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |        0 |
| 17   | Abundance direction correctly selected                               | 1   |        0 |
| 18   | Members of Signatures identified correctly                           | 2   |        0 |
| 19   | Correct use of NCBI taxonomy                                         | 2   |        2 |
|      | TOTAL                                                                | 23  |        8 |

**Comment by TheTosin** [comment]
@SvetlanaUP I would like to collaborate to resolve this pending issue

**Comment by ToluwalaseAO** [comment]
@SvetlanaUP , I'll take this feedback into account and collaborate with @TheTosin to address and improve the curation. Thank you.

**Comment by AleruDivine** [comment]
Hi @ToluwalaseAO I'd also love to collaborate with you to review this curation and make corrections if that's okay with you.
Thank you so much!

**Comment by SvetlanaUP** [comment]
@AleruDivine you could help in here https://github.com/waldronlab/BugSigDBcuration/issues/447

This curation is now supported by @TheTosin

**Comment by AleruDivine** [comment]
Got it @SvetlanaUP I'll proceed with helping out on the issue #447.

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review

**Comment by SvetlanaUP** [comment]
@TheTosin all good, thank you for corrections.
Study reviewed by @Buraah https://github.com/Buraah
