### ISSUE TITLE
Exercise Alters Gut Microbiota Composition and Function in Lean and Obese Humans

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#45]
Initiated at https://bugsigdb.org/Study_533. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by Susu-spec** [comment]
@lwaldron @cmirzayi I'd like to curate this paper

**Comment by Susu-spec** [comment]
@lwaldron this article is already in the database:)
I'll claim another

**Comment by lwaldron** [comment]
But there are no experiments or signatures, which account for all the significant work, so it can still be claimed!

**Comment by Susu-spec** [comment]
Oh I see. I've made a blunder by trying to create a new study😅. I didn't read the comment. My bad.
This curation also exists though: https://bugsigdb.org/Study_534

**Comment by ftzohra22** [comment]
@lwaldron https://bugsigdb.org/Study_534 and https://bugsigdb.org/Study_533 are duplicate studies. one of them is reviewed.

**Comment by lwaldron** [comment]
Wow I didn't even find 534 - thank you both for catching this, and not duplicating what is already in the database!

**Comment by lwaldron** [comment]
This study also got duplicated at https://bugsigdb.org/Study_633 - will delete there as well.
