### ISSUE TITLE
Revealing links between gut microbiome and its fungal community in Type 2 Diabetes Mellitus among Emirati subjects: A pilot study

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#451]
Revealing links between gut microbiome and its fungal community in Type 2 Diabetes Mellitus among Emirati subjects: A pilot study - Mohammad Tahseen Al Bataineh – Scientific Reports
https://www.nature.com/articles/s41598-020-66598-2

**Comment by Sproff** [comment]
I would like to pick this up @SvetlanaUP

**Comment by Sproff** [comment]
https://bugsigdb.org/Study_1132/Experiment_1 - It's ready for review

**Comment by Folakunmi21** [comment]
1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 0
5. Condition entered according to contrast (correct EFO ontology) (1 point):  1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 13.5

@Sproff  thank you for your efforts in curating this paper. Unfortunately, this was poorly curated. This should be curated as 2 experiments. The first experiment for the bacteria differences should be curated from the paragraph that says “Finally, we search for taxonomic features significantly different between non-T2DM and T2DM groups while accounting for cofounding variables…”. The statistical test for that should be deseq2 and the signature source should be “fig 1G and within result text”, confounders with significant effect are age, disease state and BMI. The second experiment is for fungal microbiome composition. The signatures should be curated from the last paragraph under “fungal composition is different between T2DM and non-TSDM subjects”. confounders with significant effect are age and disease state. The signatures sources for this should be “figure 2 and within result text” Note that the sequencing carried out for the fungi experiment was ITS. This is a case-control study, body site is faeces.

@SvetlanaUP Reviewed✅

**Comment by Folakunmi21** [comment]
@TheTosin please, collaborate with @Sproff on making the corrections to this curation. Thank you.

**Comment by TheTosin** [comment]
@Folakunmi21 noted! I would begin immediately.

@Sproff can I edit directly?

**Comment by Sproff** [comment]
> @Folakunmi21 noted! I would begin immediately.

Yeah, sure.

**Comment by TheTosin** [comment]
@SvetlanaUP kindly delete https://bugsigdb.org/Study_1132/experiment_2/signature_2.

@SvetlanaUP @Folakunmi21 This study is ready for review. Kindly check discussion on this study as well.

https://bugsigdb.org/Study_1132
https://bugsigdb.org/Study_1132/experiment_2/signature_3.

**Comment by SvetlanaUP** [comment]
@Folakunmi21 check please the corrected version of this curation, thanks!

**Comment by Folakunmi21** [comment]
corrected version reviewed @SvetlanaUP
