### ISSUE TITLE
Microbial gut evaluation in an angolan paediatric population with sickle cell disease

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#452]
Microbial gut evaluation in an angolan paediatric population with sickle cell disease - Mariana Delgadinho – J Cell Mol Med.
https://onlinelibrary.wiley.com/doi/10.1111/jcmm.17402

**Comment by azizgueye47** [comment]
hi, I would like to work on this project @SvetlanaUP

**Comment by SvetlanaUP** [comment]
This paper is under curation by @azizgueye47 
@Nathcynthia please select other one.

**Comment by AleruDivine** [comment]
Hi @azizgueye47, hope you're doing well!

I wanted to check in and see how your curation is progressing. I'd be happy to help if you're having any challenges.

Thanks!

**Comment by AleruDivine** [comment]
Hello @azizgueye47, I'm checking in again. This study is yet to be added on BugSigDB, are you having any challenges curating this paper? I'll be more than happy to help you out. 

Having gone through this paper briefly, I identified one experiment with signatures to be curated. Please feel free to reach out to me on Slack if you need help. @AleruDivine 

In case you have difficulty getting the PMID, here's the [PubMed](https://pmc.ncbi.nlm.nih.gov/articles/PMC9639033/) link to the article, which also contains the PMID = 36168945

 Thank you so much!

**Comment by TheTosin** [comment]
Hi @azizgueye47 I would like to know if you need assistance on creating this study.

16s, illumina.
Group 0: 36 Healthy siblings
Group 1: 36 SCA patients.

Figure 5 seems curatable.
Relative abundance of the ten most prevalent bacterial genera between SCA children and corresponding healthy siblings.

You can reach me at @Adeshile Oluwatosin on slack.
We can collaborate to make this curation faster.
I hope to hear from you.

**Comment by SvetlanaUP** [comment]
@TheTosin please note Figure 5 is not of BugSigDB interest since we are curating differential abundances not prevalence.

Since @AleruDivine was the first one asking for this curation, it's assigned to Aleru.
@TheTosin, you can do its peer review if you are still interested.

**Comment by TheTosin** [comment]
Thank you for clarifying @SvetlanaUP 
I would be interested in collaborating with @AleruDivine

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP
I'll get started on curating the study.

I'll be sure to tag you once I'm finished @TheTosin

**Comment by AleruDivine** [comment]
Good evening @SvetlanaUP I'd like to put this study up for review.
Link: https://bugsigdb.org/Study_1183

**Comment by SvetlanaUP** [comment]
@KateRasheed https://github.com/KateRasheed could you please do review of this curation?

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP . I would get on it.

**Comment by AleruDivine** [comment]
Thanks again for the review @KateRasheed 
I’ve changed the following:
1. Study design has been changed from **case-control** to **cross-sectional observational, not case-control**.
2. Group 1 name has been updated to **Sickle Cell Anaemia Children**. 
3. MHT correction has been updated to **NO** (my apologies for the omission).

As for **Clostridium XI**, this isn’t missing. It is resolved as [**Peptostreptococcaceae**](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=186804&lvl=3&keep=1&srchmode=1&unlock) with Taxonomy ID 186804. 

@SvetlanaUP In addition, I also updated the alpha diversity (Shannon Index) I missed initially in experiment 1 between siblings and SS groups. 

Thank you so much @KateRasheed 😊

**Comment by KateRasheed** [comment]
Thanks for the changes @AleruDivine . 

@SvetlanaUP This study has been reviewed and everything is good.
