### ISSUE TITLE
Antenatal gut microbiome profiles and effect on pregnancy outcome in HIV infected and HIV uninfected women in a resource limited setting

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#455]
Antenatal gut microbiome profiles and effect on pregnancy outcome in HIV infected and HIV uninfected women in a resource limited setting - Panashe Chandiwana – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-022-02747-z

**Comment by TheTosin** [comment]
Hello @SvetlanaUP can this issue also be assigned to me.

**Comment by TheTosin** [comment]
Hi @SvetlanaUP This paper is ready for review.

Can I request for another article to be assigned to me?

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1168 ready for review.

**Comment by SvetlanaUP** [comment]
@TheTosin please help other applicants to finalize their "assigned" curations.

**Comment by TheTosin** [comment]
@SvetlanaUP i am currently collaborating with someone, i will request to collaborate with more people.

Thank you

**Comment by TheTosin** [comment]
@SvetlanaUP kindly help remove the tag, I would like to make some changes in this study. 🙏

**Comment by TheTosin** [comment]
Hello @SvetlanaUP Apologies for the delay.

https://bugsigdb.org/Study_1168
The study is ready for review now!

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . Can I review this please?

**Comment by SvetlanaUP** [comment]
@KateRasheed assigned. Please also put your name in the table, next to this issue.

**Comment by KateRasheed** [comment]
Good afternoon @TheTosin . Welldone on this great curation. 

Here are some few things I would like you to correct on the study:

- For experiment 1, please use the full name of HIV. 
- The data transformation for MaAsLin2 is arscine square root.
- For experiment 3, kindly add  (Viral Load ≤ 1000 copies/ml) to group 0, and  (Viral Load > 1000 copies/ml) to group 1.

Thank you so much.

**Comment by TheTosin** [comment]
Thank you so much @KateRasheed All corrections has been made to the study.

**Comment by KateRasheed** [comment]
Thank you so much for the corrections done. @TheTosin 

@SvetlanaUP Everything is good now.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1168 reviewed.
