### ISSUE TITLE
A signature of Prevotella copri and Faecalibacterium prausnitzii depletion, and a link with bacterial glutamate degradation in the Kenyan colorectal cancer patients

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#456]
A signature of Prevotella copri and Faecalibacterium prausnitzii depletion, and a link with bacterial glutamate degradation in the Kenyan colorectal cancer patients – Sarah Obuya – J Gastrointest Oncol.
https://jgo.amegroups.org/article/view/67507/html

**Comment by IfeanyiSam** [comment]
@SvetlanaUP I'd like to work on this paper

**Comment by IfeanyiSam** [comment]
@SvetlanaUP  the study is ready for review
https://bugsigdb.org/Study_1192

**Comment by KateRasheed** [comment]
Good afternoon @IfeanyiSam @SvetlanaUP . Please can I have the supplementary figures of this article. It was referenced in the paper but I can't see it in the article.

**Comment by SvetlanaUP** [comment]
Here you go: 
[JGO-22-116-Supplementary.pdf](https://github.com/user-attachments/files/18239798/JGO-22-116-Supplementary.pdf)

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP

**Comment by KateRasheed** [comment]
Good afternoon @IfeanyiSam . Great job on this curation. Just a few things to correct on this:

- Please put the MHT correction as No.
- In experiment 1 signature 2, YS2 is rumen bacterium YS2 with the taxid 209265 from Google search.

Thank you so much

**Comment by IfeanyiSam** [comment]
@KateRasheed Thank you for the observations. The corrections have been made. Kindly review
Happy Holidays

**Comment by KateRasheed** [comment]
Good morning @IfeanyiSam . Thank you for effecting these corrections and happy holidays 💃.

@SvetlanaUP This study has been reviewed. Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1192 reviewed.
