### ISSUE TITLE
Analysis of subgingival microbiome of periodontal disease and rheumatoid arthritis in Chinese: A case-control study

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#46]
Initiated at https://bugsigdb.org/Study_708. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by sopeadeniji** [comment]
@lwaldron @cmirzayi @ftzohra22
Please, I will like to complete study 708

**Comment by cmirzayi** [comment]
Hi @sopeadeniji I see you are claiming this one as well as: https://github.com/waldronlab/BugSigDBcuration/issues/48. Could you please choose one to start? We'd like to review your work first before you perform multiple curations. Thank you!

**Comment by sopeadeniji** [comment]
@cmirzayi . It's now been curated at https://bugsigdb.org/Study_708

**Comment by sopeadeniji** [comment]
@cmirzayi  please review https://bugsigdb.org/Study_708. Thanks.

**Comment by Mehak-4545** [comment]
@lwaldron @cmirzayi  I would like to take up this study please, can it be assigned to me?

**Comment by cmirzayi** [comment]
Hi @sopeadeniji  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by sopeadeniji** [comment]
Hi Chloe,

Please, open up the curation for other curators to finish. I have other priorities at this time and can no longer work on BugSigDB project.

Best,

Sophy


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by atrayees** [comment]
I have finished this curation. Also @cmirzayi @ftzohra22 @lwaldron could you please delete signatures 3 and 4 for Experiment 1? I have combined all the signatures for this experiment into Signatures 1 and 2. Thank you!
