### ISSUE TITLE
Distinctive Gut Microbiota Alteration Is Associated with Poststroke Functional Recovery: Results from a Prospective Cohort Study

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#460]
Distinctive Gut Microbiota Alteration Is Associated with Poststroke Functional Recovery: Results from a Prospective Cohort Study – Yini Dang – Neural Plasticity
https://onlinelibrary.wiley.com/doi/10.1155/2021/1469339

**Comment by Tino-code07** [comment]
Hello @SvetlanaUP  may I be assigned this issue.

**Comment by Rahila-me** [comment]
@Tino-code07  Hope you are well. I am reaching out to you so that we can collaborate and get this curation done. If you need help feel free to reach out. 
Thank you

**Comment by Rahila-me** [comment]
@Tino-code07  Hope you are well. I am reaching out to you so that we can collaborate and get this curation done. If you need help feel free to reach out. 
Thank you

**Comment by Rahila-me** [comment]
@Tino-code07  Hope you are well. I am reaching out to you so that we can collaborate and get this curation done. If you need help feel free to reach out. 
Thank you

**Comment by Tino-code07** [comment]
@Rahila-me thank you will surely reach out when I need assistance.

**Comment by SvetlanaUP** [comment]
@Tino-code07 I see that the study was not even created yet. Feel free to reach out your colleagues and ask for help in Slack.

**Comment by Tino-code07** [comment]
@SvetlanaUP I had trouble adding my study automatically but I ended up doing it manually and I added the experiment but I am still working on adding the signatures. I am now confused if the study is reflecting to you as not created yet. I would appreciate any help. Thank you

**Comment by Rahila-me** [comment]
@Tino-code07 I saw what you did wrong can i help out. you created a study without adding the PMID. That's why is not reflecting in BugSigDB

**Comment by Tino-code07** [comment]
@Rahila-me I failed to identify the PMID on the study and just added the doi. I would appreciate your help doing so!

**Comment by Tino-code07** [comment]
@Rahila-me is it the one labelled article ID 1469339

**Comment by Tino-code07** [comment]
@Rahila-me Thank you, indeed I had left out that article ID, now I have added it and my study is now reflecting on BugSigDb.

**Comment by SvetlanaUP** [comment]
I see it now as https://bugsigdb.org/Study_1170
Do not forget to claim it for review here, once it's ready.

**Comment by Tino-code07** [comment]
@SvetlanaUP my study is now ready for review.

**Comment by Tino-code07** [comment]
@SvetlanaUP 
After attending today's office hour I noticed some mistakes that I made in my curation. Is it possible to ask for my issue to be untagged from 'needs review' so that I can make the necessary edits.

**Comment by SvetlanaUP** [comment]
@Tino-code07 when the GitHub issue with your curation is claimed for review and got a label "needs review" any edits from this point are not allowed.

**Comment by Tino-code07** [comment]
@SvetlanaUP I noticed that **not** all my signatures are loaded when I click on my study link (https://bugsigdb.org/Study_1170). Signature_2 for experiment 2 is missing. However, it only appears when I enter (https://bugsigdb.org/Study_1170/Experiment_2/Signature_2). I have tried refreshing the page but still no change yet. Please help!

**Comment by Peacesandy** [comment]
Hi @Tino-code07 this is an excellent curation attempt 🎈



**CURATION RESULTS**

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on factors (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of Signatures identified correctly (2 points): 2
Correct use of NCBI taxonomy (2 points): 2

**Total (maximum 23 points): 23**

**Comment by Peacesandy** [comment]
@SvetlanaUP  https://bugsigdb.org/Study_1170 reviewed

**Comment by Tino-code07** [comment]
@Peacesandy Thank you for the review!
