### ISSUE TITLE
Dysbiosis of Gut Microbiota and Short-Chain Fatty Acids in Acute Ischemic Stroke and the Subsequent Risk for Poor Functional Outcomes

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#464]
Dysbiosis of Gut Microbiota and Short-Chain Fatty Acids in Acute Ischemic Stroke and the Subsequent Risk for Poor Functional Outcomes - Chuhong Tan – Journal of Parenteral and Enteral Nutrition

https://aspenjournals.onlinelibrary.wiley.com/doi/10.1002/jpen.1861

**Comment by Ini-25** [comment]
I would like to work on this 
Inimfon Ebong

**Comment by Ini-25** [comment]
Thank you

**Comment by MyleeeA** [comment]
Hi @Ini-25 

Trust you are doing good
I would like to know how your curation is going

I am currently done with my second contribution and I am available to collaborate or offer peer review, if you are experiencing any blockers please let me know 

Thank you 🙏🏾

**Comment by Ini-25** [comment]
Hi Mylee thank you for the offer I'll certainly reach out to you. I'm
currently handling a family health emergency so I'm preoccupied but I'll
reach out to you if I have any issues.

**Comment by MyleeeA** [comment]
Okay @Ini-25 

I hope you sort out your family emergency

**Comment by Rahila-me** [comment]
@Ini-25 Hope your family is well now. Whenever you are ready i am open to collaboration along side @MyleeeA .
Thank you

**Comment by Rahila-me** [comment]
@SvetlanaUP this article has been curated but no signature: https://bugsigdb.org/Study_1140
Can i and @MyleeeA of course with the origin curators permission @Ini-25 go ahead and complete it as collaboration. I have to look it up on the wiki

**Comment by SvetlanaUP** [comment]
@MyleeeA @Rahila-me please finalize this curation.

**Comment by Ini-25** [comment]
> @MyleeeA @Rahila-me please finalize this curation.
@SvetlanaUP should I not work on it anymore?

**Comment by SvetlanaUP** [comment]
My apologies @Ini-25, I dropped your name as the original curator. Please see the update above.

**Comment by Ini-25** [comment]
ok thank you @SvetlanaUP

**Comment by Ini-25** [comment]
hello @SvetlanaUP https://bugsigdb.org/Study_1140 this curation is ready for review

**Comment by Folakunmi21** [comment]
Hello @Ini-25 Here is the result of your curation:

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 1

Total (maximum 23 points): 19.5


1. Bradyrhizobiaceae should not be curated as unclassified in experiment 2. It can be found as a heterotypic synonym under NCBI ID  41294.
2. Remove spearman correlation as a statistical test in the experiments curated from fig 3. 
3. For experiment 5, Lactobacillacae should be curated as the one with NCBI ID 33958, not unclassified.
4. The comparison between the mild group and the moderate group (in fig 3) only occurred in Roseburia and Akkermansia. Adjust the signatures in experiment 6
5. The comparison between the mild group and the severe group (in fig 3) only occurred in Roseburia. Adjust the signatures in experiment 7
6. Mild and moderate were not directly compared. Experiment 8 is not needed (you were not penalized for this)
7. For experiments 5-7, at the end of the signature source description, add “according to taxonomic classification and LEfSe analysis”
8. For experiments comparing 2 stroke groups (e.g mild vs severe), “stroke outcome severity measurement” should be the condition. 

@SvetlanaUP graded

**Comment by SvetlanaUP** [comment]
@Ini-25 @MyleeeA @Rahila-me thank you for your contribution. Please make corrections based on @Folakunmi21 feedback, thank you!

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP 

Thank you @Folakunmi21

**Comment by Ini-25** [comment]
Thank you @Folakunmi21 
The corrections will be made @SvetlanaUP

**Comment by Rahila-me** [comment]
@Folakunmi21 Thanks for the corrections @SvetlanaUP Noted

**Comment by MyleeeA** [comment]
Hi @Folakunmi21 

This curation is ready for a second review https://bugsigdb.org/Study_1140
Thank you 

@Rahila-me @Ini-25

**Comment by Folakunmi21** [comment]
All changes reviewed, thank you all.
