### ISSUE TITLE
Metagenomic analysis reveals linkages between cecal microbiota and feed efficiency in Xiayan chickens

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#466]
Metagenomic analysis reveals linkages between cecal microbiota and feed efficiency in Xiayan chickens - Wenya Du –
 Poultry Science
https://www.sciencedirect.com/science/article/pii/S0032579120307288

**Comment by TheTosin** [comment]
Hello @SvetlanaUP can this issue be assigned to me?

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This issue is ready for review.

https://bugsigdb.org/Study_1204

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This issue is ready for review.

https://bugsigdb.org/Study_1204

**Comment by AleruDivine** [comment]
Well done on your curation @TheTosin 👏🏽👏🏽

I just have a few suggestions I’d like you to consider:

1. **Group names**: Please correct (H-FE) and (L-FE) to (M-HFE) and (M-LFE) for experiment 1 and (F-HFE) and (F-LFE). Also correct these in the signature descriptions as well.
2. **Additional experiments**: Table 2 shows relative abundance results of the dominant phyla and genera in the cecum of the high and low FE groups of male and female chickens. I believe these should be curated as different experiments with Kruskal-Wallis as the statistical test used.
3. **Signatures**: For Signature 2 in Experiment 1, I noticed you curated unclassified Lentisphaerota. When I checked Figure 2A (red bars), it shows:
Order: o_Unclassified_Lentisphaerae (ID: 1674875)
Class: c_Unclassified_Lentisphaerae (ID: 1368584)
Family: f_Unclassified_Lentisphaerae (ID: 2461379).
What you’ve curated (unclassified Lentisphaerota) falls under the phylum Lentisphaerota, but the figure specifically represents the order, class, and family levels instead.

Let me know what you think or if anything is unclear
Thank you so much!

**Comment by TheTosin** [comment]
Hello @AleruDivine i would go over the corrections suggested for this study. Thank you

**Comment by TheTosin** [comment]
Hello @AleruDivine all corrections have been made to the study. Kindly review

**Comment by AleruDivine** [comment]
Well done @TheTosin 
I removed "uncultured Oscillatoria sp." as I could not find it in table 1 and added "_Elusimicrobiota_" which was initially omitted.
I also removed "_Actinomycetota_" from signature 1 in experiment 4. This is only increased in the F-LFE group.

@SvetlanaUP this review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1204 reviewed.
