### ISSUE TITLE
Community composition of cecal microbiota in commercial yellow broilers with high and low feed efficiencies

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#467]
Community composition of cecal microbiota in commercial yellow broilers with high and low feed efficiencies - Yun Huang – Poultry Science
https://www.sciencedirect.com/science/article/pii/S0032579121000304

**Comment by AleruDivine** [comment]
Good morning, @SvetlanaUP! 
I've completed all my individual curations and would love to be assigned this paper. Thank you!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP, I'd like to put this study up for review
https://bugsigdb.org/Study_1197
Thank you so much!

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . Please I can't access the supplementary figures.  Can you help me with it please?

**Comment by SvetlanaUP** [comment]
Sure, here you go [1-s2.0-S0032579121000304-mmc1.docx](https://github.com/user-attachments/files/18227742/1-s2.0-S0032579121000304-mmc1.docx)

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP . I needed to be sure I'm not missing out on anything.

Amazing job @AleruDivine . Nothing to correct on this study.

This review is complete @SvetlanaUP

**Comment by AleruDivine** [comment]
Thank you so much for the review @KateRasheed

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1197 reviewed.
