### ISSUE TITLE
Role of the Gut Microbiota in the Increased Infant Body Mass Index Induced by Gestational Diabetes Mellitus

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#471]
Role of the Gut Microbiota in the Increased Infant Body Mass Index Induced by Gestational Diabetes Mellitus – Qingyi Zhu – mSystems

https://journals.asm.org/doi/full/10.1128/msystems.00465-22

**Comment by Rahila-me** [comment]
@SvetlanaUP @Scholarpat @cmirzayi @lwaldron 
This paper is ready for review: 
https://bugsigdb.org/Study_1117
https://bugsigdb.org/Study_1117/Experiment_1
https://bugsigdb.org/Study_1117/Experiment_1/Signature_1
https://bugsigdb.org/Study_1117/Experiment_1/Signature_2
Thank you

**Comment by Scholarpat** [comment]
An excellent curation! @Rahila-me  Kudos!⭐

Something to note:
Samples were collected from infants born to women with GDM and not the women themselves. I've corrected the group 1 definition to reflect this.

**CURATION RESULTS:**

| S/N | Criteria                                                                 | Total Points | Points Earned |
|-----|--------------------------------------------------------------------------|-----------------|---------------|
| 1   | All elements marked "Needs review" (none "Incomplete")                   | 1               | 1             |
| 2   | Correct study design                                                      | 1               | 1             |
| 3   | Entered all relevant experiments and no irrelevant experiments            | 1               | 1             |
| 4   | Body site correctly identified (i.e. does not include multiple sites)     | 1               | 1             |
| 5   | Condition entered according to contrast (correct EFO ontology)            | 1               | 1             |
| 6   | Contrast groups correctly identified                                      | 1               | 1             |
| 7   | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)                 | 1               | 1             |
| 8   | Antibiotic exclusion correctly identified                                 | 1               | 1             |
| 9   | Correctly identified sequencing details                                   | 2               | 2             |
| 10  | Identified correct statistical test                                       | 1               | 1             |
| 11  | Identified MHT correction                                                 | 1               | 1             |
| 12  | Correctly recorded matched on factors                                     | 1               | 1             |
| 13  | Entered correct number of statistical tests per experiment                | 1               | 1             |
| 14  | All diversity measures identified                                         | 1               | 1             |
| 15  | Diversity results correctly entered as increased/decreased/unchanged      | 1               | 1             |
| 16  | All signature sources correctly identified (-1 for each error)            | 2               | 2             |
| 17  | Abundance direction correctly selected                                    | 1               | 1             |
| 18  | Members of Signatures identified correctly                                | 2               | 2             |
| 19  | Correct use of NCBI taxonomy                                              | 2               | 2             |


Total: 23/23

Hi @SvetlanaUP Study 1117 is complete. Please kindly mark as 'Reviewed'.

**Comment by Rahila-me** [comment]
@Scholarpat Thank you for your kind review, I have also noted what you pointed out.
@SvetlanaUP Thank you too
and Good morning from Nigeria, do have a lovely day ahead

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1117 reviewed.
