### ISSUE TITLE
Gut microbiota alterations in response to sleep length among African-origin adults

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#474]
Gut microbiota alterations in response to sleep length among African-origin adults – Na Fei – PlosOne
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0255323

**Comment by Eniola-C** [comment]
Hi Scholarpat and SvetlanaUp, 
I will like to be assigned to curate this paper. 
I am done with my first contribution. Thank you.

**Comment by azizgueye47** [comment]
hi, I would like to work on this project

**Comment by SvetlanaUP** [comment]
@azizgueye47 you have already been assigned to https://github.com/waldronlab/BugSigDBcuration/issues/452

**Comment by AishatBolarinwa** [comment]
Greetings 
I would like to be assigned to this project please
Thank you.

**Comment by AishatBolarinwa** [comment]
Greetings.
This paper is ready for review please.

https://bugsigdb.org/Study_1158

https://bugsigdb.org/Study_1158/Experiment_1
https://bugsigdb.org/Study_1158/Experiment_1/Signature_1
https://bugsigdb.org/Study_1158/Experiment_1/Signature_2

https://bugsigdb.org/Study_1158/Experiment_2
https://bugsigdb.org/Study_1158/Experiment_2/Signature_1

https://bugsigdb.org/Study_1158/Experiment_3
https://bugsigdb.org/Study_1158/Experiment_3/Signature_1
https://bugsigdb.org/Study_1158/Experiment_3/Signature_2

Thank you.

**Comment by KateRasheed** [comment]
Good afternoon @AishatBolarinwa . Great job on this curation. However, I would like to point out some corrections to be made on the study:

1. For the confounder, change gender to sex.
2. The statistical test used is ANCOM with MHT correction. Data transformation is Centered log ratio. 
3. Body site is Feces alone.
4. For signature 2 in experiment 1, please remove Prevotella and add Oscillospira, 
5. Experiment 2:  Please remove Oscillospira from the signature.
6. Experiment 3:  Please remove Catenibacterium and add Prevotella and Dialister to increased abundance. Also add Dialister to decreased. 

Please let me know if you would need my help in correcting the curation. Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1158 reviewed.
