### ISSUE TITLE
Feeding-Related Gut Microbial Composition Associates With Peripheral T-Cell Activation and Mucosal Gene Expression in African Infants

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#477]
Feeding-Related Gut Microbial Composition Associates With Peripheral T-Cell Activation and Mucosal Gene Expression in African Infants - Lianna F Wood – Clinical Infectious Diseases

https://academic.oup.com/cid/article/67/8/1237/4961341

**Comment by Zzee2** [comment]
Zara Adwan

**Comment by TheTosin** [comment]
Hello @Zzee2 

How is your day going?
Do you need help with curating this issue?
I am happy to assist.

Feel free to reach me as Adeshile Oluwatosin on slack.

**Comment by KateRasheed** [comment]
Hello @Zzee2 . I see that you've created a study and added a study design; however, you are yet to add experiment(s) and signature(s). Just as @TheTosin mentioned, we are happy to collaborate with you in the completion of this curation. Kindly drop your slack name so we can reach out.

**Comment by Zzee2** [comment]
> Hello @Zzee2
> 
> How is your day going? Do you need help with curating this issue? I am happy to assist.
> 
> Feel free to reach me as Adeshile Oluwatosin on slack.

Hi, thanks @TheTosin. i am Okay. appreciate the offer

**Comment by Zzee2** [comment]
> Hello @Zzee2 . I see that you've created a study and added a study design; however, you are yet to add experiment(s) and signature(s). Just as @TheTosin mentioned, we are happy to collaborate with you in the completion of this curation. Kindly drop your slack name so we can reach out.

Hi @KateRasheed thanks. I am Okay, had some technical challenges earlier which delayed me, but am fine now. appreciate the offer.

**Comment by TheTosin** [comment]
@Zzee2 Noted! Feel free to reach out if you experience any blockers still.

Have fun curating.

**Comment by Zzee2** [comment]
@SvetlanaUP So I was done with the paper, took me a bit long cause I had some technical challenge from my end, however, now that  am done with the paper,  I discovered that the paper is probably curated in BugSigDB cause I got this error
![image](https://github.com/user-attachments/assets/65ec6401-f7f5-4f8f-800f-7490a2c80786)

I still went ahead and filled it without the PMID just incase, you can check it out as well. https://bugsigdb.org/Study_1174

**Comment by KateRasheed** [comment]
https://bugsigdb.org/Study_1107

Hi @Zzee2 I see that your article has been curated in this study.

**Comment by TheTosin** [comment]
Hello @Zzee2 From the study, these are my observations; Firstly, see a link to the curation policy: https://bugsigdb.org/w/index.php?title=Curation_Policy&veaction=edit&section=9
 
1. I believe the correct condition is HIV mother to child transmission(only one condition should be curated). 
Statement “ We performed a prospective, longitudinal study of infants from a high-HIV-prevalence, low-income setting in South Africa.”

Here, you can see they performed the study on infants already with HIV not those susceptible.

2. I see they mentioned feces and mouth mucosa as body sites. I believe it’s best to curate both body sites as different experiments. But in this case, I can only see significant results using feces(stool) and blood, so the rest should be deleted.
- Stool; V3-V4
“ The V4 region of the 16S rRNA gene was amplified using universal 515F/806R primers [16]. Pooled triplicate samples were purified (Agencourt AMPure XP beads, Beckman Coulter). Equimolar amplicon pools of 96 samples were quantified (KAPA Library Quantification kit, Kapa Biosystems) and sequenced from both ends (Illumina MiSeq platform, v3 chemistry).”

4. Antibiotics exclusion should be left empty. There’s no need to write the statement.

5. Group 0 is non-exclusively fed infants. Group 1 is exclusively fed infants(this is the exposed group in the study).

6. MHT is yes.
“ Adjustment for multiple comparisons was performed using the Holm step-down approach [24] for immunological data and Benjamini-Hochberg [25] for microbiota data.”

7. There should be no details in LDA score: it’s for LeFSe results only.

8. I can’t see any confounders or matched on in the study as well. Also alpha-diversity faith was mentioned ( Figure 1B).

9. There should be signatures in each experiments 
In your study, Figure 4B is curatable. Deseq (0.05)
Here, only Akkermansia muciniphila is in the increased abundance. Group 0 and 1 is different here. 
“ Linear combinations of all immunological factors measured did not significantly improve the model compared to HLA-DR alone (permutational ANOVA P = .035). Using DeSeq2 [27], we found that counts of Akkermansia muciniphila in stool.”

10. Here, I will state the Figures and Tables I see curatable. Also number of experiments I believe your study should have.

- body site: feces- supplementary Figure 2. [ 2 different experiments for 6 weeks and 14 weeks (for non-exclusively breast fed and breasted infants).]
Unsure about curating an experiment for infants from birth as they didn’t state the sample size specifically for EBF and Non-EBF.(My opinion).

- body site: blood(serum) - Figure 4B.

I apologize that it’s lengthy

**Comment by SvetlanaUP** [comment]
@Zzee2 is your curation ready for review?

**Comment by SvetlanaUP** [comment]
@KateRasheed @TheTosin could you please clarify the status of this curation(s)?

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . I don't think it is ready for review. @Zzee2 hasn't effected the corrections @TheTosin made.

**Comment by TheTosin** [comment]
@SvetlanaUP The last time I reviewed the study link, I saw that @Zzee2 had a lot to correct. 
He insisted he does not need help, that’s why I dropped my view here.

Okay, I will finalize the curation.
Thank you

**Comment by TheTosin** [comment]
@SvetlanaUP This study is ready for review.

https://bugsigdb.org/Study_1107

**Comment by SvetlanaUP** [comment]
@KateRasheed could you please do review of this curation?

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP . I would get on it.

**Comment by KateRasheed** [comment]
Hello @TheTosin . 

Welldone on your curation. Here are a few corrections to be made on the study:

1. For the group names for experiment 1 and 2, please add the time of the visit (6 weeks, 14weeks)
2. Streptococcus luteciae has a new name: Streptococcus lutetiensis with the ID 150055
3. For experiment 3, please state the full meaning of HLA-DR as Human Leukocyte Antigen - DR isotype.
4. You should add Streptococcus and Bacteroides in the supplementary figure 2 to experiment 1 and 2. However, you can leave this pending when we confirm during the next office hours if all taxa should be curated or only the lowest rank.
5. For Signature 2 in Experiment 2, use Supplementary figure 2 as the source.

Thank you @SvetlanaUP

**Comment by TheTosin** [comment]
Hello @KateRasheed Thank you so much for the review.

1. I’ve specified this in the group names.

2. As of the time of curation, the taxa was unresolved. Changes has been made.

3. Also, the full meaning of the study wasn’t mentioned in the article. However, I’ve added it to the curation.

4. I believe the curation is accurate as well as both Taxa were initially curated in the stated experiments. Hence, the specification of the text as a source for better clarification. “Bacteroides” was initially curated as Experiment 2/Signature 2 and Streptococcus was initially curated  in Experiment 1 and 2. No changes have been made to this.

5. For the experiments, i believe the text and the Figure is to be mentioned as the source. I have also added that for the stated signature.

**Comment by KateRasheed** [comment]
Hello @TheTosin . I noticed that Streptococcus is yet to be added to experiment 1 and 2 of this study.

**Comment by TheTosin** [comment]
Hello @KateRasheed could you kindly be more specific.

As intially stated, Experiment 1/signature 1: Streptococcus lutetiensis.

Experiment 2/signature 1: Streptococcus Lactarius

These two taxa were intially curated in the study, both source from Supplementary Figure 2.

**Comment by KateRasheed** [comment]
@TheTosin I mentioned Streptococcus from Supplementary Figure 1 and 2. It's different from Streptococcus Lutetiencis and Streptococcus Lactarius

**Comment by TheTosin** [comment]
@KateRasheed The Streptococcus mentioned is both Taxa curated. Hence, why the Text should be referenced as well as a source.

“At 6 weeks, EBF infants had lower relative abundance of Streptococcus luteciae (Figure 1 and [Supplementary Figure 2]”

At 14 weeks, EBF infants had higher relative abundance of Streptococcus lactarius, as well as Actinomyces and Atopobium

Kindly go over the study again to have a better understanding. Except, if you are suggesting not curating it in full and actually just curating it as streptococcus, which I believe doing this won’t allow for specification of the particular streptococcus.

**Comment by KateRasheed** [comment]
I see what you mean. It's fine that way. In the paper, the exact species was stated but this was not shown in the figures.

Welldone @TheTosin 

This study has been reviewed. Everything checks out @SvetlanaUP 

Thank you so much

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . Please this study has been reviewed.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1107 reviewed.
