### ISSUE TITLE
Gut microbiome of treatment-naïve MS patients of different ethnicities early in disease course

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#478]
Gut microbiome of treatment-naïve MS patients of different ethnicities early in disease  – R E Ventura – Scientific Reports

https://www.nature.com/articles/s41598-019-52894-z

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP Can I be assigned this study to curate?

I'm done with my first contribution

**Comment by MyleeeA** [comment]
Hi @SvetlanaUP 
This [curation](https://bugsigdb.org/Study_1111) is ready for review

**Comment by Omabekee** [comment]
Excellent curation! @MyleeeA  Keep it up! ⭐

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |    1    |
| 2    | Correct study design                                                 | 1   |    1    |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |    1    |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |   1     |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |   1     |
| 6    | Contrast groups correctly identified                                 | 1   |    1    |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |    1    |
| 8    | Antibiotic exclusion correctly identified                            | 1   |   1     |
| 9    | Correctly identified sequencing details                              | 2   |   2     |
| 10   | Identified correct statistical test                                  | 1   |   1     |
| 11   | Identified MHT correction                                            | 1   |    1    |
| 12   | Correctly recorded matched on factors                                | 1   |     1   |
| 13   | Entered correct number of statistical tests per experiment           | 1   |    1    |
| 14   | All diversity measures identified                                    | 1   |    1    |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |    1    |
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |     2   |
| 17   | Abundance direction correctly selected                               | 1   |    1    |
| 18   | Members of Signatures identified correctly                           | 2   |  2      |
| 19   | Correct use of NCBI taxonomy                                         | 2   |   2     |
|      | TOTAL                                                                | 23  |    23    |

Hi @SvetlanaUP , Review of Study 1111 is complete. Please kindly mark as 'Reviewed'.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1111 reviewed.

**Comment by MyleeeA** [comment]
Thank you so much for this review @Omabekee 
Thank you too @SvetlanaUP 

Happy to keep up the good work and take on more curations 😊
