### ISSUE TITLE
Dysbiosis in the Gut Microbiota of Patients with Multiple Sclerosis, with a Striking Depletion of Species Belonging to Clostridia XIVa and IV Clusters

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#479]
Dysbiosis in the Gut Microbiota of Patients with Multiple Sclerosis, with a Striking Depletion of Species Belonging to Clostridia XIVa and IV Clusters - Sachiko Miyake – PlosOne

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0137429

**Comment by Rahila-me** [comment]
@SvetlanaUP please maybe assigned this issue

**Comment by Rahila-me** [comment]
Ok thank you @SvetlanaUP

**Comment by Rahila-me** [comment]
@SvetlanaUP @Scholarpat 
Please this too is ready for review, But as third contribution
https://bugsigdb.org/Study_1131

**Comment by Peacesandy** [comment]
@SvetlanaUP Please can I review this study

**Comment by SvetlanaUP** [comment]
Hi @Peacesandy, there are applicants waiting for a review of their second contribution. (@Rahila-me got their feedback for it already and move on with more contributions.)

Please do select "needs review" and "second contribution". Thanks!

**Comment by Peacesandy** [comment]
Okay, @SvetlanaUP 
Got it.

**Comment by KateRasheed** [comment]
Good morning @Rahila-me . Great job on this curation. However, there are some things I would like you to correct in this curation:

- For the antibiotics exclusion, please leave it blank
- The study is a cross-sectional not case-control study (an element of case-control is the presence of matched on variables)
- Chao1 is unchanged in experiment 1 
- You didn't curate Fig. 4 which has significance taxa(Faecalibacterium, Anaerostipes, Prevotella)
- Signature 1 and 2 sources should be Fig. S2, Table 1.

For experiment 2, Bacteroides coprocola, Meganomonas funiformis and Bacteroides coprophilus were increased in abundance as well. Also, please remove the meganomonas funiformis YIT 11815 in signature 2 and replace it with "meganomonas funiformis"; do the same for Prevotella copri; please add Streptococcus thermophilus and Streptococcus salivarius to signature 2 as they were decreased as well. 

Please remove Lactobacillus rogosae and Roseburia sp.1120 from signature 2 in experiment 1 and 2; they are not in the sources referenced. I see that you used the OTU ID on NCBI; it's actually not the same(it's stated that the OTU is unmapped). It's best you use the repeated specie. 

Thank you so much.

**Comment by Rahila-me** [comment]
@KateRasheed let me fix them, Thank you for the review

**Comment by Rahila-me** [comment]
@KateRasheed All correction fixed: https://bugsigdb.org/Study_1131,
Please this is now ready for second review

**Comment by KateRasheed** [comment]
Thank you so much @Rahila-me for effecting this corrections. I noticed you curated another experiment. The taxa in Fig. 4 are meant to be added to signature 2 of experiment 1 since they are decreased in MS20 compared to HC20.

I'll correct it from my end.

Thank you so much.

@SvetlanaUP Kindly delete experiment 3 from this study.

**Comment by SvetlanaUP** [comment]
Study 1131/Experiment 3 deleted.

**Comment by KateRasheed** [comment]
This study has been reviewed @SvetlanaUP . Thank you so much.

**Comment by Rahila-me** [comment]
@KateRasheed ok..Thank you

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1131 reviewed.
