### ISSUE TITLE
Altered Virome and Bacterial Microbiome in Human Immunodeficiency Virus-Associated Acquired Immunodeficiency Syndrome

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#480]
Altered Virome and Bacterial Microbiome in Human Immunodeficiency Virus-Associated Acquired Immunodeficiency Syndrome - Cynthia L Monaco – Cell Host & Microbe

https://www.cell.com/cell-host-microbe/fulltext/S1931-3128(16)30052-X

**Comment by Aeeshah1** [comment]
Hello, I'd like to be assigned to this please

**Comment by vandana123maddi** [comment]
Hello ma'am @SvetlanaUP I'd like to be assigned please

**Comment by Ini-25** [comment]
Hello @Aeeshah1 would you like to collaborate?

**Comment by SvetlanaUP** [comment]
@Aeeshah1 I see this study is not even created yet. Please do team up with @Ini-25 and enjoy this curation together.

**Comment by KateRasheed** [comment]
Good morning @Ini-25 . Trust you are doing well? I see that you are yet to create a study on this article.

Are you experiencing any blocker you would like me to assist with?

**Comment by Ini-25** [comment]
Hi Kate, not a block necessarily I just wanted to arrange all the facts
first and I've been trying to contact Aeeshah.
I would love to collaborate

**Comment by SvetlanaUP** [comment]
@Ini-25 @KateRasheed @Aeeshah1 please do finalize this curation, thanks!

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP .

**Comment by KateRasheed** [comment]
Good afternoon @Ini-25 . I've dropped messages on slack for you since yesterday but you are yet to respond.

I mentioned that I have created a study and added experiment 1 and its signatures. We are left with experiment 2. Will you work on experiment 2 so we can finalize the curation?

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . This study is ready for review:

https://bugsigdb.org/Study_1210

@Ini-25

**Comment by KateRasheed** [comment]
Good afternoon @Aleru Divine. Please can you review this?

**Comment by AleruDivine** [comment]
Hi @KateRasheed, good afternoon. Yes I'll be happy to review this.

**Comment by SvetlanaUP** [comment]
Please bring up this question tomorrow at the team meeting, thanks!

**Comment by AleruDivine** [comment]
That’s okay @KateRasheed 
You can find the instance in Signature 1 of experiment 1. 

The reason I raised the concern is because you’ve also curated insect species, a lot of these curated species are not on the table and a lot of the signatures on the table are not curated either. That is why I’m asking where you curated from and how it is curated. I hope this is clear enough 🙏

**Comment by KateRasheed** [comment]
@AleruDivine I see what you mean. I believe the error is from my end. I was using the OTU ID thinking it represents the species/genus at the extreme. I'll rework on the signatures and get back to you when I am done.

Thank you so much.

**Comment by KateRasheed** [comment]
Good morning @AleruDivine . The taxa and abundance direction has been corrected.

Thank you so much.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1210 reviewed.
