### ISSUE TITLE
Comparison of targeted metagenomics and IS-Pro methods for analysing the lung microbiome

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#482]
Comparison of targeted metagenomics and IS-Pro methods for analysing the lung microbiome - T Goolam Mahomed – BMC Microbiology

https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02288-x

**Comment by AnushaR-star** [comment]
Hello @SvetlanaUP  and @Scholarpat  i would like to contribute could u pls assign this

**Comment by TheTosin** [comment]
Hi @AnushaR-star 

How is your day going?
Do you need help in completing this curation.
I am happy to assist.
You can as well reach me as Adeshile Oluwatosin on slack.

**Comment by KateRasheed** [comment]
Hello @AnushaR-star . Good morning to you. I see that you haven't created a study on this article. Are you experiencing any blocker? We are here to help if you need anything. Do have a great day.

**Comment by AleruDivine** [comment]
Good morning, @AnushaR-star. I hope you are doing okay. This study is yet to be added to BugSigDB, and I am wondering if you are having any difficulties with the curation.

I went through the paper this morning and identified 1 potential experiment to be curated (the comparison of targeted metagenomics and IS-Pro methods) and signatures from DESeq2 analysis. We are all available to help and collaborate to tackle the difficulties you are facing. You can reach out to me on Slack @AleruDivine or to any of the applicants who have offered to help before me.

Thank you so much!

**Comment by SvetlanaUP** [comment]
@TheTosin @AleruDivine @KateRasheed please work on this curation together.

**Comment by TheTosin** [comment]
Noted! @SvetlanaUP Good Afternoon

**Comment by AleruDivine** [comment]
Got it @SvetlanaUP thank you so much!

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP .

**Comment by TheTosin** [comment]
@AleruDivine @KateRasheed Please let’s create a group on slack for easy communication and team work 🙏

**Comment by vandana123maddi** [comment]
Good morning @AnushaR-star i found this paper intresting and  if u need any help that u think i could add value u can approach me in slack if collaboration I love to do if there is a chance do consider me ! 
Have a good day

**Comment by AleruDivine** [comment]
Hi @vandana123maddi this study has been reassigned to me, @TheTosin and @KateRasheed to work on by @SvetlanaUP. You're welcome to join us to complete the curation🤗

**Comment by SvetlanaUP** [comment]
@AnushaR-star What's the status of this curation? Thanks!

**Comment by TheTosin** [comment]
Good afternoon, @SvetlanaUP it’s ready for review

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP here is the link to the study
https://bugsigdb.org/Study_1159
Thank you so much!

**Comment by SvetlanaUP** [comment]
Great team effort! I corrected descriptions of the groups: please see how you should provide precise details and also abbreviations first time mentioned.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 22.5 |

**Comment by TheTosin** [comment]
Thank you so much @SvetlanaUP Noted.

**Comment by AleruDivine** [comment]
Duly noted! Thank you so much for the review and for the correction @SvetlanaUP. 🙏
Great work @TheTosin @KateRasheed 🙌🏽
