### ISSUE TITLE
Immune activation and inflammation in lactating women on combination antiretroviral therapy: role of gut dysfunction and gut microbiota imbalance

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#483]
Immune activation and inflammation in lactating women on combination antiretroviral therapy: role of gut dysfunction and gut microbiota imbalance - Privilege Tendai Munjoma – Frontiers in Immunology

https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2023.1280262/full

**Comment by paavni-goyal-189** [comment]
Hello @SvetlanaUP I’d like to curate this paper for my second contribution, can I contribute for this one. 

Paavni Goyal, Thanks.

**Comment by SvetlanaUP** [comment]
@paavni-goyal-189 please post your question in our dedicated Slack channel where you can share your curation with community and get the feedback. Thanks!

**Comment by AleruDivine** [comment]
Hi @paavni-goyal-189, I checked this study and I'd like to point the DOI does not automatically populate the study information but rather the PMID does this.

When you don't see the PMID in your study (not all journals include it) you can search the article on PubMed. Here, I searched for it - [Link to article](https://pubmed.ncbi.nlm.nih.gov/38045684/)

The PMID is 38045684

When you fill this in the space provided for PMID, it will automatically populate the other study information.  

I can give this a peer review to see that you are on the right path if that is okay with you.

**Comment by KateRasheed** [comment]
Hello @paavni-goyal-189. Well-done on your curation. I see the experiments and signatures added to the study. If you don't mind, I can work with you in making corrections to some omissions. Let's work together to complete this curation.

**Comment by SvetlanaUP** [comment]
@AleruDivine @KateRasheed you can work together in finalizing this curation, enjoy!

**Comment by KateRasheed** [comment]
Thank you @SvetlanaUP

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
Super excited to collaborate with you on this @KateRasheed

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP 
@KateRasheed and I would like to put this study up for review.
Thank you so much!

https://bugsigdb.org/Study_1108

**Comment by Omabekee** [comment]
Well done @KateRasheed and @AleruDivine, great curation!

Something to note: Your signature source descriptions should be more uniform (for both signatures) for all experiments. Kindly update and revert. 

- HIV-infected women were on antibiotics during the study period.

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |        1 |
| 2    | Correct study design                                                 | 1   |        1 |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |        1 |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |        1 |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |        1 |
| 6    | Contrast groups correctly identified                                 | 1   |        1 |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |        1 |
| 8    | Antibiotic exclusion correctly identified                            | 1   |        0 |
| 9    | Correctly identified sequencing details                              | 2   |        2 |
| 10   | Identified correct statistical test                                  | 1   |        1 |
| 11   | Identified MHT correction                                            | 1   |        1 |
| 12   | Correctly recorded matched on factors                                | 1   |        1 |
| 13   | Entered correct number of statistical tests per experiment           | 1   |        1 |
| 14   | All diversity measures identified                                    | 1   |        1 |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |        |
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |        2 |
| 17   | Abundance direction correctly selected                               | 1   |        1 |
| 18   | Members of Signatures identified correctly                           | 2   |        2 |
| 19   | Correct use of NCBI taxonomy                                         | 2   |        2 |
|      | TOTAL                                                                | 23  |        22 |

**Comment by SvetlanaUP** [comment]
Great team effort, @KateRasheed and @AleruDivine! Please correct curation as advised by @Omabekee.

**Comment by AleruDivine** [comment]
Thank you so much for the review 😊 @Omabekee 
I’ll proceed to update the curation with the suggestions you’ve provided. 
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
I have corrected the sources of signatures and their descriptions to be more uniform.
I'm a bit confused about the antibiotics exclusion.
We did not curate antibiotics exclusion as it was not mentioned among the exclusion criteria in the paper. Could you clarify this please @Omabekee 

Thank you so much!

**Comment by Omabekee** [comment]
Confirmed. Scores have been reviewed!

@SvetlanaUP, Study 1108 reviewed. ✅

**Comment by AleruDivine** [comment]
Thank you so much @Omabekee 😊

**Comment by KateRasheed** [comment]
Thank you so much @Omabekee @SvetlanaUP . It was amazing teaming up with @AleruDivine to finalize this curation.

**Comment by AleruDivine** [comment]
Likewise @KateRasheed! 🤗 I enjoyed working together and look forward to more collaborations!
