### ISSUE TITLE
Intestinal microbiota, microbial translocation, and systemic inflammation in chronic HIV infection

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#484]
Intestinal microbiota, microbial translocation, and systemic inflammation in chronic HIV infection – Duy M Dinh – The Journal of Infectious Diseases

https://academic.oup.com/jid/article/211/1/19/801451

**Comment by Agatha-Chineke** [comment]
I am interested in curating this work "Intestinal microbiota, microbial translocation, and systemic inflammation in chronic HIV infection #484"

I did appreciate if it is assigned to me

**Comment by Agatha-Chineke** [comment]
> Intestinal microbiota, microbial translocation, and systemic inflammation in chronic HIV infection – Duy M Dinh – The Journal of Infectious Diseases
> 
> https://academic.oup.com/jid/article/211/1/19/801451

Please assigned this work to me for curation 

Thank you

**Comment by KateRasheed** [comment]
Hi @Agatha-Chineke . How is this curation going? Would you like me to assist in any way?

**Comment by Agatha-Chineke** [comment]
Hi Kate, thank you for reaching out

Yeah I definitely need your help. I have been not been able to keep up with
others because I fell sick but now, I am better

Please do let me know when you are available, I have a couple of questions
to ask.
Thank you

**Comment by KateRasheed** [comment]
Ohh. Great. What is your slack name let me send a DM.

**Comment by KateRasheed** [comment]
@Agatha-Chineke Can you share your slack name so I can reach out to you.

**Comment by Agatha-Chineke** [comment]
Agatha

**Comment by KateRasheed** [comment]
@Agatha-Chineke Good afternoon to you. The last time we communicated on slack, you mentioned you were adding signatures. I would like to know the progress of your curations, are you done entering the experiments and signatures?

**Comment by KateRasheed** [comment]
Greetings again @Agatha-Chineke . I see that you have added an experiment and a signature. Can I collaborate with you so we can complete this curation?

**Comment by Agatha-Chineke** [comment]
@SvetlanaUP , please how do I submit my work for review and grading?

**Comment by SvetlanaUP** [comment]
@Agatha-Chineke by writing a comment here:
https://bugsigdb.org/Study_1152 ready for review.

**Comment by Agatha-Chineke** [comment]
@SvetlanaUP this work is ready for a review:

https://bugsigdb.org/Study_1152

**Comment by SvetlanaUP** [comment]
Hi @Agatha-Chineke, thank you for your contribution. This was a good start of curation but critical curation points finally were missed. Please see the details below and revise in collaboration with @KateRasheed. 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0.5 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0.5 |
|  | TOTAL | 23 | 13 |

- Statistical Analysis information is not correctly identified

- Signatures are not correctly identified: Fig 3A and 3B include results for Experiment 1, and Fig 3C is Experiment 2 with other statistical test performed.

**Comment by KateRasheed** [comment]
Ohh. Thank you @SvetlanaUP . We'll get to work.

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . Corrections have been made to the study. I would like to state that for the MHT correction, I did not see any indication of multiple hypothesis testing.

Thank you so much. @Agatha-Chineke
