### ISSUE TITLE
Microbiome recovery in adult females with uncomplicated urinary tract infections in a randomised phase 2A trial of the novel antibiotic gepotidacin (GSK140944)

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#49]
Initiated at https://bugsigdb.org/Study_556. Note - there are no guarantees that information already entered here (such as study design) is correct, so please proceed as you would for a new study with no information pre-entered.

**Comment by EuniceMiriti** [comment]
Kindly assign this to me.

**Comment by AmeerahKabir** [comment]
Hi @lwaldron , I would love to curate this study

**Comment by AmeerahKabir** [comment]
Hi @lwaldron and @cmirzayi , I am trying to enter the PMID of the study but it keeps showing " must be unique"

**Comment by cmirzayi** [comment]
@AmeerahKabir Please add to the existing study linked above. Do not make a new study.

**Comment by AmeerahKabir** [comment]
Alright, I will and I sent you a direct message on slack relating to my first study, I will appreciate a review on it, thank youu.

**Comment by atrayees** [comment]
Curated at https://bugsigdb.org/Study_556.

**Comment by Peacesandy** [comment]
Reviewed
