### ISSUE TITLE
The impact of breastfeeding on the preterm infant’s microbiome and metabolome: a pilot study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#490]
The impact of breastfeeding on the preterm infant’s microbiome and metabolome: a pilot study – Keriann Schulkers Escalante – Pediatric Research
https://www.nature.com/articles/s41390-024-03440-9

**Comment by TheTosin** [comment]
Hello @SvetlanaUP  I’d like to curate this paper for my second contribution

**Comment by SvetlanaUP** [comment]
This study is not be curated due to grouping of taxa. 

@TheTosin Your effort is noted, please select other paper to curate.

**Comment by TheTosin** [comment]
Okay, noted @SvetlanaUP 
Thank you
