### ISSUE TITLE
Next generation sequencing to examine associations between vaginal washing and vaginal microbiota: A cohort study 

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#491]
Next generation sequencing to examine associations between vaginal washing and vaginal microbiota: A cohort study - Michelle C Sabo – Int J STD AIDS

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11075686/

**Comment by Sproff** [comment]
@Scholarpat @SvetlanaUP I will curate this one

**Comment by SvetlanaUP** [comment]
Hi @Sproff, have you completed your first contribution https://cunysph.az1.qualtrics.com/jfe/form/SV_1RfUgk72TYmcBHE ?

**Comment by Sproff** [comment]
Yeah, I have submitted the first contribution. @SvetlanaUP

**Comment by Sproff** [comment]
@SvetlanaUP This is up for review, kindly check it out https://bugsigdb.org/Study_1116

**Comment by SvetlanaUP** [comment]
@Sproff https://bugsigdb.org/Study_1116 ready for review?

**Comment by Sproff** [comment]
@SvetlanaUP It's up for review, kindly check it out https://bugsigdb.org/Study_1116

**Comment by Sproff** [comment]
While I wait for a review, can I pick up another issue? @SvetlanaUP @Scholarpat

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1116 ready for review.

**Comment by SvetlanaUP** [comment]
@Sproff yes, you can select the next paper to curate, enjoy!

**Comment by Scholarpat** [comment]
Hi @Sproff,

Unfortunately, this study is NOT to be curated. This is because none of the results remained statistically significant after applying a 10% FDR. However, your effort is noted. Please select another paper to curate.

**Comment by Sproff** [comment]
Oops, does that mean I can't record it as part of my contribution?

**Comment by SvetlanaUP** [comment]
@Sproff you can record it, but with a highlight why was not curated in the end.

**Comment by Sproff** [comment]
> @Sproff you can record it, but with a highlight why was not curated in the end.

Alright, thank you.
