### ISSUE TITLE
Meta-analysis of effects of exclusive breastfeeding on infant gut microbiota across populations

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#492]
Meta-analysis of effects of exclusive breastfeeding on infant gut microbiota across populations - Nhan T Ho – Nature Communications

https://pubmed.ncbi.nlm.nih.gov/30301893/

**Comment by Shulamite54** [comment]
Good day @SvetlanaUP @Scholarpat can this paper be assigned to me.
My name is Shulamite.
Thanks

**Comment by SvetlanaUP** [comment]
Hi @Shulamite54, have you completed your first contribution https://cunysph.az1.qualtrics.com/jfe/form/SV_1RfUgk72TYmcBHE ?

**Comment by Shulamite54** [comment]
Yes, i have completed that and waiting for the second contribution to be
assigned to me.
Thank you.

**Comment by Shulamite54** [comment]
Thanks @SvetlanaUP

**Comment by Shulamite54** [comment]
Good day @SvetlanaUP my study is ready for review
https://bugsigdb.org/Study_1106

**Comment by Peacesandy** [comment]
Hi @Shulamite54 
This is an excellent curation attempt, well done for the efforts.

| **Criteria**                                                               | **Points** |
|----------------------------------------------------------------------------|------------|
| All elements marked "Needs review" (none "Incomplete") (1 point)           | 1          |
| Correct study design (1 point)                                             | 1          |
| Entered all relevant experiments and no irrelevant experiments (1 point)  | 1          |
| Body site correctly identified (i.e. does not include multiple sites) (1 point) | 1      |
| Condition entered according to contrast (correct EFO ontology) (1 point)  | 1          |
| Contrast groups correctly identified (1 point)                             | 1          | 1
| Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point)        | 1          | 1
| Antibiotic exclusion correctly identified (1 point)                        | 1          | 1
| Correctly identified sequencing details (2 points)                         | 2          | 2
| Identified correct statistical test (1 point)                              | 1          | 0.5
| Identified MHT correction (1 point)                                        | 1          | 1
| Correctly recorded matched on factors (1 point)                            | 1        | 1
| Entered correct number of statistical tests per experiment (1 point)       | 0.5         |
| All diversity measures identified (1 point)                                | 1          |
| Diversity results correctly entered as increased/decreased/unchanged (1 point) | 1     |
| All signature sources correctly identified (-1 for each error) (2 points)  | 1       |
| Abundance direction correctly selected (1 point)                           | 1          |
| Members of Signatures identified correctly (2 points)                      | 2          |
| Correct use of NCBI taxonomy (2 points)                                    | 2          |
| **Total (maximum 23 points)**                                              | **21.5**   |


**N/B**; However, there are some minor changes. You entered the wrong statistical test for some experiments and didn't correctly enter some signature changes. Those minor changes have been made. Thank you so much for your hard work.

**Comment by Peacesandy** [comment]
@SvetlanaUP https://bugsigdb.org/Study_1106 Reviewed 🎉

**Comment by SvetlanaUP** [comment]
Thanks @Peacesandy,
is there any particular reason why https://bugsigdb.org/Study_1106/Experiment_4/Signature_2 is still "needs review"?

**Comment by Peacesandy** [comment]
Hi @SvetlanaUP 
So sorry, It was an oversight. The study did not reflect on the page at the time of review, I've cross-checked and reviewed it.
