### ISSUE TITLE
Gut microbiota patterns associated with duration of diarrhea in children under five years of age in Ethiopia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#493]
Gut microbiota patterns associated with duration of diarrhea in children under five years of age in Ethiopia – Getnet Tesfaw – Nature Communications
https://www.nature.com/articles/s41467-024-51464-w

**Comment by Cateline** [comment]
Cateline Ouma. 
I'd like to curate this paper

**Comment by SvetlanaUP** [comment]
Hi @Cateline, have you completed your first contribution https://cunysph.az1.qualtrics.com/jfe/form/SV_1RfUgk72TYmcBHE ?

**Comment by Cateline** [comment]
Hello, yes I have

**Comment by Cateline** [comment]
Thank you. Is this the link I'm supposed to upload on Outreachy for the
contribution phase?

**Comment by SvetlanaUP** [comment]
@Cateline please note that we communicate about not-related-to-this-curation topics **in the bugsigdb Slack channel**
I believe here you can find your answer https://community-bioc.slack.com/archives/C04RATV9VCY/p1727849386260229

**Comment by Cateline** [comment]
Thank you for the clarification.

**Comment by MyleeeA** [comment]
Hello @Cateline 

How’s your curation coming along?

I’m open to offer assistance if you are experiencing any blockers 
Thank you 🙏🏾

**Comment by MyleeeA** [comment]
Hi @Cateline

Just checking in again on how your curation is coming along

**Comment by SvetlanaUP** [comment]
@Cateline is https://bugsigdb.org/Study_1130 ready for review?

**Comment by Cateline** [comment]
Yes, it's ready for review

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1130 ready for review.

**Comment by Peacesandy** [comment]
@SvetlanaUP Please can I review this.

**Comment by SvetlanaUP** [comment]
Sure, @Peacesandy!

**Comment by Peacesandy** [comment]
Hello @Cateline this is an amazing curation attempt 🎈

However, you missed out on some details
- The alpha diversity index was entered wrongly.
- The matched on factors were not correctly entered.

**N/B:** I've made all the necessary corrections. Please go through the reviewed curation and the paper again for ease. This will help you gain a better understanding for future curations.

CURATION RESULTS

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 0.5
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified (-1 for each error) (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 21.5

@SvetlanaUP  https://bugsigdb.org/Study_1130 Reviewed and corrected

**Comment by SvetlanaUP** [comment]
@Cateline please see my message in https://github.com/waldronlab/BugSigDBcuration/issues/440

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1130 reviewed.
