### ISSUE TITLE
Faecal microbiota and cytokine profiles of rural Cambodian infants linked to diet and diarrhoeal episodes

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#495]
Faecal microbiota and cytokine profiles of rural Cambodian infants linked to diet and diarrhoeal episodes – Matthew J. Dalby – npj Biofilms and Microbiomes
https://link.springer.com/article/10.1038/s41522-024-00562-0

**Comment by Aeeshah1** [comment]
Aishat, hello, can I be assigned to this please?

**Comment by Aeeshah1** [comment]
Thank you, I am done curating this. Here is the link- https://bugsigdb.org/Study_1166
The signatures for experiment 1 are not showing, despite following all suggestions in the bugsigdb channel. Here are the links- https://bugsigdb.org/Study_1166/Experiment_1/Signature_1, https://bugsigdb.org/Study_1166/Experiment_1/Signature_2, https://bugsigdb.org/Study_1166/Experiment_1/Signature_3

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1166 ready for review.

**Comment by KateRasheed** [comment]
Good morning @Aeeshah1 . Great attempt on this curation. However, I would like to point out these corrections:

1. Figure 1D-K is curatable. The experiment is paired frozen samples vs DNA preservation solution (DNAShield) stored samples. Mann-whitney test was used with MHT correction. The condition for this would be Sample treatment protocol. Significant threshold is 0.05
2. Experiment 2 should have sub-experiments for the different time points. Please request that signature 3 and 4 be deleted from experiment 2. Signature sources for the experiments in this category (Diarrhea illness) is Fig 2F-H and Fig 3F-G
3. For experiment 1, please request that signature 1 be deleted. Also, the statistical test is MaAsLin. Signature 1 source is Fig 2D, 3D(add the taxa in 2D) while Signature 2 source is Fig 2E, 3E(add the taxa in 2E). The condition would be Breastfeeding duration. There were no confounders in this experiment. The alpha diversity is decreased in Shannon (Fig. 2J). This experiment should have sub-experiments for the different time points as well(Time point 1, 2, 3).
4. The sequencing region is V1-V2 for all experiments.

Please let me know if you would need my help in making these corrections. Thank you so much.

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP Please delete signature 3 and 4 from experiment 2; signature 1 from experiment 1

**Comment by SvetlanaUP** [comment]
Study 1166/Experiment 1/Signature 3
Study 1166/Experiment 2/Signature 3
Study 1166/Experiment 2/Signature 4
deleted.

**Comment by KateRasheed** [comment]
Thank you so much @SvetlanaUP . Please Study 1166/Experiment 2/Signature 4 is still showing from here.

**Comment by SvetlanaUP** [comment]
Study 1166/Experiment 2/Signature 4
deleted.

**Comment by KateRasheed** [comment]
Good afternoon @SvetlanaUP . This study has been corrected and review is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1166 reviewed.
