### ISSUE TITLE
Depletion of the paternal gut microbiome alters sperm small RNAs and impacts offspring physiology and behavior in mice

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#496]
Depletion of the paternal gut microbiome alters sperm small RNAs and impacts offspring physiology and behavior in mice – Bethany A. Masson – Brain, Behavior, and Immunity

https://www.sciencedirect.com/science/article/pii/S088915912400624X
[1-s2.0-S088915912400624X-main.pdf](https://github.com/user-attachments/files/17127398/1-s2.0-S088915912400624X-main.pdf)

Supplementary material:

<img width="560" alt="FigS1" src="https://github.com/user-attachments/assets/63201e0c-387b-41c0-a7cd-9ee20cf31742">
<img width="571" alt="FigS2" src="https://github.com/user-attachments/assets/55f0f1fd-438c-4fb3-8493-a37d914046a8">
<img width="623" alt="FigS3_4" src="https://github.com/user-attachments/assets/7c47e333-4dba-41dc-9cd2-21393ebe724f">
<img width="553" alt="FigS5" src="https://github.com/user-attachments/assets/b55c82db-ed39-42d2-9a02-9d7d8a1952df">
<img width="561" alt="FigS6" src="https://github.com/user-attachments/assets/f15dced4-84ae-46ed-898d-5d7fe7ad6c27">
<img width="605" alt="FigS7" src="https://github.com/user-attachments/assets/a50835a0-dcf8-41fd-9e2d-592c0bb6d9d7">

**Comment by wendy640** [comment]
Chinwendu Joy Enyidiegwu

please, I'd like to claim this issue for curation.
Thank you so much!

**Comment by SvetlanaUP** [comment]
@wendy640 is this curation ready for review?

**Comment by wendy640** [comment]
yes ma'am, it is ready for review.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1104 ready for review.

**Comment by Nathcynthia** [comment]
> Depletion of the paternal gut microbiome alters sperm small RNAs and impacts offspring physiology and behavior in mice – Bethany A. Masson – Brain, Behavior, and Immunity
> 
> https://www.sciencedirect.com/science/article/pii/S088915912400624X [1-s2.0-S088915912400624X-main.pdf](https://github.com/user-attachments/files/17127398/1-s2.0-S088915912400624X-main.pdf)

Good day,
@SvetlanaUP, Can this paper be assigned to me @Cynthia Iwuoha.

**Comment by SvetlanaUP** [comment]
@Nathcynthia this paper is already curated and under review.
Please select other one that has labels: paper to curate and outreachy dec2024

**Comment by SvetlanaUP** [comment]
Hi @wendy640, thank you for your contribution. Unfortunately this is a poor curation with critical curation points missed. Please see the details below and revise. 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 0.5 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 0 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0.5 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 7 |

- condition should refer to "The experimental condition / phenotype studied"
- antibiotic exclusion here is not applied 
- V regions of 16S rRNA gene sequenced are not correctly identified
- Statistical Analysis information is not correctly identified
- Alpha diversity is not correctly identified: the Pielou index is closely related to the Shannon index, but they are not the same measurement
- Signatures are not correctly identified: Table 1 is the correct source

**Comment by Shulamite54** [comment]
Good day @SvetlanaUP can this be assigned to me @Shulamite54

**Comment by SvetlanaUP** [comment]
@Shulamite54 @wendy640 enjoy your team work!

**Comment by Shulamite54** [comment]
Thanks @SvetlanaUP

**Comment by wendy640** [comment]
thank you @SvetlanaUP

**Comment by Shulamite54** [comment]
@SvetlanaUP I can't download the pdf, it takes long to load, and since then it has been showing downloading pending, i have tried searching for the paper on Google scholar and even on CU scholar, but it all send me back to science direct. What else can I do.

**Comment by SvetlanaUP** [comment]
@Shulamite54 check your email, I sent it there.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1104 ready for review.

**Comment by SvetlanaUP** [comment]
@wendy640 @Shulamite54 unfortunately, this curation is not fully corrected: 

- condition should refer to "The experimental condition / phenotype studied"
- antibiotic exclusion here is not applied
- alpha diversity: "Antibiotic-treated male mice had significantly lower number of bacterial species in the fecal microbiome compared to control mice, indicated by the Shannon α-diversity index (P=0.0464, [Fig. 1](https://www.sciencedirect.com/science/article/pii/S088915912400624X#f0005)G)."
- statistical test and its details should be revised

Please ask your colleagues for help in Slack.

**Comment by wendy640** [comment]
@SvetlanaUP the corrections has been made, pls kindly review as we await your feedback. 
@Shulamite54

**Comment by SvetlanaUP** [comment]
@wendy640 @Shulamite54  
Please fix Study information: incomplete to complete
And for confounders, in "adjusting for experimental factors including sex and **cohort**" you missed one, right?

**Comment by Shulamite54** [comment]
I inputted the Cohort before, but it was showing a yellow dot beside it, so I deleted it, but i have putting it back again. I have also changed the incomplete to complete. Thank you @SvetlanaUP for the correction.

**Comment by SvetlanaUP** [comment]
@Shulamite54 if it's yellow, we should find the appropriate EFO term, right?

**Comment by Shulamite54** [comment]
i searched for cohort on EFO and this is what i found EFO:0004445, its also for cohort, how else can i search for this @SvetlanaUP

**Comment by SvetlanaUP** [comment]
@Shulamite54 ok, let's live it like that.

https://bugsigdb.org/Study_1104 reviewed.

**Comment by Shulamite54** [comment]
thanks for your guidance @SvetlanaUP , can i go on with NCBI cleaning
