### ISSUE TITLE
Bacteroides uniformis degrades β-glucan to promote Lactobacillus johnsonii improving indole-3-lactic acid levels in alleviating colitis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#497]
Bacteroides uniformis degrades β-glucan to promote Lactobacillus johnsonii improving indole-3-lactic acid levels in alleviating colitis – Shanshan Zhang – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01896-9

**Comment by Appleeyes** [comment]
Hi @SvetlanaUP 

Please I'd like to be assigned to this, I finushed my first contribution

**Comment by AleruDivine** [comment]
Hi @Appleeyes, how are you doing and how's your curation going? 

I am currently done with my second contribution and open to help if you're having any difficulties.

**Comment by Appleeyes** [comment]
Hi @AleruDivine thanks for checking up, your help will be appreciated actually, I will text you on slack when I am ready, hope that's okay?

**Comment by AleruDivine** [comment]
Yes that's okay @Appleeyes.
Looking forward to your message.

My slack is @AleruDivine

**Comment by SvetlanaUP** [comment]
Well done @Appleeyes  and @AleruDivine!

Note: write the explanation in full the first time you use an abbreviation. DSS explained.

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |        1 |
| 2    | Correct study design                                                 | 1   |        1 |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |        1 |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |        1 |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |        1 |
| 6    | Contrast groups correctly identified                                 | 1   |        1 |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |        1 |
| 8    | Antibiotic exclusion correctly identified                            | 1   |        1|
| 9    | Correctly identified sequencing details                              | 2   |        2 |
| 10   | Identified correct statistical test                                  | 1   |        1 |
| 11   | Identified MHT correction                                            | 1   |        1 |
| 12   | Correctly recorded matched on factors                                | 1   |        1 |
| 13   | Entered correct number of statistical tests per experiment           | 1   |        1 |
| 14   | All diversity measures identified                                    | 1   |        1 |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |        1|
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |        2 |
| 17   | Abundance direction correctly selected                               | 1   |        1 |
| 18   | Members of Signatures identified correctly                           | 2   |        2 |
| 19   | Correct use of NCBI taxonomy                                         | 2   |        2 |
|      | TOTAL                                                                | 23  |        23 |

**Comment by AleruDivine** [comment]
Duly noted @SvetlanaUP 
Thank you so much for the review 🙏

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP 
I believe you have already made the corrections regarding the abbreviations as I have checked and they have been updated.
I have informed @Appleeyes on Slack that this study has been reviewed too.

Is there any outstanding issue on this?

**Comment by Appleeyes** [comment]
Thank you @SvetlanaUP

**Comment by SvetlanaUP** [comment]
@AleruDivine @Appleeyes yes, this curation is corrected and closed. Thank you!
