### ISSUE TITLE
The skin microbiome stratifies patients with cutaneous T cell lymphoma and determines event-free survival

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#499]
The skin microbiome stratifies patients with cutaneous T cell lymphoma and determines event-free survival – Philipp Licht – NPJ Biofilms Microbiomes
https://www.nature.com/articles/s41522-024-00542-4

**Comment by masembebrian** [comment]
id like to have this assigned to curate

**Comment by SvetlanaUP** [comment]
Hi @masembebrian, have you completed your first contribution https://cunysph.az1.qualtrics.com/jfe/form/SV_1RfUgk72TYmcBHE ?

**Comment by Jayybb** [comment]
I would love to be assigned this

**Comment by Jayybb** [comment]
please @SvetlanaUP i need a review for my second project
https://bugsigdb.org/Study_1126

**Comment by Jayybb** [comment]
i'd like to review my project @SvetlanaUP 
https://bugsigdb.org/Study_1126
https://bugsigdb.org/Study_1126/Experiment_1/Signature_1
https://bugsigdb.org/Study_1126/Experiment_1/Signature_2

**Comment by SvetlanaUP** [comment]
@Peacesandy please review this curation, thanks!

**Comment by Peacesandy** [comment]
Okay, I'll take this up
Thank you so much @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1126 reviewed.

**Comment by Jayybb** [comment]
Thank you . I will implement the corrections 👏

**Comment by Jayybb** [comment]
@SvetlanaUP i noticed after I sent the reply 🤭🤭🤭. I'm giving it my all next time 😊😊😊😊

**Comment by SvetlanaUP** [comment]
@Jayybb please ask this question in Slack channel #bugsigdb.

**Comment by Jayybb** [comment]
@SvetlanaUP Okay ma. Thank you 👏
