### ISSUE TITLE
Integrating metagenomics with metabolomics for gut microbiota and metabolites profiling in acute pancreatitis

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#501]
Integrating metagenomics with metabolomics for gut microbiota and metabolites profiling in acute pancreatitis – Yan Jia – Scientific Reports
https://www.nature.com/articles/s41598-024-72057-z

**Comment by KateRasheed** [comment]
I would like to claim this. Kate Rasheed

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP 
This article is ready for review. Here is the link:
https://bugsigdb.org/Study_1110

**Comment by KateRasheed** [comment]
Good day @svetlana_up. After I submitted my paper for review, the following edits were made:
1. I removed all taxa in signatures(under experiment 2-4) with p-value threshold above 0.05.
2. I added more taxa to signatures 2 (under experiment 2-4) where the taxa was increased abundance in the control group.

Thank you.

**Comment by KateRasheed** [comment]
Good morning @SvetlanaUP . Please my second contribution is yet to be reviewed.

**Comment by SvetlanaUP** [comment]
@KateRasheed It's on our to do list. Thank you for your patience! And, enjoy your weekend.

**Comment by Folakunmi21** [comment]
Hello @KateRasheed. Thanks for your effort on this curation. Unfortunately, there were a lot of errors in it.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point):  1
6. Contrast groups correctly identified (1 point): 0.5
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0
16. All signature sources correctly identified  (-1 for each error)  (2 points): 0
17. Abundance direction correctly selected (1 point): 0
18. Members of Signatures identified correctly (2 points): 0
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 14.5

**Comment by KateRasheed** [comment]
I'm really grateful for this review. I'll correct immediately. 

For the supplementary table, I have taken note of the explanation as to why it should not be curated. I have a similar table in another study I'm collaborating on; I'll tag you to it on slack. Thank you once again @Folakunmi21

**Comment by KateRasheed** [comment]
Good day @Folakunmi21 . I have made corrections to this study. I have also tagged you to the table I need clarity on. Thank you so much.

**Comment by SvetlanaUP** [comment]
@Folakunmi21 please see corrections here, thanks!

**Comment by Folakunmi21** [comment]
Thank you! @KateRasheed all changes reviewed

**Comment by KateRasheed** [comment]
Good day @SvetlanaUP . Please this is the issue Chloe gave clarity on.

**Comment by KateRasheed** [comment]
Okay. Chloe mentioned that the supplementary table is curatable. The log fold change shows the decreased/increased value for the case group. @SvetlanaUP

**Comment by Folakunmi21** [comment]
Hi @KateRasheed I apologize for the oversight on the supplementary table. Please, curate it and I will adjust your score for point 3 in the marking guide. You combined the signature sources initially so I'll still have to deduct a mark for that (point 16 in the marking guide) but I'll give you 1 mark for it. Your combination of different signature sources affected the signatures you curated as well as their abundance directions so points 17 and 18 will have to remain that way. Sorry for the double work once again!

**Comment by KateRasheed** [comment]
It's fine. I'll get to work. Thank you so much.

**Comment by KateRasheed** [comment]
Good morning to you @Folakunmi21 . I have added all the signatures in the supplementary table. Thank you so much.

**Comment by KateRasheed** [comment]
Yes yes. I noticed it as well. The signatures will show when they are entered manually.

For example: https://bugsigdb.org/Study_1110/Experiment_6/Signature_2

@Folakunmi21

**Comment by KateRasheed** [comment]
Good day @Folakunmi21 . All signatures are now showing on the study. I had to make edits (adding LEfSe statistical test and removing it from the experiments without signatures), because I observed that editing the experiments would make previous signatures show.

Thank you so much.

**Comment by Folakunmi21** [comment]
Good job! @KateRasheed I've adjusted your points
@SvetlanaUP all sorted✅
