### ISSUE TITLE
The intensive physical activity causes changes in the composition of gut and oral microbiota

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#502]
The intensive physical activity causes changes in the composition of gut and oral microbiota – Szymon Urban – Scientific Reports
https://www.nature.com/articles/s41598-024-71684-w

⚽ "Twenty professional football players and twelve amateurs were invited to the study groups."

**Comment by AleruDivine** [comment]
Divine Aleru

I'd like to claim this issue for curation.
Thank you so much!

**Comment by masembebrian** [comment]
id like to have this issue assigned to me please.

**Comment by SvetlanaUP** [comment]
Assigned to @AleruDivine

**Comment by AleruDivine** [comment]
Thank you so much!

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP 
This study is ready for review
https://bugsigdb.org/Study_1105

**Comment by Omabekee** [comment]
| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |     1   |
| 2    | Correct study design                                                 | 1   |   2     |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |    1    |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |     1   |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |    1    |
| 6    | Contrast groups correctly identified                                 | 1   |    1    |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |    1    |
| 8    | Antibiotic exclusion correctly identified                            | 1   |    1    |
| 9    | Correctly identified sequencing details                              | 2   |    2    |
| 10   | Identified correct statistical test                                  | 1   |    1    |
| 11   | Identified MHT correction                                            | 1   |     1   |
| 12   | Correctly recorded matched on factors                                | 1   |    1    |
| 13   | Entered correct number of statistical tests per experiment           | 1   |    1    |
| 14   | All diversity measures identified                                    | 1   |    1    |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |    1    |
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |    2    |
| 17   | Abundance direction correctly selected                               | 1   |    1    |
| 18   | Members of Signatures identified correctly                           | 2   |    2    |
| 19   | Correct use of NCBI taxonomy                                         | 2   |    2    |
|      | TOTAL                                                                | 23  |    23    |

**Comment by AleruDivine** [comment]
Thank you so much for the review @Omabekee 😊
This makes me really happy and boosts my confidence to take on more curations. Looking forward to continuing my contributions!✨

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1105 reviewed.
