### ISSUE TITLE
Visceral adiposity in postmenopausal women is associated with a pro-inflammatory gut microbiome and immunogenic metabolic endotoxemia

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#504]
Visceral adiposity in postmenopausal women is associated with a pro-inflammatory gut microbiome and immunogenic metabolic endotoxemia – Mohamed Gaber – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01901-1

**Comment by eve10111** [comment]
Hello @SvetlanaUP Can you kindly assign this paper to me?
Thank you.

**Comment by Aeeshah1** [comment]
Hello @SvetlanaUP can this be assigned to me please?

**Comment by SvetlanaUP** [comment]
https://github.com/waldronlab/BugSigDBcuration/issues/495 is assigned to you @Aeeshah1

**Comment by vandana123maddi** [comment]
Hi @SvetlanaUP can u please assign me this !?

**Comment by vandana123maddi** [comment]
@SvetlanaUP thanks for the feedback i finally found unassigned paper  🙂

**Comment by vandana123maddi** [comment]
Hi @SvetlanaUP would u please assign this paper to me 
Thank you

**Comment by AnushaR-star** [comment]
Hello @SvetlanaUP  I want to curate this! Could u please

**Comment by SvetlanaUP** [comment]
This paper is assigned to @vandana123maddi 
@AnushaR-star please select other one, thanks!

**Comment by TheTosin** [comment]
Hello, @vandana123maddi please feel free to reach out if you need any assistance in curating the article. I would be happy to collaborate to make the process smoother and more efficient. You can reach me as “Adeshile Oluwatosin” on slack.

**Comment by vandana123maddi** [comment]
Thank you @SvetlanaUP 😊

**Comment by vandana123maddi** [comment]
Sure @TheTosin If i got stucked I will ! 😃

**Comment by MyleeeA** [comment]
Hi @vandana123maddi 

Well done on your curation, are you experiencing any blockers?
I see you curated experiments based on the functional analysis that were done using correlation, I"ll be happy to collaborate if you need any help finishing this curation

Thank you

**Comment by vandana123maddi** [comment]
Hi  @SvetlanaUP  ma'am 😊 
I would like to keep this study for review 
Link [https://bugsigdb.org/Study_1185]
Thank you 😁

**Comment by vandana123maddi** [comment]
Hi ma'am ! I would like u review 
https://bugsigdb.org/Study_1185
Thank you 😊

**Comment by vandana123maddi** [comment]
Hi @MyleeeA i would like to collaborate is there any other  paper ur working on please do 
recommend and  consider me ! 
Thank you

**Comment by TheTosin** [comment]
@vandana123maddi I think it’s best to assist others that are yet to submit their articles for review. You can check here on github for issues with the assigned label but without review, tag a mentor and request from the original curator to assist or look for a new article.

**Comment by vandana123maddi** [comment]
Sure @TheTosin if i think they need or i could add value i will surely 
This contribution period have great time to meet new people across global who are collaborators and mentors great study at the same time 💫

**Comment by MyleeeA** [comment]
Hi @vandana123maddi 

I am currently working on a paper 
Let me see if I can tag you

You can request to collaborate on it
But @TheTosin idea is also a great one

**Comment by MyleeeA** [comment]
This is what I’m working on now @vandana123maddi #468

**Comment by vandana123maddi** [comment]
Sure @MyleeeA I want to collaborate

**Comment by MyleeeA** [comment]
You can leave a comment here #468 @vandana123maddi

**Comment by Omabekee** [comment]
Hello @vandana123maddi, you made several mistakes, but with more practice, I’m confident you’ll improve your curating skills. That said, I suggest the entire set of experiments be deleted and re-curated from scratch. Collaborating with @KateRasheed for the re-curation might also be helpful. Here are the corrections I’ve noted.:

- Matched on = age and sex
- No confounders controlled
- Alpha diversity = Chao and Shannon, both unchanged
- Antibiotic exclusion = 3 months

- **Experiments Identified**
- Experiment 1
Figures 3D and 3E = Differentially enriched taxa in Postmenopausal women with high VAT area compared with participants with low VAT area

Stat test= Mann-Whitney

condition = VAT

- Experiment 2
Figure 4B = Proportional abundance of significant genera by VAT area.
Stat test= Mann-Whitney

- Experiment 3
Figure 4C = Linear discriminant analysis Effect Size (LEfSe) method identifying differentially enriched taxa in High VAT compared to Low VAT Postmenopausal women

Stat test = LEfSE

- Experiment 4
Figures 6B and 6E =  The percentage of LPS-containing bacteria significantly enriched in the high VAT group compared to the low VAT group

Stat test= Mann-Whitney

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |    1    |
| 2    | Correct study design                                                 | 1   |    1    |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |   0     |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |   0     |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |   0     |
| 6    | Contrast groups correctly identified                                 | 1   |    0    |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |   0.5     |
| 8    | Antibiotic exclusion correctly identified                            | 1   |    0.5    |
| 9    | Correctly identified sequencing details                              | 2   |    1    |
| 10   | Identified correct statistical test                                  | 1   |    0    |
| 11   | Identified MHT correction                                            | 1   |   1     |
| 12   | Correctly recorded matched on factors                                | 1   |    0    |
| 13   | Entered correct number of statistical tests per experiment           | 1   |  0      |
| 14   | All diversity measures identified                                    | 1   |     0   |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |    1    |
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |    0    |
| 17   | Abundance direction correctly selected                               | 1   |   0     |
| 18   | Members of Signatures identified correctly                           | 2   |    0    |
| 19   | Correct use of NCBI taxonomy                                         | 2   |   2     |
|      | TOTAL                                                                | 23  |    8    |

**Comment by KateRasheed** [comment]
Good morning @Omabekee for this corrections. We would work on it.

@vandana123maddi I would love to collaborate with you on this curation. 

Thank you so much.

**Comment by KateRasheed** [comment]
Good morning @Omabekee . Thank you once again for the review. Corrections have been made on the study. However, I would like to state some observations:

1. I curated figure 4b and 3e into one experiment since they have the same experiment and statistical test.
2. I didn't curate Figure 3d since it's a F/B ratio and Chloe mentioned during one of the office hours that we don't curate F/B ratio.
3. There is another experiment in Fig 4C with Pearson correlation heatmap which I added to the study 

PS. I have requested that Experiment 5 be deleted.

Thank you so much.

**Comment by Omabekee** [comment]
Thanks for working on this @KateRasheed.
Few corrections to note:
- For Expt. 1 Sig 1, there's no Figure 2E.
- For Expt. 2 Sig 1, there's no Figure 4E.
- I'm not sure how Expt. 2/ Sig. 2 was curated; I can't find the taxa you curated (Alistipes) in the source indicated; please clarify.
- Expt. 4/ Sig. 1 should have 3 taxa according to the text explaining the figure. I also think it's good to add the text as a reference to the source for this experiment. E.g. Figure 4C + Within text (Paragraph 4, Line 2).

**Comment by KateRasheed** [comment]
Good evening @Omabekee . Thank you so much for the corrections.

Sincere apologies please. For experiment 1 and 2, I mixed-up the figure number. It's well corrected now. Alistipes is in Fig. 6B while Pseudonomota is in Fig. 6E(for the second experiment)

For Experiment 4, I counted the strains in the figure and they are 15. 4 increase and 11 decrease. I guess it was omitted in the text. I also noticed that for the text, although they mentioned 11, it was only 10 that was listed, hence, my source was the figure to avoid confusion. I would add within text as well.

Thank you so much.

**Comment by KateRasheed** [comment]
@AleruDivine Please can you also review this correction 😁

**Comment by AleruDivine** [comment]
Yes, of course. I’ll add it to my list of studies to be reviewed.

**Comment by AleruDivine** [comment]
Well done @KateRasheed 
This is one interesting study, and I really commend your efforts with corrections.👏👏

This review is complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1185 reviewed.
