### ISSUE TITLE
Gut microbiome and serum metabolome alterations associated with lactose intolerance (LI): a case‒control study and paired-sample study based on the American Gut Project (AGP)

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#505]
Gut microbiome and serum metabolome alterations associated with lactose intolerance (LI): a case‒control study and paired-sample study based on the American Gut Project (AGP) – Hing Xue – mSystems
https://journals.asm.org/doi/10.1128/msystems.00839-24

**Comment by Nathcynthia** [comment]
> Gut microbiome and serum metabolome alterations associated with lactose intolerance (LI): a case‒control study and paired-sample study based on the American Gut Project (AGP) – Hing Xue – mSystems https://journals.asm.org/doi/10.1128/msystems.00839-24

@SvetlanaUP , Can this paper be assigned to me @Cynthia Iwuoha

**Comment by TheTosin** [comment]
Hello @Nathcynthia Kindly reach me on slack “Adeshile Oluwatosin”. I would like to collaborate with you on this article curation. Let me know if you require assistance.

**Comment by Nathcynthia** [comment]
> Hello @Nathcynthia Kindly reach me on slack “Adeshile Oluwatosin”. I would like to collaborate with you on this article curation. Let me know if you require assistance.

Hi @TheTosin, I’d love to collaborate with you
You’ve been more than helpful already on slack.
Please go ahead.

**Comment by Jayybb** [comment]
@SvetlanaUP please I want to work on this article. Thank you

**Comment by SvetlanaUP** [comment]
@TheTosin @Nathcynthia please finalize this curation.

**Comment by TheTosin** [comment]
@SvetlanaUP This study is ready for review.
https://bugsigdb.org/Study_1151

**Comment by Jayybb** [comment]
https://bugsigdb.org/Study_1178 this study is ready for review

**Comment by SvetlanaUP** [comment]
@Jayybb this curation was not assigned to you.

**Comment by SvetlanaUP** [comment]
Note: https://bugsigdb.org/Study_1178 to be deleted.

**Comment by SvetlanaUP** [comment]
@Jayybb please tell me, where this study was assigned https://bugsigdb.org/Study_1178?

**Comment by SvetlanaUP** [comment]
@MyleeeA https://github.com/MyleeeA could you please do review of this curation?

**Comment by MyleeeA** [comment]
Okay @SvetlanaUP 

I’ll get to it

**Comment by MyleeeA** [comment]
Hi @TheTosin @Nathcynthia Well done on your curation. This is an almost perfect curation
1. **Source and source description:** In experiment 3, the source and source description doesn’t match. I think since you used the description for the figure (7c), you can either use just the figure as the source or you use both figure and text (Both showing the same thing). I also think the text Source doesn’t need to include the whole paragraph, maybe just writing **_Results text-FMT animal study, Page 16_** should do. This applies to experiment 5, the text referenced figure 3c and you left that out. Also, For the signature source description, instead of saying ‘between the two groups’ you can be more specific and state the groups.

2.  **Alpha diversity:** In Experiment 2, you left out Sobs which can be curated as richness (Unchanged).

Overall, this is a great curation. Great work

**Comment by Nathcynthia** [comment]
@MyleeeA, Thank you for the review.

**Comment by Nathcynthia** [comment]
> Hi @TheTosin @Nathcynthia Well done on your curation. This is an almost perfect curation 👏🏾👏🏾
> 
> 1. **Source and source description:** In experiment 3, the source and source description doesn’t match. I think since you used the description for the figure (7c), you can either use just the figure as the source or you use both figure and text (Both showing the same thing). I also think the text Source doesn’t need to include the whole paragraph, maybe just writing **_Results text-FMT animal study, Page 16_** should do. This applies to experiment 5, the text referenced figure 3c and you left that out. Also, For the signature source description, instead of saying ‘between the two groups’ you can be more specific and state the groups.
> 2. **Alpha diversity:** In Experiment 2, you left out Sobs which can be curated as richness (Unchanged).
> 
> Overall, this is a great curation. Great work 👏🏾

**Comment by MyleeeA** [comment]
You are welcome @TheTosin @Nathcynthia 

Also the source description for Experiment 1 is not really clear, Describing the actual source should be more appropriate. i.e replacing signature 1 and 2 description with this '**_Gut microbiota alterations between LI cohort and non-LI cohort assessed  using the linear discriminative analysis (LDA) effect size (LEfSe)'._**

**Comment by Nathcynthia** [comment]
@MyleeeA Thank you again for the review.
The description of Signature 1 and Signature 2  for  Experiment 1 have been corrected to "Gut microbiota alterations between LI cohort and non-LI cohort assessed using the linear discriminative analysis (LDA) effect size (LEfSe)'"
