### ISSUE TITLE
Gut microbiota-derived gamma-aminobutyric acid improves host appetite by inhibiting satiety hormone secretion

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#506]
Gut microbiota-derived gamma-aminobutyric acid improves host appetite by inhibiting satiety hormone secretion – Shouren Li  – mSystems
https://journals.asm.org/doi/10.1128/msystems.01015-24

**Comment by TheTosin** [comment]
Hello, @yokoDots do you need help with curating this issue, let’s collaborate.
You can reach me as Adeshile Oluwatosin on slack.
I am always ready to help out.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1148 ready for review.

**Comment by Scholarpat** [comment]
Under review @SvetlanaUP

**Comment by Scholarpat** [comment]
Hi @yokoDots,

Good job on your curation! I adjusted your signature source from fig 4 to fig 4**H** and fig 4**G** for experiments 1 and 2 respectively and also the source description for experiment 2.

**CURATION RESULTS:**

| S/N | Criteria                                                           | Total Points | Points Earned |
|-----|--------------------------------------------------------------------|--------------|---------------|
| 1   | All elements marked "Needs review" (none "Incomplete")             | 1            | 1             |
| 2   | Correct study design                                                | 1            | 1             |
| 3   | Entered all relevant experiments and no irrelevant experiments      | 1            | 1             |
| 4   | Body site correctly identified (i.e. does not include multiple sites)| 1            | 1             |
| 5   | Condition entered according to contrast (correct EFO ontology)      | 1            | 1             |
| 6   | Contrast groups correctly identified                                | 1            | 1             |
| 7   | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)           | 1            | 1             |
| 8   | Antibiotic exclusion correctly identified                           | 1            | 1             |
| 9   | Correctly identified sequencing details                             | 2            | 2             |
| 10  | Identified correct statistical test                                 | 1            | 1             |
| 11  | Identified MHT correction                                           | 1            | 1             |
| 12  | Correctly recorded matched on factors                               | 1            | 1             |
| 13  | Entered correct number of statistical tests per experiment          | 1            | 1             |
| 14  | All diversity measures identified                                   | 1            | 1             |
| 15  | Diversity results correctly entered as increased/decreased/unchanged| 1            | 1             |
| 16  | All signature sources correctly identified (-1 for each error)      | 2            | 1             |
| 17  | Abundance direction correctly selected                              | 1            | 1             |
| 18  | Members of signatures identified correctly                          | 2            | 2             |
| 19  | Correct use of NCBI taxonomy                                        | 2            | 2             |
|   | **TOTAL**                                        | **23**            | **22**             |

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1148 reviewed.

**Comment by SvetlanaUP** [comment]
@yokoDots well done, just keep in mind to record **precisely** every detail of your curation (e.g. Figure 4 as a whole figure or its part, it matters). Keep up the good work!
