### ISSUE TITLE
Targeted discovery of gut microbiome-remodeling compounds for the treatment of systemic inflammatory response syndrome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#508]
Targeted discovery of gut microbiome-remodeling compounds for the treatment of systemic inflammatory response syndrome – mSystems – Luyao Liu
https://journals.asm.org/doi/10.1128/msystems.00788-24

**Comment by Aeeshah1** [comment]
I'd like to curate this please

**Comment by Aeeshah1** [comment]
Hello, I am done curating this article please. Here is the link- https://bugsigdb.org/Study_1160

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1160 ready for review.

**Comment by SvetlanaUP** [comment]
Hi @Aeeshah1, thank you for your contribution. Unfortunately this is a poor curation with critical curation points missed. Please see the details below and revise. 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 |  1|
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 0 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 7 |

- V regions of 16S rRNA gene sequenced are missed
- feces samples are missed to be recorded as a body site
- abbreviations in the groups description should be explained
- Fig6E with LEfSe results should be curated, thus the following is deleted:
https://bugsigdb.org/Study_1160/Experiment_1/Signature_1
https://bugsigdb.org/Study_1160/Experiment_1/Signature_2
https://bugsigdb.org/Study_1160/Experiment_1/Signature_3
- Fig. 5B wiith DESeq2 results should be curated
- alpha diversities should be rechecked

**Comment by IfeanyiSam** [comment]
@Aeeshah1 are you available? can't seem to get a hold of you on slack

**Comment by SvetlanaUP** [comment]
@IfeanyiSam please do finalize this curation. Thank you.

**Comment by IfeanyiSam** [comment]
https://bugsigdb.org/Study_1160
@SvetlanaUP Kindly review now.

**Comment by IfeanyiSam** [comment]
@SvetlanaUP Good afternoon, are there any more papers that need correction?

**Comment by SvetlanaUP** [comment]
@IfeanyiSam select a new "paper to curate".

**Comment by IfeanyiSam** [comment]
Thank you for bringing this to our notice @SvetlanaUP and  @Buraah. I'll make the necessary changes

**Comment by IfeanyiSam** [comment]
Hi, @Svetlana and @Buraah I've reviewed the suggested corrections and the signatures in experiments 30, 28,26,25, 24 and 23 were significant.

Experiment 12, 13, 14, 22, 27, 29 also had significant results.

Experiment 10 & 11 actually represent two experiments. From the text; "Seventeen genera showing similar trends between the uncultured model/control (M/N) and cultured model/control (MD/ND) were selected as key genera. These genera were used to quantitatively describe the effects of XFBD-derived compounds on the gut microbiome of SIRS mice through differential abundance analysis with DESeq2 ([Fig. 5B]." 
This means M/N and MD/ND are different groups even though they have the same results so should be different expereiments.
Please review the above again. Thank you

@SvetlanaUP Please delete exp 8,9, Experiment 23(signature 1) and Experiment 27(signature 1)
Thank you.

**Comment by SvetlanaUP** [comment]
Deleted
Study 1160/Experiment 8
Study 1160/Experiment 9
Study 1160/Experiment 23/Signature 1
Study 1160/Experiment 27/Signature 1

@Buraah (https://github.com/Buraah) please see comment above.

**Comment by Buraah** [comment]
Hi @IfeanyiSam,
Thank you for taking a second look at this.

Here's what I think about the Experiments:

**Experiments 10 and 11:** From this text, "_Seventeen genera showing similar trends between the uncultured model/control (M/N) and cultured model/control (MD/ND) were selected as key genera._" 
We can see the comparisons the study made, which is what you have curated. But because they have the same results and everything, it feels like a duplication. On the other hand, since it's not wrong, we can leave it the way it is.
So, to finalize this, let's make a minor correction.
Experiment 10: Our Group 1 definition should be "Un-cultured model" instead of "Cultured model".
Experiment 11: Our Data Transformation should be "Raw counts".

**Insignificant Experiments:** For these experiments, we had these significant P values:* P 0.05, ** P 0.01, *** P 0.001. The results, mainly from Fig. S5D, show how these were significant with the asterisks (*, **, **), while some comparisons are just blank (no asterisks). The blank ones can sometimes mean either higher than 0.05 or lower than 0.001 (From my experience with other studies).
Some studies provide the p values for all the signatures, which makes it easier to see which ones are within the significant range, but this one did not.
So, it's in our best interest to only curate what they specifically record as significant.

Thank you.

CC: @SvetlanaUP

**Comment by IfeanyiSam** [comment]
Hi @Buraah Thank you for taking the time to point this out. 
@SvetlanaUP  Please delete  Exp 12(signature 1), Exp14 (Signature 1),  Exp 22 (signature 1), and  Exp 25 (signature 1)

**Comment by SvetlanaUP** [comment]
/Experiment_12/Signature_1
/Experiment_14/Signature_1
/Experiment_22/Signature_1
/Experiment_25/Signature_1
deleted.

**Comment by SvetlanaUP** [comment]
@Buraah please review the corrections in order to close this curation, thanks!

**Comment by Buraah** [comment]
Hi @SvetlanaUP, This curation is ready to be closed. 

I made some corrections (Removed signatures), and we need to delete these experiments: 12, 13, 14, 22, 27, 29 and Signature 2 in experiment 26.

Thank you.

**Comment by IfeanyiSam** [comment]
Good morning @SvetlanaUP and @Buraah. I can see your corrections @Buraah. Thank you. Before these are deleted, please can we get on a huddle so we could discuss this.
For instance, in exp 23, Enterobacter and Escherichia are significant but they've been removed.
Maybe there's something you're seeing that I'm not or there's something I'm  seeing, that you're not. What do you think?

**Comment by SvetlanaUP** [comment]
@Buraah please meet with @IfeanyiSam and discuss this.

**Comment by Buraah** [comment]
Of course @IfeanyiSam
I'll say hi on Slack

**Comment by Buraah** [comment]
Hi @SvetlanaUP, I've had a call with @IfeanyiSam
It was an oversight on my end. I'm sorry about that.

We don't need to remove more experiments. Everything is great now, and we can close.

Thank you so much @IfeanyiSam

**Comment by SvetlanaUP** [comment]
Good job both @IfeanyiSam @Buraah!
