### ISSUE TITLE
Neelam Mahraj

### ISSUE THREAD

**Issue by Neelam014** [waldronlab/BugSigDBcuration#512]

**Comment by Neelam014** [comment]
I successfully completed the curated form and now want to contribute to the second task, but I don't know what to do next.

**Comment by SvetlanaUP** [comment]
@Neelam014 Please note we communicate in the Slack **#bugsigdb channel** (https://slack.bioconductor.org/) dedicated to all communication for this project. You will find there all important information for your next steps as well as the community always ready to help.
