### ISSUE TITLE
Previse preterm birth in early pregnancy through vaginal microbiome signatures using metagenomics and dipstick assays

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#513]
Previse preterm birth in early pregnancy through vaginal microbiome signatures using metagenomics and dipstick assays – Daizee Talukdar – Cell
https://www.cell.com/iscience/fulltext/S2589-0042(24)02463-5

**Comment by SvetlanaUP** [comment]
@Rahila-me based on the publishing information about this paper: "[Online now](https://www.cell.com/isci/newarticles) 111238 **October 22,** 2024", we see that it is very recently published and sometimes it needs time to get its PMID.

**Comment by Rahila-me** [comment]
@SvetlanaUP since the curation of this paper will be pending till further notice, i asked for another paper which has not be assigned to me. Waiting for your kind reply

**Comment by SvetlanaUP** [comment]
@Rahila-me thank you for your patience.

**Comment by AleruDivine** [comment]
We’ll get on it @SvetlanaUP 
Thank you so much!

**Comment by Rahila-me** [comment]
Ok

**Comment by Rahila-me** [comment]
@SvetlanaUP This study is ready for review. : https://bugsigdb.org/Study_1243
Curated by I and @AleruDivine

**Comment by AleruDivine** [comment]
@IfeanyiSam Can you review this study, please?
Thank you so much!

**Comment by IfeanyiSam** [comment]
@AleruDivine yes I will
@SvetlanaUP please assign the paper to me for review. Thank you

**Comment by AleruDivine** [comment]
Thank you so much! @IfeanyiSam

**Comment by IfeanyiSam** [comment]
Welldone on your curation. Excellent work @AleruDivine and @Rahila-me. I have reviewed this curation @SvetlanaUP and it is complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1243 reviewed.

**Comment by AleruDivine** [comment]
Thank you so much for the review @IfeanyiSam
