### ISSUE TITLE
The need for high-resolution gut microbiome characterization to design efficient strategies for sustainable aquaculture production

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#514]
The need for high-resolution gut microbiome characterization to design efficient strategies for sustainable aquaculture production – Shashank Gupta – Communications Biology
https://www.nature.com/articles/s42003-024-07087-4

**Comment by AleruDivine** [comment]
An excellent curation @yokoDots, well done! 👏👏
Just a quick note: I curated '**other genus**' as '**unidentified**' with **taxID** 32644 instead of omitting it entirely in signature 1 of experiments 3 and 4.

@SvetlanaUP, this review is now complete.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1226 reviewed.
