### ISSUE TITLE
Alterations of the gut microbiome in HIV infection highlight human anelloviruses as potential predictors of immune recovery

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#518]
Alterations of the gut microbiome in HIV infection highlight human anelloviruses as potential predictors of immune recovery – Celia Boukadida – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01925-7

**Comment by IfeanyiSam** [comment]
Hello @SvetlanaUP, I'd like to work on this paper

**Comment by IfeanyiSam** [comment]
@SvetlanaUP Hi, i've studied the paper and i'm a bit confused about how to report the differential abundance. 
Under "Bacterial dysbiosis is associated with advanced stages of HIV infection" section, they mentioned this (we explored differences in bacterial communities by differential abundance analysis (DAA) using Microbiome Multivariate Association with Linear Models (MaAsLin2). First, the top 3 phyla were Bacteroidota, Bacillota, and Pseudomonadota (formally Bacteroidetes, Firmicutes, and Proteobacteria, respectively), accounting for more than 97% of all phyla. At the genus level, Prevotella, Bacteroides, Faecalibacterium, Alloprevotella, and UCG-002 accounted for more than 50% of all genera. For DAA, we ran two models: the first one included CD4 T cell counts and HIV status, while the second one considered the five-study group stratification, in addition to age, sexual preference, BMI, antibiotic use, and hospitalization. Both models demonstrated that hospitalization was positively associated with Enterococcus and Streptococcus, and negatively with alpha diversity (Shannon index), while HIV status was positively associated with Coprococcus (Excel S7).) but looking at the supplementary data &, i can't tell what they're comparing.

**Comment by SvetlanaUP** [comment]
Hi @IfeanyiSam, this question is for Slack.

**Comment by SvetlanaUP** [comment]
@Rahila-me https://github.com/Rahila-me you could help in here.

**Comment by Rahila-me** [comment]
@SvetlanaUP got it. Do i still have to reach out to @IfeanyiSam before adding to the curation on slack

**Comment by SvetlanaUP** [comment]
Yes, please contact @IfeanyiSam and enjoy your team work!

**Comment by IfeanyiSam** [comment]
@SvetlanaUP Thanks for the clarification. I'll work with @Rahila-me on this.

**Comment by SvetlanaUP** [comment]
@Rahila-me @IfeanyiSam this study is not curatable. Please see https://community-bioc.slack.com/archives/C04RATV9VCY/p1731066637591289?thread_ts=1730988400.486679&cid=C04RATV9VCY
