### ISSUE TITLE
Oral, Vaginal, and Stool Microbial Signatures in Patients With Endometriosis as Potential Diagnostic Non-Invasive Biomarkers: A Prospective Cohort Study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#520]
Oral, Vaginal, and Stool Microbial Signatures in Patients With Endometriosis as Potential Diagnostic Non-Invasive Biomarkers: A Prospective Cohort Study – Chloe Hicks – BJOG: An International Journal of Obstetrics and Gynaecology
https://obgyn.onlinelibrary.wiley.com/doi/full/10.1111/1471-0528.17979

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP 
Absolutely🤗 @MyleeeA 
Thank you for the offer. Let’s go!!🚀

**Comment by AleruDivine** [comment]
Good afternoon @SvetlanaUP 
We'd like to put this study up for review.
Link: https://bugsigdb.org/Study_1212

Thank you so much!

**Comment by KateRasheed** [comment]
Good afternoon @AleruDivine @MyleeeA . Great job on this curation. Just a few things to note before we close this:

- Experiment 10-12 is missing age and sex matched variables. See this: "Sixty-four age- and sex-matched subjects (n = 19 healthy control (HC); n = 24 non-endometriosis (N-ENDO) and n = 21 confirmed endometriosis (ENDO))"
- From Table 1 description, oral (mouth) has 18 HCs. This would affect the group sample sizes for experiment 1-3
- RF32 is Streptococcaceae bacterium RF32 while RF39 is Enterococcaceae bacterium RF39 when entered on Google search.

Thank you so much

**Comment by AleruDivine** [comment]
Thank you so much for the review @KateRasheed.
All corrections have been made too.

Thank you so much!

**Comment by KateRasheed** [comment]
Thank you for effecting the corrections 😊. This study has been reviewed @SvetlanaUP
