### ISSUE TITLE
Insights into the gut microbiome of vitiligo patients from India

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#521]
Insights into the gut microbiome of vitiligo patients from India – Sudhir Kumar – BMC Microbiology
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-024-03529-5

**Comment by IfeanyiSam** [comment]
@SvetlanaUP I'd like to curate this paper

**Comment by IfeanyiSam** [comment]
@SvetlanaUP can I collaborate with @Shulamite54 on this paper.
Also @Shulamite54 I've read through the paper and Statistical Test used was LEfSe meaning no MHT correction. Also, only feces was used for the study, as much blood was mentioned, it wasn't used.

**Comment by SvetlanaUP** [comment]
Sure @IfeanyiSam! You can contact @Shulamite54 on Slack [Precious Orakwe]

**Comment by IfeanyiSam** [comment]
Thank you @SvetlanaUP

**Comment by IfeanyiSam** [comment]
@Shulamite54 Okay, i'll review and check for any corrections

**Comment by Shulamite54** [comment]
Good evening @SvetlanaUP i am done with my study, its ready for review
https://bugsigdb.org/Study_1224
thank you @IfeanyiSam for helping out
thank you @SvetlanaUP

**Comment by KateRasheed** [comment]
Good morning @Shulamite54 @IfeanyiSam . Great job on this curation. Here are few things I would like you to correct on this study:

Please change gender to sex for the matched on.
For the antibiotics exclusion, please change it to "Individuals receiving antibiotics were excluded from the study".

Fig. 1b shows significant taxa in the phylum rank. Please add it to the signatures.

Table S4 is curatable. Also check Fig. S5

Thank you so much.

**Comment by KateRasheed** [comment]
@IfeanyiSam Fig. 1b wasn't referenced in the paper but it has a result. Same as Table S4(fourth supplementary material). 

I can't see Fig. S5 in your signature source. I can only see Table S7.

I wanted you to check through all supplementary materials and figures so you can add any taxa that is missing before I review the taxa.

**Comment by IfeanyiSam** [comment]
@KateRasheed Fig S5 was referenced in Supplementary material 12 and the same data is seen in Table S7 sheet 2, do I still need to source it in the curation?
I also curated all the significant taxa in  sheet 2 of Table S7. The ones that were not curated didn't show the class they belonged to.

For fig 1b, there's no statistical test mentioned, no p-value hence no way to tell which taxa is significant.
https://community-bioc.slack.com/archives/C04RATV9VCY/p1734004730581579  (this is an example of where it was clarified during Office Hours for figure 5C and 5D)

**Comment by IfeanyiSam** [comment]
@KateRasheed I have made the necessary correction. Thank you

**Comment by KateRasheed** [comment]
Thank you @IfeanyiSam . This review is complete @SvetlanaUP

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1224 reviewed.
