### ISSUE TITLE
Overcoming donor variability and risks associated with fecal microbiota transplants through bacteriophage-mediated treatments

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#523]
Overcoming donor variability and risks associated with fecal microbiota transplants through bacteriophage-mediated treatments – Torben Sølbeck Rasmussen – Microbiome
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-024-01820-1

**Comment by TheTosin** [comment]
Hello @SvetlanaUP can this article also be assigned to me?

**Comment by SvetlanaUP** [comment]
@TheTosin already assigned to https://github.com/waldronlab/BugSigDBcuration/issues/436

**Comment by TheTosin** [comment]
@SvetlanaUP  I also want to work on this study. I’m almost done with the curation.

**Comment by SvetlanaUP** [comment]
Team up and enjoy the weekend!
@TheTosin @AleruDivine

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by AleruDivine** [comment]
I did not realize you were already working on the paper @TheTosin since it was not assigned to anyone yet.
My apologies

**Comment by TheTosin** [comment]
I started the curation when I requested, thinking the article will be assigned to me. I intended on asking again for it to be assigned to me to submit the curation @SvetlanaUP

**Comment by SvetlanaUP** [comment]
@TheTosin that's not our recommendable practice. Please next time work on your official assignment.

**Comment by TheTosin** [comment]
Okay, noted @SvetlanaUP I apologize.
We would work on the curation and send over .

**Comment by SvetlanaUP** [comment]
@AleruDivine @TheTosin what's the status of https://bugsigdb.org/Study_1221? Thank you.

**Comment by AleruDivine** [comment]
Good morning @SvetlanaUP 
This study is nearly complete, we are waiting to get a confirmation on whether to proceed with curating a specific figure during the office hours today. We were unable to reach a conclusion on the Slack channel, and this is the only aspect holding up the study.🙏

**Comment by TheTosin** [comment]
Hello @SvetlanaUP We intend to confirm if another figure is to be curated in today’s office hour as stated by Divine earlier.

**Comment by TheTosin** [comment]
Hello @SvetlanaUP This study is ready for review.

https://bugsigdb.org/Study_1221

**Comment by AleruDivine** [comment]
Good morning @yokoDots, could you please review this curation?
Thank you so much!

**Comment by AleruDivine** [comment]
Thank you so much for the review @yokoDots
We’ll go through your observations and update the study for a second review.

**Comment by AleruDivine** [comment]
Thank you so much for the review, @yokoDots. I have made corrections 

I understand that both virus and bacteria experiments come from the same samples, so it makes sense that the group sample sizes would be consistent across both. But, the description in Figures 5 and 6, stating 'The “n” below the bar plots highlights the number of mice of which the taxonomical average was based on,' kind of suggests that these numbers represent the group sizes included in the results. Also, the bacteriome analysis was conducted using 16S rRNA gene amplicon sequencing, while the metavirome analysis was based on whole-genome sequencing so this is another factor that should be considered and I did not find any other mention of group sample sizes in the text. What do you think?

**Comment by AleruDivine** [comment]
Okay! Got it! @yokoDots  I do believe the figure is more specific as it also includes the number of mice for each contrast group, unlike the text.

**Comment by AleruDivine** [comment]
Hi @yokoDots I'll go ahead and add the experiments from Figures 4B and 4C and let you know so you can complete the review.
Thank you so much!

**Comment by AleruDivine** [comment]
Hi @yokoDots I added the additional experiments from Figure 4b and 4c. Can you give this a second review please?
Thank you so much!

**Comment by AleruDivine** [comment]
Thank you for the changes you made @yokoDots, For the FVT-UNT group size, I intended to curate 7 because I have that on my note. Thank you for noticing the error.
I have added a note concerning the sample sizes to clarify the difference in the text and figures.

Thank you so much for your patience.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1221 reviewed.
