### ISSUE TITLE
Association of Oral Microbiome With Risk for Incident Head and Neck Squamous Cell Cancer

### ISSUE THREAD

**Issue by haoyanzh** [waldronlab/BugSigDBcuration#53]
citation: Hayes RB, Ahn J, Fan X, Peters BA, Ma Y, Yang L, Agalliu I, Burk RD, Ganly I, Purdue MP, Freedman ND, Gapstur SM, Pei Z. Association of Oral Microbiome With Risk for Incident Head and Neck Squamous Cell Cancer. JAMA Oncol. 2018 Mar 1;4(3):358-365. doi: 10.1001/jamaoncol.2017.4777. PMID: 29327043; PMCID: PMC5885828.

**Comment by joy-commits** [comment]
Hello @haoyanzh 
Please, can I be assigned this study?
Thank you

**Comment by haoyanzh** [comment]
Thank you Ufuoma! Assigned.

**Comment by joy-commits** [comment]
Hello @haoyanzh @ftzohra22 
This study has been curated and even reviewed
Here: https://bugsigdb.org/Study_139

**Comment by ftzohra22** [comment]
Thank you for noticing @joy-commits. Closing issue
