### ISSUE TITLE
The effect of cigarette smoking on the oral and nasal microbiota

### ISSUE THREAD

**Issue by haoyanzh** [waldronlab/BugSigDBcuration#54]
Yu G, Phillips S, Gail MH, Goedert JJ, Humphrys MS, Ravel J, Ren Y, Caporaso NE. The effect of cigarette smoking on the oral and nasal microbiota. Microbiome. 2017 Jan 17;5(1):3. doi: 10.1186/s40168-016-0226-6. PMID: 28095925; PMCID: PMC5240432.

**Comment by Cindy-erella** [comment]
Kindly assign this to me, Cindy

**Comment by Bahati308** [comment]
hello @lwaldron , can i take over this please

**Comment by cmirzayi** [comment]
@Cindy-erella assigned.

**Comment by Cindy-erella** [comment]
https://bugsigdb.org/Study_756

**Comment by claregri** [comment]
Hi Cindy, thank you for your curation efforts! When I took a look at this paper, I noticed that there are no significantly differentially abundant taxa (in the results section of the abstract it says "We found that alpha diversity was lower in smokers than in nonsmokers in the buccal mucosa, but in other sample sites, microbial diversity and composition were not significantly different by smoking status.") If a paper has alpha diversity but not differential taxa, we don't curate into the database, so I have deleted this experiment.
