### ISSUE TITLE
 Association Between Oral Microbiota and Cigarette Smoking in the Chinese Population

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#57]
https://pubmed.ncbi.nlm.nih.gov/34123872/

**Comment by joy-commits** [comment]
Hello @lwaldron @ftzohra22 
Please, can I be assigned this study

Name: Ufuoma Ejite

**Comment by atrayees** [comment]
May I please curate this paper? 
Atrayee Samanta

**Comment by cmirzayi** [comment]
Hi @atrayees Checking in on this one. Did you finish it?

**Comment by atrayees** [comment]
Yes, I have finished this one at: https://bugsigdb.org/Study_660

**Comment by Peacesandy** [comment]
Reviewed
