### ISSUE TITLE
Alcohol and tobacco consumption affects bacterial richness in oral cavity mucosa biofilms

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#59]
https://pubmed.ncbi.nlm.nih.gov/25278091/

**Comment by joy-commits** [comment]
Hello @lwaldron @ftzohra22 
Please, can I be assigned this study?
Thank you

Name: Ufuoma Ejite

**Comment by atrayees** [comment]
I have curated this at https://bugsigdb.org/Study_756.

**Comment by Peacesandy** [comment]
Reviwed
