### ISSUE TITLE
Differences in the gut microbiome by physical activity and BMI among colorectal cancer patients

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#6]
Condition: BMI, physical activity
URL: https://drive.google.com/file/d/1rVSKVwJ9CoKcRnuWynziTxaHCt9Z3s-k/view

**Comment by RotimiDesire** [comment]
Hello, I'm interested in this article. I'd love to be assigned to it.

**Comment by RotimiDesire** [comment]
Desire Oluwarotimi.

**Comment by cmirzayi** [comment]
Assigned!

**Comment by RotimiDesire** [comment]
Curated article : https://bugsigdb.org/Study_444

Kindly review. Thanks.

**Comment by cmirzayi** [comment]
Hi @RotimiDesire. It's a good attempt at a difficult paper. Unfortunately I think there was a bit of confusion. Your instincts were correct that the bar graphs (figure 2) could be curated but the actual statistical tests are in the supplemental tables 2 and 3. There also appears to be some weirdness in what you curated for each signature that I can't figure out. Be careful that you are curating into each signature only taxa that were different for that particular contrast--overweight and obese were separate groups, for instance. Please review carefully, ask questions, and resubmit.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (cohort as stated in Study Population)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0 (figures should not have been curated; instead supplemental tables have the statistical tests for these figures)
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (while all participants had colorectal cancer, the contrasts were on other conditions such as weight and physical activity)
6. Contrast groups correctly identified (1 point): Not scored from here on due to incorrect curation
7. Groups correctly labelled as 1 and 0 (1=cases, 0=controls) (1 point):
8. Antibiotic exclusion correctly identified (1 point):
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points):
10. Identified correct statistical test (1 point):
11. Identified MHT correction (1 point):
12. Correctly recorded matched on factors (1 point):
13. Entered correct number of statistical tests per experiment (1 point):
14. All diversity measures identified (1 point):
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point):
16. All signature sources correctly identified  (-1 for each error)  (2 points):
17. Abundance direction correctly selected (1 point):
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points):
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points):

Total (maximum 24 points): Not scored due to missing/incomplete curation

**Comment by RotimiDesire** [comment]
@cmirzayi Thank you for the feedback, I'll work on it again.

**Comment by RotimiDesire** [comment]
@cmirzayi I'm done with reviewing my curation. Please take a look at it again.

**Comment by atrayees** [comment]
Study 444
Corrected the NCBI taxonomy used in the signatures of all 7 experiments. The rest of the curation seems fine.

**Comment by lwaldron** [comment]
Thanks @atrayees ! As you complete your reviews you can go ahead and mark studies and their experiments and signatures as "Reviewed", and close issues here.
