### ISSUE TITLE
Profiling the Salivary microbiome of the Qatari population

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#61]
https://pubmed.ncbi.nlm.nih.gov/32169076/

**Comment by Susu-spec** [comment]
This looks interesting. Can I be assigned this paper?

**Comment by Susu-spec** [comment]
https://bugsigdb.org/Study_750

I'm not sure if this is a 'me' problem whenever I added the variable regions, any experiment after the first would not show up after I saved the page but it would show up in the edits. I tried adding different variable regions, that worked. It looks like similar variable regions do not show up in the rest of the experiments but then again, it could be a 'me' problem.
And the "matched on", confounding factors in this paper were confusing to me.

**Comment by Susu-spec** [comment]
The variable regions problem also happened with https://bugsigdb.org/Study_751

**Comment by ftzohra22** [comment]
@Susu-spec thank you for noticing this. I tested it myself and seems like a bug. We'll report it as an issue. As for matching, any time a study selects controls that were "matched" based on certain factors we record those factors (for example age, sex, body mass index). Please comment on this when you're done working on the paper and its ready for review.

**Comment by Susu-spec** [comment]
Thank you so much, it's ready for review
https://bugsigdb.org/Study_750

**Comment by cmirzayi** [comment]
@Susu-spec This was a very challenging curation. You did an excellent job entering the differential abundance results. There were a few issues. First, there is some info missing such as condition and variable region. The figures were not always intuitive and you missed some nuances of the statistical tests and alpha diversity measures as a result. Finally there were a few taxa that were entered incorrectly (i.e. "g__Saccharibacteria_TM7__G_1_" should be entered as Saccharibacteria TM7). Overall, I am impressed.

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 0 (missing for some experiments)
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point):  1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1 (missing variable region)
10. Identified correct statistical test (1 point): 1 (incorrect threshold. They used LDA score not statistical significance)
11. Identified MHT correction (1 point): 0 (was not MHT-corrected)
12. Correctly recorded matched on factors (1 point): 0 (incorrect matching for each experiment--you can't match on age when it's your experimental condition, for instance)
13. Entered correct number of statistical tests per experiment (1 point): 1
14. All diversity measures identified (1 point): 0 (missing for several experiments)
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 (incorrect for several experiments)
16. All signature sources correctly identified  (-1 for each error)  (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 1 (genera that weren't found could be found if edited)

Total (maximum 24 points): 16

**Comment by cmirzayi** [comment]
Hi @Susu-spec  Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by Susu-spec** [comment]
Hello, Chloe!

Sorry about the very late reply.
I've been battling final semester. I'd love to finish this curation
although it might take a while. Is that fine?

Best,
Suwaibat.

**Comment by atrayees** [comment]
Shall I go ahead and finish the curation?

**Comment by atrayees** [comment]
I made the following changes after reviewing:
1. Entered required condition for all the experiments
2. Corrected the alpha diversity results
3. Corrected the threshold values
