### ISSUE TITLE
The Gut Microbiome and Cancer Immunotherapy: Can We Use the Gut Microbiome as a Predictive Biomarker for Clinical Response in Cancer Immunotherapy?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#63]
This is a review paper and therefore should **NOT** be added directly, but the references contained within should be checked for ones reporting signatures on the gut microbiome and cancer immunotherapy. https://pubmed.ncbi.nlm.nih.gov/34638308/

**Comment by kahvecirem** [comment]
Can you assign this study to me?

Best Regards

**Comment by lwaldron** [comment]
This isn't an article for curation, but if you see another article cited within that isn't already in the wiki, please create a new issue and we'll assign it to you. This will of course be after the Outreachy contribution period though 😀
