### ISSUE TITLE
Altered infective competence of the human gut microbiome in COVID-19 - Microbiome

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#65]
URL: https://pubmed.ncbi.nlm.nih.gov/36894986/
 Condition: COVID-19

**Comment by ftzohra22** [comment]
@Aiysha689 sorry Busayo-Ojo found this paper by themself and curated it. i added it as an issue just for record. It's already assigned to them.

**Comment by Busayo-ojo** [comment]
@ftzohra22 Hi Fatima

**Comment by Busayo-ojo** [comment]
Hi Fatima, this is the link to the curated study. Thanks
https://bugsigdb.org/Study_734

**Comment by ftzohra22** [comment]
@Busayo-ojo good effort on this curatioin. A few points to note: for study design this was a case-control study not cross-sectional, because they had selected a case group and a "matched" control group. For sequencing type, this was a WMS sequencing as there was no mention of 16s rather they used a "metagenomic" library for analysis, which is why there will also be no variable regions (variable regions are only from a 16S gene). Please also remember that there cannot be more than one statistical test per experiment. I've also corrected your alpha diversity results. They only used Shannon index here (figure S2 has the results specified). Please review the corrections. Thank you.
