### ISSUE TITLE
Comparison of the respiratory microbiome in healthy nonsmokers and smokers

### ISSUE THREAD

**Issue by haoyanzh** [waldronlab/BugSigDBcuration#66]
Morris A, Beck JM, Schloss PD, Campbell TB, Crothers K, Curtis JL, Flores SC, Fontenot AP, Ghedin E, Huang L, Jablonski K, Kleerup E, Lynch SV, Sodergren E, Twigg H, Young VB, Bassis CM, Venkataraman A, Schmidt TM, Weinstock GM; Lung HIV Microbiome Project. Comparison of the respiratory microbiome in healthy nonsmokers and smokers. Am J Respir Crit Care Med. 2013 May 15;187(10):1067-75. doi: 10.1164/rccm.201210-1913OC. PMID: 23491408; PMCID: PMC3734620.

**Comment by atrayees** [comment]
Hello, I would love to curate this!

**Comment by cmirzayi** [comment]
Hi @atrayees Checking in on this one as well.

**Comment by atrayees** [comment]
I'm still working on this curation! I haven't finished it yet

**Comment by atrayees** [comment]
Curated at https://bugsigdb.org/Study_737.

**Comment by Peacesandy** [comment]
Reviewed
