### ISSUE TITLE
Recurrent urinary tract infection and estrogen shape the taxonomic ecology and function of the postmenopausal urogenital microbiome

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#69]
Recurrent urinary tract infection and estrogen shape the taxonomic ecology and function of the postmenopausal urogenital microbiome – Michael L. Neugent et al.– Cell Reports Medicine 2022 

DOI:https://doi.org/10.1016/j.xcrm.2022.100753

https://www.cell.com/cell-reports-medicine/fulltext/S2666-3791(22)00302-0

**Comment by Tolulope028** [comment]
Tolulope Ogunleye

**Comment by Folakunmi21** [comment]
Afuape Esther

**Comment by cmirzayi** [comment]
@Folakunmi21 I have assigned this to @Tolulope028. Please choose another article.

**Comment by Folakunmi21** [comment]
Noted!

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_812 

Needs Review

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_812 reviewed.
