### ISSUE TITLE
Urinary Microbiome and Psychological Factors in Women with Overactive Bladder

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#70]
Urinary Microbiome and Psychological Factors in Women with Overactive Bladder – Peng Wu – Front. Cell. Infect. Microbiol. 2017

DOI: 10.3389/fcimb.2017.00488

https://www.frontiersin.org/articles/10.3389/fcimb.2017.00488/full

**Comment by debsonalo** [comment]
Onalo Deborah.

I want to claim this article for curation. @cmirzayi

**Comment by cmirzayi** [comment]
Assigned!

**Comment by debsonalo** [comment]
Thank you!

**Comment by debsonalo** [comment]
@cmirzayi @lwaldron @SvetlanaUP I would like to submit my second contribution for review, please. I am done curating this study. This is documented at: https://bugsigdb.org/Study_776

**Comment by SvetlanaUP** [comment]
Marked for review.

**Comment by SvetlanaUP** [comment]
Hi @debsonalo 

this is a good curation, but some details should be fixed.

Please see my comments below. We are looking forward to seeing the revised curation. /cc @cmirzayi @lwaldron

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 16 |

2. Be careful, it's not rare that authors define their own study design incorrectly. This is not "cross sectional study" as authors stated in this paper.

13. missing for the experiment 2: Data transformation Not specified -> should be corrected

14. Looks like Simpson and Chao1 were the only significant alpha diversity measures. It’s not enough for them to be “markedly” it needs to be statistically significantly different to curate, just like differential abundance results.
Note: Observed species=richness

**Comment by Peacesandy** [comment]
Reviwed
