### ISSUE TITLE
Interplay between bladder microbiota and overactive bladder symptom severity: a cross‐sectional study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#71]
Interplay between bladder microbiota and overactive bladder symptom severity: a cross‐sectional study – Kun Li et al. – BMC Urology 2022

DOI: 10.1186/s12894-022-00990-0
https://bmcurol.biomedcentral.com/articles/10.1186/s12894-022-00990-0

**Comment by Tolulope028** [comment]
Tolulope Ogunleye

**Comment by cmirzayi** [comment]
Assigned.

**Comment by ChineseChikki** [comment]
@cmirzayi @SvetlanaUP @lwaldron
The owner abandoned it, so I curated it. Please take a look and do a second review.
https://bugsigdb.org/Study_787
Needs review to be closed

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_787 
Reviewed
