### ISSUE TITLE
Differential Urinary Microbiota Composition Between Women With and Without Recurrent Urinary Tract Infection

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#72]
Differential Urinary Microbiota Composition Between Women With and Without Recurrent Urinary Tract Infection – Lei Huang et al. – Frontiers in Microbiology 2022
DOI: 10.3389/fmicb.2022.888681

https://www.frontiersin.org/articles/10.3389/fmicb.2022.888681/full

**Comment by AleruDivine** [comment]
Aleru Divine

I want to claim this article for curation @cmirzayi

**Comment by AleruDivine** [comment]
Thank you so much! @cmirzayi

**Comment by AleruDivine** [comment]
@cmirzayi @SvetlanaUP @lwaldron I have completed my curation and here's the link: https://bugsigdb.org/Study_798. 
I am looking forward to your review. 
Thank you!

**Comment by AleruDivine** [comment]
Hi @cmirzayi @SvetlanaUP @lwaldron the needs review label has not been added yet and I'm just commenting as a reminder in case of an oversight.

**Comment by SvetlanaUP** [comment]
@AleruDivine it's under review. I'll get to you asap.

**Comment by AleruDivine** [comment]
Thank you so much @SvetlanaUP

**Comment by SvetlanaUP** [comment]
@AleruDivine, this is a near perfect curation, well done!! Please add one diversity measure missing.

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on variables (1 point): 1
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 0 (one missing)
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2
Total (maximum 23 points): 22

**Comment by AleruDivine** [comment]
@SvetlanaUP Thank you so much for the review. I will check and add the missing diversity measure right away.

**Comment by AleruDivine** [comment]
Hello @SvetlanaUP, I have just updated my curation and added the missing diversity measures.

Here is the link: https://bugsigdb.org/Study_798

Thank you so much!

**Comment by SvetlanaUP** [comment]
@AleruDivine well done!

**Comment by AleruDivine** [comment]
@SvetlanaUP Thank you so much!
