### ISSUE TITLE
The gut microbiota in multiple sclerosis varies with disease activity

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#73]
The gut microbiota in multiple sclerosis varies with disease activity – Florence Thirion et al. – Genome Medicine 2023
DOI: 10.1186/s13073-022-01148-1
https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01148-1

**Comment by cmirzayi** [comment]
**NOTE TO CURATOR:** This paper includes a viral species differential abundance in the supplementary information. This should be curated, but may be a more challenging curation as we don't have a ton of examples of virus studies.

**Comment by Omabekee** [comment]
Thanks for the heads up @cmirzayi  I'll ask questions on slack if I get stuck.
May I curate this?
Chioma Blessing Onyido

**Comment by Omabekee** [comment]
Hi @SvetlanaUP @cmirzayi 👋🏾😅

**Comment by SvetlanaUP** [comment]
@Omabekee please see other papers, I added some new ones yesrterday. This one is out of outreachy curation.

**Comment by Omabekee** [comment]
Got it!
