### ISSUE TITLE
Gut microbiome and atrial fibrillation—results from a large population-based study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#74]
Gut microbiome and atrial fibrillation—results from a large population-based study – Joonatan Palmu et al. – eBioMedicine 2023
DOI: 10.1016/j.ebiom.2023.104583
https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(23)00148-2/fulltext

**Comment by iram-jamshed** [comment]
@SvetlanaUP @lwaldron @cmirzayi Requesting you to assign this paper to me!

**Comment by cmirzayi** [comment]
Assigned.

**Comment by iram-jamshed** [comment]
Thank you so much! :)

**Comment by Peacesandy** [comment]
Reviewed

https://bugsigdb.org/Study_832

**Comment by SvetlanaUP** [comment]
@Peacesandy https://bugsigdb.org/Study_832 any particular reason why the Experiment 3 is not reviewed? Thanks.

**Comment by Peacesandy** [comment]
Hi @SvetlanaUP 
Sorry about the mix-up. Experiment 3 was added after the study had been reviewed. Going by the date, the study was reviewed on 2023/2/21, but the experiment was added on 2023/10/16. From the look of things experiment 3 is irrelevant, no group 0 or comparison group, He or She just added one group.

**Comment by SvetlanaUP** [comment]
Experiment 3 with Signatures 1 and 2 deleted.

**Comment by Peacesandy** [comment]
Thank you so much @SvetlanaUP
