### ISSUE TITLE
Sputum Microbiome and Chronic Obstructive Pulmonary Disease in a Rural Ugandan Cohort of Well-Controlled HIV Infection

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#75]
Sputum Microbiome and Chronic Obstructive Pulmonary Disease in a Rural Ugandan Cohort of Well-Controlled HIV Infection – Alex Kayongo et al. – Microbiology Spectrum
DOI: 10.1128/spectrum.02139-21
https://journals.asm.org/doi/full/10.1128/spectrum.02139-21

**Comment by shakirandagire** [comment]
Would you assign me to this article please

**Comment by cmirzayi** [comment]
Assigned.

**Comment by ChineseChikki** [comment]
@cmirzayi @SvetlanaUP @lwaldron 
The owner abandoned it, so I curated it. Please take a look and do a second review.
 https://bugsigdb.org/Study_799
 Needs review

**Comment by Peacesandy** [comment]
Reviewed

https://bugsigdb.org/Study_799
