### ISSUE TITLE
Shotgun sequencing of the vaginal microbiome reveals both a species and functional potential signature of preterm birth

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#76]
Shotgun sequencing of the vaginal microbiome reveals both a species and functional potential signature of preterm birth – Conor Feehily et al. –  npj Biofilms and Microbiomes 2020
DOI: 10.1038/s41522-020-00162-8
https://www.nature.com/articles/s41522-020-00162-8

**Comment by Analyst-Joan** [comment]
Joan C. Chukwuemeka

Please I want to claim this article for curation @cmirzayi @lwaldron @SvetlanaUP

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Analyst-Joan** [comment]
Thank you

**Comment by Analyst-Joan** [comment]
Good day @cmirzayi @SvetlanaUP @lwaldron 

I have finished curating this [article](https://www.nature.com/articles/s41522-020-00162-8) to the best of my knowledge. 
You can find the BugSigDB link at [Study_791](https://bugsigdb.org/Study_791) for your review. 

Please take a look and let me know if there are any changes or improvements needed. 
Your feedback is greatly appreciated!

Thank you.

**Comment by cmirzayi** [comment]
Marked for review.

**Comment by SvetlanaUP** [comment]
Hi @Analyst-Joan 
I have to admit this study is a though one to curate. 

Please see my comment below. We are looking forward to seeing the revised curation. /cc @cmirzayi @lwaldron 

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 0 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 1 |
|  | TOTAL | 23 | 14 |

Table 2 is potentially curatable but it is confusing because it seems to present the results from several different contrasts at once. Analyze more carefully Figure 2, especially statistically significant species as signature members.

**Comment by Analyst-Joan** [comment]
Thanks for the helpful feedback @SvetlanaUP. 😃 

I have reviewed the study again and updated the curation. The additional guidance and clarity from @cmirzayi and @lwaldron went a long way to assist me in this learning journey.

The **[revised curation](https://bugsigdb.org/Study_791)** is now ready for review.

Thanks for your time. Look forward to hearing from you.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_791 reviewed.

**Comment by SvetlanaUP** [comment]
@Fificode please take a look https://www.nature.com/articles/s41522-020-00162-8#data-availability and curate this study for the cMD database.

Also, check it out if this BugSigDB curation has been recorded in your working table with other Women Health studies.
