### ISSUE TITLE
The upper respiratory tract microbiota of healthy adults is affected by Streptococcus pneumoniae carriage, smoking habits, and contact with children

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#79]
The upper respiratory tract microbiota of healthy adults is affected by Streptococcus pneumoniae carriage, smoking habits, and contact with children – A. Cristina Paulo et al. – Microbiome 2023
DOI: 10.1186/s40168-023-01640-9
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01640-9

**Comment by Kingecha** [comment]
Name: Karen254.
Hey @SvetlanaUP I would like to claim this article.

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Kingecha** [comment]
Thankyou.

**Comment by Kingecha** [comment]
Hey @lwaldron @cmirzayi @SvetlanaUP I'm done curating my paper kindly review.

**Comment by cmirzayi** [comment]
Marked for review.

**Comment by cmirzayi** [comment]
Unfortunately I think you had a fairly fundamental misunderstanding of the paper and how to curate it. I would focus on the results presented in the supplemental tables S5 through S7 as well as Figure 5E.

The statistical test was a type of linear model, not a chi-squared test.

There were 3 experiments that I could identify:
Carriers vs. not
Smokers vs. not
Child exposure vs. not

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 0 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 0 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 0 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 0 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 11 |


https://bugsigdb.org/Study_795

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_795

Reviewed
