### ISSUE TITLE
Reduced Abundance of Butyrate-Producing Bacteria Species in the Fecal Microbial Community in Crohn's Disease

### ISSUE THREAD

**Issue by ftzohra22** [waldronlab/BugSigDBcuration#8]
Condition: Crohn's Disease
URL : https://pubmed.ncbi.nlm.nih.gov/26789999/

**Comment by cheyemera** [comment]
Hi, I would like to work on this article! Caroline Shi

**Comment by ftzohra22** [comment]
Assigned to you @cheyemera.

**Comment by cmirzayi** [comment]
Hi @cheyemera Thank you so much for your contributions to the BugSigDB project. I wanted to check to see if you wanted to finish this curation. I understand that with the Outreachy applicant selection process over, you may no longer wish to help out with BugSigDB or have other priorities right now.

If not, I will open it up to other curators to finish the curation.

**Comment by atrayees** [comment]
Curated at https://bugsigdb.org/Study_89 .

Also I just curated this study, but almost all of the fields have appeared with the 'Reviewed' tag, despite me not reviewing any of them

**Comment by atrayees** [comment]
Yes, I got it and made the changes. I'll go through my other curations to correct mistakes, if any.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_89

Reviewed
