### ISSUE TITLE
Exploring the gut microbiota in patients with pre-diabetes and treatment naïve diabetes type 2 - a pilot study

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#80]
Exploring the gut microbiota in patients with pre-diabetes and treatment naïve diabetes type 2 - a pilot study – Kristin Gravdal et al. – BMC Endocrine Disorders 2023
DOI: 10.1186/s12902-023-01432-0
https://bmcendocrdisord.biomedcentral.com/articles/10.1186/s12902-023-01432-0

**Comment by Kadeniyi23** [comment]
Adeniyi Kabirat

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Kadeniyi23** [comment]
Hey @lwaldron @SvetlanaUP @cmirzayi Im happy to submit my curated paper for review. the link is [https://bugsigdb.org/Study_786](https://bugsigdb.org/Study_786)

**Comment by cmirzayi** [comment]
Marked as ready for review.

**Comment by cmirzayi** [comment]
Excellent curation. It just needs some small changes as well as some fixes to clarify the difference between experiments 1 and 2 compared to experiment 3 (which uses a different sequencing platform).

Case-control study

One experiment was done using GA-map 131-plex not Illumina.

"Dorea spp." is not the same thing as "Dorea." This is true for many of the curated taxa and needs to be corrected.

Experiment 3 comes from table 2 but is labeled table 3.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 0 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 0 |
|  | TOTAL | 23 | 18 |

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_786

Reviewed
