### ISSUE TITLE
Gastrointestinal symptoms of long COVID-19 related to the ectopic colonization of specific bacteria that move between the upper and lower alimentary tract and alterations in serum metabolites

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#82]
Gastrointestinal symptoms of long COVID-19 related to the ectopic colonization of specific bacteria that move between the upper and lower alimentary tract and alterations in serum metabolites – Deyu Zhang – BMC Medicine 2023
DOI: 10.1186/s12916-023-02972-x
https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-023-02972-x

**Comment by wendeee** [comment]
Chinwendu Enyinna

I want to claim this article for curation.

**Comment by cmirzayi** [comment]
Assigned.
