### ISSUE TITLE
Global branches and local states of the human gut microbiome define associations with environmental and intrinsic factors

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#83]
Global branches and local states of the human gut microbiome define associations with environmental and intrinsic factors – Julien Tap – Nature Communications 2023
DOI: 10.1038/s41467-023-38558-7
https://www.nature.com/articles/s41467-023-38558-7

**Comment by cmirzayi** [comment]
I think this one might be a bit too difficult as a second curation--the differential abundance analysis is conducted on the results from a unsupervised partition task. I would imagine even seasoned curators might struggle with curating this article.

**Comment by Omabekee** [comment]
Hi @cmirzayi @SvetlanaUP, may I please curate this?
Chioma Blessing Onyido

**Comment by SvetlanaUP** [comment]
@Omabekee I added more papers, please take a look! This one is out of our outreachy contribution stage because of too many challenges.
