### ISSUE TITLE
Differential Responses to Dietary Protein and Carbohydrate Ratio on Gut Microbiome in Obese vs. Lean Cats

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#84]
For the cat lovers out there

 Li Q and Pan Y (2020) Differential Responses to Dietary Protein and Carbohydrate Ratio on Gut Microbiome in Obese vs. Lean Cats. Front. Microbiol. 11:591462. doi: 10.3389/fmicb.2020.591462

https://www.frontiersin.org/articles/10.3389/fmicb.2020.591462/full

**Comment by RotimiDesire** [comment]
Desire Oluwarotimi.

I want to claim this article for curation. @cmirzayi

**Comment by RotimiDesire** [comment]
Thank you @lwaldron 

I'm awaiting instructions from you or @cmirzayi then.

**Comment by cmirzayi** [comment]
Hi @RotimiDesire 

I've taken a look at your first contribution (the mini curation) and I think you're good to start on this. I will assign this article to you. Please post any questions on the Slack channel as I think this article may bring some challenges compared to a human study.

**Comment by RotimiDesire** [comment]
Alright. 

Thank you.

**Comment by RotimiDesire** [comment]
I completed my curation. @lwaldron @cmirzayi 

I await your review.

**Comment by cmirzayi** [comment]
@RotimiDesire Good curation of an interesting paper. There were some small errors: richness was measured (they referred to it as observed species), they did kruskal-wallis tests followed by Dunn's tests for pairwise comparisons, and your matched on variables were slightly off. Overall, excellent work. Please feel free to make these edits and/or you can claim another article if you'd like to continue curating.

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 1
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
Condition entered according to contrast (correct EFO ontology) (1 point): 1
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 1
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
Identified correct statistical test (1 point): 1
Identified MHT correction (1 point): 1
Correctly recorded matched on variables (1 point): 0 (body weight was not matched on; you cannot match on a condition)
Entered correct number of statistical tests per experiment (1 point): 0 (missing Dunn's post-hoc test)
All diversity measures identified (1 point): 0 (missing richness/observed species)
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 2
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2
Total (maximum 23 points): 20

**Comment by RotimiDesire** [comment]
Thank you for the review. @cmirzayi

I'd make the necessary corrections and also claim another paper for curation. I think it's fun.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_772

Reviewed
