### ISSUE TITLE
Differential Dynamics of the Ruminal Microbiome of Jersey Cows in a Heat Stress Environment

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#86]
🐄 🐄 🐄 🐄 🐄 🐄 

Kim D-H, Kim M-H, Kim S-B, Son J-K, Lee J-H, Joo S-S, Gu B-H, Park T, Park B-Y, Kim E-T. Differential Dynamics of the Ruminal Microbiome of Jersey Cows in a Heat Stress Environment. Animals. 2020; 10(7):1127. https://doi.org/10.3390/ani10071127

https://www.mdpi.com/2076-2615/10/7/1127

**Comment by 0x-Ryker** [comment]
Hello, my name is Greatman. I want to curate this.

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_788

Reviewed
