### ISSUE TITLE
Alteration of faecal microbiota balance related to long-term deep meditation

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#87]
Alteration of faecal microbiota balance related to long-term deep meditation – Ying Sun et al. – General Psychiatry 2023
doi: 10.1136/gpsych-2022-100893
https://gpsych.bmj.com/content/36/1/e100893

**Comment by Otakuwind** [comment]
hello, my name is Edgar and i want to curate this

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_780

Reviewed
