### ISSUE TITLE
Assessment of microbiota in the gut and upper respiratory tract associated with SARS-CoV-2 infection

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#88]
Assessment of microbiota in the gut and upper respiratory tract associated with SARS-CoV-2 infection – Jiarui Li et al. – Microbiome 2023
doi: 10.1186/s40168-022-01447-0
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01447-0

**Comment by Tolulope028** [comment]
Ogunleye Tolulope

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_782

Reviewed
