### ISSUE TITLE
Ambient temperature alters body size and gut microbiota of _Xenopus tropicalis_

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#90]
Ambient temperature alters body size and gut microbiota of _Xenopus tropicalis_ https://link.springer.com/article/10.1007/s11427-019-9540-y

![image](https://github.com/waldronlab/BugSigDBcuration/assets/639942/ac7438c0-b4b4-4018-9417-4bdbed477509)

[s11427-019-9540-y.pdf](https://github.com/waldronlab/BugSigDBcuration/files/12769084/s11427-019-9540-y.pdf)

**Comment by kamberry** [comment]
I would like to claim this paper to curate

**Comment by cmirzayi** [comment]
Assigned.

**Comment by cmirzayi** [comment]
This curation is well done and close to complete, but there are a number of small errors that need to be corrected. As well, the signatures seem to have some issues and should be thoroughly checked against Table S4 as well as the NCBI taxonomy to ensure proper taxonomic identification.

DESeq2 was used for differential abundance (and therefore the data transformation was raw counts).

We do not record matched on or confounders controlled for a laboratory experiment.

Richness (observed OTUs) is missing from alpha diversity measures. All alpha diversity measures should be unchanged as no significant results were observed.

I noticed some curation errors in the signatures. For instance, Melainabacteria (Candidatus Melainabacteria in the NCBI taxonomy) is missing. Bacilli and Bacillales are also missing. Please check all taxa carefully.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 0 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 0 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 17 |

**Comment by Peacesandy** [comment]
Reviewed
