### ISSUE TITLE
Genomic investigations of acute munitions exposures on the health and skin microbiome composition of leopard frog (Rana pipiens) tadpoles

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#91]
Genomic investigations of acute munitions exposures on the health and skin microbiome composition of leopard frog (Rana pipiens) tadpoles

https://www.sciencedirect.com/science/article/pii/S0013935120311427?casa_token=AMHUTxrSEO0AAAAA:TyUcWOzlElLI3kYk4gN8Q-IWLVscUMrmG18_MCs6quxO-zrvP4Al9kUJ7oL_StcNYT1KBzQD49BB

![image](https://github.com/waldronlab/BugSigDBcuration/assets/639942/ed8a5957-504e-4245-a606-f024766d52b4)

**Comment by Kehindeadebisi** [comment]
Kehinde Adebisi

**Comment by Kehindeadebisi** [comment]
Hi @lwaldron I'll like to curate this article

**Comment by cmirzayi** [comment]
Assigned.

**Comment by runananya** [comment]
Hey! I am Ananya Tomar, I would like to be assigned this article for the curation work.
Thank you!

**Comment by Buraah** [comment]
@SvetlanaUP I'm trying to pick a second article to curate since the first one I picked wasn't curatable.
It seems it is the case with this one too, I don't think this is also curatable. Can you please take a look at it?

**Comment by SvetlanaUP** [comment]
@Buraah this paper provides bacterial signatures that are curatable.

**Comment by Buraah** [comment]
> @Buraah this paper provides bacterial signatures that are curatable.

Oh, that is true. I can see more details now after downloading the pdf.
Thank you for assigning it to me.

**Comment by Buraah** [comment]
Hello @SvetlanaUP 
I am unable to start curating this because it seems it is already in the database.
![Screenshot (30)](https://github.com/waldronlab/BugSigDBcuration/assets/59023747/09fcd14a-448c-418e-8e82-724a184fe6cc)

**Comment by SvetlanaUP** [comment]
@Buraah please try it again. It should be fixed now.

**Comment by Buraah** [comment]
> @Buraah please try it again. It should be fixed now.

Yes, it works now. Thank you for your quick response!

**Comment by Buraah** [comment]
Hello @SvetlanaUP, I am done curating this article.

**Comment by Buraah** [comment]
Thank you for reviewing my work @AleruDivine

**Comment by Buraah** [comment]
Hello @keamybams, @flourishralph
thank you!

**Comment by Buraah** [comment]
Here is the link to my curation 
https://bugsigdb.org/Study_900

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_900 reviewed.
