### ISSUE TITLE
Breastfeeding patterns are associated with human milk microbiome composition: The Mother-Infant Microbiomes, Behavior, and Ecology Study (MIMBES)

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#92]
Holdsworth EA, Williams JE, Pace RM, Lane AA, Gartstein M, McGuire MA, et al. (2023) Breastfeeding patterns are associated with human milk microbiome composition: The Mother-Infant Microbiomes, Behavior, and Ecology Study (MIMBES). PLoS ONE 18(8): e0287839. https://doi.org/10.1371/journal.pone.0287839

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0287839

**Comment by Peacesandy** [comment]
Name: Peace Sandy

Hi @cmirzayi I'll like to claim this article

**Comment by cmirzayi** [comment]
Assigned!

**Comment by Peacesandy** [comment]
Thank You

**Comment by Peacesandy** [comment]
Hi @cmirzayi I'm done curating this paper
https://bugsigdb.org/Study_829 here is the link to the curation

**Comment by cmirzayi** [comment]
Marked for review.

**Comment by Peacesandy** [comment]
Thank you

**Comment by cmirzayi** [comment]
Wow this is perfect. Excellent work!

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 23 |

**Comment by Peacesandy** [comment]
Thank you, @cmirzayi  for reviewing my curation. I appreciate your time and effort. Looking forward to making more contributions.
