### ISSUE TITLE
Characterizing both bacteria and fungi improves understanding of the Arabidopsis root microbiome

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#93]
Characterizing both bacteria and fungi improves understanding of the _Arabidopsis_ root microbiome
https://www.nature.com/articles/s41598-018-37208-z

Limit taxonomic differential abundance results to **Table 1 The top 10 differentially enriched genera from each kingdom and their preferred habitats** to avoid unnecessary complexity. I think each plant part would be a different "body site" and therefore another experiment.

**Comment by spykelionel** [comment]
Ndi Lionel

**Comment by cmirzayi** [comment]
Assigned.

**Comment by spykelionel** [comment]
Ready for review: [https://bugsigdb.org/Study_792](https://bugsigdb.org/Study_792)

**Comment by cmirzayi** [comment]
@spykelionel This paper is a tough one. We usually do studies of humans, not plants, so I understand how much of it would be difficult to curate. Unfortunately, there are significant errors in this curation. Please ask questions, revise, and then we will review it again.

All elements marked "Needs review" (none "Incomplete") (1 point): 1
Correct study design (1 point): 0 (laboratory experiment)
Entered all relevant experiments and no irrelevant experiments (1 point): 1
Body site correctly identified (i.e. does not include multiple sites) (1 point): 0 (identifies a neural nerve)
Condition entered according to contrast (correct EFO ontology) (1 point): 0 (condition should be site or sampling site)
Contrast groups correctly identified (1 point): 1
Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
Antibiotic exclusion correctly identified (1 point): 0 
Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 2
Identified correct statistical test (1 point): 0 (Poisson model)
Identified MHT correction (1 point): 0 
Correctly recorded matched on variables (1 point): 0
Entered correct number of statistical tests per experiment (1 point): 1
All diversity measures identified (1 point): 1
Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 0 (decreased not increased)
All signature sources correctly identified (-1 for each error) (2 points): 2
Abundance direction correctly selected (1 point): 1
Members of signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 0
Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 0 missing several taxa
Total (maximum 23 points): 11

**Comment by Peacesandy** [comment]
Reviewed
