### ISSUE TITLE
Alterations in the oral microbiome in HIV-infected participants after antiretroviral therapy administration are influenced by immune status

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#97]
Presti, Rachel M.a; Handley, Scott A.a; Droit, Lindsaya; Ghannoum, Mahmoudb; Jacobson, Markc; Shiboski, Caroline H.c; Webster-Cyriaque, Jenniferd; Brown, Todde; Yin, Michael T.f; Overton, Edgar T.g. Alterations in the oral microbiome in HIV-infected participants after antiretroviral therapy administration are influenced by immune status. AIDS 32(10):p 1279-1287, June 19, 2018. | DOI: 10.1097/QAD.0000000000001811

https://journals.lww.com/aidsonline/Fulltext/2018/06190/Alterations_in_the_oral_microbiome_in_HIV_infected.8.aspx

**Comment by MyleeeA** [comment]
Name: Mildred Andokie Anashie

I will like to claim this article please

**Comment by MyleeeA** [comment]
Please I need help deleting signature 1 and 2 for this 
Here's the link https://bugsigdb.org/Study_819

**Comment by lwaldron** [comment]
Why do you want these deleted @MyleeeA? I only delete a page if it was added in error and doesn't belong there at all.

**Comment by lwaldron** [comment]
Deleted now @MyleeeA .

**Comment by MyleeeA** [comment]
Thank you  🙏

**Comment by MyleeeA** [comment]
Hi @lwaldron @cmirzayi @SvetlanaUP I finished my curation:  https://bugsigdb.org/Study_819. Waiting for your reviews.

**Comment by cmirzayi** [comment]
Marked as ready for review.

**Comment by cmirzayi** [comment]
Great curation! There is an experiment missing and I have some small changes that need to be made. I count 4 experiments worth of findings presented:

24W vs BL all samples (present)
BL low CD4 vs. BL high CD4 (present)
BL low CD4 vs 24W low CD4 (missing)
24W low CD4 vs. 24W high CD4 (present)

Condition should be antiviral agent.

Statistical test was DESeq2.

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 0 |
| 6 | Contrast groups correctly identified | 1 | 1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of Signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 20 |

**Comment by MyleeeA** [comment]
Thank you for your review…
This is way better than I thought I’ll do, I’m more confident now 😊
I’ll effect the changes accordingly

I’ve looked at the paper again and I noticed the experiment you pointed out I missed

**Comment by MyleeeA** [comment]
Hi

I’ve made some changes with regards the statistical test for the differential abundant taxas recorded and the condition (Changed it from HIV-1 infection to Response to antiviral drug) since antiviral drug wasn’t available 

I’m hoping this works

**Comment by Peacesandy** [comment]
https://bugsigdb.org/Study_819

Reviewed
