### ISSUE TITLE
Long-term benefit of DAAs on gut dysbiosis and microbial translocation in HCV-infected patients with and without HIV coinfection

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBcuration#98]
Chuaypen, N., Jinato, T., Avihingsanon, A. et al. Long-term benefit of DAAs on gut dysbiosis and microbial translocation in HCV-infected patients with and without HIV coinfection. Sci Rep 13, 14413 (2023). https://doi.org/10.1038/s41598-023-41664-7

https://www.nature.com/articles/s41598-023-41664-7

**Comment by Imsara123** [comment]
Sara Mohammed

I would like to be assigned to this project for the second contribution.
Thank you.

**Comment by cmirzayi** [comment]
Assigned.

**Comment by Peacesandy** [comment]
Assigned @Chioma-a

**Comment by Chioma-a** [comment]
Thank you

**Comment by SvetlanaUP** [comment]
@Scholarpat Please do help out here. Thanks.

**Comment by Scholarpat** [comment]
@SvetlanaUP I'm happy to help out ☺️

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP ,

I hope you're having a great weekend!

I reached out to the original assignee before starting the curation process, and she expressed a desire to initiate the curation herself. She mentioned that she would contact me if she encounters any difficulties along the way. As this is her second contribution, she kindly requested some time to get started.

**Comment by SvetlanaUP** [comment]
Excellent! Thanks, @Scholarpat!

**Comment by Scholarpat** [comment]
Hello @Chioma-a , happy holidays!
Hope you are doing well?
Just checking to see how the curation is going and how I can help.

Sending my best ☺️

**Comment by Scholarpat** [comment]
Hello @SvetlanaUP I've reached out again to the original assignee via slack but haven't gotten any feedback. Can this be assigned to me please?
https://bugsigdb.org/Study_1074

**Comment by SvetlanaUP** [comment]
Assigned to @Scholarpat

**Comment by Scholarpat** [comment]
Happy weekend @SvetlanaUP 🤗
@isioma20 and I collaborated to complete this curation. It is now ready for review.
https://bugsigdb.org/Study_1074.

**Comment by SvetlanaUP** [comment]
https://bugsigdb.org/Study_1074 reviewed.
